(() => {
  if (typeof units === 'undefined') return;

  const tag = '<span class="supplementalTag">Interactive visualization · course-aligned</span>';

  function addScreen(unitId, screen, afterTitle) {
    const unit = units.find(u => u && u.id === unitId);
    if (!unit || !unit.lessons || !unit.lessons[0]) return;
    const screens = unit.lessons[0].screens || (unit.lessons[0].screens = []);
    if (screens.some(s => s && s.title === screen.title)) return;
    let at = screens.length;
    if (afterTitle) {
      const i = screens.findIndex(s => s && s.title === afterTitle);
      if (i >= 0) at = i + 1;
    }
    screens.splice(at, 0, screen);
  }

  addScreen('l6-resonance', {
    type: 'teach',
    title: 'Interactive Desmos — resonance response curve',
    html: `<p>${tag}</p><p>The steady-state displacement amplitude for a sinusoidally forced damped oscillator is</p><div class="eq">\\[R(\\omega)=\\frac{A}{\\sqrt{(k-m\\omega^2)^2+(c\\omega)^2}}.\\]</div><p>Use the sliders to change \\(m,k,c\\), and the forcing amplitude \\(A\\). The dashed markers show the undamped natural frequency \\(\\omega_0=\\sqrt{k/m}\\) and, when it exists, the actual displacement-response peak \\(\\omega_r\\).</p><div class="beginner"><b>Experiment:</b> start with light damping and increase \\(c\\). The resonance peak becomes lower and broader, and its frequency shifts below \\(\\omega_0\\). When \\(c^2\\ge2mk\\), there is no nonzero-frequency resonance peak: over \\(\\omega\\ge0\\), the displacement amplitude is largest at \\(\\omega=0\\) and decreases as frequency increases.</div><div class="mathExplorer"><div class="mathExplorerTop"><div><b>Frequency-response explorer</b><span>steady-state displacement amplitude</span></div><div id="resonanceBadge" class="mathExplorerBadge">Loading…</div></div><div class="mathExplorerPresetRow"><button type="button" onclick="setMathExplorerPreset('resonance','none')">No damping</button><button type="button" onclick="setMathExplorerPreset('resonance','light')">Light damping</button><button type="button" onclick="setMathExplorerPreset('resonance','strong')">Strong damping</button><button type="button" onclick="setMathExplorerPreset('resonance','nopeak')">No peak</button></div><div id="resonanceDesmos" class="mathDesmos" data-desmos-explorer="resonance" aria-label="Interactive resonance response curve"></div><div id="resonanceReadout" class="mathExplorerReadout"><span>\\(\\omega_0=\\sqrt{k/m}\\)</span><span>\\(\\omega_r\\) depends on damping</span></div></div><div class="whybox"><b>Important distinction:</b> \\(\\omega_0\\) is the undamped natural frequency. A nonzero-frequency displacement peak exists only when \\(c^2&lt;2mk\\); then it occurs at \\(\\omega_r=\\sqrt{k/m-c^2/(2m^2)}\\), below \\(\\omega_0\\).</div>`
  }, 'Damping changes the resonance story');

  addScreen('l7-rlc-response', {
    type: 'teach',
    title: 'Interactive Desmos — RLC transient explorer',
    html: `<p>${tag}</p><p>For a source-free series RLC circuit, charge satisfies</p><div class="eq">\\[Lq''+Rq'+\\frac1Cq=0,\\qquad i=q'.\\]</div><p>The electrical discriminant is \\(\\Delta=R^2-4L/C\\). This is exactly the spring–mass–damper classification with \\(L\\leftrightarrow m\\), \\(R\\leftrightarrow c\\), and \\(1/C\\leftrightarrow k\\).</p><div class="mathExplorer"><div class="mathExplorerTop"><div><b>Free RLC response</b><span>charge q(t) and current i(t)=q′(t)</span></div><div id="rlcBadge" class="mathExplorerBadge">Loading…</div></div><div class="mathExplorerPresetRow"><button type="button" onclick="setMathExplorerPreset('rlc','undamped')">R = 0</button><button type="button" onclick="setMathExplorerPreset('rlc','under')">Underdamped</button><button type="button" onclick="setMathExplorerPreset('rlc','critical')">Critical</button><button type="button" onclick="setMathExplorerPreset('rlc','over')">Overdamped</button></div><div id="rlcDesmos" class="mathDesmos" data-desmos-explorer="rlc" aria-label="Interactive free RLC transient graph"></div><div id="rlcReadout" class="mathExplorerReadout"><span>\\(\\Delta=R^2-4L/C\\)</span><span>\\(R_{crit}=2\\sqrt{L/C}\\)</span></div></div><div class="whybox"><b>Read the graph physically:</b> oscillating charge means energy is exchanging between the inductor and capacitor. Resistance dissipates that stored energy. At and above critical resistance, the transient has no repeated oscillation; depending on the initial charge and current, it can still cross \\(q=0\\) once before settling.</div>`
  }, 'Natural and damped frequencies');

  addScreen('l7-kelvin', {
    type: 'teach',
    title: 'Interactive Desmos — Maxwell vs Kelvin–Voigt creep',
    html: `<p>${tag}</p><p>Apply the same constant stress \\(\\sigma_0\\) at \\(t=0\\) to the two basic viscoelastic models. Their creep responses are fundamentally different:</p><div class="eq">\\[\\varepsilon_M(t)=\\frac{\\sigma_0}{E}+\\frac{\\sigma_0}{\\eta}t,\\qquad \\varepsilon_K(t)=\\frac{\\sigma_0}{E}\\left(1-e^{-Et/\\eta}\\right).\\]</div><p>Change \\(E\\), \\(\\eta\\), and \\(\\sigma_0\\). The same parameters produce an immediate elastic jump plus unbounded viscous creep in the Maxwell model, but delayed approach to the finite elastic strain \\(\\sigma_0/E\\) in Kelvin–Voigt.</p><div class="mathExplorer"><div class="mathExplorerTop"><div><b>Viscoelastic creep comparison</b><span>constant stress applied at t = 0</span></div><div id="viscoBadge" class="mathExplorerBadge">Loading…</div></div><div class="mathExplorerPresetRow"><button type="button" onclick="setMathExplorerPreset('visco','balanced')">Balanced</button><button type="button" onclick="setMathExplorerPreset('visco','fast')">Low viscosity</button><button type="button" onclick="setMathExplorerPreset('visco','slow')">High viscosity</button></div><div id="viscoDesmos" class="mathDesmos" data-desmos-explorer="visco" aria-label="Interactive Maxwell and Kelvin-Voigt creep comparison"></div><div id="viscoReadout" class="mathExplorerReadout"><span>\\(\\tau=\\eta/E\\)</span><span>Kelvin–Voigt limit \\(=\\sigma_0/E\\)</span></div></div><div class="whybox"><b>Do not confuse the two time scales:</b> for Kelvin–Voigt, \\(\\tau=\\eta/E\\) controls how quickly the finite asymptote is approached. For Maxwell creep under constant stress, \\(\\eta\\) instead controls the long-time linear creep rate \\(\\sigma_0/\\eta\\).</div>`
  }, 'Maxwell versus Kelvin–Voigt');

  addScreen('l11-pulses', {
    type: 'teach',
    title: 'Interactive Desmos — step, pulse, and true delay',
    html: `<p>${tag}</p><p>Use one graph to separate three ideas that are easy to mix up: a <b>step</b>, a finite <b>pulse</b>, and a genuinely <b>delayed waveform</b>.</p><div class="mathExplorer"><div class="mathExplorerTop"><div><b>Switching explorer</b><span>drag a, b, A, and ω</span></div><div id="heavisideBadge" class="mathExplorerBadge">Loading…</div></div><div class="mathExplorerPresetRow"><button type="button" onclick="setMathExplorerPreset('heaviside','step')">Step H(t−a)</button><button type="button" onclick="setMathExplorerPreset('heaviside','pulse')">Pulse</button><button type="button" onclick="setMathExplorerPreset('heaviside','delay')">Delayed sine</button></div><div id="heavisideDesmos" class="mathDesmos" data-desmos-explorer="heaviside" aria-label="Interactive Heaviside step pulse and delayed sine graph"></div><div id="heavisideReadout" class="mathExplorerReadout"><span>Choose a signal above</span><span>The internal clock shifts only for a true delay</span></div></div><div class="whybox"><b>Key check:</b> \\(H(t-a)\\sin(\\omega t)\\) merely gates the original sine. A true time-delayed sine is \\(H(t-a)\\sin[\\omega(t-a)]\\): both the switch and the waveform’s internal clock move to \\(t=a\\).</div>`
  }, 'Derive the pulse piece by piece');

  addScreen('l12-periodic', {
    type: 'teach',
    title: 'Interactive Desmos — periodic waveform vs staircase',
    html: `<p>${tag}</p><p>A periodic rectangular signal repeats the <i>same values</i> every \\(T\\). A staircase only repeats its <i>jump timing</i>; its level keeps increasing. Change the period \\(T\\), amplitude \\(A\\), and duty fraction \\(d\\), then switch between the two.</p><div class="mathExplorer"><div class="mathExplorerTop"><div><b>Repeated-input explorer</b><span>periodicity versus accumulating steps</span></div><div id="periodicBadge" class="mathExplorerBadge">Loading…</div></div><div class="mathExplorerPresetRow"><button type="button" onclick="setMathExplorerPreset('periodic','pulse')">Periodic pulse train</button><button type="button" onclick="setMathExplorerPreset('periodic','stair')">Staircase</button></div><div id="periodicDesmos" class="mathDesmos" data-desmos-explorer="periodic" aria-label="Interactive periodic rectangular signal and staircase graph"></div><div id="periodicReadout" class="mathExplorerReadout"><span>Periodic: f(t+T)=f(t)</span><span>Staircase: r(t+T)=r(t)+A</span></div></div><div class="whybox"><b>Laplace consequence:</b> the periodic formula applies to the pulse train because its values repeat. It does not apply to the staircase itself, because the staircase gains another increment after every period.</div>`
  }, 'Periodic does not mean “use Heaviside repeatedly by hand”');

  addScreen('l8-existence', {
    type: 'teach',
    title: 'Interactive Desmos — why the Laplace integral converges',
    html: `<p>${tag}</p><p>For the textbook prototype \\(f(t)=e^{at}\\), the Laplace integrand is</p><div class="eq">\\[e^{-st}f(t)=e^{(a-s)t}.\\]</div><p>Move \\(a\\) and \\(s\\). The blue curve is the weighted integrand; the green curve is its accumulated area \\(C(T)=\\int_0^T e^{(a-s)t}\,dt\\).</p><div class="mathExplorer"><div class="mathExplorerTop"><div><b>Laplace convergence explorer</b><span>watch the improper integral as T grows</span></div><div id="laplaceBadge" class="mathExplorerBadge">Loading…</div></div><div class="mathExplorerPresetRow"><button type="button" onclick="setMathExplorerPreset('laplace','converges')">s &gt; a</button><button type="button" onclick="setMathExplorerPreset('laplace','boundary')">s = a</button><button type="button" onclick="setMathExplorerPreset('laplace','diverges')">s &lt; a</button></div><div id="laplaceDesmos" class="mathDesmos" data-desmos-explorer="laplace" aria-label="Interactive Laplace transform convergence graph"></div><div id="laplaceReadout" class="mathExplorerReadout"><span>\\(\\mathcal L\\{e^{at}\\}=1/(s-a)\\)</span><span>only when \\(s&gt;a\\)</span></div></div><div class="whybox"><b>Why the condition is \\(s&gt;a\\) here:</b> in this course we are treating real \\(s\\). Then \\(a-s&lt;0\\) makes the weighted integrand decay, so the accumulated area approaches the finite limit \\(1/(s-a)\\). More generally, for complex \\(s\\), the condition is \\(\\operatorname{Re}(s)&gt;a\\).</div>`
  }, 'Why exponential order is enough');

  addScreen('l13-convolution', {
    type: 'teach',
    title: 'Interactive Desmos — convolution as sliding overlap',
    html: `<p>${tag}</p><p>Convolution measures overlap while one input is shifted and reversed:</p><div class="eq">\\[(f*g)(t)=\\int_{-\\infty}^{\\infty}f(\\tau)g(t-\\tau)\,d\\tau.\\]</div><p>Here both functions are unit rectangular pulses on \\([0,1]\\). The blue interval is \\(f(\\tau)\\); the red interval is \\(g(T-\\tau)\\). Drag \\(T\\) and watch their overlap grow, peak, then disappear.</p><div class="mathExplorer"><div class="mathExplorerTop"><div><b>Sliding-overlap explorer</b><span>the green segment is the product being integrated</span></div><div id="convolutionBadge" class="mathExplorerBadge">Loading…</div></div><div class="mathExplorerPresetRow"><button type="button" onclick="setMathExplorerPreset('convolution','enter')">Entering</button><button type="button" onclick="setMathExplorerPreset('convolution','peak')">Full overlap</button><button type="button" onclick="setMathExplorerPreset('convolution','leave')">Leaving</button><button type="button" onclick="setMathExplorerPreset('convolution','gone')">No overlap</button></div><div id="convolutionDesmos" class="mathDesmos" data-desmos-explorer="convolution" aria-label="Interactive convolution sliding overlap graph"></div><div id="convolutionReadout" class="mathExplorerReadout"><span>overlap area = \\((f*g)(T)\\)</span><span>drag T to slide the second pulse</span></div></div><div class="whybox"><b>This is the integral geometrically:</b> because both pulse heights are 1, the integral equals the overlap length. Therefore the convolution is the triangular function \\(T\\) for \\(0\\le T\\le1\\), \\(2-T\\) for \\(1\\le T\\le2\\), and 0 otherwise.</div>`
  }, 'Why the convolution theorem is plausible');

  addScreen('l14-review', {
    type: 'teach',
    title: 'Interactive Desmos — partial sums and radius of convergence',
    html: `<p>${tag}</p><p>The geometric series is the cleanest visual model of a power series:</p><div class="eq">\\[1+x+x^2+\\cdots=\\frac1{1-x},\\qquad |x|<1.\\]</div><p>The blue curve is the finite partial sum \\(S_N(x)=\\sum_{n=0}^{N}x^n\\); the comparison curve is \\(1/(1-x)\\) only inside its radius of convergence. Increase \\(N\\) and move the sample point \\(p\\).</p><div class="mathExplorer"><div class="mathExplorerTop"><div><b>Power-series convergence explorer</b><span>N is an integer partial-sum order</span></div><div id="seriesBadge" class="mathExplorerBadge">Loading…</div></div><div class="mathExplorerPresetRow"><button type="button" onclick="setMathExplorerPreset('series','inside')">p = 0.5</button><button type="button" onclick="setMathExplorerPreset('series','near')">p = 0.95</button><button type="button" onclick="setMathExplorerPreset('series','outside')">p = 1.1</button></div><div id="seriesDesmos" class="mathDesmos" data-desmos-explorer="series" aria-label="Interactive geometric series partial sums and radius of convergence"></div><div id="seriesReadout" class="mathExplorerReadout"><span>Radius R = 1 about x₀ = 0</span><span>Increase N to test convergence</span></div></div><div class="whybox"><b>What the picture should teach:</b> inside \\(|x|<1\\), the partial sums settle toward \\(1/(1-x)\\). Near the boundary they converge much more slowly. Outside the radius, adding more terms does not make the partial sums approach that function.</div>`
  }, 'Why differentiating term by term is legal');

  addScreen('l18-proj', {
    type: 'teach',
    title: 'Interactive Desmos — projection is the closest point',
    html: `<p>${tag}</p><p>Let \\(u=(u_x,u_y)\\) and let the target line point in the unit direction \\(v=(\\cos\\phi,\\sin\\phi)\\). The projection is</p><div class="eq">\\[p=(u\\cdot v)v.\\]</div><p>Drag \\(u_x,u_y,\\phi\\). The residual \\(u-p\\) is drawn from the projected point to \\(u\\), and it remains perpendicular to the target line.</p><div class="mathExplorer"><div class="mathExplorerTop"><div><b>Orthogonal projection explorer</b><span>vector = projection + perpendicular error</span></div><div id="projectionBadge" class="mathExplorerBadge">Loading…</div></div><div class="mathExplorerPresetRow"><button type="button" onclick="setMathExplorerPreset('projection','oblique')">Oblique line</button><button type="button" onclick="setMathExplorerPreset('projection','horizontal')">Horizontal line</button><button type="button" onclick="setMathExplorerPreset('projection','vertical')">Vertical line</button></div><div id="projectionDesmos" class="mathDesmos" data-desmos-explorer="projection" aria-label="Interactive orthogonal vector projection graph"></div><div id="projectionReadout" class="mathExplorerReadout"><span>\\(p=(u\\cdot v)v\\)</span><span>\\((u-p)\\cdot v=0\\)</span></div></div><div class="whybox"><b>Closest-point fact:</b> any other point on the line adds some along-line displacement to the already perpendicular residual, making the distance larger by the Pythagorean theorem.</div>`
  }, 'Orthogonal projection onto a subspace');

  addScreen('l20-nonhom', {
    type: 'teach',
    title: 'Interactive Desmos — one, none, or infinitely many solutions',
    html: `<p>${tag}</p><p>A two-equation linear system can be seen as two lines. This explorer uses</p><div class="eq">\\[y=mx+b,\\qquad y=nx+c.\\]</div><p>Move the slopes and intercepts. The geometry makes the algebraic consistency test visible immediately.</p><div class="mathExplorer"><div class="mathExplorerTop"><div><b>2×2 consistency explorer</b><span>intersection geometry for AX=B</span></div><div id="systemBadge" class="mathExplorerBadge">Loading…</div></div><div class="mathExplorerPresetRow"><button type="button" onclick="setMathExplorerPreset('system','unique')">One solution</button><button type="button" onclick="setMathExplorerPreset('system','none')">No solution</button><button type="button" onclick="setMathExplorerPreset('system','infinite')">Infinitely many</button></div><div id="systemDesmos" class="mathDesmos" data-desmos-explorer="system" aria-label="Interactive geometry of a two by two linear system"></div><div id="systemReadout" class="mathExplorerReadout"><span>different slopes → one intersection</span><span>same slope → compare intercepts</span></div></div><div class="whybox"><b>Connection to row reduction:</b> different slopes produce two pivots and a unique solution. Distinct parallel lines encode an inconsistency. Coincident lines represent a redundant equation and therefore one free parameter.</div>`
  }, 'The augmented column matters');

  addScreen('l21-det', {
    type: 'teach',
    title: 'Interactive Desmos — determinant as signed area scale',
    html: `<p>${tag}</p><p>For</p><div class="eq">\\[A=\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix},\\]</div><p>the unit-square basis vectors are sent to the columns \\((a,c)\\) and \\((b,d)\\). Those two column vectors form a parallelogram whose area is</p><div class="eq">\\[\\boxed{|\\det A|=|ad-bc|}.\\]</div><p>Change all four matrix entries. The outlined parallelogram is the transformed unit square.</p><div class="mathExplorer"><div class="mathExplorerTop"><div><b>Determinant geometry explorer</b><span>columns determine the transformed unit square</span></div><div id="detBadge" class="mathExplorerBadge">Loading…</div></div><div class="mathExplorerPresetRow"><button type="button" onclick="setMathExplorerPreset('determinant','stretch')">Stretch</button><button type="button" onclick="setMathExplorerPreset('determinant','shear')">Shear</button><button type="button" onclick="setMathExplorerPreset('determinant','reflect')">Reflection</button><button type="button" onclick="setMathExplorerPreset('determinant','singular')">Singular</button></div><div id="detDesmos" class="mathDesmos" data-desmos-explorer="determinant" aria-label="Interactive determinant and transformed unit square graph"></div><div id="detReadout" class="mathExplorerReadout"><span>signed scale = det(A)</span><span>geometric area = |det(A)|</span></div></div><div class="whybox"><b>Why det(A)=0 means noninvertible:</b> the two transformed basis vectors become collinear, so the parallelogram collapses to zero area. A two-dimensional region has been flattened into a lower-dimensional set, so the transformation cannot be undone uniquely.</div>`
  }, 'From 2×2 to n×n');

  addScreen('l22-char', {
    type: 'teach',
    title: 'Interactive Desmos — see an eigenvector not turn',
    html: `<p>${tag}</p><p>This explorer builds a real symmetric \\(2\\times2\\) transformation from an orthonormal pair \\(q_1,q_2\\) and eigenvalues \\(\\lambda_1,\\lambda_2\\). When \\(\\lambda_1\\ne\\lambda_2\\), these are the two perpendicular eigendirections, and a vector with components in both is scaled differently and generally turns. When \\(\\lambda_1=\\lambda_2=\\lambda\\), the matrix is \\(A=\\lambda I\\), so every nonzero direction is an eigendirection.</p><div class="mathExplorer"><div class="mathExplorerTop"><div><b>Eigen-direction explorer</b><span>input v and transformed vector Av</span></div><div id="eigenBadge" class="mathExplorerBadge">Loading…</div></div><div class="mathExplorerPresetRow"><button type="button" onclick="setMathExplorerPreset('eigen','generic')">Generic vector</button><button type="button" onclick="setMathExplorerPreset('eigen','eig1')">Along q₁</button><button type="button" onclick="setMathExplorerPreset('eigen','eig2')">Along q₂</button><button type="button" onclick="setMathExplorerPreset('eigen','reverse')">Negative λ₂</button></div><div id="eigenDesmos" class="mathDesmos" data-desmos-explorer="eigen" aria-label="Interactive eigenvector transformation graph"></div><div id="eigenReadout" class="mathExplorerReadout"><span>\\(Av=\\lambda v\\) only on eigen-directions</span><span>Matrix shown from the current sliders</span></div></div><div class="whybox"><b>What to watch:</b> when the input lies on \\(q_1\\) or \\(q_2\\), the output stays on that same line. A negative eigenvalue reverses orientation along that line as well as scaling it. If \\(\\lambda_1=\\lambda_2\\), every direction has this no-turning property.</div>`
  }, 'Eigenvalues and eigenspaces — complete calculation');

  addScreen('l23-phase', {
    type: 'teach',
    title: 'Interactive Desmos — rotation, centers, and radial nodes',
    html: `<p>${tag}</p><p>For the canonical planar system</p><div class="eq">\\[X'=\\begin{pmatrix}\\alpha&-\\beta\\\\\\beta&\\alpha\\end{pmatrix}X,\\]</div><p>The eigenvalues are \\(\\alpha\\pm i\\beta\\). When \\(\\beta\\ne0\\), the solution rotates at angular rate \\(|\\beta|\\) while its radius is multiplied by \\(e^{\\alpha t}\\). When \\(\\beta=0\\), rotation disappears and the motion is purely radial. Change \\(\\alpha,\\beta\\) and the initial state to see these cases directly.</p><div class="mathExplorer"><div class="mathExplorerTop"><div><b>Canonical 2×2 phase portrait</b><span>α controls radial growth/decay; β controls rotation</span></div><div id="phaseBadge" class="mathExplorerBadge">Loading…</div></div><div class="mathExplorerPresetRow"><button type="button" onclick="setMathExplorerPreset('phase','sink')">Spiral sink</button><button type="button" onclick="setMathExplorerPreset('phase','center')">Center</button><button type="button" onclick="setMathExplorerPreset('phase','source')">Spiral source</button><button type="button" onclick="setMathExplorerPreset('phase','node')">No rotation</button><button type="button" onclick="setMathExplorerPreset('phase','slow')">Slow rotation</button></div><div id="phaseDesmos" class="mathDesmos" data-desmos-explorer="phase" aria-label="Interactive phase portrait for the canonical two dimensional alpha beta system"></div><div id="phaseReadout" class="mathExplorerReadout"><span>\\(\\lambda=\\alpha\\pm i\\beta\\)</span><span>\\(r(t)=r_0e^{\\alpha t}\\)</span></div></div><div class="whybox"><b>Classification is visible:</b> when \\(\\beta\\ne0\\), \\(\\alpha<0\\) gives a spiral sink, \\(\\alpha=0\\) a center, and \\(\\alpha>0\\) a spiral source. When \\(\\beta=0\\), there is no rotation: the same signs of \\(\\alpha\\) instead give straight radial decay, equilibrium, or straight radial growth.</div>`
  }, 'Phase portrait — saddle from opposite signs');

  if (typeof renderCourseMap === 'function') renderCourseMap();
  if (typeof render === 'function') render();
})();