/*
  Lesson 9 — Oct. 14: MIDTERM 1 day.

  The official syllabus schedules no new mathematical content on Oct. 14: it is a
  50-minute, closed-book Midterm 1 on Parts 1–2 (O’Neil Chapters 1–2 as taught).
  This lesson is therefore a faithful exam-simulation/final-review module, not an
  invented new topic. Laplace material from Lesson 8 is explicitly excluded.

  Authentic textbook policy:
  - First-order O’Neil questions below are taken directly from §§1.1–1.4.
  - Higher-order questions are cloned from the already source-verified O’Neil problem
    screens in Lessons 3–6, preserving their Lesson-1-depth worked solutions.
  - Clairaut is syllabus/lecture-slide content but is not a normal O’Neil Ch. 1 section
    in this edition, so its check is clearly labeled course-syllabus supplemental.
*/

const lesson9ExamTag='<span class="supplementalTag">Midterm 1 · Oct. 14 · Parts 1–2 · 50 min closed book</span>';
const lesson9BookTag='<span class="supplementalTag">Authentic O’Neil textbook exercise</span>';
const lesson9ExplainTag='<span class="supplementalTag">Final review · Lesson 1 depth standard</span>';
const lesson9SuppTag='<span class="supplementalTag">Syllabus/lecture skill · supplemental, not an O’Neil exercise</span>';

function l9BookProblem(section,number,prompt,solution){
  return {type:'bookproblem',bookSection:section,title:`O’Neil ${section} Problem ${number}`,prompt,solution};
}

const l9FirstOrderBook=[
  l9BookProblem('§1.1',12,
    `<p>${lesson9BookTag}<br>Solve the initial-value problem</p><div class="eq">\\[y'=3x^2(y+2),\\qquad y(2)=8.\\]</div>`,
    `<p><b>Plan before calculating.</b> The right side is a product of a function of \\(x\\) and a function of \\(y\\), so the equation is separable. We must also notice that dividing by \\(y+2\\) temporarily excludes \\(y=-2\\).</p>
     <p><b>1. Separate the variables.</b> For \\(y\\ne-2\\),</p><div class="eq">\\[\\frac{dy}{y+2}=3x^2dx.\\]</div>
     <p><b>2. Integrate once on each side.</b></p><div class="eq">\\[\\ln|y+2|=x^3+C.\\]</div>
     <p><b>3. Exponentiate.</b> Absorb the sign into a nonzero constant \\(A\\):</p><div class="eq">\\[y+2=Ae^{x^3}.\\]</div><p>The excluded equilibrium \\(y=-2\\) is recovered by allowing \\(A=0\\), so the compact family is</p><div class="eq">\\[y=Ae^{x^3}-2.\\]</div>
     <p><b>4. Apply the initial condition.</b></p><div class="eq">\\[8=Ae^8-2\\Rightarrow Ae^8=10\\Rightarrow A=10e^{-8}.\\]</div>
     <div class="whybox"><div class="eq">\\[\\boxed{y(x)=10e^{x^3-8}-2}.\\]</div></div>
     <p><b>Verification.</b> \\(y+2=10e^{x^3-8}\\), so \\(y'=30x^2e^{x^3-8}=3x^2(y+2)\\), and \\(y(2)=8\\).</p>`),
  l9BookProblem('§1.2',6,
    `<p>${lesson9BookTag}<br>Solve the initial-value problem</p><div class="eq">\\[y'+3y=5e^{2x}-6,\\qquad y(0)=2.\\]</div>`,
    `<p><b>Plan.</b> This is already in linear standard form \\(y'+p(x)y=q(x)\\) with \\(p=3\\). Build the integrating factor instead of guessing a trial.</p>
     <p><b>1. Integrating factor.</b></p><div class="eq">\\[I(x)=e^{\\int3dx}=e^{3x}.\\]</div>
     <p><b>2. Multiply the entire equation.</b></p><div class="eq">\\[e^{3x}y'+3e^{3x}y=5e^{5x}-6e^{3x}.\\]</div><p>The left side is exactly</p><div class="eq">\\[(e^{3x}y)'=5e^{5x}-6e^{3x}.\\]</div>
     <p><b>3. Integrate.</b></p><div class="eq">\\[e^{3x}y=e^{5x}-2e^{3x}+C.\\]</div>
     <p><b>4. Divide by the integrating factor.</b></p><div class="eq">\\[y=e^{2x}-2+Ce^{-3x}.\\]</div>
     <p><b>5. Fit the initial value.</b></p><div class="eq">\\[2=1-2+C\\Rightarrow C=3.\\]</div>
     <div class="whybox"><div class="eq">\\[\\boxed{y=e^{2x}-2+3e^{-3x}}.\\]</div></div>
     <p><b>Check.</b> At \\(x=0\\), \\(y=2\\). Differentiating and substituting gives \\(y'+3y=5e^{2x}-6\\).</p>`),
  l9BookProblem('§1.3',2,
    `<p>${lesson9BookTag}<br>Test for exactness and, if exact, find the general solution:</p><div class="eq">\\[4xy+2x+(2x^2+3y^2)y'=0.\\]</div>`,
    `<p><b>Plan.</b> Rewrite as \\(Mdx+Ndy=0\\) and test \\(M_y=N_x\\) before attempting to reconstruct a potential.</p>
     <p><b>1. Identify the components.</b></p><div class="eq">\\[M=4xy+2x,\\qquad N=2x^2+3y^2.\\]</div>
     <p><b>2. Exactness test.</b></p><div class="eq">\\[M_y=4x,\\qquad N_x=4x.\\]</div><p>They agree, so the equation is exact on the plane.</p>
     <p><b>3. Reconstruct the potential.</b> Integrate \\(M\\) with respect to \\(x\\), holding \\(y\\) fixed:</p><div class="eq">\\[\\phi=\\int(4xy+2x)dx=2x^2y+x^2+f(y).\\]</div>
     <p><b>4. Differentiate in \\(y\\) and match \\(N\\).</b></p><div class="eq">\\[\\phi_y=2x^2+f'(y)=2x^2+3y^2\\Rightarrow f'(y)=3y^2.\\]</div><p>Thus \\(f(y)=y^3\\); its additive constant is absorbed into the final level constant.</p>
     <div class="whybox"><div class="eq">\\[\\boxed{2x^2y+x^2+y^3=C}.\\]</div></div>
     <p><b>Check.</b> Differentiating this level-curve equation gives exactly \\((4xy+2x)dx+(2x^2+3y^2)dy=0\\).</p>`),
  l9BookProblem('§1.4',3,
    `<p>${lesson9BookTag}<br>Find the general solution:</p><div class="eq">\\[y'+xy=xy^2.\\]</div>`,
    `<p><b>Plan.</b> This is a Bernoulli equation \\(y'+P(x)y=Q(x)y^n\\) with \\(n=2\\). First preserve the equilibrium \\(y=0\\); then solve the nonzero branch using \\(v=y^{1-n}=y^{-1}\\).</p>
     <p><b>1. Nonzero branch.</b> Divide by \\(y^2\\):</p><div class="eq">\\[\\frac{y'}{y^2}+x\\frac1y=x.\\]</div><p>Set \\(v=y^{-1}\\). Then \\(v'=-y^{-2}y'\\), so multiplying the last equation by \\(-1\\) gives</p><div class="eq">\\[v'-xv=-x.\\]</div>
     <p><b>2. Solve the linear equation for \\(v\\).</b> Its integrating factor is</p><div class="eq">\\[I=e^{\\int(-x)dx}=e^{-x^2/2}.\\]</div><p>Therefore</p><div class="eq">\\[(ve^{-x^2/2})'=-xe^{-x^2/2}.\\]</div>
     <p>Integrate:</p><div class="eq">\\[ve^{-x^2/2}=e^{-x^2/2}+C.\\]</div><p>Hence</p><div class="eq">\\[v=1+Ce^{x^2/2}.\\]</div>
     <p><b>3. Restore \\(y\\).</b></p><div class="whybox"><div class="eq">\\[\\boxed{y=\\frac1{1+Ce^{x^2/2}}},\\qquad \\boxed{y\\equiv0}.\\]</div></div>
     <p>The zero solution must be listed separately because \\(v=1/y\\) excluded it.</p><p><b>Verification.</b> For the nonzero family, \\(v=1/y=1+Ce^{x^2/2}\\) satisfies \\(v'-xv=-x\\), which was obtained by an algebraically reversible substitution on the nonzero branch. The separate solution \\(y=0\\) gives both sides of \\(y'+xy=xy^2\\) equal to zero.</p><div class="warn"><b>Textbook answer-key audit:</b> the selected-answers page in the uploaded edition prints the exponential constant term with the opposite sign in its exponent. Direct substitution into the printed Problem 3 shows that version does not satisfy the ODE. The \\(e^{+x^2/2}\\) form above follows from the integrating-factor derivation and passes the original equation exactly.</div>`),
  l9BookProblem('§1.4',8,
    `<p>${lesson9BookTag}<br>Find the general solution:</p><div class="eq">\\[xy'=x\\cos(y/x)+y.\\]</div>`,
    `<p><b>Plan.</b> Divide by \\(x\\) on an interval where \\(x\\ne0\\). The resulting slope depends on the ratio \\(y/x\\), so use the homogeneous substitution \\(u=y/x\\), i.e. \\(y=ux\\).</p>
     <p><b>1. Differentiate the substitution.</b></p><div class="eq">\\[y'=u+xu'.\\]</div>
     <p><b>2. Substitute into the ODE.</b> Dividing the original equation by \\(x\\) gives \\(y'=\\cos(y/x)+y/x\\). Therefore</p><div class="eq">\\[u+xu'=\\cos u+u\\Rightarrow xu'=\\cos u.\\]</div>
     <p><b>3. Separate the nonconstant branch.</b> Where \\(\\cos u\\ne0\\),</p><div class="eq">\\[\\sec u\\,du=\\frac{dx}{x}.\\]</div>
     <p><b>4. Integrate.</b></p><div class="eq">\\[\\ln|\\sec u+\\tan u|=\\ln|x|+C.\\]</div><p>Exponentiating and absorbing signs/constants gives</p><div class="eq">\\[\\sec u+\\tan u=Cx.\\]</div>
     <p><b>5. Restore \\(u=y/x\\).</b></p><div class="whybox"><div class="eq">\\[\\boxed{\\sec(y/x)+\\tan(y/x)=Cx}.\\]</div></div>
     <p><b>6. Return to values divided out.</b> The separation divided by \\(\\cos u\\). Constant ratios with \\(\\cos u=0\\), namely \\(u=\\pi/2+k\\pi\\), also satisfy \\(xu'=\\cos u\\). Hence the straight lines</p><div class="eq">\\[\\boxed{y=(\\pi/2+k\\pi)x},\\qquad k\\in\\mathbb Z,\\]</div><p>must be reported separately on intervals not crossing \\(x=0\\).</p>`),
  l9BookProblem('§1.4',13,
    `<p>${lesson9BookTag}<br>Find the general solution:</p><div class="eq">\\[y'=-e^{-x}y^2+y+e^x.\\]</div>`,
    `<p><b>Plan.</b> This is Riccati. A Riccati equation becomes linear once one particular solution is known. Try the natural exponential \\(S=e^x\\).</p>
     <p><b>1. Verify the particular solution before using it.</b> \\(S'=e^x\\), while</p><div class="eq">\\[-e^{-x}(e^x)^2+e^x+e^x=-e^x+2e^x=e^x=S'.\\]</div><p>So \\(S=e^x\\) is valid.</p>
     <p><b>2. Use the Riccati substitution.</b></p><div class="eq">\\[y=e^x+\\frac1z,\\qquad y'=e^x-\\frac{z'}{z^2}.\\]</div>
     <p><b>3. Substitute and expand every term.</b></p><div class="eq">\\[-e^{-x}\\left(e^x+\\frac1z\\right)^2+e^x+\\frac1z+e^x=e^x-\\frac1z-\\frac{e^{-x}}{z^2}.\\]</div><p>Thus</p><div class="eq">\\[e^x-\\frac{z'}{z^2}=e^x-\\frac1z-\\frac{e^{-x}}{z^2}.\\]</div><p>Cancel \\(e^x\\) and multiply by \\(z^2\\):</p><div class="eq">\\[-z'=-z-e^{-x}\\Rightarrow z'-z=e^{-x}.\\]</div>
     <p><b>4. Solve the linear equation for \\(z\\).</b> The integrating factor is \\(e^{-x}\\):</p><div class="eq">\\[(ze^{-x})'=e^{-2x}.\\]</div><p>Integrating gives</p><div class="eq">\\[ze^{-x}=-\\frac12e^{-2x}+C\\Rightarrow z=Ce^x-\\frac12e^{-x}.\\]</div>
     <p><b>5. Restore \\(y\\).</b></p><div class="whybox"><div class="eq">\\[\\boxed{y=e^x+\\frac1{Ce^x-\\tfrac12e^{-x}}}.\\]</div><p>After renaming the arbitrary constant, an equivalent compact form is \\(y=e^x(Ke^{2x}+1)/(Ke^{2x}-1)\\).</p></div>
     <p><b>6. Restore the particular solution lost by the substitution.</b> No finite \\(z\\) produces \\(y=S=e^x\\), so \\(\\boxed{y=e^x}\\) must also be listed. The family is valid on intervals where its denominator is nonzero.</p><p><b>Verification.</b> Substitution of the displayed family into \\(y'=-e^{-x}y^2+y+e^x\\) gives zero residual; \\(y=e^x\\) was verified before the substitution.</p><div class="warn"><b>Textbook answer-key audit:</b> the selected-answers page in the uploaded edition gives a different fraction for Problem 13. Direct substitution of that printed fraction into the printed ODE leaves a nonzero residual. The family derived above follows the Riccati reduction step by step and satisfies the equation.</div>`)
];

function l9FindExisting(title){
  for(const u of units)for(const l of (u.lessons||[]))for(const s of (l.screens||[]))if(s.type==='bookproblem'&&s.title===title)return {...s,inlineBookPractice:true};
  return null;
}
function l9Clone(screen){return screen?{...screen,inlineBookPractice:true}:null;}

// These are exact O’Neil problems already source-checked and depth-expanded in Lessons 3–6.
const l9HigherTitles=[
  'O’Neil §2.2 Problem 14',
  'O’Neil §2.2 Problem 22',
  'O’Neil §2.3 Problem 17',
  'O’Neil §2.3 Problem 1',
  'O’Neil §2.4 Problem 11',
  'O’Neil §2.2 Problem 23',
  'O’Neil §2.3 Problem 23'
];
const l9HigherBook=l9HigherTitles.map(l9FindExisting).filter(Boolean);

const l9Clairaut={
  type:'bookproblem',bookSection:'Syllabus',practiceLabel:'Midterm syllabus skill · Clairaut',title:'Syllabus Check · Clairaut singular solution',
  prompt:`<p>${lesson9SuppTag}<br>Solve</p><div class="eq">\\[y=xy'+2(y')^2.\\]</div><p>Find both the one-parameter line family and the singular envelope.</p>`,
  solution:`<p><b>Plan.</b> This has Clairaut form \\(y=xp+f(p)\\) with \\(p=y'\\) and \\(f(p)=2p^2\\).</p><p><b>1. General line family.</b> Set \\(p=c\\) constant:</p><div class="eq">\\[\\boxed{y=cx+2c^2}.\\]</div><p>Every constant \\(c\\) gives a straight-line solution.</p><p><b>2. Singular branch.</b> Differentiate the Clairaut equation:</p><div class="eq">\\[p=p+(x+4p)p'\\Rightarrow(x+4p)p'=0.\\]</div><p>The factor \\(p'=0\\) reproduces the line family. The other factor gives \\(x+4p=0\\), so \\(p=-x/4\\).</p><p><b>3. Substitute the envelope condition into the original Clairaut relation.</b></p><div class="eq">\\[y=x(-x/4)+2(x^2/16)=-\\frac{x^2}{4}+\\frac{x^2}{8}=-\\frac{x^2}{8}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y_s=-\\frac{x^2}{8}}.\\]</div><p>This curve is not obtained by choosing one fixed constant \\(c\\); it is the envelope tangent to members of the line family.</p></div><p><b>Verify.</b> \\(y_s'=-x/4\\), and \\(xy_s'+2(y_s')^2=-x^2/4+x^2/8=-x^2/8=y_s\\).</p>`
};

const lesson9BookBank=[...l9FirstOrderBook,...l9HigherBook];
function l9ByTitle(title){const s=[...lesson9BookBank,l9Clairaut].find(x=>x&&x.title===title);return l9Clone(s);}

const lesson9BaseUnits=[
  {
    id:'l9-rules',courseLesson:9,color:'#4059ad',badge:'1',label:'Exam day',
    title:'Midterm 1: Final Boundary Check',subtitle:'No new mathematics today',
    desc:'Use the official assessment conditions and keep Laplace completely outside the Midterm 1 answer space.',
    lessons:[{title:'Scope and execution',screens:[
      {type:'teach',title:'What Oct. 14 actually is',html:`<p>${lesson9ExamTag}</p><p>The syllabus schedules a <b>50-minute, closed-book Midterm 1</b> on <b>Parts 1 and 2</b>. This lesson introduces no new examinable mathematics; it is a final simulation and audit of the methods already learned.</p><div class="warn"><b>Exam boundary:</b> do not use Lesson 8 Laplace material as Midterm 1 content; the syllabus explicitly excludes it. The course policy also states that generative AI cannot be used during Midterm 1. This app is for preparation <em>before</em> the exam, not for use during it.</div>`},
      {type:'teach',title:'The 50-minute control loop',html:`<p>${lesson9ExplainTag}</p><div class="whybox"><ol><li><b>0–3 min:</b> scan every question and label the method.</li><li><b>3–43 min:</b> solve in confidence order; write the structure that justifies each method.</li><li><b>43–48 min:</b> revisit skipped algebra/sign/domain issues.</li><li><b>48–50 min:</b> verify initial conditions, lost solutions, and boxed answers.</li></ol></div><p>A correct method with visible reasoning is safer than a compressed answer that cannot be audited.</p>`},
      {type:'quiz',title:'Exam-scope guardrail',q:'Which topic is explicitly outside Midterm 1 even though it began two days earlier?',options:['Laplace transforms','Euler equations','RLC circuits'],answer:0,why:'The Oct. 12 syllabus entry explicitly marks Laplace material as not examined on Midterm 1.'}
    ]}]
  },
  {
    id:'l9-memory',courseLesson:9,color:'#8b5d3b',badge:'★',label:'Remember everything',
    title:'Remember Everything for Midterm 1',subtitle:'Parts 1–2 · every method · every formula · every trap · every model',
    desc:'A complete active-recall pass over the Midterm 1 syllabus. Try to reconstruct each item before opening its answer, then use the final blank-paper dump to make the whole course retrievable from memory.',
    lessons:[
      {title:'How to use this memory pass',screens:[
        {type:'teach',title:'Do not read this like notes',html:`<p>${lesson9ExamTag}</p><p>This section is built for <b>retrieval</b>, not rereading. For every closed item below, stop for 10–20 seconds and say or write the answer <em>before</em> opening it. If you cannot reconstruct it, open it, close it again, and immediately reproduce it once from memory.</p><div class="whybox"><p><b>Best use:</b> one pass every few days now; then daily in the final week. The target is not word-for-word memorization. The target is that an unfamiliar equation triggers the correct structure, method, formula, and danger automatically.</p></div><p><b>90-second start:</b> on blank paper write two headings: <em>Part 1 — first-order</em> and <em>Part 2 — higher-order</em>. Under each, list every method you can remember. Then compare with the rest of this section.</p>`}
      ]},
      {title:'Part 1 · foundations and recognition',screens:[
        {type:'teach',title:'First-order foundations — reconstruct these before opening',html:`
          <details><summary><b>What are the basic classifications and equation forms?</b></summary><div class="whybox"><p><b>ODE vs PDE:</b> an ODE has derivatives with respect to one independent variable; a PDE has partial derivatives with respect to two or more independent variables. <b>Order</b> is the highest derivative present. A linear ODE has the dependent variable and its derivatives only to the first power, not multiplied together, with coefficients depending only on the independent variable.</p><p>For first order, move freely among <span class="eq">\\(y'=f(x,y)\\)</span>, <span class="eq">\\(F(x,y,y')=0\\)</span>, and <span class="eq">\\(M(x,y)dx+N(x,y)dy=0\\)</span>.</p></div></details>
          <details><summary><b>What solution language must I know?</b></summary><div class="whybox"><p>A <b>general solution</b> normally contains one arbitrary constant for a first-order ODE. A <b>particular solution</b> results after fixing the constant. An <b>IVP</b> adds a condition such as \\(y(x_0)=y_0\\). A solution may be <b>explicit</b>, \\(y=f(x)\\), or <b>implicit</b>, \\(\\Phi(x,y)=C\\). A branch excluded by algebra can be a separate equilibrium/exceptional solution and must be checked in the <em>original</em> ODE.</p><p>Always verify by substitution or by differentiating an implicit answer; also state the interval/domain when division, logarithms, radicals, or singular coefficients restrict it.</p></div></details>
          <details><summary><b>What is the first-order decision tree?</b></summary><div class="whybox"><ol><li>Separable?</li><li>Homogeneous in the first-order sense — slope only in \\(y/x\\), or \\(M,N\\) homogeneous of the same degree?</li><li>Exact? If not, do an integrating-factor test apply?</li><li>Linear in \\(y\\)?</li><li>Bernoulli, Riccati, or Clairaut pattern?</li></ol><p>Several methods can sometimes work. Classification is about finding a legal, efficient route.</p></div></details>`}
      ]},
      {title:'Part 1 · every solving method',screens:[
        {type:'teach',title:'Separable, homogeneous, exact, and non-exact',html:`
          <details><summary><b>Separable — what is the complete workflow?</b></summary><div class="whybox"><p>Recognize \\(y'=F(x)G(y)\\). Wherever \\(G(y)\\ne0\\), write</p><div class="eq">\\[\\frac{1}{G(y)}dy=F(x)dx.\\]</div><p>Integrate both sides using <b>one</b> arbitrary constant, solve explicitly if convenient, then return to every value divided out. Any constant \\(y=y_*\\) with \\(G(y_*)=0\\) solves the original equation and may need to be reported separately.</p></div></details>
          <details><summary><b>Homogeneous first-order — what exactly identifies it?</b></summary><div class="whybox"><p>If \\(y'=g(y/x)\\), set \\(y=ux\\), where \\(u=u(x)\\), so</p><div class="eq">\\[y'=u+xu'.\\]</div><p>The equation becomes separable in \\(u\\) and \\(x\\). In differential form, if \\(M\\) and \\(N\\) are homogeneous functions of the <b>same degree</b>, this reduction is guaranteed. Restore \\(u=y/x\\) at the end and check any excluded ratios.</p><p>The generalized scaling \\(y=ux^\\alpha\\) is an <b>ansatz</b> for selected non-homogeneous equations: choose \\(\\alpha\\) so powers collapse. It is useful, but not guaranteed to exist.</p></div></details>
          <details><summary><b>Exact — what test and reconstruction must I remember?</b></summary><div class="whybox"><p>Write \\(Mdx+Ndy=0\\). Test</p><div class="eq">\\[M_y=N_x.\\]</div><p>If exact, find a potential \\(\\phi\\) with \\(\\phi_x=M\\), \\(\\phi_y=N\\). For example, integrate \\(M\\) in \\(x\\):</p><div class="eq">\\[\\phi=\\int M(x,y)dx+f(y).\\]</div><p>Differentiate in \\(y\\), match \\(N\\), solve for \\(f'(y)\\), and finish with \\(\\phi(x,y)=C\\).</p></div></details>
          <details><summary><b>Non-exact — what integrating-factor tests are in the course?</b></summary><div class="whybox"><p>Using the course convention \\(Mdx+Ndy=0\\):</p><div class="eq">\\[\\frac{M_y-N_x}{N}=f(x)\\Rightarrow \\mu(x)=e^{\\int f(x)dx},\\]</div><div class="eq">\\[\\frac{M_y-N_x}{M}=g(y)\\Rightarrow \\mu(y)=e^{-\\int g(y)dy},\\]</div><div class="eq">\\[\\frac{M_y-N_x}{N-M}=h(x+y)\\Rightarrow \\mu=e^{\\int h(z)dz},\\quad z=x+y.\\]</div><p>For selected polynomial pairs, the lecture also permits the ansatz \\(\\mu=x^\\alpha y^\\beta\\). After multiplying by \\(\\mu\\), <b>retest exactness</b> and then solve as an exact equation.</p></div></details>`},
        {type:'teach',title:'Linear, Bernoulli, Riccati, and Clairaut',html:`
          <details><summary><b>Linear first-order — what must happen before the integrating factor?</b></summary><div class="whybox"><p>First force standard form:</p><div class="eq">\\[y'+p(x)y=q(x).\\]</div><p>Then</p><div class="eq">\\[I(x)=e^{\\int p(x)dx}.\\]</div><p>Multiply the <b>entire</b> equation by \\(I\\). The left side must collapse to</p><div class="eq">\\[(Iy)'=Iq.\\]</div><p>Integrate once and divide by \\(I\\). Do not include an arbitrary constant inside the integrating factor. If the original coefficient of \\(y'\\) is not 1, divide through first.</p></div></details>
          <details><summary><b>Bernoulli — what substitution and what lost branch?</b></summary><div class="whybox"><p>Recognize</p><div class="eq">\\[y'+P(x)y=Q(x)y^n,\\qquad n\\ne0,1.\\]</div><p>Preserve any zero branch before dividing by a power of \\(y\\). Set</p><div class="eq">\\[v=y^{1-n}.\\]</div><p>Then the equation becomes</p><div class="eq">\\[v'+(1-n)P(x)v=(1-n)Q(x),\\]</div><p>which is linear in \\(v\\). Solve it and restore \\(y\\), including all real branches allowed by the power.</p></div></details>
          <details><summary><b>Riccati — what makes it solvable in this course?</b></summary><div class="whybox"><p>Recognize</p><div class="eq">\\[y'=P(x)y^2+Q(x)y+R(x).\\]</div><p>There is no general elementary recipe. If one particular solution \\(S(x)\\) is known or found, <b>verify it first</b>, then set</p><div class="eq">\\[y=S+\\frac1z.\\]</div><p>The quadratic terms cancel and the equation for \\(z\\) is linear. The substitution cannot produce \\(y=S\\) for finite \\(z\\), so include the known particular solution separately if it is not contained in the resulting family.</p></div></details>
          <details><summary><b>Clairaut — what are the two branches?</b></summary><div class="whybox"><p>Recognize</p><div class="eq">\\[y=xy'+f(y').\\]</div><p>Set \\(y'=c\\) to get the line family</p><div class="eq">\\[y=cx+f(c).\\]</div><p>For the singular envelope, write \\(p=y'\\), differentiate, and factor:</p><div class="eq">\\[p'\\bigl(x+f'(p)\\bigr)=0.\\]</div><p>The \\(p'=0\\) factor gives the line family; the other factor \\(x=-f'(p)\\) gives the singular envelope parametrically.</p></div></details>`},
        {type:'teach',title:'First-order models you should recognize without relearning them',html:`
          <details><summary><b>Newton cooling / thermal relaxation</b></summary><div class="whybox"><div class="eq">\\[T'=k(T-T_{amb}),\\qquad k<0.\\]</div><p>The temperature difference from ambient decays exponentially. Initial temperature fixes one constant; one later measurement can determine \\(k\\).</p></div></details>
          <details><summary><b>Exponential growth/decay and half-life</b></summary><div class="whybox"><div class="eq">\\[m'=km\\Rightarrow m=m_0e^{kt}.\\]</div><p>For decay \\(k<0\\). If the half-life is \\(h\\), then \\(e^{kh}=1/2\\), so</p><div class="eq">\\[h=-\\frac{\\ln2}{k},\\qquad m(t)=m_0\\,2^{-t/h}.\\]</div></div></details>
          <details><summary><b>Mixing problems</b></summary><div class="whybox"><p>Start from the balance, not a memorized finished ODE:</p><div class="eq">\\[Q'=\\text{rate in}-\\text{rate out}.\\]</div><p>Salt-out rate = outflow rate × current concentration, usually \\(Q/V\\). Equal inflow/outflow keeps \\(V\\) constant and normally produces a first-order linear ODE with a steady state plus a transient.</p></div></details>`}
      ]},
      {title:'Part 2 · linear structure',screens:[
        {type:'teach',title:'Second-order structure, independence, and reduction of order',html:`
          <details><summary><b>What is the standard linear second-order structure?</b></summary><div class="whybox"><p>After dividing by the leading coefficient on an interval where it is nonzero:</p><div class="eq">\\[y''+P(x)y'+Q(x)y=g(x).\\]</div><p>If \\(g=0\\), the equation is homogeneous and superposition holds. If \\(g\\ne0\\), every solution has the form</p><div class="eq">\\[\\boxed{y=y_h+y_p}.\\]</div><p>If \\(P,Q,g\\) are continuous on an interval, prescribing \\(y(x_0)\\) and \\(y'(x_0)\\) at a point in that interval determines a unique IVP solution.</p></div></details>
          <details><summary><b>What does the Wronskian tell me?</b></summary><div class="whybox"><div class="eq">\\[W(y_1,y_2)=y_1y_2'-y_1'y_2.\\]</div><p>For two solutions of the same regular homogeneous linear second-order ODE, a nonzero Wronskian at one point certifies linear independence on the interval. Two independent solutions form a fundamental pair and</p><div class="eq">\\[y_h=c_1y_1+c_2y_2.\\]</div><p>The Wronskian does <b>not</b> generate characteristic roots.</p></div></details>
          <details><summary><b>Reduction of order — what if one homogeneous solution is already known?</b></summary><div class="whybox"><p>For \\(y''+P(x)y'+Q(x)y=0\\) with known nonzero \\(y_1\\), set \\(y_2=u(x)y_1(x)\\). The standard result is</p><div class="eq">\\[\\boxed{y_2=y_1\\int\\frac{e^{-\\int P(x)dx}}{y_1^2}dx}.\\]</div><p>The logic is that substitution cancels the terms already satisfied by \\(y_1\\) and reduces the order to an equation for \\(u'\\).</p></div></details>`},
        {type:'teach',title:'Characteristic roots — all cases and the nth-order extension',html:`
          <details><summary><b>Second-order constant coefficients — what are the three root cases?</b></summary><div class="whybox"><p>For \\(ay''+by'+cy=0\\), try \\(y=e^{rx}\\) and solve \\(ar^2+br+c=0\\).</p><div class="reviewGrid"><div class="mini"><b>Distinct real \\(r_1,r_2\\)</b><div class="eq">\\[y_h=c_1e^{r_1x}+c_2e^{r_2x}.\\]</div></div><div class="mini"><b>Repeated real \\(r\\)</b><div class="eq">\\[y_h=(c_1+c_2x)e^{rx}.\\]</div></div><div class="mini"><b>Complex \\(\\alpha\\pm i\\beta\\)</b><div class="eq">\\[y_h=e^{\\alpha x}(c_1\\cos\\beta x+c_2\\sin\\beta x).\\]</div></div></div></div></details>
          <details><summary><b>What changes for nth order?</b></summary><div class="whybox"><p>For a constant-coefficient homogeneous \\(n\\)th-order equation, \\(e^{rx}\\) gives an \\(n\\)th-degree characteristic polynomial. A real root \\(r\\) of multiplicity \\(m\\) contributes</p><div class="eq">\\[e^{rx},\\;xe^{rx},\\;\\ldots,\\;x^{m-1}e^{rx}.\\]</div><p>A complex pair \\(\\alpha\\pm i\\beta\\) of multiplicity \\(m\\) contributes the corresponding real sine/cosine pair multiplied successively by \\(1,x,\\ldots,x^{m-1}\\).</p></div></details>`}
      ]},
      {title:'Part 2 · forcing and Euler equations',screens:[
        {type:'teach',title:'Undetermined coefficients — rebuild the trial instead of memorizing one',html:`
          <details><summary><b>When is UC legal?</b></summary><div class="whybox"><p>Use it for a <b>linear constant-coefficient</b> ODE when the forcing belongs to a finite derivative-closed family: polynomials, exponentials, sines/cosines, and products/sums of those families. It is not the general method for forcing such as \\(\\tan x\\), \\(\\ln x\\), or arbitrary variable-coefficient equations.</p></div></details>
          <details><summary><b>What trial family should I write?</b></summary><div class="whybox"><ul><li>\\(P_n(x)\\): use a complete degree-\\(n\\) polynomial.</li><li>\\(Ce^{ax}\\): use \\(Ae^{ax}\\).</li><li>\\(C\\cos bx+D\\sin bx\\): use both sine and cosine.</li><li>\\(e^{ax}P_n(x)\\): exponential × complete polynomial.</li><li>\\(e^{ax}P_n(x)\\cos bx\\) or sine: exponential × complete polynomial × <b>both</b> trig partners.</li><li>For a sum of forcing terms, superpose the corresponding trials.</li></ul></div></details>
          <details><summary><b>What is the overlap rule?</b></summary><div class="whybox"><p>Compare the naive trial with the homogeneous solution space. If it overlaps a characteristic root of multiplicity \\(s\\), multiply the <b>entire</b> trial by \\(x^s\\). This is not a cosmetic trick: the differential operator annihilates any trial already inside its homogeneous null space.</p></div></details>`},
        {type:'teach',title:'Variation of parameters and Euler–Cauchy',html:`
          <details><summary><b>Variation of parameters — what formulas and prerequisites?</b></summary><div class="whybox"><p>Normalize first:</p><div class="eq">\\[y''+P(x)y'+Q(x)y=g(x).\\]</div><p>Given an independent homogeneous basis \\(y_1,y_2\\) with Wronskian \\(W\\), set \\(y_p=v_1y_1+v_2y_2\\), where</p><div class="eq">\\[v_1'=-\\frac{y_2g}{W},\\qquad v_2'=\\frac{y_1g}{W}.\\]</div><p>Equivalently,</p><div class="eq">\\[\\boxed{y_p=-y_1\\int\\frac{y_2g}{W}dx+y_2\\int\\frac{y_1g}{W}dx}.\\]</div><p>VP handles much broader forcing and variable coefficients than UC, but requires a known homogeneous basis and potentially difficult integrals.</p></div></details>
          <details><summary><b>Euler–Cauchy — how do I recognize and solve it?</b></summary><div class="whybox"><p>A second-order Euler equation has powers matched to derivative order, typically</p><div class="eq">\\[ax^2y''+bxy'+cy=f(x).\\]</div><p>For the homogeneous equation, try \\(y=x^r\\) on an interval where the sign of \\(x\\) is fixed. This gives an algebraic equation in \\(r\\). Distinct, repeated, and complex roots produce power/log/trigonometric-in-\\(\\ln|x|\\) analogues of the constant-coefficient cases.</p><p>The substitution</p><div class="eq">\\[t=\\ln|x|\\]</div><p>converts the Euler structure into a constant-coefficient equation in \\(t\\). State the interval: Euler equations are naturally solved separately on \\(x>0\\) and \\(x<0\\) when \\(x=0\\) is singular.</p></div></details>`}
      ]},
      {title:'Part 2 · engineering models and boundaries',screens:[
        {type:'teach',title:'Spring–mass–damper and resonance — remember the physics and the math together',html:`
          <details><summary><b>What equation do I rebuild from Newton's law?</b></summary><div class="whybox"><div class="eq">\\[my''+cy'+ky=F(t).\\]</div><p>\\(my''\\) = inertia, \\(cy'\\) = damping force, \\(ky\\) = spring restoring force, \\(F(t)\\) = applied forcing. The free equation has \\(F=0\\).</p></div></details>
          <details><summary><b>What are all four damping regimes?</b></summary><div class="whybox"><p>The characteristic discriminant is \\(\\Delta=c^2-4mk\\), with natural frequency \\(\\omega_0=\\sqrt{k/m}\\).</p><div class="reviewGrid"><div class="mini"><b>Undamped</b><p>\\(c=0\\): sustained sinusoidal motion.</p></div><div class="mini"><b>Underdamped</b><p>\\(0<c<2\\sqrt{mk}\\): complex roots, decaying oscillation.</p></div><div class="mini"><b>Critical</b><p>\\(c=2\\sqrt{mk}\\): repeated real root, boundary to non-oscillatory behavior.</p></div><div class="mini"><b>Overdamped</b><p>\\(c>2\\sqrt{mk}\\): two distinct negative real modes, no repeated oscillation.</p></div></div><p>For underdamping,</p><div class="eq">\\[\\omega_d=\\sqrt{\\frac{k}{m}-\\frac{c^2}{4m^2}},\\qquad y=e^{-ct/(2m)}(c_1\\cos\\omega_dt+c_2\\sin\\omega_dt).\\]</div></div></details>
          <details><summary><b>What is resonance and how does it connect to UC overlap?</b></summary><div class="whybox"><p>In an ideal undamped oscillator, sinusoidal forcing at the natural frequency overlaps the homogeneous sine/cosine mode. Algebraically the naive UC trial is annihilated, so a factor of \\(t\\) is required; physically that produces a response with a growing envelope. With damping, energy is dissipated and the response remains bounded.</p><p>For forced linear systems, distinguish the <b>transient</b> homogeneous part from the <b>steady-state</b> forced response.</p></div></details>`},
        {type:'teach',title:'RLC, viscoelasticity, and two-point BVPs',html:`
          <details><summary><b>Series RLC — what is the exact mechanical analogy?</b></summary><div class="whybox"><div class="eq">\\[Lq''+Rq'+\\frac1Cq=E(t),\\qquad i=q'.\\]</div><p>Inductor: \\(V_L=Li'=Lq''\\). Resistor: \\(V_R=Ri=Rq'\\). Capacitor: \\(V_C=q/C\\). Kirchhoff's voltage law adds the drops. The analogy is</p><div class="eq">\\[m\\leftrightarrow L,\\quad c\\leftrightarrow R,\\quad k\\leftrightarrow1/C,\\quad y\\leftrightarrow q,\\quad F\\leftrightarrow E.\\]</div></div></details>
          <details><summary><b>Maxwell and Kelvin–Voigt — which connection rule belongs to which?</b></summary><div class="whybox"><p><b>Maxwell = series:</b> same stress, strains add. With spring modulus \\(E\\) and dashpot viscosity \\(\\eta\\),</p><div class="eq">\\[\\boxed{\\sigma'+\\frac{E}{\\eta}\\sigma=E\\varepsilon'}.\\]</div><p>It exhibits stress relaxation under fixed strain and continuing/unbounded creep under fixed stress.</p><p><b>Kelvin–Voigt = parallel:</b> same strain, stresses add:</p><div class="eq">\\[\\boxed{\\sigma=E\\varepsilon+\\eta\\varepsilon'}.\\]</div><p>Under constant stress, strain approaches the finite elastic limit \\(\\sigma_0/E\\) with time scale \\(\\eta/E\\).</p></div></details>
          <details><summary><b>Two-point BVP — why is it not just an IVP with two conditions?</b></summary><div class="whybox"><p>An IVP prescribes value/slope information at the same point. A BVP imposes conditions at different points, such as \\(y(a)=A\\), \\(y(b)=B\\), or derivative/mixed conditions. Solve the ODE first, then impose the boundary conditions as a linear system for the constants.</p><p>If the boundary system is nonsingular, the constants are unique. If it is singular, test compatibility: there may be <b>no solution</b> or <b>infinitely many</b>. Do not import the IVP uniqueness theorem automatically.</p></div></details>`}
      ]},
      {title:'The traps you must remember',screens:[
        {type:'teach',title:'The complete Midterm 1 danger list',html:`<p>${lesson9ExplainTag}</p><div class="whybox"><ul><li><b>Classify first.</b> Do not start algebra before identifying the structure.</li><li><b>Division can lose solutions.</b> Recheck every factor you divided by.</li><li><b>Domains matter.</b> Track zeros of leading coefficients, denominators, logarithm arguments, square roots, and Euler intervals.</li><li><b>Exactness must be tested before potential reconstruction.</b></li><li><b>Linear first-order equations must be normalized before reading off \\(p(x)\\).</b></li><li><b>Riccati needs a verified particular solution.</b></li><li><b>Wronskian and characteristic polynomial do different jobs.</b></li><li><b>For nonhomogeneous higher-order equations, keep \\(y=y_h+y_p\\) conceptually separate.</b></li><li><b>UC requires the complete trial family</b> and an overlap check before coefficients are solved.</li><li><b>VP formulas assume normalized standard form.</b></li><li><b>Euler–Cauchy has a singular point at \\(x=0\\); state the interval.</b></li><li><b>Engineering equations come from balances and connection rules.</b> Check units and limiting behavior.</li><li><b>BVP uniqueness is not IVP uniqueness.</b></li><li><b>Verify the final answer</b> in the original equation and then verify ICs/BCs separately.</li></ul></div>`},
        {type:'quiz',title:'Memory trigger · first-order',q:'You see M(x,y)dx+N(x,y)dy=0. What should happen before you integrate either component?',options:['Test M_y=N_x','Assume a potential exists','Immediately divide by N'],answer:0,why:'Exactness is the gate. Only after M_y=N_x should you reconstruct a potential; otherwise run the integrating-factor tests.'},
        {type:'quiz',title:'Memory trigger · forced second-order',q:'You have a constant-coefficient forced ODE with forcing e^{2x}, and r=2 is a double characteristic root. What is the key correction to the naive UC trial?',options:['Multiply the entire trial by x²','Use the Wronskian instead','Divide the ODE by e^{2x}'],answer:0,why:'Overlap multiplicity two requires x² so the trial leaves the homogeneous solution space.'},
        {type:'quiz',title:'Memory trigger · model',q:'Which pair is the correct connection rule?',options:['Maxwell: series/same stress; Kelvin–Voigt: parallel/same strain','Maxwell: parallel/same strain; Kelvin–Voigt: series/same stress','Both are series'],answer:0,why:'Those connection rules generate the different constitutive ODEs and different creep/relaxation behavior.'}
      ]},
      {title:'Two-minute blank-paper dump',screens:[
        {type:'teach',title:'If you can reproduce this spine, the material is retrievable',html:`<p>Close this screen and, from memory, reproduce the following on one blank page. Then reopen it and mark every omission.</p><div class="reviewGrid"><div class="mini"><b>1 · First-order tree</b><p>Separable → homogeneous → exact / integrating factor → linear → Bernoulli → Riccati → Clairaut.</p></div><div class="mini"><b>2 · First-order core formulas</b><p>\\(y=ux\\); \\(M_y=N_x\\); \\(I=e^{\\int p dx}\\); \\(v=y^{1-n}\\); \\(y=S+1/z\\); Clairaut line family + envelope.</p></div><div class="mini"><b>3 · Second-order structure</b><p>\\(y=y_h+y_p\\); Wronskian; reduction of order; 3 characteristic-root cases; nth-order multiplicity.</p></div><div class="mini"><b>4 · Forcing methods</b><p>UC trial families + \\(x^s\\) overlap rule; VP with \\(v_1'=-y_2g/W\\), \\(v_2'=y_1g/W\\).</p></div><div class="mini"><b>5 · Euler</b><p>\\(y=x^r\\), or \\(t=\\ln|x|\\); state sign-consistent interval.</p></div><div class="mini"><b>6 · Models</b><p>\\(my''+cy'+ky=F\\); damping regimes + resonance; RLC analogy; Maxwell; Kelvin–Voigt; two-point BVP compatibility.</p></div><div class="mini"><b>7 · Universal checks</b><p>Lost branches · domains · IC/BC · substitution · units/physical limits.</p></div></div><div class="whybox"><p><b>Retention rule:</b> anything you fail to reproduce becomes tomorrow's first 5-minute review. Anything you reproduce correctly stays in the mixed rotation instead of being reread from scratch.</p></div>`}
      ]}
    ]
  },
  {
    id:'l9-part1',courseLesson:9,color:'#2e7d69',badge:'2',label:'Part 1',
    title:'Part 1 Final Review: Recognize Before You Solve',subtitle:'Classification is the first mathematical step',
    desc:'Use authentic Chapter 1 exercises to rehearse separable, linear, exact, and Bernoulli workflows, plus a clearly labeled Clairaut syllabus check.',
    lessons:[
      {title:'Method map',screens:[
        {type:'teach',title:'One-page first-order decision map',html:`<p>${lesson9ExplainTag}</p><div class="reviewGrid"><div class="mini"><b>Separable</b><p>Move all \\(y\\)-dependence with \\(dy\\), all \\(x\\)-dependence with \\(dx\\); recheck divided-out values.</p></div><div class="mini"><b>Linear</b><p>Standardize \\(y'+py=q\\); use \\(I=e^{\\int p dx}\\).</p></div><div class="mini"><b>Exact</b><p>Test \\(M_y=N_x\\); reconstruct \\(\\phi\\) only if exact.</p></div><div class="mini"><b>Homogeneous</b><p>Use \\(u=y/x\\) when the slope depends on the ratio.</p></div><div class="mini"><b>Bernoulli</b><p>Preserve \\(y=0\\); use \\(v=y^{1-n}\\).</p></div><div class="mini"><b>Riccati</b><p>Given/find one particular \\(S\\), then \\(y=S+1/z\\).</p></div><div class="mini"><b>Clairaut</b><p>Line family from \\(y'=c\\); differentiate to expose the singular envelope.</p></div></div>`},
        {type:'teach',title:'Non-exact does not mean stop',html:`<p>If \\(M_y\\ne N_x\\), the lecture syllabus still expects the integrating-factor tests. With the course convention \\(Mdx+Ndy=0\\):</p><div class="reviewGrid"><div class="mini"><b>μ(x)</b><p>If \\((M_y-N_x)/N=f(x)\\), use \\(\\mu=e^{\\int f(x)dx}\\).</p></div><div class="mini"><b>μ(y)</b><p>If \\((M_y-N_x)/M=g(y)\\), use \\(\\mu=e^{-\\int g(y)dy}\\).</p></div><div class="mini"><b>μ(x+y)</b><p>If \\((M_y-N_x)/(N-M)=h(x+y)\\), set \\(z=x+y\\) and use \\(\\mu=e^{\\int h(z)dz}\\).</p></div></div><p>For selected polynomial equations, the lecture also allows the ansatz \\(\\mu=x^\\alpha y^\\beta\\), with the exponents determined by demanding exactness.</p>`},
        {type:'quiz',title:'Do not solve before classifying',q:`Which clue most strongly identifies \\(y'+xy=xy^2\\) as a Bernoulli equation?`,options:['It has the form y′+P(x)y=Q(x)yⁿ with n=2','It contains x and y','It is second order'],answer:0,why:'The defining Bernoulli pattern determines the substitution v=y^(1−n).'}
      ]},
      {title:'Authentic Chapter 1 practice',screens:l9FirstOrderBook.map(l9Clone)},
      {title:'Syllabus-only Clairaut check',screens:[l9Clairaut]}
    ]
  },
  {
    id:'l9-part2',courseLesson:9,color:'#7651b8',badge:'3',label:'Part 2',
    title:'Part 2 Final Review: Structure, Forcing, Euler, and Applications',subtitle:'Keep the root cases and forcing methods separate',
    desc:'Rehearse the exact higher-order distinctions tested by Lessons 2–7, then work selected authentic O’Neil Chapter 2 exercises.',
    lessons:[
      {title:'Method map',screens:[
        {type:'teach',title:'One-page higher-order decision map',html:`<p>${lesson9ExplainTag}</p><div class="whybox"><ol><li>Is the equation linear and homogeneous or forced?</li><li>Constant coefficients? Use the characteristic polynomial for \\(y_h\\).</li><li>Forced with a derivative-closed RHS? Use undetermined coefficients and check overlap multiplicity.</li><li>More general forcing/variable coefficients with a known basis? Use variation of parameters.</li><li>Euler–Cauchy coefficients? Try \\(x^r\\) on a sign-consistent interval.</li><li>Engineering model? Derive the ODE and units before solving.</li><li>Two-point BVP? Solve the boundary constant system and check compatibility.</li></ol></div>`},
        {type:'teach',title:'Root pattern table you must be able to reconstruct',html:`<p>For a second-order constant-coefficient homogeneous equation:</p><div class="reviewGrid"><div class="mini"><b>Distinct real r₁,r₂</b><div class="eq">\\[c_1e^{r_1x}+c_2e^{r_2x}\\]</div></div><div class="mini"><b>Repeated real r</b><div class="eq">\\[(c_1+c_2x)e^{rx}\\]</div></div><div class="mini"><b>α±iβ</b><div class="eq">\\[e^{\\alpha x}(c_1\\cos\\beta x+c_2\\sin\\beta x)\\]</div></div></div><p>The Euler equation uses the analogous power/log basis because \\(t=\\ln|x|\\) converts it to a constant-coefficient equation.</p>`},
        {type:'teach',title:'Structure, reduction of order, and the nth-order extension',html:`<p>${lesson9ExplainTag}</p><p>These are separate syllabus items, so keep the logic distinct.</p><div class="whybox"><p><b>Homogeneous structure:</b> if \\(y_1,y_2\\) are independent solutions of a regular second-order homogeneous equation, every solution is \\(y_h=c_1y_1+c_2y_2\\). For a forced equation, one particular solution adds to this entire homogeneous family:</p><div class="eq">\\[\\boxed{y=y_h+y_p}.\\]</div><p><b>Reduction of order:</b> if one nonzero solution \\(y_1\\) of \\(y''+P(x)y'+Q(x)y=0\\) is already known, set \\(y_2=u(x)y_1(x)\\). After substitution and cancellation, the standard companion formula is</p><div class="eq">\\[\\boxed{y_2=y_1\\int\\frac{e^{-\\int P(x)dx}}{y_1^2}dx}.\\]</div><p>The formula is not magic: the substitution deliberately turns the unknown second solution into an equation for \\(u'\\).</p><p><b>nth-order constant coefficients:</b> for \\(a_ny^{(n)}+\\cdots+a_1y'+a_0y=0\\), the trial \\(e^{rx}\\) produces an \\(n\\)-degree characteristic polynomial. A real root \\(r\\) of multiplicity \\(m\\) contributes \\(e^{rx},xe^{rx},\\ldots,x^{m-1}e^{rx}\\); complex conjugate roots are converted to real sine/cosine pairs, with the same multiplicity rule.</p></div>`},
        {type:'teach',title:'Engineering application equations you should be able to rebuild',html:`<p>${lesson9ExplainTag}</p><p>The exam scope includes the applications taught in Lessons 6–7. Do not memorize these as disconnected formulas; remember the physical connection rule that creates each ODE.</p><div class="reviewGrid"><div class="mini"><b>Spring–mass–damper</b><div class="eq">\\[my''+cy'+ky=F(t)\\]</div><p>Newton's second law: inertia + damping + restoring force = applied force. The sign of \\(c^2-4mk\\) classifies the free damping regime.</p></div><div class="mini"><b>Series RLC</b><div class="eq">\\[Lq''+Rq'+\\frac1Cq=E(t)\\]</div><p>Kirchhoff voltage balance; current is \\(i=q'\\). It is mathematically analogous to the spring equation.</p></div><div class="mini"><b>Maxwell · series</b><div class="eq">\\[\\sigma'+\\frac{E}{\\eta}\\sigma=E\\varepsilon'\\]</div><p>Same stress through spring and dashpot; strains add. It captures stress relaxation and continuing creep.</p></div><div class="mini"><b>Kelvin–Voigt · parallel</b><div class="eq">\\[\\sigma=E\\varepsilon+\\eta\\varepsilon'\\]</div><p>Same strain; stresses add. Under constant stress, strain approaches a finite limit with retardation time \\(\\eta/E\\).</p></div></div><p><b>Two-point BVP reminder:</b> conditions such as \\(y(a)=A\\) and \\(y(b)=B\\) create a linear system for the integration constants. If that system is singular, test compatibility; the answer can be none or infinitely many rather than automatically unique.</p>`},
        {type:'quiz',title:'Application structure check',q:`Which statement correctly distinguishes the elementary Maxwell and Kelvin–Voigt models?`,options:['Maxwell is series: same stress and additive strains; Kelvin–Voigt is parallel: same strain and additive stresses','Maxwell is parallel and Kelvin–Voigt is series','Both use the same connection rule'],answer:0,why:'The series/parallel connection rule is what produces their different constitutive ODEs and different creep/relaxation behavior.'},
        {type:'quiz',title:'UC overlap check',q:`If the forcing suggests \\(Ae^{2x}\\) but r=2 is a double characteristic root, what must happen to the trial?`,options:['Multiply the entire trial by x²','Multiply only the coefficient by 2','Switch automatically to a separable method'],answer:0,why:'A root of multiplicity two means e^{2x} and xe^{2x} are both homogeneous directions, so x² is the first non-overlapping trial.'}
      ]},
      {title:'Authentic Chapter 2 practice',screens:l9HigherBook.map(l9Clone)}
    ]
  },
  {
    id:'l9-concepts',courseLesson:9,color:'#b35f4a',badge:'4',label:'Concept checks',
    title:'The Conceptual Questions That Prevent Method Errors',subtitle:'Wronskians · uniqueness · resonance · IVP versus BVP',
    desc:'Review the reasons behind formulas so an unfamiliar wording does not break method selection.',
    lessons:[{title:'Reasoning checks',screens:[
      {type:'teach',title:'Wronskian: what it proves and what it does not',html:`<p>The Wronskian of two known functions is</p><div class="eq">\\[W=y_1y_2'-y_1'y_2.\\]</div><p>On a regular interval for a homogeneous linear second-order ODE, a nonzero Wronskian at one point certifies linear independence of the solution pair. It does <b>not</b> generate characteristic roots and it does not replace solving the ODE.</p>`},
      {type:'teach',title:'Resonance is overlap with physical meaning',html:`<p>In undetermined coefficients, overlap means the naive trial lies in the homogeneous solution space, so the operator annihilates it. Multiplying by \\(x^s\\) moves the trial out of that null space.</p><p>In an ideal undamped oscillator, a sinusoidal forcing at the natural frequency creates exactly this overlap; the resulting \\(t\\)-factor produces a linearly growing envelope. The algebraic rule and the physical phenomenon are the same structure viewed from two sides.</p>`},
      {type:'teach',title:'Why BVP uniqueness is different',html:`<p>An IVP gives \\(y(a)\\) and \\(y'(a)\\) at one point and is covered by the regular linear IVP theorem. A two-point BVP instead gives conditions at different points, producing a separate 2×2 system for the constants.</p><p>If that boundary system is singular, the BVP may have no solution or infinitely many solutions. Never import the IVP uniqueness theorem without checking the boundary system.</p>`},
      {type:'quiz',title:'What does W=0 at one point mean for two arbitrary functions?',q:'Can you always conclude that two arbitrary differentiable functions are globally linearly dependent just because their Wronskian vanishes at one point?',options:['No — the strong conclusion needs the linear-ODE theorem hypotheses','Yes, always','Only if both functions are polynomials'],answer:0,why:'The Wronskian theorem used in the course is tied to solutions of the same regular homogeneous linear ODE on an interval.'}
    ]}]
  },
  {
    id:'l9-mock',courseLesson:9,color:'#d27a42',badge:'5',label:'50-min mock',
    title:'50-Minute Midterm Simulation',subtitle:'Distinct original transfer set · use no notes while timing yourself',
    desc:'A timed set that tests the same syllabus skills in unfamiliar forms instead of repeating the textbook exercises already used in the review units. Every problem is clearly labeled original course practice.',
    lessons:[
      {title:'Before you start the clock',screens:[
        {type:'teach',title:'Simulation rules',html:`<p>${lesson9ExamTag}</p><p>Close the lesson explanations, set a <b>50-minute timer</b>, and solve the next six problems on scratch boards before revealing any solution.</p><p>Suggested timing: 4 min classification scan, about 7 min per problem, and 4 min for final verification.</p><div class="warn"><b>The solutions are for post-attempt auditing.</b> These are original transfer problems, so success requires method recognition rather than memory of a previously seen textbook answer.</div>`}
      ]},
      {title:'Original transfer · first-order',screens:[
        {type:'bookproblem',bookSection:'Original course problem',practiceLabel:'Original Midterm 1 transfer',title:'Mock A1 · Separable with an excluded branch',prompt:`<p>${lesson9SuppTag}<br>Solve the IVP</p><div class="eq">\\[y'=x(y-1)^2,\\qquad y(0)=2.\\]</div><p>State any equilibrium branch excluded during separation and verify the IVP solution.</p>`,solution:`<p>The equilibrium \\(y=1\\) satisfies the ODE and would be excluded by dividing by \\((y-1)^2\\). For the non-equilibrium branch,</p><div class="eq">\\[\\frac{dy}{(y-1)^2}=x\\,dx.\\]</div><p>Integrate:</p><div class="eq">\\[-\\frac1{y-1}=\\frac{x^2}{2}+C.\\]</div><p>Use \\(y(0)=2\\): \\(-1=C\\). Hence</p><div class="eq">\\[-\\frac1{y-1}=\\frac{x^2}{2}-1.\\]</div><p>Solving for \\(y\\),</p><div class="whybox"><div class="eq">\\[\\boxed{y=1+\\frac{1}{1-x^2/2}}.\\]</div></div><p>The IVP branch is valid on the maximal interval containing 0 before the denominator vanishes, \\(|x|<\\sqrt2\\). Direct differentiation gives \\(y'=x/(1-x^2/2)^2=x(y-1)^2\\), and \\(y(0)=2\\).</p>`},
        {type:'bookproblem',bookSection:'Original course problem',practiceLabel:'Original Midterm 1 transfer',title:'Mock A2 · Exactness before integration',prompt:`<p>${lesson9SuppTag}<br>Solve</p><div class="eq">\\[(2xy+3)dx+(x^2+4y^3)dy=0.\\]</div>`,solution:`<p>Let \\(M=2xy+3\\), \\(N=x^2+4y^3\\). Then</p><div class="eq">\\[M_y=2x=N_x,\\]</div><p>so the equation is exact. Integrate \\(M\\) with respect to \\(x\\):</p><div class="eq">\\[\\phi=x^2y+3x+g(y).\\]</div><p>Differentiate in \\(y\\):</p><div class="eq">\\[\\phi_y=x^2+g'(y)=x^2+4y^3\\Rightarrow g(y)=y^4.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{x^2y+3x+y^4=C}.\\]</div></div><p>Differentiating the implicit answer reproduces the original differential form.</p>`},
        {type:'bookproblem',bookSection:'Original course problem',practiceLabel:'Original Midterm 1 transfer',title:'Mock A3 · Bernoulli recognition and zero branch',prompt:`<p>${lesson9SuppTag}<br>Solve</p><div class="eq">\\[y'+2y=e^{-x}y^3.\\]</div><p>Keep any branch lost by the standard Bernoulli substitution.</p>`,solution:`<p>This is Bernoulli with \\(n=3\\). Preserve \\(y=0\\). For \\(y\\ne0\\), set \\(v=y^{1-3}=y^{-2}\\). Since \\(v'=-2y^{-3}y'\\), multiply the ODE by \\(y^{-3}\\):</p><div class="eq">\\[y^{-3}y'+2y^{-2}=e^{-x}.\\]</div><p>Thus</p><div class="eq">\\[-\\frac12v'+2v=e^{-x}\\Rightarrow v'-4v=-2e^{-x}.\\]</div><p>The integrating factor is \\(e^{-4x}\\):</p><div class="eq">\\[(ve^{-4x})'=-2e^{-5x}.\\]</div><p>Integrate:</p><div class="eq">\\[ve^{-4x}=\\frac25e^{-5x}+C\\Rightarrow v=\\frac25e^{-x}+Ce^{4x}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y=\\pm\\left(\\frac25e^{-x}+Ce^{4x}\\right)^{-1/2}},\\qquad \\boxed{y\\equiv0}.\\]</div></div><p>The nonzero branches are valid where the quantity inside the square root is positive.</p>`}
      ]},
      {title:'Original transfer · higher-order',screens:[
        {type:'bookproblem',bookSection:'Original course problem',practiceLabel:'Original Midterm 1 transfer',title:'Mock B1 · Repeated roots with IV data',prompt:`<p>${lesson9SuppTag}<br>Solve</p><div class="eq">\\[y''-6y'+9y=0,\\qquad y(0)=2,\\quad y'(0)=1.\\]</div>`,solution:`<p>The characteristic polynomial is \\((r-3)^2\\), so</p><div class="eq">\\[y=(c_1+c_2x)e^{3x}.\\]</div><p>From \\(y(0)=2\\), \\(c_1=2\\). Differentiate:</p><div class="eq">\\[y'=[c_2+3(c_1+c_2x)]e^{3x}.\\]</div><p>At zero, \\(1=c_2+6\\), so \\(c_2=-5\\).</p><div class="whybox"><div class="eq">\\[\\boxed{y=(2-5x)e^{3x}}.\\]</div></div><p>Substitution into the ODE gives zero residual and the two initial values are satisfied.</p>`},
        {type:'bookproblem',bookSection:'Original course problem',practiceLabel:'Original Midterm 1 transfer',title:'Mock B2 · UC overlap diagnosis',prompt:`<p>${lesson9SuppTag}<br>Find one particular solution of</p><div class="eq">\\[y''-4y'+4y=e^{2x}.\\]</div><p>Explain why the naive trial fails before computing coefficients.</p>`,solution:`<p>The homogeneous characteristic polynomial is \\((r-2)^2\\), so both \\(e^{2x}\\) and \\(xe^{2x}\\) are homogeneous directions. A naive \\(Ae^{2x}\\) trial is annihilated by the differential operator.</p><p>The overlap multiplicity is two, so try</p><div class="eq">\\[y_p=Ax^2e^{2x}.\\]</div><p>Because the operator is \\((D-2)^2\\), use \\((D-2)[e^{2x}v]=e^{2x}v'\\). Applying it twice to \\(Ax^2e^{2x}\\) gives \\(2Ae^{2x}\\). Matching the RHS yields \\(2A=1\\), hence</p><div class="whybox"><div class="eq">\\[\\boxed{y_p=\\frac12x^2e^{2x}}.\\]</div></div>`},
        {type:'bookproblem',bookSection:'Original course problem',practiceLabel:'Original Midterm 1 transfer',title:'Mock B3 · Euler equation and interval',prompt:`<p>${lesson9SuppTag}<br>Solve on \\(x>0\\):</p><div class="eq">\\[x^2y''-3xy'+4y=0.\\]</div>`,solution:`<p>Use the Euler trial \\(y=x^r\\). Then \\(y'=rx^{r-1}\\), \\(y''=r(r-1)x^{r-2}\\). Substitution gives</p><div class="eq">\\[r(r-1)-3r+4=0\\Rightarrow r^2-4r+4=(r-2)^2=0.\\]</div><p>A repeated Euler root \\(r=2\\) produces</p><div class="whybox"><div class="eq">\\[\\boxed{y=c_1x^2+c_2x^2\\ln x},\\qquad x>0.\\]</div></div><p>The logarithm and power basis are stated on the requested positive interval.</p>`}
      ]}
    ]
  },
  {
    id:'l9-audit',courseLesson:9,color:'#6a6f7b',badge:'6',label:'Self-audit',
    title:'Mark the Method, Not Just the Final Answer',subtitle:'Diagnose exactly where marks would be lost',
    desc:'Use a causal error audit after the mock so each correction changes a future decision, not just one line of arithmetic.',
    lessons:[{title:'Post-mock audit',screens:[
      {type:'teach',title:'Four error categories',html:`<div class="reviewGrid"><div class="mini"><b>Recognition error</b><p>Wrong method chosen or equation misclassified.</p></div><div class="mini"><b>Setup error</b><p>Correct method, wrong standard form/trial/integrating factor/basis.</p></div><div class="mini"><b>Execution error</b><p>Differentiation, integration, algebra, sign, or constant mistake.</p></div><div class="mini"><b>Verification error</b><p>Lost solution, wrong interval, IC/BC not checked, physical interpretation inconsistent.</p></div></div><p>Write the category beside every missed problem. “Careless” is not a useful diagnosis; identify the exact decision that failed.</p>`},
      {type:'teach',title:'Independent checks by problem type',html:`<p>${lesson9ExplainTag}</p><div class="whybox"><ul><li><b>First-order explicit solution:</b> differentiate and substitute into the original ODE.</li><li><b>Exact implicit solution:</b> differentiate \\(\\phi(x,y)=C\\) and recover \\(Mdx+Ndy=0\\).</li><li><b>Linear second-order:</b> substitute basis/particular terms; verify ICs separately.</li><li><b>Euler:</b> verify the power/log basis on the stated interval.</li><li><b>Engineering model:</b> check units and limiting behavior as well as the ODE.</li><li><b>BVP:</b> verify both endpoint conditions independently.</li></ul></div>`},
      {type:'quiz',title:'Best response to a wrong answer',q:'After discovering a wrong answer, what is the most useful next step?',options:['Identify whether the failure was recognition, setup, execution, or verification, then redo from the failed decision','Memorize the correct final expression','Immediately move on without checking'],answer:0,why:'A causal diagnosis changes the future method choice; memorizing one answer does not.'}
    ]}]
  },
  {
    id:'l9-final-bank',courseLesson:9,color:'#3f7f8f',badge:'7',label:'Error diagnosis',
    title:'Final Error-Diagnosis Bank',subtitle:'Six short traps · explain what is wrong before repairing it',
    desc:'A non-repetitive final bank focused on the mistakes most likely to survive ordinary practice: lost branches, wrong method assumptions, overlap, Wronskian misuse, unit/model errors, and BVP uniqueness errors.',
    lessons:[
      {title:'First-order traps',screens:[
        {type:'bookproblem',bookSection:'Original course problem',practiceLabel:'Original diagnostic · not an O’Neil exercise',title:'Diagnostic 1 · Lost equilibrium',prompt:`<p>A student solves \\(y'=xy\\) by writing \\(dy/y=x\\,dx\\) and reports only \\(y=Ce^{x^2/2}\\) with \\(C\\ne0\\). What was implicitly assumed, and how should the final family be stated?</p>`,solution:`<p>Dividing by \\(y\\) assumes \\(y\\ne0\\), so the equilibrium \\(y=0\\) was temporarily excluded. After integration and exponentiation, the constant can be allowed to take the value zero:</p><div class="eq">\\[\\boxed{y=Ce^{x^2/2},\\qquad C\\in\\mathbb R}.\\]</div><p>This compact family includes the lost equilibrium branch.</p>`},
        {type:'bookproblem',bookSection:'Original course problem',practiceLabel:'Original diagnostic · not an O’Neil exercise',title:'Diagnostic 2 · Exactness assumed without testing',prompt:`<p>A student integrates \\(M=2xy\\) with respect to \\(x\\) in \\(2xy\\,dx+x^2\\,dy=0\\) and immediately declares a potential. Is that legitimate? Show the check.</p>`,solution:`<p>It is legitimate only after exactness is checked:</p><div class="eq">\\[M_y=2x,\\qquad N_x=2x.\\]</div><p>Since they agree, the form is exact. Integrating \\(M\\) gives \\(\\phi=x^2y+g(y)\\), and matching \\(\\phi_y=x^2=N\\) gives \\(g'=0\\). Hence \\(x^2y=C\\). The key correction is methodological: <b>test exactness before reconstructing a potential</b>.</p>`},
        {type:'bookproblem',bookSection:'Original course problem',practiceLabel:'Original diagnostic · not an O’Neil exercise',title:'Diagnostic 3 · Riccati substitution without verifying S',prompt:`<p>A proposed Riccati solution begins “take the particular solution \\(S(x)=1\\) and set \\(y=S+1/z\\)” but never checks \\(S\\). What must be verified before that substitution is valid?</p>`,solution:`<p>For a Riccati equation \\(y'=a(x)y^2+b(x)y+c(x)\\), the claimed \\(S\\) must satisfy</p><div class="eq">\\[S'=aS^2+bS+c.\\]</div><p>If it does not, the cancellation that makes the \\(z\\)-equation linear fails. A guessed particular solution is not a free choice; it must first be substituted into the original Riccati equation.</p>`}
      ]},
      {title:'Higher-order traps',screens:[
        {type:'bookproblem',bookSection:'Original course problem',practiceLabel:'Original diagnostic · not an O’Neil exercise',title:'Diagnostic 4 · UC overlap ignored',prompt:`<p>For \\(y''+4y=\\cos2x\\), a student tries \\(A\\cos2x+B\\sin2x\\). Explain why this cannot work and give the corrected trial form.</p>`,solution:`<p>The characteristic roots are \\(\\pm2i\\), so both \\(\\cos2x\\) and \\(\\sin2x\\) already lie in the homogeneous solution space. The differential operator annihilates the naive trial. Multiply the entire trial by \\(x\\):</p><div class="eq">\\[\\boxed{y_p=x(A\\cos2x+B\\sin2x)}.\\]</div><p>The extra factor moves the trial out of the homogeneous null space.</p>`},
        {type:'bookproblem',bookSection:'Original course problem',practiceLabel:'Original diagnostic · not an O’Neil exercise',title:'Diagnostic 5 · Wronskian overclaim',prompt:`<p>A student computes \\(W(0)=0\\) for two arbitrary differentiable functions and concludes they are globally linearly dependent. What is wrong with that conclusion?</p>`,solution:`<p>For arbitrary differentiable functions, a Wronskian that vanishes at one point is not enough to conclude global dependence. The strong theorem used in this course applies to two solutions of the <b>same regular homogeneous linear ODE</b> on an interval: under those hypotheses, a nonzero Wronskian at one point certifies independence, and Abel's identity controls its behavior across the interval.</p>`},
        {type:'bookproblem',bookSection:'Original course problem',practiceLabel:'Original diagnostic · not an O’Neil exercise',title:'Diagnostic 6 · BVP uniqueness imported from an IVP',prompt:`<p>A student says \\(y''+y=0,\\ y(0)=0,\\ y(\\pi)=0\\) has a unique solution because “a second-order ODE with two conditions is unique.” Diagnose the error.</p>`,solution:`<p>The regular IVP uniqueness theorem applies when value and derivative data are prescribed at the <b>same point</b>. Here the data are at two different points. The general solution is \\(y=c_1\\cos x+c_2\\sin x\\). The first boundary condition gives \\(c_1=0\\), while the second becomes \\(c_2\\sin\\pi=0\\), which is true for every \\(c_2\\). Therefore</p><div class="eq">\\[\\boxed{y=c_2\\sin x}\\]</div><p>is an infinite family. The boundary constant system is singular and compatible.</p>`}
      ]}
    ]
  },
  {
    id:'l9-ready',courseLesson:9,color:'#9a3f69',badge:'8',label:'Ready check',
    title:'Final Readiness Check',subtitle:'You should be able to justify every “why” without notes',
    desc:'A short final gate for method selection, scope, and verification. Nothing new is introduced here.',
    lessons:[{title:'Five questions before the exam',screens:[
      {type:'teach',title:'The readiness standard',html:`<p>${lesson9ExamTag}</p><div class="whybox"><ol><li>Can I classify a first-order equation before manipulating it?</li><li>Can I reconstruct the integrating-factor/exactness/Bernoulli logic rather than only recite formulas?</li><li>Can I derive the correct homogeneous basis from any characteristic-root pattern?</li><li>Can I choose UC versus VP, handle overlap, and fit IVP constants without hidden steps?</li><li>Can I verify my answer in the original equation and state lost solutions/domains/physical meaning where relevant?</li></ol></div><p>If any answer is “not reliably,” return to the corresponding unit rather than rereading everything.</p>`},
      {type:'quiz',title:'Final scope check',q:'What is the correct content boundary for Midterm 1?',options:['Parts 1–2 as taught; Laplace is excluded','Parts 1–3 including Laplace','Only first-order ODEs'],answer:0,why:'The syllabus states Midterm 1 covers Parts 1 and 2, while the Oct. 12 Laplace introduction is explicitly not examined.'}
    ]}]
  }
];

// Remove the harmless computed-key placeholder above if the runtime preserves it; it is not a screen field.
const lesson9Units=lesson9BaseUnits;
if(!units.some(u=>u&&u.id==='l9-rules'))units.push(...lesson9Units);

courseLessons[8]={
  number:9,
  title:'Midterm 1 Simulation & Final Review',
  subtitle:'Oct. 14 · Parts 1–2 · 50-min closed-book simulation · authentic O’Neil Chapter 1–2 practice',
  status:'current'
};

if(typeof renderCourseMap==='function')renderCourseMap();
if(typeof render==='function')render();

// Load the dedicated randomized 50-minute Midterm 1 simulator after Lesson 9 registers.
(()=>{
  const s=document.createElement("script");
  s.src="./midterm-simulator.js?v=4";
  s.defer=true;
  document.head.appendChild(s);
})();
