/* Lesson 16 — Nov. 11: Midterm 2 preparation, Parts 3–4 only. */
const l16Core='<span class="supplementalTag">Core · Nov. 11 syllabus · Midterm 2 preparation</span>';
const l16Book='<span class="supplementalTag">Authentic textbook · supplied O’Neil edition</span>';
const l16Explain='<span class="supplementalTag">Expanded explanation · Lesson 1 depth standard</span>';
const l16Recon='<span class="supplementalTag">Exam-style reconstruction · not claimed as an O’Neil problem</span>';
function l16Board(title,prompt,solution,section){return {type:'bookproblem',bookSection:section,title,prompt,solution};}
function l16Clone(s){return s?{...s,inlineBookPractice:true}:null;}
const l16P31=l16Board('O’Neil §3.1 Problem 1 — transform a product involving t',`<p>${l16Book}</p><p>Find the Laplace transform of</p><div class="eq">\\[f(t)=3t\\cos(2t).\\]</div><p>Do not search the table for the whole expression; build it from a known transform and the multiplication-by-\\(t\\) rule.</p>`,`<p><b>1 · Start from a transform you know.</b></p><div class="eq">\\[\\mathcal L\\{\\cos(2t)\\}=\\frac{s}{s^2+4}.\\]</div><p><b>2 · Use the rule for multiplication by \\(t\\).</b> If \\(F(s)=\\mathcal L\\{f(t)\\}\\), then</p><div class="eq">\\[\\mathcal L\\{t f(t)\\}=-F'(s).\\]</div><p>Differentiate:</p><div class="eq">\\[-\\frac{d}{ds}\\left(\\frac{s}{s^2+4}\\right)=-\\frac{(s^2+4)-2s^2}{(s^2+4)^2}=\\frac{s^2-4}{(s^2+4)^2}.\\]</div><p>Finally multiply by 3:</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L\\{3t\\cos 2t\\}=\\frac{3(s^2-4)}{(s^2+4)^2}}.\\]</div></div>`,'§3.1 · Problem 1');
const l16P32=l16Board('O’Neil §3.2 Problem 1 — solve an IVP by Laplace transform',`<p>${l16Book}</p><p>Use the Laplace transform to solve</p><div class="eq">\\[y'+4y=1,\\qquad y(0)=-3.\\]</div>`,`<p>Let \\(Y(s)=\\mathcal L\\{y(t)\\}\\). Transform each term:</p><div class="eq">\\[\\mathcal L\\{y'\\}=sY-y(0)=sY+3,\\qquad \\mathcal L\\{1\\}=\\frac1s.\\]</div><p>Therefore</p><div class="eq">\\[(s+4)Y+3=\\frac1s,\\]</div><div class="eq">\\[Y=\\frac{1-3s}{s(s+4)}=\\frac{1}{4s}-\\frac{13}{4(s+4)}.\\]</div><p>Invert term by term:</p><div class="whybox"><div class="eq">\\[\\boxed{y(t)=\\frac14-\\frac{13}{4}e^{-4t}}.\\]</div></div><p><b>Check the initial condition:</b> \\(y(0)=1/4-13/4=-3\\). <b>Check the ODE:</b> \\(y'+4y=13e^{-4t}+1-13e^{-4t}=1\\).</p>`,'§3.2 · Problem 1');
const l16Shift=l16Board('Exam-style — Heaviside and second shifting theorem',`<p>${l16Recon}</p><p>Find the inverse transform</p><div class="eq">\\[F(s)=e^{-3s}\\frac{s}{s^2+4}.\\]</div><p>State what the answer is doing in time.</p>`,`<p>Ignore the exponential shift for one moment:</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac{s}{s^2+4}\\right\\}=\\cos(2t).\\]</div><p>The second shifting theorem says</p><div class="eq">\\[e^{-as}G(s)\\longleftrightarrow H(t-a)g(t-a).\\]</div><p>With \\(a=3\\),</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=H(t-3)\\cos(2(t-3))}.\\]</div></div><p>Before \\(t=3\\), the Heaviside factor makes the signal zero. At \\(t=3\\), the cosine waveform is switched on with its internal clock reset to zero.</p>`,'Midterm 2 shifting review');
const l16Series=l16Board('Exam-style — ordinary power-series recurrence',`<p>${l16Recon}</p><p>For</p><div class="eq">\\[y''+x^2y=0,\\]</div><p>derive the recurrence about \\(x=0\\), identify the free coefficients, and write the first nonzero terms.</p>`,`<p>Use</p><div class="eq">\\[y=\\sum_{n=0}^{\\infty}a_nx^n,\\qquad y''=\\sum_{n=0}^{\\infty}(n+2)(n+1)a_{n+2}x^n.\\]</div><p>Also</p><div class="eq">\\[x^2y=\\sum_{n=2}^{\\infty}a_{n-2}x^n.\\]</div><p>The low powers give \\(a_2=a_3=0\\). For \\(n\\ge2\\),</p><div class="eq">\\[(n+2)(n+1)a_{n+2}+a_{n-2}=0,\\]</div><div class="whybox"><div class="eq">\\[\\boxed{a_{n+2}=-\\frac{a_{n-2}}{(n+2)(n+1)}}.\\]</div></div><p>Thus \\(a_0\\) and \\(a_1\\) are free:</p><div class="eq">\\[y=a_0\\left(1-\\frac{x^4}{12}+\\frac{x^8}{672}+\\cdots\\right)+a_1\\left(x-\\frac{x^5}{20}+\\frac{x^9}{1440}+\\cdots\\right).\\]</div>`,'§2.5.1 review · O’Neil Example 2.19 structure');
const l16Frob=l16Board('Exam-style — classify before using Frobenius',`<p>${l16Recon}</p><p>For</p><div class="eq">\\[x^2y''+5xy'+(x+4)y=0,\\]</div><p>(a) classify \\(x=0\\), (b) obtain the indicial equation, and (c) identify the root case.</p>`,`<p>Since the leading coefficient \\(P=x^2\\) vanishes at zero, the point is singular. Test regularity:</p><div class="eq">\\[x\\frac{Q}{P}=5,\\qquad x^2\\frac{R}{P}=x+4,\\]</div><p>both analytic at 0. Hence 0 is <b>regular singular</b>.</p><p>Try \\(y=\\sum c_nx^{n+r}\\). The lowest power gives</p><div class="eq">\\[[r(r-1)+5r+4]c_0=0.\\]</div><p>Because \\(c_0\\ne0\\),</p><div class="eq">\\[r^2+4r+4=(r+2)^2=0.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{r=-2\\text{ is a repeated root: Frobenius Case 2}.}\\]</div></div><p>The repeated root warns you that one ordinary Frobenius series is not the whole solution space; a logarithmic second-solution template is expected.</p>`,'§2.5.2 review · O’Neil Example 2.20 structure');
const l16Mixed=l16Board('Midterm 2 simulation — method selection before algebra',`<p>${l16Recon}</p><p>For each task, name the first method or theorem you would reach for and explain why:</p><p><b>A.</b> \\(Y(s)=e^{-2s}/(s^2+9)\\).<br><b>B.</b> Solve an IVP with \\(y''\\) and initial values at \\(t=0\\).<br><b>C.</b> Series solution at a point where the coefficient of \\(y''\\) is nonzero.<br><b>D.</b> Series solution at a regular singular point.</p>`,`<p><b>A:</b> Second shifting theorem, because \\(e^{-2s}\\) represents a time delay.</p><p><b>B:</b> Transform derivatives using the initial values; this converts the differential equation into an algebraic equation for \\(Y(s)\\).</p><p><b>C:</b> Ordinary power series \\(y=\\sum a_n(x-x_0)^n\\).</p><p><b>D:</b> Frobenius series \\(y=\\sum c_n(x-x_0)^{n+r}\\).</p><div class="whybox"><p><b>Exam habit:</b> classify the structure first. Most lost time comes from doing correct algebra with the wrong method.</p></div>`,'Midterm 2 synthesis');
const lesson16Units=[
{id:'l16-map',courseLesson:16,color:'#476a91',badge:'1',label:'Nov. 11 map',title:'Midterm 2 Preparation',subtitle:'Parts 3–4 only · Laplace transforms · power series · Frobenius',desc:'Organize the tested material before solving mixed problems.',lessons:[{title:'Scope',screens:[
{type:'teach',title:'What is actually on Midterm 2?',html:`<p>${l16Core}</p><p>The syllabus states that Midterm 2 covers <b>Parts 3 and 4</b>. The linear-algebra material beginning Nov. 16 comes afterward and is explicitly marked <b>not examined on Midterm 2</b>. So this review does not pull vectors or matrices forward.</p><p>Your two big toolboxes are: <b>Laplace methods</b> and <b>series methods</b>.</p>`},
{type:'teach',title:'The exam decision tree',html:`<p>${l16Explain}</p><p><b>Laplace side:</b> identify transforms → handle derivatives and initial data → simplify \\(Y(s)\\) → use partial fractions/completing the square/shifting → invert.</p><p><b>Series side:</b> classify the expansion point → ordinary power series if ordinary → Frobenius if regular singular → align indices → compare coefficients → solve recurrence → interpret the indicial roots.</p><p>Do not start manipulating symbols until you can say which branch of this decision tree you are on.</p>`},
{type:'quiz',title:'Scope check',q:'Which topic should NOT be introduced as tested material in this Midterm 2 review?',options:['Basis and dimension in Rⁿ','Second shifting theorem','Frobenius indicial roots'],answer:0,why:'The syllabus starts Part 5 linear algebra after the review and marks it not examined on Midterm 2.'}
]}]},
{id:'l16-laplace',courseLesson:16,color:'#34776e',badge:'2',label:'Laplace core',title:'Transforms, Inverses, and IVPs',subtitle:'table recognition · derivative rules · initial conditions',desc:'Make every transform step traceable.',lessons:[{title:'Core problems',screens:[l16Clone(l16P31),l16Clone(l16P32),
{type:'quiz',title:'Derivative transform',q:'If y(0)=a, what is L{yʹ}?',options:['sY(s)−a','sY(s)+a','Y(s)/s'],answer:0,why:'The initial value enters as the subtraction term in L{yʹ}=sY−y(0).'}]}]},
{id:'l16-shifts',courseLesson:16,color:'#795d9a',badge:'3',label:'Shifts & pulses',title:'First Shift, Second Shift, Heaviside',subtitle:'do not confuse frequency shifts with time delays',desc:'Separate the two shifting theorems conceptually.',lessons:[{title:'Shifts',screens:[
{type:'teach',title:'Two shifting theorems, two different ideas',html:`<p>${l16Explain}</p><p><b>First shifting:</b> \\(F(s-a)\\leftrightarrow e^{at}f(t)\\). The shift happens inside the \\(s\\)-expression and creates an exponential multiplier in time.</p><p><b>Second shifting:</b> \\(e^{-as}F(s)\\leftrightarrow H(t-a)f(t-a)\\). The exponential in \\(s\\) creates a delayed signal in time.</p><p>The visual clue \\(e^{-as}\\) should make you think <b>delay</b>, not merely “shift the denominator.”</p>`},l16Clone(l16Shift),
{type:'quiz',title:'Delay recognition',q:'What does a factor e⁻⁵ˢ most directly signal?',options:['A time delay of 5','Multiplication by e⁵ᵗ','A derivative in time'],answer:0,why:'It is the hallmark of the second shifting theorem.'}
]}]},
{id:'l16-series',courseLesson:16,color:'#9a6038',badge:'4',label:'Power series',title:'Ordinary-Point Series Under Exam Conditions',subtitle:'index shifts · low-index terms · recurrence',desc:'Prevent the bookkeeping mistakes that create false coefficients.',lessons:[{title:'Series',screens:[l16Clone(l16Series),
{type:'teach',title:'The low-index trap',html:`<p>${l16Explain}</p><p>When two reindexed sums begin at different values, you may not combine them immediately. First extract the unmatched low-power terms. Those equations often force coefficients such as \\(a_2\\) or \\(a_3\\) to zero.</p><p>If you skip that step, you can accidentally invent extra arbitrary constants—an immediate warning sign for a second-order ODE, which should have exactly two independent constants.</p>`},
{type:'quiz',title:'Sanity check',q:'At an ordinary point, how many free starting coefficients should a homogeneous second-order ODE normally leave?',options:['Two','Three','One'],answer:0,why:'They correspond to two independent initial data values.'}
]}]},
{id:'l16-frobenius',courseLesson:16,color:'#3e7287',badge:'5',label:'Frobenius',title:'Regular Singular Points and Indicial Roots',subtitle:'classification first · then r · then recurrence',desc:'Use the point classification to choose the series template.',lessons:[{title:'Frobenius',screens:[l16Clone(l16Frob),
{type:'teach',title:'Root-case checklist',html:`<p>If \\(r_1-r_2\\) is not a positive integer, expect two direct Frobenius series. If the root is repeated, expect the repeated-root logarithmic template. If the roots differ by a positive integer, the second solution may require a logarithm, but the log coefficient can sometimes vanish.</p><p>The root difference tells you the <b>form to try</b>; it does not let you skip the coefficient calculation.</p>`},
{type:'quiz',title:'Integer-separated roots',q:'If r₁−r₂=4, what is safe to conclude?',options:['Case 3 applies; a logarithmic term may be needed','A nonzero logarithm is guaranteed','There is only one solution'],answer:0,why:'Case 3 allows the logarithmic template, but its coefficient can be zero.'}
]}]},
{id:'l16-sim',courseLesson:16,color:'#536b48',badge:'6',label:'Mixed simulation',title:'Mini Midterm — Choose, Solve, Verify',subtitle:'mixed recognition instead of chapter-by-chapter cues',desc:'Practice switching methods without being told which chapter the question came from.',lessons:[{title:'Simulation',screens:[l16Mixed,l16P31,l16Shift,l16P32,l16Series,l16Frob]}]},
{id:'l16-check',courseLesson:16,color:'#856b37',badge:'7',label:'Error audit',title:'Five Checks Before You Box an Answer',subtitle:'initial values · shifts · algebra · recurrence · root case',desc:'Build verification into the solution rather than treating it as optional.',lessons:[{title:'Audit',screens:[
{type:'teach',title:'A fast verification routine',html:`<p>${l16Explain}</p><p><b>1.</b> IVP: substitute \\(t=0\\) into your final answer. <b>2.</b> Laplace inversion: mentally transform one term back to confirm the pair. <b>3.</b> Shift: check that delayed signals are zero before the switch time. <b>4.</b> Series: substitute the first few coefficients back and inspect the lowest powers. <b>5.</b> Frobenius: confirm the singular-point classification and root difference before choosing the second-solution form.</p><p>These checks are short enough to use in a 50-minute exam and catch high-cost sign/index mistakes.</p>`},
{type:'quiz',title:'Best series check',q:'What is the fastest useful check of a recurrence-derived series?',options:['Substitute the first few terms back into the ODE','Re-copy the recurrence','Assume matching coefficients guarantees no arithmetic error'],answer:0,why:'A truncated substitution exposes sign and index errors quickly.'}
]}]},
{id:'l16-mastery',courseLesson:16,color:'#a24458',badge:'8',label:'Mastery',title:'Midterm 2 Mastery Boards',subtitle:'authentic O’Neil + mixed exam synthesis',desc:'Solve without cues, then reveal complete worked solutions.',lessons:[{title:'Laplace',screens:[l16P31,l16P32,l16Shift]},{title:'Series',screens:[l16Series,l16Frob]},{title:'Mixed',screens:[l16Mixed]}]}
];

// Add one fresh authentic numbered problem so the review also contains a small textbook set across both exam parts.
const l16P2523=l16Board('O’Neil §2.5.2 Problem 3 — Frobenius review from a fresh textbook problem',`<p>${l16Book}</p><p>Find two independent solutions near \\(x=0\\) for</p><div class="eq">\\[x(x-1)y''+3y'-2y=0.\\]</div><p>Classify the root case before using the selected textbook forms.</p>`,`<p>At zero,</p><div class="eq">\\[x\\frac{Q}{P}=\\frac{3}{x-1},\\qquad x^2\\frac{R}{P}=\\frac{-2x}{x-1},\\]</div><p>are analytic, so zero is regular singular. The lowest Frobenius power gives</p><div class="eq">\\[r(4-r)=0,\\]</div><p>hence \\(r=4\\) and \\(r=0\\). The difference is the positive integer 4, so this is Case 3.</p><p>O’Neil’s selected answers simplify to</p><div class="whybox"><div class="eq">\\[\\boxed{y_1=\\frac{x^4}{(1-x)^2},\\qquad y_2=\\frac{3-4x}{(1-x)^2}}.\\]</div></div><p>The first begins</p><div class="eq">\\[y_1=x^4+2x^5+3x^6+4x^7+5x^8+\\cdots.\\]</div><p>The second is independent and has no logarithm despite the integer root separation. Direct substitution verifies both exact expressions.</p>`,'§2.5.2 · Problem 3');
const l16FrobUnitBook=lesson16Units.find(u=>u&&u.id==='l16-frobenius');
if(l16FrobUnitBook)l16FrobUnitBook.lessons[0].screens.push(l16Clone(l16P2523));

if(!units.some(u=>u&&u.id==='l16-map'))units.push(...lesson16Units);
if(courseLessons[14])courseLessons[14].status='complete';
courseLessons[15]={number:16,title:'Midterm 2 Preparation',subtitle:'Nov. 11 · Parts 3–4 · Laplace + power series/Frobenius',status:'current'};
// Reconstruction pass: mastery must transfer ideas rather than replay guided examples.
const l16Transfer=[
l16Board('Transfer 1 — derivative transform with two initial data',`<p>${l16Recon}</p><p>Without solving the IVP, transform \\(y''+3y'=e^{-t}\\), where \\(y(0)=2\\), \\(y'(0)=-1\\), into an algebraic equation for \\(Y(s)\\).</p>`,`<p>Use \\(\\mathcal L\\{y''\\}=s^2Y-sy(0)-y'(0)=s^2Y-2s+1\\) and \\(\\mathcal L\\{y'\\}=sY-2\\).</p><div class="eq">\\[(s^2Y-2s+1)+3(sY-2)=\\frac1{s+1}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{(s^2+3s)Y-2s-5=\\frac1{s+1}}.\\]</div></div><p>The common trap is losing the sign on \\(-y'(0)\\): here \\(y'(0)=-1\\), so that contribution is \\(+1\\).</p>`,'Original transfer · Laplace IVP'),
l16Board('Transfer 2 — distinguish first and second shifting',`<p>${l16Recon}</p><p>Match each expression to its time-domain effect: (A) \\(F(s-4)\\); (B) \\(e^{-4s}F(s)\\).</p>`,`<p><b>A:</b> first shifting theorem: \\(F(s-4)\\leftrightarrow e^{4t}f(t)\\).</p><p><b>B:</b> second shifting theorem: \\(e^{-4s}F(s)\\leftrightarrow H(t-4)f(t-4)\\).</p><div class="whybox"><p>An exponential multiplying the transform means a <b>time delay</b>; replacing \\(s\\) by \\(s-a\\) means an <b>exponential multiplier</b> in time.</p></div>`,'Original diagnostic · shifting theorems'),
l16Board('Transfer 3 — ordinary-series low-index audit',`<p>${l16Recon}</p><p>For \\(y''+xy=0\\), derive the recurrence and identify the unmatched low-index equation.</p>`,`<p>Write \\(y''=\\sum_{n=0}^\\infty(n+2)(n+1)a_{n+2}x^n\\) and \\(xy=\\sum_{n=1}^\\infty a_{n-1}x^n\\).</p><p>The unmatched \\(x^0\\) term gives \\(2a_2=0\\), hence \\(a_2=0\\). For \\(n\\ge1\\),</p><div class="eq">\\[(n+2)(n+1)a_{n+2}+a_{n-1}=0,\\]</div><div class="eq">\\[\\boxed{a_{n+2}=-\\frac{a_{n-1}}{(n+2)(n+1)}}.\\]</div><p>The free coefficients remain \\(a_0,a_1\\), as expected for a second-order homogeneous ODE.</p>`,'Original transfer · power series'),
l16Board('Transfer 4 — regular singular classification',`<p>${l16Recon}</p><p>Classify \\(x=0\\) for \\(x^2y''+xy'+(x^2-1)y=0\\) and obtain the indicial equation.</p>`,`<p>Here \\(P=x^2,Q=x,R=x^2-1\\). The regular-singular tests are</p><div class="eq">\\[xQ/P=1,\\qquad x^2R/P=x^2-1,\\]</div><p>both analytic at zero. Thus zero is regular singular. The lowest-power coefficient from \\(y=\\sum c_nx^{n+r}\\) is</p><div class="eq">\\[[r(r-1)+r-1]c_0=(r^2-1)c_0.\\]</div><p>Since \\(c_0\\ne0\\),</p><div class="eq">\\[\\boxed{r^2-1=0,\\quad r=1,-1}.\\]</div><p>The roots differ by the positive integer 2, so this is Case 3; a logarithmic term may be needed, but is not guaranteed.</p>`,'Original transfer · Frobenius'),
l16Board('Transfer 5 — verification catches a false delayed answer',`<p>${l16Recon}</p><p>A student claims \\(\\mathcal L^{-1}\\{e^{-2s}/(s^2+1)\\}=H(t-2)\\sin t\\). Diagnose the error and repair it.</p>`,`<p>The unshifted inverse is \\(\\sin t\\), but the second shifting theorem requires the <b>entire waveform</b> to be evaluated at \\(t-a\\):</p><div class="eq">\\[\\boxed{H(t-2)\\sin(t-2)}.\\]</div><p>The student's formula switches on the old clock at \\(t=2\\) instead of resetting the waveform clock. A quick check is the theorem template \\(e^{-as}F(s)\\leftrightarrow H(t-a)f(t-a)\\).</p>`,'Original diagnostic · theorem use'),
l16Board('Transfer 6 — mixed method selection gate',`<p>${l16Recon}</p><p>Choose the first tool for each: (A) \\(e^{-3s}(s+1)/((s+1)^2+9)\\); (B) a second-order ODE at an ordinary point; (C) an ODE whose leading coefficient vanishes at the expansion point but passes the regular-singular tests.</p>`,`<p><b>A:</b> combine first-shift recognition inside the rational factor with the second shifting theorem for \\(e^{-3s}\\).</p><p><b>B:</b> ordinary power series.</p><p><b>C:</b> Frobenius series and indicial equation.</p><div class="whybox"><p>Method selection precedes algebra. This problem tests whether the structural cues—not chapter labels—control the choice.</p></div>`,'Original mastery · recognition'),
l16Board('Transfer 7 — periodic forcing from one period',`<p>${l16Recon}</p><p>A periodic input has period \\(T=2\\) and on one period is</p><div class="eq">\\[f(t)=t,\\qquad 0\\le t<2.\\]</div><p>Write its Laplace transform using the periodic-function theorem. You do not need to simplify the integral completely.</p>`,`<p>For a period-\\(T\\) function,</p><div class="eq">\\[F(s)=\\frac{1}{1-e^{-sT}}\\int_0^T e^{-st}f(t)\\,dt.\\]</div><p>Here \\(T=2\\) and \\(f(t)=t\\) on the generating interval, so</p><div class="whybox"><div class="eq">\\[\\boxed{F(s)=\\frac{1}{1-e^{-2s}}\\int_0^2 t e^{-st}\\,dt}.\\]</div></div><p>The denominator represents the infinite repetition. A common mistake is to transform only the first period and forget the geometric repetition factor.</p>`,'Original transfer · periodic forcing'),
l16Board('Transfer 8 — staircase versus periodic signal',`<p>${l16Recon}</p><p>A command jumps by +1 at \\(t=1\\), +2 at \\(t=3\\), and -1 at \\(t=5\\), with no later jumps. Write the signal with Heaviside functions and explain why the periodic-transform formula is inappropriate.</p>`,`<p>Add each change at the instant it occurs:</p><div class="eq">\\[\\boxed{r(t)=H(t-1)+2H(t-3)-H(t-5)}.\\]</div><p>This is a finite staircase. After \\(t=5\\) its level stays at 2; no waveform repeats with a fixed period. Therefore the periodic theorem does not apply. Its transform is simply</p><div class="eq">\\[R(s)=\\frac{e^{-s}+2e^{-3s}-e^{-5s}}s.\\]</div>`,'Original diagnostic · staircase'),
l16Board('Transfer 9 — convolution and impulse response',`<p>${l16Recon}</p><p>A zero-state LTI model has transfer function</p><div class="eq">\\[G(s)=\\frac1{(s+1)(s+3)}.\\]</div><p>(a) Find the impulse response. (b) For an arbitrary input \\(f(t)\\), write the output as a convolution.</p>`,`<p>Partial fractions give</p><div class="eq">\\[G(s)=\\frac12\\left(\\frac1{s+1}-\\frac1{s+3}\\right),\\]</div><p>so the impulse response is</p><div class="eq">\\[\\boxed{g(t)=\\frac12(e^{-t}-e^{-3t})}.\\]</div><p>For arbitrary zero-state input, multiplication \\(Y=GF\\) in transform space becomes convolution in time:</p><div class="whybox"><div class="eq">\\[\\boxed{y(t)=\\int_0^t \\frac12[e^{-(t-\\tau)}-e^{-3(t-\\tau)}]f(\\tau)\\,d\\tau}.\\]</div></div><p>Pointwise multiplication \\(g(t)f(t)\\) would be the wrong operation.</p>`,'Original transfer · convolution and impulse response'),
l16Board('Transfer 10 — coupled system by Laplace',`<p>${l16Recon}</p><p>Use Laplace transforms to solve</p><div class="eq">\\[x'+y=0,\\qquad y'-x=0,\\qquad x(0)=0,\\quad y(0)=1.\\]</div>`,`<p>Transform both equations:</p><div class="eq">\\[sX+Y=0,\\qquad sY-1-X=0.\\]</div><p>From the first, \\(Y=-sX\\). Substitute into the second:</p><div class="eq">\\[-s^2X-1-X=0\\quad\\Rightarrow\\quad X=-\\frac1{s^2+1}.\\]</div><p>Thus \\(Y=s/(s^2+1)\\). Invert:</p><div class="whybox"><div class="eq">\\[\\boxed{x(t)=-\\sin t,\\qquad y(t)=\\cos t}.\\]</div></div><p>Differentiate directly: \\(x'+y=-\\cos t+\\cos t=0\\) and \\(y'-x=-\\sin t+\\sin t=0\\), with the stated initial data.</p>`,'Original transfer · systems by Laplace')
];
const l16SimUnit=units.find(u=>u&&u.id==='l16-sim');
if(l16SimUnit){l16SimUnit.lessons=[{title:'Unseen mixed simulation',screens:l16Transfer.slice(0,4)}];l16SimUnit.subtitle='unseen transfer · no replay of guided examples';l16SimUnit.desc='A fresh mini-midterm that requires method recognition without repeating the teaching boards.';}
const l16MasteryUnit=units.find(u=>u&&u.id==='l16-mastery');
if(l16MasteryUnit){l16MasteryUnit.title='Midterm 2 Transfer Mastery';l16MasteryUnit.subtitle='10 original transfer/diagnostic boards · full Parts 3–4 coverage';l16MasteryUnit.desc='Recognition, theorem use, bookkeeping, verification and transfer across the full Laplace, series and Frobenius syllabus without replaying the teaching banks.';l16MasteryUnit.lessons=[{title:'Laplace foundations',screens:l16Transfer.slice(0,2)},{title:'Series & Frobenius transfer',screens:l16Transfer.slice(2,4)},{title:'Diagnostics & method selection',screens:l16Transfer.slice(4,6)},{title:'Periodic & staircase forcing',screens:l16Transfer.slice(6,8)},{title:'Convolution, impulse response & systems',screens:l16Transfer.slice(8,10)}];}
if(typeof renderCourseMap==='function')renderCourseMap();
if(typeof render==='function')render();