/* Lesson 20 — Nov. 30: homogeneous/nonhomogeneous linear systems, null spaces, consistency and parameterized solutions. */
const l20Core='<span class="supplementalTag">Core · Nov. 30 syllabus · Part 5</span>',l20Book='<span class="supplementalTag">Authentic textbook · supplied O’Neil §§11.3–11.4</span>',l20Explain='<span class="supplementalTag">Expanded explanation · Lesson 1 depth standard</span>',l20Recon='<span class="supplementalTag">Syllabus-aligned reconstruction · not claimed as an O’Neil example</span>';
function l20Board(title,prompt,solution,section){return {type:'bookproblem',bookSection:section,title,prompt,solution};} function l20Clone(s){return s?{...s,inlineBookPractice:true}:null;}
const l20Hom=l20Board('Homogeneous system — turn free variables into a basis',`<p>${l20Recon}</p><p>Solve \\(AX=0\\) when</p><div class="eq">\\[A_R=\\begin{pmatrix}1&0&2&-1\\\\0&1&-3&2\\\\0&0&0&0\\end{pmatrix}.\\]</div><p>Give the null-space basis and its dimension.</p>`,`<p>The pivot variables are \\(x_1,x_2\\); let the free variables be \\(x_3=s,x_4=t\\).</p><div class="eq">\\[x_1=-2s+t,\\qquad x_2=3s-2t.\\]</div><p>Therefore</p><div class="eq">\\[X=s\\begin{pmatrix}-2\\\\3\\\\1\\\\0\\end{pmatrix}+t\\begin{pmatrix}1\\\\-2\\\\0\\\\1\\end{pmatrix}.\\]</div><p>The two direction vectors are independent, so they form a basis for \\(N(A)\\):</p><div class="eq">\\[\\boxed{\\dim N(A)=2=4-\\operatorname{rank}(A)}.\\]</div><p>Verification: multiplying either basis vector by the reduced matrix gives the zero vector; row equivalence preserves the homogeneous solution set.</p>`,'§11.3 homogeneous systems');
const l20Cons=l20Board('Consistency test — detect an impossible row',`<p>${l20Book}</p><p>O’Neil’s nonhomogeneous discussion shows that a reduced augmented row such as</p><div class="eq">\\[\\begin{bmatrix}0&0&|&-4\\end{bmatrix}\\]</div><p>makes a system inconsistent. Explain why and state the rank test.</p>`,`<p>The row represents</p><div class="eq">\\[0x_1+0x_2=-4,\\]</div><p>or \\(0=-4\\), which is impossible. Thus there is no solution.</p><p>Equivalently, the coefficient matrix has fewer pivots than the augmented matrix:</p><div class="eq">\\[\\boxed{\\operatorname{rank}(A)<\\operatorname{rank}([A|B])\\Rightarrow\\text{inconsistent}.}\\]</div><p>If the ranks are equal, the system is consistent.</p>`,'§11.4 consistency');
const l20Nonhom=l20Board('Nonhomogeneous system — parameterize all solutions',`<p>${l20Recon}</p><p>Solve the reduced augmented system</p><div class="eq">\\[\\left[\\begin{array}{cccc|c}1&0&2&-1&3\\\\0&1&-3&2&-1\\\\0&0&0&0&0\\end{array}\\right].\\]</div>`,`<p>Again let \\(x_3=s,x_4=t\\). Then</p><div class="eq">\\[x_1=3-2s+t,\\qquad x_2=-1+3s-2t.\\]</div><p>Separate one particular solution from the free homogeneous directions:</p><div class="eq">\\[\\boxed{X=\\begin{pmatrix}3\\\\-1\\\\0\\\\0\\end{pmatrix}+s\\begin{pmatrix}-2\\\\3\\\\1\\\\0\\end{pmatrix}+t\\begin{pmatrix}1\\\\-2\\\\0\\\\1\\end{pmatrix}}.\\]</div><p>This displays the general principle \\(X=X_p+X_h\\): one particular solution plus every solution of the associated homogeneous system.</p>`,'§11.4 parameterized solutions');
const l20Unique=l20Board('Unique, infinite, or none?',`<p>${l20Recon}</p><p>A system \\(AX=B\\) has 4 unknowns. Classify the solution set in each case: (a) both ranks are 4; (b) both ranks are 3; (c) \\(\\operatorname{rank}(A)=3\\) but \\(\\operatorname{rank}([A|B])=4\\).</p>`,`<p>(a) Consistent with four pivots and no free variables: <b>one unique solution</b>.</p><p>(b) Consistent but one free variable: <b>infinitely many solutions</b>, with one parameter.</p><p>(c) The augmented rank is larger: an impossible row occurs, so <b>no solution</b>.</p><div class="whybox"><p>First ask <i>is it consistent?</i> Only then count free variables to distinguish unique from infinitely many solutions.</p></div>`,'§§11.3–11.4 classification');
const l20Ex1115=l20Board('O’Neil Example 11.15 — homogeneous solution space',`<p>${l20Book}</p><p>For the authentic O’Neil system</p><div class="eq">\\[\\begin{aligned}x_1-3x_2+2x_3&=0,\\\\-2x_1+x_2-3x_3&=0,\\end{aligned}\\]</div><p>use the supplied reduced coefficient matrix to write the general solution and identify a basis.</p>`,`<p>O’Neil reduces the coefficient matrix to</p><div class="eq">\\[A_R=\\begin{pmatrix}1&0&7/5\\\\0&1&-1/5\\end{pmatrix}.\\]</div><p>Thus</p><div class="eq">\\[x_1=-\\frac75x_3,\\qquad x_2=\\frac15x_3.\\]</div><p>Let \\(x_3=5\\alpha\\). Then</p><div class="eq">\\[\\boxed{X=\\alpha\\begin{pmatrix}-7\\\\1\\\\5\\end{pmatrix}}.\\]</div><p>The solution space is one-dimensional with basis \\(\\{(-7,1,5)^T\\}\\). O’Neil uses this example to motivate</p><div class="eq">\\[\\dim(\\text{solution space})=m-\\operatorname{rank}(A).\\]</div>`,'§11.3 · Example 11.15');
const l20Ex1119=l20Board('O’Neil Example 11.19 — inconsistency appears as 0 = −4',`<p>${l20Book}</p><p>O’Neil considers</p><div class="eq">\\[2x_1-3x_2=6,\\qquad4x_1-6x_2=8.\\]</div><p>Explain why reduction proves the system inconsistent.</p>`,`<p>Reducing the augmented matrix gives a second row equivalent to</p><div class="eq">\\[0x_1+0x_2=-4.\\]</div><p>This is impossible. The coefficient block has one nonzero row while the full augmented matrix has two, so</p><div class="eq">\\[\\boxed{\\operatorname{rank}(A)<\\operatorname{rank}([A|B])}.\\]</div><p>Hence the system is inconsistent.</p>`,'§11.4 · Example 11.19');
const lesson20Units=[
{id:'l20-map',courseLesson:20,color:'#476a91',badge:'1',label:'Nov. 30 map',title:'Linear Systems & Solution Spaces',subtitle:'homogeneous · null space · consistency',desc:'Move from row reduction to the structure of complete solution sets.',lessons:[{title:'Map',screens:[{type:'teach',title:'Textbook numbering reconciliation',html:`<p>${l20Core}</p><p>The syllabus labels this O’Neil §§6.3–6.4. In the supplied 8th SI edition the matching material is <b>§11.3 Solution of Homogeneous Linear Systems</b> and <b>§11.4 Solution of Nonhomogeneous Linear Systems</b>.</p>`},{type:'teach',title:'What changes after Lesson 19?',html:`<p>${l20Explain}</p><p>Lesson 19 taught how to reduce a matrix. Now the reduced form must be <b>interpreted</b>: which variables are pivots, which are free, whether a system is possible at all, and how to write every solution without losing any degrees of freedom.</p>`}]}]},
{id:'l20-hom',courseLesson:20,color:'#34776e',badge:'2',label:'Homogeneous',title:'Homogeneous Systems AX = 0',subtitle:'trivial solution · free variables · null space',desc:'Understand why zero is always a solution and when more solutions exist.',lessons:[{title:'Homogeneous',screens:[{type:'teach',title:'Why homogeneous systems are special',html:`<p>${l20Book}</p><p>A homogeneous system has the form \\(AX=0\\). The zero vector always works, so the system is never inconsistent. If every column is a pivot, \\(X=0\\) is the only solution. If there is a free variable, nonzero solutions exist.</p><p>The set of all solutions is the <b>null space</b> \\(N(A)\\), and it is a subspace because sums and scalar multiples of solutions remain solutions.</p>`},l20Clone(l20Ex1115),l20Clone(l20Hom)]}]},
{id:'l20-null',courseLesson:20,color:'#795d9a',badge:'3',label:'Null space',title:'Basis and Dimension of the Null Space',subtitle:'one direction per free parameter',desc:'Translate parameters into basis vectors.',lessons:[{title:'Null space',screens:[{type:'teach',title:'From equations to a basis',html:`<p>${l20Explain}</p><p>After RREF, assign a parameter to each free variable. Write the solution vector as a linear combination of parameter vectors. Those vectors span the null space; after reduction they naturally give an independent basis.</p><div class="eq">\\[\\boxed{\\dim N(A)=n-\\operatorname{rank}(A)}\\]</div><p>where \\(n\\) is the number of columns/unknowns.</p>`},{type:'quiz',title:'Dimension check',q:'A homogeneous system has 7 unknowns and rank 4. How many independent free directions?',options:['3','4','7'],answer:0,why:'Nullity = 7 − 4 = 3.'}]}]},
{id:'l20-nonhom',courseLesson:20,color:'#9a6038',badge:'4',label:'Nonhomogeneous',title:'Nonhomogeneous Systems AX = B',subtitle:'augmented matrix · consistency',desc:'Learn why the right-hand side can make a system impossible.',lessons:[{title:'Consistency',screens:[{type:'teach',title:'The augmented column matters',html:`<p>${l20Book}</p><p>For \\(AX=B\\), reduce the <b>augmented matrix</b> \\([A|B]\\). If reduction creates a row with all-zero coefficients but a nonzero right-hand side, the system asserts \\(0=c\\) with \\(c\\ne0\\), so it is inconsistent.</p>`},l20Clone(l20Ex1119),l20Clone(l20Cons)]}]},
{id:'l20-param',courseLesson:20,color:'#3e7287',badge:'5',label:'Parameters',title:'Parameterized Solution Sets',subtitle:'particular + homogeneous',desc:'Write infinitely many solutions in a form that exposes their geometry.',lessons:[{title:'Parameterization',screens:[{type:'teach',title:'Why X = Xp + Xh',html:`<p>${l20Explain}</p><p>If \\(AX_p=B\\) and \\(AX_h=0\\), then \\(A(X_p+X_h)=B\\). Conversely, subtracting a particular solution from any solution of \\(AX=B\\) produces a homogeneous solution. Therefore</p><div class="eq">\\[\\boxed{X=X_p+X_h}.\\]</div><p>Geometrically, a consistent nonhomogeneous solution set is a translated copy of the null space.</p>`},l20Clone(l20Nonhom)]}]},
{id:'l20-class',courseLesson:20,color:'#536b48',badge:'6',label:'Classification',title:'Consistency, Uniqueness & Freedom',subtitle:'rank first · free variables second',desc:'Classify a system without guessing.',lessons:[{title:'Classification',screens:[l20Clone(l20Unique),{type:'quiz',title:'Consistent but underdetermined',q:'rank(A)=rank([A|B])=2 for a system with 5 unknowns. What follows?',options:['Infinitely many solutions with 3 free parameters','No solution','Exactly one solution'],answer:0,why:'Equal ranks give consistency; 5−2=3 free variables give infinitely many solutions.'}]}]},
{id:'l20-method',courseLesson:20,color:'#856b37',badge:'7',label:'Workflow',title:'A Reliable Systems Workflow',subtitle:'augment · reduce · consistency · parameterize',desc:'Use the same decision process on every linear system.',lessons:[{title:'Workflow',screens:[{type:'teach',title:'Four questions in order',html:`<p>${l20Explain}</p><p><b>1.</b> Is the system homogeneous? <b>2.</b> Reduce \\(A\\) or \\([A|B]\\) appropriately. <b>3.</b> For nonhomogeneous systems, check for an impossible row before doing anything else. <b>4.</b> Identify pivots/free variables and parameterize.</p><p>Do not call a system “underdetermined” merely because it has many unknowns; inconsistency must be ruled out first.</p>`}]}]},
{id:'l20-mastery',courseLesson:20,color:'#a24458',badge:'8',label:'Mastery',title:'Nov. 30 Transfer Mastery',subtitle:'6 unseen problems · null spaces, consistency, parameterization',desc:'The mastery set now tests recognition and transfer rather than repeating the guided systems.',lessons:[{title:'Homogeneous transfer',screens:[
 l20Board('Transfer 1 — build a null-space basis from RREF',`<p>${l20Recon}</p><p>For</p><div class="eq">\\[A_R=\\begin{pmatrix}1&2&0&-1&3\\\\0&0&1&4&-2\\end{pmatrix},\\]</div><p>write the general solution of \\(AX=0\\), a basis for \\(N(A)\\), and its dimension.</p>`,`<p>Pivot variables are \\(x_1,x_3\\); let \\(x_2=s,x_4=t,x_5=u\\). Then</p><div class="eq">\\[x_1=-2s+t-3u,\\qquad x_3=-4t+2u.\\]</div><p>Hence</p><div class="eq">\\[X=s\\begin{pmatrix}-2\\\\1\\\\0\\\\0\\\\0\\end{pmatrix}+t\\begin{pmatrix}1\\\\0\\\\-4\\\\1\\\\0\\end{pmatrix}+u\\begin{pmatrix}-3\\\\0\\\\2\\\\0\\\\1\\end{pmatrix}.\\]</div><p>These parameter vectors form a basis, so \\(\\boxed{\\dim N(A)=3}\\).</p>`,'Original transfer · homogeneous systems'),
 l20Board('Transfer 2 — nontrivial solution without solving everything',`<p>${l20Recon}</p><p>A homogeneous system has 4 unknowns and coefficient rank 3. Must it have a nonzero solution? Explain without computing the full RREF.</p>`,`<p>Yes. Rank 3 leaves</p><div class="eq">\\[4-3=1\\]</div><p>free direction. Therefore the solution space has positive dimension and contains nonzero vectors:</p><div class="eq">\\[\\boxed{\\dim N(A)=1}.\\]</div><p>The trivial solution still exists, but it is not the only solution.</p>`,'Original diagnostic · homogeneous structure') ]},{title:'Consistency transfer',screens:[
 l20Board('Transfer 3 — read inconsistency from a reduced augmented matrix',`<p>${l20Recon}</p><p>Classify the system represented by</p><div class="eq">\\[\\left[\\begin{array}{ccc|c}1&0&2&3\\\\0&1&-1&4\\\\0&0&0&5\\end{array}\\right].\\]</div>`,`<p>The last row states \\(0=5\\), which is impossible. Thus</p><div class="eq">\\[\\boxed{\\text{no solution}}.\\]</div><p>The coefficient rank is 2 while the augmented rank is 3, so the rank criterion gives the same conclusion.</p>`,'Original transfer · consistency'),
 l20Board('Transfer 4 — parameterize a fresh affine solution set',`<p>${l20Recon}</p><p>Solve</p><div class="eq">\\[\\left[\\begin{array}{ccc|c}1&0&2&5\\\\0&1&-3&-2\\end{array}\\right].\\]</div>`,`<p>Let the free variable \\(x_3=t\\). Then</p><div class="eq">\\[x_1=5-2t,\\qquad x_2=-2+3t.\\]</div><p>Therefore</p><div class="eq">\\[\\boxed{X=\\begin{pmatrix}5\\\\-2\\\\0\\end{pmatrix}+t\\begin{pmatrix}-2\\\\3\\\\1\\end{pmatrix}}.\\]</div><p>The first vector is one particular solution; the direction vector spans the associated homogeneous null space.</p>`,'Original transfer · parameterized solutions') ]},{title:'Interpretation & traps',screens:[
 l20Board('Transfer 5 — particular solution choice is not unique',`<p>${l20Recon}</p><p>A consistent system has general solution \\(X=X_p+N(A)\\). A student claims there is only one valid particular solution \\(X_p\\). Diagnose the claim.</p>`,`<p>False. If \\(X_p\\) is one particular solution and \\(h\\in N(A)\\), then</p><div class="eq">\\[A(X_p+h)=AX_p+Ah=B+0=B.\\]</div><p>So \\(X_p+h\\) is another particular solution. Different choices of \\(X_p\\) describe the same affine solution set once the full homogeneous part is included.</p>`,'Original diagnostic · affine solution sets'),
 l20Board('Transfer 6 — unique versus infinite solutions',`<p>${l20Recon}</p><p>A consistent system has 6 unknowns and rank 4. Can it have a unique solution?</p>`,`<p>No. Consistency only rules out “none.” With six unknowns and rank four there are two free variables:</p><div class="eq">\\[6-4=2.\\]</div><p>Therefore the system has an infinite two-parameter family of solutions. A unique solution would require rank 6.</p>`,'Original diagnostic · uniqueness') ]}]}
];
if(!units.some(u=>u&&u.id==='l20-map'))units.push(...lesson20Units); if(courseLessons[18])courseLessons[18].status='complete'; courseLessons[19]={number:20,title:'Linear Systems & Solution Spaces',subtitle:'Nov. 30 · supplied O’Neil §§11.3–11.4',status:'current'};

// Spaced retrieval: revisit pre-Midterm-1 material after a substantial delay without adding new theory.
const l20Spaced=[
 l20Board('Cumulative retrieval · first-order method selection',`<p><span class="supplementalTag">Spaced retrieval · Parts 1–2 · no new theory</span></p><p>For each equation, name the first method you would use and give the structural clue. Do not solve.</p><p><b>A.</b> \\(y'+2xy=x\\).<br><b>B.</b> \\(y'=x(1+y^2)\\).<br><b>C.</b> \\(y'+y=xy^3\\).</p>`,`<p><b>A — linear first order:</b> it has standard form \\(y'+P(x)y=Q(x)\\).</p><p><b>B — separable:</b> \\(dy/(1+y^2)=x\\,dx\\).</p><p><b>C — Bernoulli:</b> it has \\(y'+P(x)y=Q(x)y^n\\) with \\(n=3\\).</p><div class="whybox"><p>The point of delayed retrieval is classification from structure after the chapter labels are no longer nearby.</p></div>`,'Spaced cumulative retrieval · Parts 1–2'),
 l20Board('Cumulative retrieval · higher-order resonance',`<p><span class="supplementalTag">Spaced retrieval · Parts 1–2 · no new theory</span></p><p>For</p><div class="eq">\\[y''+4y=\\cos 2x,\\]</div><p>state the homogeneous basis and the correct undetermined-coefficients trial form. Explain the modification.</p>`,`<p>The characteristic roots are \\(\\pm2i\\), so</p><div class="eq">\\[y_h=C_1\\cos2x+C_2\\sin2x.\\]</div><p>The naive trial \\(A\\cos2x+B\\sin2x\\) lies entirely in the homogeneous solution space. Multiply the whole trial by \\(x\\):</p><div class="eq">\\[\\boxed{y_p=x(A\\cos2x+B\\sin2x)}.\\]</div><p>This is resonance/overlap: the extra factor moves the trial out of the homogeneous null space.</p>`,'Spaced cumulative retrieval · Parts 1–2')
];
const l20MasteryUnit=units.find(u=>u&&u.id==='l20-mastery');
if(l20MasteryUnit&&!l20MasteryUnit.lessons.some(l=>l.title==='Cumulative retrieval · Parts 1–2'))l20MasteryUnit.lessons.push({title:'Cumulative retrieval · Parts 1–2',screens:l20Spaced});

const l20P1131=l20Board('O’Neil §11.3 Problem 1 — homogeneous solution space',`<p>${l20Book}</p><p>Find the general solution, a basis, and the dimension of the solution space for</p><div class="eq">\\[\\begin{aligned}x_1+2x_2-x_3+x_4&=0,\\\\x_2-x_3+x_4&=0.\\end{aligned}\\]</div>`,`<p>Reduction gives</p><div class="eq">\\[A_R=\\begin{pmatrix}1&0&1&-1\\\\0&1&-1&1\\end{pmatrix}.\\]</div><p>Let \\(x_3=s\\), \\(x_4=t\\). Then</p><div class="eq">\\[x_1=-s+t,\\qquad x_2=s-t.\\]</div><p>Hence</p><div class="eq">\\[X=s\\begin{pmatrix}-1\\\\1\\\\1\\\\0\\end{pmatrix}+t\\begin{pmatrix}1\\\\-1\\\\0\\\\1\\end{pmatrix}.\\]</div><p>The two parameter vectors are independent, so</p><div class="eq">\\[\\boxed{\\dim S=2,\\quad \\mathcal B=\\{(-1,1,1,0)^T,(1,-1,0,1)^T\\}}.\\]</div>`,'§11.3 · Problem 1');
const l20P1141=l20Board('O’Neil §11.4 Problem 1 — solve a nonhomogeneous system',`<p>${l20Book}</p><p>Find the general solution, or show inconsistency:</p><div class="eq">\\[\\begin{aligned}3x_1-2x_2+x_3&=6,\\\\x_1+10x_2-x_3&=2,\\\\-3x_1-2x_2+x_3&=0.\\end{aligned}\\]</div>`,`<p>The reduced augmented matrix is</p><div class="eq">\\[\\left[\\begin{array}{ccc|c}1&0&0&1\\\\0&1&0&1/2\\\\0&0&1&4\\end{array}\\right].\\]</div><p>There is a pivot in every unknown column and no contradictory row, so the system has the unique solution</p><div class="eq">\\[\\boxed{(x_1,x_2,x_3)=(1,1/2,4)}.\\]</div><p>Substitution checks all three original equations.</p>`,'§11.4 · Problem 1');
const l20P1144=l20Board('O’Neil §11.4 Problem 4 — detect inconsistency',`<p>${l20Book}</p><p>Determine whether</p><div class="eq">\\[\\begin{aligned}2x_1-3x_2&=1,\\\\-x_1+3x_2&=0,\\\\x_1-4x_2&=3\\end{aligned}\\]</div><p>has a solution.</p>`,`<p>Reducing the augmented matrix produces a contradictory row; equivalently its RREF is</p><div class="eq">\\[\\left[\\begin{array}{cc|c}1&0&0\\\\0&1&0\\\\0&0&1\\end{array}\\right].\\]</div><p>The last row means \\(0=1\\), so</p><div class="eq">\\[\\boxed{\\text{the system is inconsistent}.}\\]</div><p>As a quick check, the first two equations imply \\(x_1=1,x_2=1/3\\), which fails the third equation.</p>`,'§11.4 · Problem 4');
const l20HomUnit=units.find(u=>u&&u.id==='l20-hom');
if(l20HomUnit&&!l20HomUnit.lessons[0].screens.some(s=>s.title===l20P1131.title))l20HomUnit.lessons[0].screens.push(l20Clone(l20P1131));
const l20NonhomUnit=units.find(u=>u&&u.id==='l20-nonhom');
if(l20NonhomUnit){
 if(!l20NonhomUnit.lessons[0].screens.some(s=>s.title===l20P1141.title))l20NonhomUnit.lessons[0].screens.push(l20Clone(l20P1141));
 if(!l20NonhomUnit.lessons[0].screens.some(s=>s.title===l20P1144.title))l20NonhomUnit.lessons[0].screens.push(l20Clone(l20P1144));
}

if(typeof renderCourseMap==='function')renderCourseMap();if(typeof render==='function')render();