/* Lesson 22 — Dec. 7: eigenvalues/eigenvectors, eigenspaces, diagonalization, special matrices. */
const l22Core='<span class="supplementalTag">Core · Dec. 7 syllabus · Part 5</span>',l22Book='<span class="supplementalTag">Authentic textbook concept · supplied O’Neil §§12.1–12.3</span>',l22Explain='<span class="supplementalTag">Expanded explanation · Lesson 1 depth standard</span>',l22Recon='<span class="supplementalTag">Syllabus-aligned reconstruction · not claimed as an O’Neil example</span>';
function l22Board(title,prompt,solution,section){return {type:'bookproblem',bookSection:section,title,prompt,solution};} function l22Clone(s){return s?{...s,inlineBookPractice:true}:null;}
const l22Eig=l22Board('Eigenvalues and eigenspaces — complete calculation',`<p>${l22Recon}</p><p>For</p><div class="eq">\\[A=\\begin{pmatrix}4&1\\\\2&3\\end{pmatrix},\\]</div><p>find all eigenvalues and a basis for each eigenspace.</p>`,`<p>An eigenvector \\(v\\ne0\\) satisfies \\(Av=\\lambda v\\), so equivalently</p><div class="eq">\\[(\\lambda I-A)v=0.\\]</div><p>A nonzero solution exists only when \\(\\lambda I-A\\) is singular. Using O’Neil’s characteristic-polynomial convention,</p><div class="eq">\\[0=p_A(\\lambda)=\\det(\\lambda I-A)=(\\lambda-4)(\\lambda-3)-2=\\lambda^2-7\\lambda+10.\\]</div><div class="eq">\\[(\\lambda-5)(\\lambda-2)=0,\\qquad \\lambda=5,2.\\]</div><p>For \\(\\lambda=5\\): \\((A-5I)v=0\\Rightarrow -x+y=0\\), so</p><div class="eq">\\[E_5=\\operatorname{span}\\left\\{\\binom11\\right\\}.\\]</div><p>For \\(\\lambda=2\\): \\((A-2I)v=0\\Rightarrow2x+y=0\\), so</p><div class="eq">\\[E_2=\\operatorname{span}\\left\\{\\binom1{-2}\\right\\}.\\]</div><p>Check: \\(A(1,1)^T=5(1,1)^T\\) and \\(A(1,-2)^T=2(1,-2)^T\\).</p>`,'§12.1 eigenvalues/eigenvectors');
const l22Diag=l22Board('Diagonalize a 2×2 matrix',`<p>${l22Recon}</p><p>Diagonalize \\(A=\\begin{pmatrix}4&1\\\\2&3\\end{pmatrix}\\) using the eigenvectors already found.</p>`,`<p>The two distinct eigenvalues give two linearly independent eigenvectors. Put them in the columns of</p><div class="eq">\\[P=\\begin{pmatrix}1&1\\\\1&-2\\end{pmatrix},\\qquad D=\\begin{pmatrix}5&0\\\\0&2\\end{pmatrix}.\\]</div><p>Because \\(AP=PD\\), multiplying by \\(P^{-1}\\) on the left gives</p><div class="eq">\\[\\boxed{P^{-1}AP=D}.\\]</div><p>Equivalently, \\(A=PDP^{-1}\\). This is useful because powers and differential systems become simple in diagonal coordinates.</p>`,'§12.2 diagonalization');
const l22Defect=l22Board('Repeated eigenvalue — can it diagonalize?',`<p>${l22Recon}</p><p>Determine whether</p><div class="eq">\\[B=\\begin{pmatrix}2&1\\\\0&2\\end{pmatrix}\\]</div><p>is diagonalizable.</p>`,`<p>The characteristic polynomial is \\((2-\\lambda)^2\\), so \\(\\lambda=2\\) has algebraic multiplicity 2. But</p><div class="eq">\\[B-2I=\\begin{pmatrix}0&1\\\\0&0\\end{pmatrix},\\]</div><p>so \\(y=0\\) and the eigenspace is only</p><div class="eq">\\[E_2=\\operatorname{span}\\{(1,0)^T\\}.\\]</div><p>There is only one independent eigenvector. A \\(2\\times2\\) matrix needs two independent eigenvectors to diagonalize, so \\(\\boxed{B\\text{ is not diagonalizable}}\\).</p>`,'§12.2 diagonalization criterion');
const l22Sym=l22Board('Symmetric matrix — exploit structure',`<p>${l22Recon}</p><p>For \\(S=\\begin{pmatrix}2&1\\\\1&2\\end{pmatrix}\\), find an orthonormal eigenbasis and an orthogonal diagonalization.</p>`,`<p>The characteristic polynomial is \\((2-\\lambda)^2-1=(\\lambda-3)(\\lambda-1)\\). Corresponding eigenvectors are \\((1,1)^T\\) and \\((1,-1)^T\\). They are already orthogonal. Normalize:</p><div class="eq">\\[q_1=\\frac1{\\sqrt2}\\binom11,\\qquad q_2=\\frac1{\\sqrt2}\\binom1{-1}.\\]</div><p>With \\(Q=[q_1\\ q_2]\\), \\(Q^TQ=I\\), hence \\(Q^{-1}=Q^T\\), and</p><div class="eq">\\[\\boxed{Q^TSQ=\\operatorname{diag}(3,1)}.\\]</div>`,'§12.3 symmetric/orthogonal matrices');
const lesson22Units=[
{id:'l22-map',courseLesson:22,color:'#476a91',badge:'1',label:'Dec. 7 map',title:'Eigenvalues, Eigenvectors & Diagonalization',subtitle:'characteristic equation · eigenspaces · special matrices',desc:'Turn a matrix transformation into its natural directions and scale factors.',lessons:[{title:'Map',screens:[{type:'teach',title:'Textbook numbering reconciliation',html:`<p>${l22Core}</p><p>The syllabus labels this O’Neil §§7.1–7.3. In the supplied 8th SI edition, the matching material is <b>§12.1 Eigenvalues and Eigenvectors</b>, <b>§12.2 Diagonalization</b>, and <b>§12.3 Special Matrices and Their Eigenvalues and Eigenvectors</b>.</p>`},{type:'teach',title:'The central idea',html:`<p>${l22Explain}</p><p>A general vector changes direction when multiplied by \\(A\\). An <b>eigenvector</b> is a special nonzero direction that does not turn: \\(Av=\\lambda v\\). The scalar \\(\\lambda\\) tells how that direction is stretched, compressed, or reversed.</p>`}]}]},
{id:'l22-char',courseLesson:22,color:'#34776e',badge:'2',label:'Characteristic equation',title:'Why det(A−λI)=0?',subtitle:'nonzero null vector requires singularity',desc:'Derive the characteristic equation instead of memorizing it.',lessons:[{title:'Derivation',screens:[{type:'teach',title:'From Av=λv to a determinant',html:`<p>${l22Explain}</p><div class="eq">\\[Av=\\lambda v\\iff(\\lambda I-A)v=0.\\]</div><p>We specifically require \\(v\\ne0\\). A homogeneous square system has a nonzero solution only when its coefficient matrix is singular. O’Neil therefore defines</p><div class="eq">\\[\\boxed{p_A(\\lambda)=\\det(\\lambda I-A)=0}.\\]</div><p>The roots of this characteristic polynomial are the eigenvalues. Using \\(A-\\lambda I\\) gives the same singularity condition, but \\(\\det(\\lambda I-A)\\) is the supplied textbook’s named polynomial convention.</p>`},l22Clone(l22Eig)]}]},
{id:'l22-space',courseLesson:22,color:'#795d9a',badge:'3',label:'Eigenspaces',title:'Eigenspaces & Independence',subtitle:'null(A−λI) · distinct λ ⇒ independent vectors',desc:'Treat every eigenvalue as a null-space problem.',lessons:[{title:'Eigenspace',screens:[{type:'teach',title:'An eigenspace is a null space',html:`<p>${l22Book}</p><p>For a fixed eigenvalue \\(\\lambda\\), all associated eigenvectors together with the zero vector form</p><div class="eq">\\[E_\\lambda=\\operatorname{null}(A-\\lambda I).\\]</div><p>O’Neil’s independence theorem says eigenvectors belonging to distinct eigenvalues are linearly independent. This immediately guarantees diagonalizability when an \\(n\\times n\\) matrix has \\(n\\) distinct eigenvalues.</p>`},{type:'quiz',title:'Multiplicity warning',q:'A 3×3 matrix has eigenvalues 2, 2, 5. Is diagonalization automatically guaranteed?',options:['No; λ=2 must provide enough independent eigenvectors','Yes; there are three eigenvalues counting repetition','Only if det(A)=0'],answer:0,why:'Repeated roots do not automatically supply enough independent eigenvectors.'}]}]},
{id:'l22-diag',courseLesson:22,color:'#9a6038',badge:'4',label:'Diagonalize',title:'Diagonalization',subtitle:'P⁻¹AP=D · eigenvectors are columns of P',desc:'Change coordinates to make the transformation independent component by component.',lessons:[{title:'Diagonalization',screens:[{type:'teach',title:'Why eigenvectors diagonalize A',html:`<p>${l22Book}</p><p>If \\(P=[v_1\\cdots v_n]\\) contains independent eigenvectors and \\(D=\\operatorname{diag}(\\lambda_1,\\ldots,\\lambda_n)\\), then column by column \\(AP=PD\\). Thus</p><div class="eq">\\[\\boxed{P^{-1}AP=D}.\\]</div><p>O’Neil’s criterion is exact: \\(A\\) is diagonalizable iff it has \\(n\\) linearly independent eigenvectors.</p>`},l22Clone(l22Diag)]}]},
{id:'l22-repeat',courseLesson:22,color:'#3e7287',badge:'5',label:'Repeated roots',title:'Algebraic vs Geometric Multiplicity',subtitle:'repeated λ can be harmless or defective',desc:'Count eigenvectors, not merely roots.',lessons:[{title:'Repeated roots',screens:[{type:'teach',title:'Two different multiplicities',html:`<p>${l22Explain}</p><p>The <b>algebraic multiplicity</b> is how many times \\(\\lambda\\) occurs as a characteristic root. The <b>geometric multiplicity</b> is \\(\\dim E_\\lambda\\). Diagonalization requires the total number of independent eigenvectors to reach \\(n\\).</p>`},l22Clone(l22Defect)]}]},
{id:'l22-special',courseLesson:22,color:'#536b48',badge:'6',label:'Special matrices',title:'Symmetric, Orthogonal & Related Matrices',subtitle:'structure gives stronger eigenvalue facts',desc:'Use matrix type before doing unnecessary algebra.',lessons:[{title:'Special matrices',screens:[{type:'teach',title:'Real symmetric matrices',html:`<p>${l22Book}</p><p>For real symmetric \\(S=S^T\\), eigenvalues are real and eigenvectors belonging to distinct eigenvalues are orthogonal. An orthonormal eigenbasis gives an orthogonal matrix \\(Q\\), so \\(Q^{-1}=Q^T\\) and \\(Q^TSQ=D\\).</p><p>The supplied text also treats orthogonal, unitary, Hermitian, and skew-Hermitian matrices; recognize these definitions and exploit their structure rather than treating them as generic matrices.</p>`},l22Clone(l22Sym)]}]},
{id:'l22-meaning',courseLesson:22,color:'#856b37',badge:'7',label:'Interpret',title:'What Eigenvalues Tell You',subtitle:'natural directions · repeated action · later ODE growth modes',desc:'Connect linear algebra to the next lesson.',lessons:[{title:'Interpretation',screens:[{type:'teach',title:'Why this matters for differential equations',html:`<p>${l22Explain}</p><p>If \\(Av=\\lambda v\\), repeated matrix action stays on the same direction: \\(A^kv=\\lambda^kv\\). In the system \\(X'=AX\\), the analogous mode is \\(X=e^{\\lambda t}v\\). This is why today’s eigenvectors become tomorrow’s solution directions.</p>`},{type:'quiz',title:'Mode preview',q:'If λ<0 in X′=AX, what does e^{λt} do as t increases?',options:['Decays toward 0','Grows without bound','Oscillates with fixed amplitude'],answer:0,why:'A negative real exponent produces exponential decay.'}]}]},
{id:'l22-mastery',courseLesson:22,color:'#a24458',badge:'8',label:'Mastery',title:'Dec. 7 Mastery',subtitle:'find · interpret · diagonalize · diagnose',desc:'Solve each on a scratch board, then reveal the verified route.',lessons:[{title:'Eigenpairs',screens:[l22Eig]},{title:'Diagonalization',screens:[l22Diag,l22Defect]},{title:'Special matrices',screens:[l22Sym]}]}
];
if(!units.some(u=>u&&u.id==='l22-map'))units.push(...lesson22Units);if(courseLessons[20])courseLessons[20].status='complete';courseLessons[21]={number:22,title:'Eigenvalues, Eigenvectors & Diagonalization',subtitle:'Dec. 7 · supplied O’Neil §§12.1–12.3',status:'current'};

// Quality reconstruction: preserve unit IDs, add authentic O’Neil teaching, and replace repeated mastery.
const l22Ex128=l22Board('O’Neil Example 12.8 — diagonalization from eigenvectors',`<p>${l22Book}</p><p>O’Neil gives</p><div class="eq">\\[A=\\begin{pmatrix}-1&4\\\\0&3\\end{pmatrix},\\]</div><p>with eigenvalues \\(-1,3\\) and corresponding eigenvectors \\((1,0)^T,(1,1)^T\\). Build the diagonalizing matrix and state the diagonal result.</p>`,`<p>Place the independent eigenvectors in the same order as their eigenvalues:</p><div class="eq">\\[P=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix},\\qquad P^{-1}=\\begin{pmatrix}1&-1\\\\0&1\\end{pmatrix}.\\]</div><p>O’Neil’s diagonalization theorem gives the result immediately:</p><div class="eq">\\[\\boxed{P^{-1}AP=\\begin{pmatrix}-1&0\\\\0&3\\end{pmatrix}}.\\]</div><p>The diagonal order must match the eigenvector-column order. The point is not matrix grinding: once the columns of \\(P\\) are verified eigenvectors, \\(AP=PD\\) already determines \\(D\\).</p>`,'§12.2 · Example 12.8');
const l22P1=l22Board('O’Neil §12.1 Problem 1 — eigenpair portion',`<p>${l22Book}</p><p>For</p><div class="eq">\\[A=\\begin{pmatrix}1&3\\\\2&1\\end{pmatrix},\\]</div><p>find the eigenvalues and one eigenvector for each.</p>`,`<p>The characteristic polynomial is</p><div class="eq">\\[p_A(\\lambda)=\\det(\\lambda I-A)=(\\lambda-1)^2-6.\\]</div><p>Hence</p><div class="eq">\\[\\lambda_{1,2}=1\\pm\\sqrt6.\\]</div><p>From \\((1-\\lambda)x+3y=0\\), choose \\(x=3\\). Then \\(y=\\lambda-1\\), giving</p><div class="eq">\\[\\boxed{v_1=(3,\\sqrt6)^T,\\qquad v_2=(3,-\\sqrt6)^T}.\\]</div><p>Direct multiplication verifies \\(Av_j=\\lambda_jv_j\\).</p>`,'§12.1 · Problem 1');
const l22Transfer=[
l22Board('Transfer 1 — eigenvalue without a determinant',`<p>${l22Recon}</p><p>You are told \\(v=(2,-1)^T\\) and \\(Av=(6,-3)^T\\). Without computing any determinant, identify the eigenvalue and justify your answer.</p>`,`<p>Compare the vectors:</p><div class="eq">\\[Av=(6,-3)^T=3(2,-1)^T=3v.\\]</div><p>Since \\(v\\ne0\\), the defining relation \\(Av=\\lambda v\\) gives \\(\\boxed{\\lambda=3}\\).</p>`,'Original transfer · definition'),
l22Board('Transfer 2 — eigenspace dimension diagnosis',`<p>${l22Recon}</p><p>A \\(3\\times3\\) matrix has characteristic polynomial \\((\\lambda-4)^2(\\lambda+1)\\). Row reduction gives \\(\\dim\\ker(A-4I)=1\\). Can the matrix be diagonalized?</p>`,`<p>The eigenvalue \\(4\\) has algebraic multiplicity 2 but geometric multiplicity 1. The eigenvalue \\(-1\\) can contribute at most one additional independent eigenvector, so the total is at most 2, not 3. Therefore \\(\\boxed{A\\text{ is not diagonalizable}}\\).</p>`,'Original diagnostic · multiplicity'),
l22Board('Transfer 3 — ordering in P and D',`<p>${l22Recon}</p><p>Suppose \\(Av_1=-2v_1\\) and \\(Av_2=5v_2\\), with \\(P=[v_2\\ v_1]\\). What is \\(P^{-1}AP\\)?</p>`,`<p>The diagonal entries follow the column order of \\(P\\). Column 1 is the \\(5\\)-eigenvector and column 2 is the \\(-2\\)-eigenvector, so</p><div class="eq">\\[\\boxed{P^{-1}AP=\\operatorname{diag}(5,-2)}.\\]</div>`,'Original transfer · diagonalization'),
l22Board('Transfer 4 — use diagonalization to take a power',`<p>${l22Recon}</p><p>If \\(A=P\\operatorname{diag}(2,-1)P^{-1}\\), express \\(A^5\\) without multiplying \\(A\\) by itself five times.</p>`,`<p>Adjacent factors \\(P^{-1}P\\) cancel:</p><div class="eq">\\[A^5=P D^5P^{-1}.\\]</div><p>Because powers of a diagonal matrix act entrywise,</p><div class="eq">\\[D^5=\\operatorname{diag}(32,-1).\\]</div><p>Thus \\(\\boxed{A^5=P\\operatorname{diag}(32,-1)P^{-1}}\\).</p>`,'Original transfer · powers'),
l22Board('Transfer 5 — symmetric-matrix shortcut',`<p>${l22Recon}</p><p>A real symmetric \\(3\\times3\\) matrix has three distinct eigenvalues. What can you assert about its eigenvectors and the type of diagonalization available?</p>`,`<p>Distinct eigenvalues give independent eigenvectors. For a real symmetric matrix, eigenvectors for distinct eigenvalues are also orthogonal. Normalize them to form an orthogonal matrix \\(Q\\). Then</p><div class="eq">\\[\\boxed{Q^TAQ=D}.\\]</div><p>Here \\(Q^{-1}=Q^T\\), so the diagonalization is orthogonal.</p>`,'Original transfer · special matrices'),
l22Board('Transfer 6 — zero eigenvalue meaning',`<p>${l22Recon}</p><p>What does the presence of eigenvalue \\(0\\) tell you about a square matrix \\(A\\)? Explain through both eigenvectors and determinants.</p>`,`<p>If \\(0\\) is an eigenvalue, some \\(v\\ne0\\) satisfies \\(Av=0\\), so the null space is nontrivial and \\(A\\) is singular. Equivalently, \\(p_A(0)=\\det(-A)=0\\), hence \\(\\det A=0\\). Thus \\(\\boxed{0\\text{ eigenvalue }\\Longleftrightarrow A\\text{ singular}}\\).</p>`,'Original diagnostic · singularity')
];
const l22DiagUnit=units.find(u=>u&&u.id==='l22-diag');if(l22DiagUnit&&!l22DiagUnit.lessons[0].screens.some(s=>s.title&&s.title.includes('Example 12.8')))l22DiagUnit.lessons[0].screens.push(l22Ex128);
const l22EigUnit=units.find(u=>u&&u.id==='l22-char');if(l22EigUnit&&!l22EigUnit.lessons[0].screens.some(s=>s.title&&s.title.includes('Problem 1')))l22EigUnit.lessons[0].screens.push(l22P1);
const l22Mastery=units.find(u=>u&&u.id==='l22-mastery');if(l22Mastery){l22Mastery.title='Dec. 7 Transfer Mastery';l22Mastery.subtitle='6 unseen problems · meaning, multiplicity, diagonalization, structure';l22Mastery.desc='Tests whether eigenvalue ideas transfer beyond the guided examples; no guided board is replayed.';l22Mastery.lessons=[{title:'Definition & eigenspaces',screens:l22Transfer.slice(0,2)},{title:'Diagonalization transfer',screens:l22Transfer.slice(2,4)},{title:'Structure & diagnosis',screens:l22Transfer.slice(4,6)}];}

// Spaced retrieval: revisit Parts 3–4 after Midterm 2, without changing Part 5 syllabus scope.
const l22Spaced=[
 l22Board('Cumulative retrieval · delayed Laplace signal',`<p><span class="supplementalTag">Spaced retrieval · Parts 3–4 · no new theory</span></p><p>Without re-deriving the theorem, invert</p><div class="eq">\\[e^{-3s}\\frac{1}{s^2+4}.\\]</div><p>State the causality check.</p>`,`<p>The base inverse is \\(\\tfrac12\\sin2t\\). The factor \\(e^{-3s}\\) delays the entire waveform by 3:</p><div class="eq">\\[\\boxed{\\frac12H(t-3)\\sin(2(t-3))}.\\]</div><p>Causality check: the result is exactly zero for \\(t<3\\).</p>`,'Spaced cumulative retrieval · Parts 3–4'),
 l22Board('Cumulative retrieval · series method gate',`<p><span class="supplementalTag">Spaced retrieval · Parts 3–4 · no new theory</span></p><p>At \\(x=0\\), choose the appropriate series method for each equation and give the reason:</p><p><b>A.</b> \\((1+x)y''+xy'+y=0\\).<br><b>B.</b> \\(x^2y''+xy'+(x-1)y=0\\).</p>`,`<p><b>A — ordinary power series.</b> The leading coefficient is nonzero at zero, and after normalization the coefficients are analytic nearby.</p><p><b>B — Frobenius.</b> The leading coefficient vanishes at zero, but \\(xQ/P=1\\) and \\(x^2R/P=x-1\\) are analytic there, so zero is a regular singular point.</p><div class="whybox"><p>The delayed skill being tested is classification before coefficient algebra.</p></div>`,'Spaced cumulative retrieval · Parts 3–4')
];
if(l22Mastery&&!l22Mastery.lessons.some(l=>l.title==='Cumulative retrieval · Parts 3–4'))l22Mastery.lessons.push({title:'Cumulative retrieval · Parts 3–4',screens:l22Spaced});

const l22P17=l22Board('O’Neil §12.1 Problem 17 — powers preserve an eigenvector',`<p>${l22Book}</p><p>Suppose \\(AE=\\lambda E\\) with \\(E\\ne0\\). For a positive integer \\(k\\), show that \\(\\lambda^k\\) is an eigenvalue of \\(A^k\\) with the same eigenvector \\(E\\).</p>`,`<p>Apply \\(A\\) repeatedly:</p><div class="eq">\\[A^2E=A(AE)=A(\\lambda E)=\\lambda AE=\\lambda^2E.\\]</div><p>Continuing in the same way gives</p><div class="eq">\\[A^kE=\\lambda^kE.\\]</div><p>Because \\(E\\ne0\\), this is exactly the eigenvalue equation for \\(A^k\\). Therefore</p><div class="eq">\\[\\boxed{A^kE=\\lambda^kE}.\\]</div>`,'§12.1 · Problem 17');
const l22P1222=l22Board('O’Neil §12.2 Problem 2 — diagonalize a fresh matrix',`<p>${l22Book}</p><p>Find a matrix \\(P\\) that diagonalizes</p><div class="eq">\\[A=\\begin{pmatrix}5&3\\\\1&3\\end{pmatrix}.\\]</div>`,`<p>The characteristic polynomial is</p><div class="eq">\\[\\det(\\lambda I-A)=\\lambda^2-8\\lambda+12=(\\lambda-2)(\\lambda-6).\\]</div><p>For \\(\\lambda=2\\), one eigenvector is \\(v_1=(-1,1)^T\\). For \\(\\lambda=6\\), one is \\(v_2=(3,1)^T\\). They are independent, so use them as columns:</p><div class="eq">\\[P=\\begin{pmatrix}-1&3\\\\1&1\\end{pmatrix}.\\]</div><p>Then</p><div class="eq">\\[\\boxed{P^{-1}AP=\\begin{pmatrix}2&0\\\\0&6\\end{pmatrix}}.\\]</div><p>The diagonal order follows the eigenvector-column order.</p>`,'§12.2 · Problem 2');
const l22CharUnit=units.find(u=>u&&u.id==='l22-char');
if(l22CharUnit&&!l22CharUnit.lessons[0].screens.some(s=>s.title===l22P17.title))l22CharUnit.lessons[0].screens.push(l22Clone(l22P17));
const l22DiagPracticeUnit=units.find(u=>u&&u.id==='l22-diag');
if(l22DiagPracticeUnit&&!l22DiagPracticeUnit.lessons[0].screens.some(s=>s.title===l22P1222.title))l22DiagPracticeUnit.lessons[0].screens.push(l22Clone(l22P1222));

if(typeof renderCourseMap==='function')renderCourseMap();if(typeof render==='function')render();