/* Lesson 17 — Nov. 16: vectors, lines/planes, products, R^n, subspaces, basis and dimension. */
const l17Core='<span class="supplementalTag">Core · Nov. 16 syllabus · Part 5 begins</span>';
const l17Book='<span class="supplementalTag">Authentic textbook · supplied O’Neil §§10.1–10.4</span>';
const l17Explain='<span class="supplementalTag">Expanded explanation · Lesson 1 depth standard</span>';
const l17Recon='<span class="supplementalTag">Syllabus-aligned reconstruction · not claimed as an O’Neil example</span>';
function l17Board(title,prompt,solution,section){return {type:'bookproblem',bookSection:section,title,prompt,solution};}
function l17Clone(s){return s?{...s,inlineBookPractice:true}:null;}
const l17Ex101=l17Board('O’Neil Example 10.1 — line through two points',`<p>${l17Book}</p><p>Find parametric equations for the line through</p><div class="eq">\\[P_0=(-1,-1,7),\\qquad P_1=(7,-1,4).\\]</div><p>Explain where the direction vector comes from.</p>`,`<p>A line needs <b>one point</b> plus a <b>direction</b>. The displacement from \\(P_0\\) to \\(P_1\\) is</p><div class="eq">\\[\\mathbf d=P_1-P_0=(8,0,-3).\\]</div><p>Every point on the line is obtained by starting at \\(P_0\\) and moving an arbitrary scalar multiple of \\(\\mathbf d\\):</p><div class="eq">\\[\\mathbf r(t)=(-1,-1,7)+t(8,0,-3).\\]</div><div class="whybox"><div class="eq">\\[\\boxed{x=-1+8t,\\qquad y=-1,\\qquad z=7-3t}.\\]</div></div><p>At \\(t=0\\) we get \\(P_0\\); at \\(t=1\\) we get \\(P_1\\). That is an immediate geometric check.</p>`,'§10.1 · Example 10.1');
const l17Ex104=l17Board('O’Neil Example 10.4 — plane from a point and normal',`<p>${l17Book}</p><p>A plane contains \\(P_0=(-6,1,1)\\) and has normal vector</p><div class="eq">\\[\\mathbf N=(-2,4,1).\\]</div><p>Find its equation and explain why a dot product appears.</p>`,`<p>If \\(P=(x,y,z)\\) is any point in the plane, then the displacement \\(P-P_0\\) lies <b>inside</b> the plane. A normal vector is perpendicular to every in-plane displacement, so</p><div class="eq">\\[(P-P_0)\\cdot\\mathbf N=0.\\]</div><p>Hence</p><div class="eq">\\[-2(x+6)+4(y-1)+(z-1)=0.\\]</div><p>Simplify:</p><div class="whybox"><div class="eq">\\[\\boxed{-2x+4y+z=17}.\\]</div></div><p>Substituting \\((-6,1,1)\\) gives 17, confirming the given point lies on the plane.</p>`,'§10.2.1 · Example 10.4');
const l17Projection=l17Board('Projection — split a vector into parallel and perpendicular parts',`<p>${l17Recon}</p><p>Project \\(\\mathbf v=(3,4)\\) onto \\(\\mathbf u=(2,0)\\). Then find the component of \\(\\mathbf v\\) perpendicular to \\(\\mathbf u\\).</p>`,`<p>The projection formula is</p><div class="eq">\\[\\operatorname{proj}_{\\mathbf u}\\mathbf v=\\frac{\\mathbf v\\cdot\\mathbf u}{\\mathbf u\\cdot\\mathbf u}\\mathbf u.\\]</div><p>Compute the scalar:</p><div class="eq">\\[\\frac{(3,4)\\cdot(2,0)}{(2,0)\\cdot(2,0)}=\\frac6{4}=\\frac32.\\]</div><p>Therefore</p><div class="eq">\\[\\operatorname{proj}_{\\mathbf u}\\mathbf v=\\frac32(2,0)=(3,0).\\]</div><p>The leftover perpendicular part is</p><div class="eq">\\[\\mathbf v-\\operatorname{proj}_{\\mathbf u}\\mathbf v=(0,4).\\]</div><div class="whybox"><p>Check: \\((0,4)\\cdot(2,0)=0\\), so the remainder really is perpendicular.</p></div>`,'§10.2.2 projection practice');
const l17Cross=l17Board('Cross product — construct a perpendicular vector',`<p>${l17Recon}</p><p>For</p><div class="eq">\\[\\mathbf a=(1,2,0),\\qquad \\mathbf b=(0,1,3),\\]</div><p>find \\(\\mathbf a\\times\\mathbf b\\) and verify perpendicularity.</p>`,`<p>Use the determinant formula:</p><div class="eq">\\[\\mathbf a\\times\\mathbf b=\\begin{vmatrix}\\mathbf i&\\mathbf j&\\mathbf k\\\\1&2&0\\\\0&1&3\\end{vmatrix}=(6,-3,1).\\]</div><p>Now verify both dot products:</p><div class="eq">\\[(6,-3,1)\\cdot(1,2,0)=6-6=0,\\]</div><div class="eq">\\[(6,-3,1)\\cdot(0,1,3)=-3+3=0.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{\\mathbf a\\times\\mathbf b=(6,-3,1)}.\\]</div></div><p>The cross product is perpendicular to the plane spanned by the two original vectors; its magnitude equals the parallelogram area.</p>`,'§10.3 cross-product practice');
const l17Ex107=l17Board('O’Neil Example 10.7 — prove a set is a subspace',`<p>${l17Book}</p><p>Let</p><div class="eq">\\[S=\\{(x,5x):x\\in\\mathbb R\\}.\\]</div><p>Show that \\(S\\) is a subspace of \\(\\mathbb R^2\\).</p>`,`<p>A subspace must contain the zero vector and be closed under vector addition and scalar multiplication.</p><p><b>Zero:</b> choose \\(x=0\\), giving \\((0,0)\\in S\\).</p><p><b>Addition:</b> if \\((a,5a),(b,5b)\\in S\\), then</p><div class="eq">\\[(a,5a)+(b,5b)=(a+b,5(a+b))\\in S.\\]</div><p><b>Scalar multiplication:</b></p><div class="eq">\\[\\alpha(a,5a)=(\\alpha a,5\\alpha a)\\in S.\\]</div><div class="whybox"><p>All three conditions hold, so \\(\\boxed{S\\text{ is a subspace of }\\mathbb R^2}\\).</p></div><p>Geometrically, it is the line through the origin with direction vector \\((1,5)\\).</p>`,'§10.4 · Example 10.7');
const l17Ex1010=l17Board('O’Neil Examples 10.10 & 10.12 — dependence means redundancy',`<p>${l17Book}</p><p>Let</p><div class="eq">\\[F_1=(2,1,-1,0),\\quad F_2=(4,5,-3,-4),\\quad F_3=(1,-1,0,2).\\]</div><p>Show that the three vectors are linearly dependent.</p>`,`<p>O’Neil observes the concrete redundancy</p><div class="eq">\\[F_2=3F_1-2F_3.\\]</div><p>Move everything to one side:</p><div class="eq">\\[3F_1-F_2-2F_3=\\mathbf0.\\]</div><p>The coefficients \\(3,-1,-2\\) are not all zero. Therefore a nontrivial linear combination equals the zero vector:</p><div class="whybox"><p>\\[\\boxed{F_1,F_2,F_3\\text{ are linearly dependent}.}\\]</p></div><p>Conceptually, \\(F_2\\) adds no new direction to the span; \\(F_1\\) and \\(F_3\\) already contain the same spanning information.</p>`,'§10.4 · Examples 10.10 & 10.12');
const l17Ex1013=l17Board('O’Neil Example 10.13 — basis and dimension',`<p>${l17Book}</p><p>Let \\(S\\subset\\mathbb R^4\\) consist of all vectors</p><div class="eq">\\[(x,0,z,0).\\]</div><p>Find a basis and the dimension.</p>`,`<p>Separate the free parameters:</p><div class="eq">\\[(x,0,z,0)=x(1,0,0,0)+z(0,0,1,0).\\]</div><p>Thus the two displayed vectors span \\(S\\). They are also linearly independent: neither is a scalar multiple of the other, and</p><div class="eq">\\[a(1,0,0,0)+b(0,0,1,0)=0\\]</div><p>forces \\(a=b=0\\). Therefore</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal B=\\{(1,0,0,0),(0,0,1,0)\\},\\qquad \\dim S=2}.\\]</div></div><p>A basis must satisfy <b>both</b> requirements: span the space and contain no redundancy.</p>`,'§10.4 · Example 10.13');
const l17P17=l17Board('O’Neil §10.4 Problem 17 — parameter form to basis',`<p>${l17Book}</p><p>Let \\(S\\) consist of all vectors</p><div class="eq">\\[(x,y,-y,-x)\\in\\mathbb R^4.\\]</div><p>Show that \\(S\\) is a subspace, then find a basis and dimension.</p>`,`<p>Separate the two free parameters:</p><div class="eq">\\[(x,y,-y,-x)=x(1,0,0,-1)+y(0,1,-1,0).\\]</div><p>Therefore</p><div class="eq">\\[S=\\operatorname{span}\\{(1,0,0,-1),(0,1,-1,0)\\}.\\]</div><p>A span is automatically closed under addition and scalar multiplication and contains zero, so \\(S\\) is a subspace. The two spanning vectors are independent because</p><div class="eq">\\[a(1,0,0,-1)+b(0,1,-1,0)=0\\]</div><p>forces \\(a=0\\) from the first component and \\(b=0\\) from the second.</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal B=\\{(1,0,0,-1),(0,1,-1,0)\\},\\qquad \\dim S=2}.\\]</div></div>`,'§10.4 · Problem 17');
const lesson17Units=[
{id:'l17-map',courseLesson:17,color:'#476a91',badge:'1',label:'Nov. 16 map',title:'Part 5 Begins — Vectors to Vector Spaces',subtitle:'geometry first · abstraction second',desc:'Build Rⁿ from familiar arrows, lines, planes, and forces.',lessons:[{title:'Map',screens:[
{type:'teach',title:'First fix the textbook numbering mismatch',html:`<p>${l17Core}</p><p>The syllabus labels this Nov. 16 block as <b>O’Neil §§5.1–5.4</b>. In the supplied 8th Edition SI, the exact listed topics occur in <b>Chapter 10, §§10.1–10.4</b>: vectors and lines, dot product/planes/projections, cross product, and the algebraic structure of \\(\\mathbb R^n\\). This lesson follows the syllabus topics while citing the supplied edition’s actual section numbers.</p>`},
{type:'teach',title:'Scalar versus vector',html:`<p>${l17Explain}</p><p>A <b>scalar</b> is specified by magnitude alone: mass, temperature, time. A <b>vector</b> carries components that encode magnitude and direction: displacement, velocity, force.</p><p>In coordinates, \\(\\mathbf v=(v_1,v_2,v_3)\\). Vector addition combines components; multiplying by a scalar stretches, shrinks, or reverses the vector. Those simple operations will become the defining algebra behind subspaces later in this lesson.</p>`},
{type:'quiz',title:'Vector meaning',q:'Which quantity is naturally a vector?',options:['Force','Temperature','Mass'],answer:0,why:'A force needs both magnitude and direction.'}
]}]},
{id:'l17-lines',courseLesson:17,color:'#34776e',badge:'2',label:'Lines',title:'A Line = Point + Direction',subtitle:'parametric vector equations · two-point construction',desc:'Translate geometry into one compact vector formula.',lessons:[{title:'Lines',screens:[
{type:'teach',title:'The line formula',html:`<p>${l17Explain}</p><p>If a line passes through point \\(P_0\\) and has nonzero direction vector \\(\\mathbf d\\), every point on it can be written</p><div class="eq">\\[\\boxed{\\mathbf r(t)=\\mathbf r_0+t\\mathbf d}.\\]</div><p>The parameter \\(t\\) is not a coordinate; it tells how far, and in which signed direction, we move along \\(\\mathbf d\\). If two points are given, subtract them to manufacture the direction vector.</p>`},l17Clone(l17Ex101),
{type:'quiz',title:'Direction from points',q:'Given points P₀ and P₁, which vector is parallel to their line?',options:['P₁−P₀','P₁+P₀','P₁·P₀'],answer:0,why:'The displacement from one point to the other is a direction vector for the line.'}
]}]},
{id:'l17-dot',courseLesson:17,color:'#795d9a',badge:'3',label:'Dot product',title:'Dot Product, Angles, Planes, Projections',subtitle:'one scalar reveals alignment',desc:'Use the dot product as a geometric test and decomposition tool.',lessons:[{title:'Dot product',screens:[
{type:'teach',title:'What the dot product measures',html:`<p>${l17Explain}</p><div class="eq">\\[\\mathbf u\\cdot\\mathbf v=u_1v_1+\\cdots+u_nv_n=\\|\\mathbf u\\|\\|\\mathbf v\\|\\cos\\theta.\\]</div><p>If the result is positive, the vectors point partly together; if negative, partly opposite; if zero, they are perpendicular (provided neither is zero). This one scalar is therefore an angle test.</p>`},l17Clone(l17Ex104),l17Clone(l17Projection),
{type:'quiz',title:'Orthogonality',q:'For nonzero vectors, u·v=0 means what?',options:['They are perpendicular','They are equal','They are parallel'],answer:0,why:'The angle formula forces cos θ=0, hence θ=90°.'}
]}]},
{id:'l17-cross',courseLesson:17,color:'#9a6038',badge:'4',label:'Cross product',title:'Cross Product in R³',subtitle:'perpendicular direction · area · right-hand orientation',desc:'Construct a vector normal to two directions.',lessons:[{title:'Cross product',screens:[
{type:'teach',title:'What makes the cross product different',html:`<p>${l17Explain}</p><p>The dot product returns a <b>scalar</b>. The cross product \\(\\mathbf a\\times\\mathbf b\\) returns a <b>vector</b> perpendicular to both inputs and is specific to the familiar three-dimensional setting used here.</p><div class="eq">\\[\\|\\mathbf a\\times\\mathbf b\\|=\\|\\mathbf a\\|\\|\\mathbf b\\|\\sin\\theta.\\]</div><p>Its magnitude is the area of the parallelogram spanned by the two vectors. Reversing the order reverses the sign.</p>`},l17Clone(l17Cross),
{type:'quiz',title:'Order matters',q:'How is b×a related to a×b?',options:['b×a=−(a×b)','b×a=a×b','b×a=0 always'],answer:0,why:'The cross product is anti-commutative.'}
]}]},
{id:'l17-rn',courseLesson:17,color:'#3e7287',badge:'5',label:'Rⁿ',title:'From Arrows to n-Vectors and Subspaces',subtitle:'closure · zero vector · span',desc:'Generalize the same addition/scaling rules beyond 3D.',lessons:[{title:'Rⁿ and subspaces',screens:[
{type:'teach',title:'Rⁿ is an algebraic space, not a picture you must draw',html:`<p>${l17Core}</p><p>\\(\\mathbb R^n\\) is the set of ordered real \\(n\\)-tuples. We keep the same componentwise addition and scalar multiplication used in 2D and 3D. We may not be able to visualize \\(\\mathbb R^{20}\\), but the algebra works exactly the same way.</p><p>A subset \\(S\\subseteq\\mathbb R^n\\) is a <b>subspace</b> when it contains zero and is closed under addition and scalar multiplication. Intuitively: once you are inside the set, the legal vector operations cannot throw you out.</p>`},l17Clone(l17Ex107),
{type:'teach',title:'Span means every reachable linear combination',html:`<p>A <b>linear combination</b> of vectors \\(v_1,\\ldots,v_k\\) is</p><div class="eq">\\[c_1v_1+\\cdots+c_kv_k.\\]</div><p>The <b>span</b> is the set of all such combinations. Because sums and scalar multiples of linear combinations are still linear combinations, a span is automatically a subspace.</p>`},
{type:'quiz',title:'Fast subspace rejection',q:'A set does not contain the zero vector. Can it be a subspace?',options:['No','Yes, if it is closed under addition','Only in R²'],answer:0,why:'Containing the zero vector is mandatory.'}
]}]},
{id:'l17-independence',courseLesson:17,color:'#536b48',badge:'6',label:'Independence',title:'Linear Independence = No Redundant Direction',subtitle:'nontrivial zero combination · redundancy test',desc:'Understand dependence before memorizing a definition.',lessons:[{title:'Independence',screens:[
{type:'teach',title:'The equation that tests independence',html:`<p>${l17Explain}</p><p>Vectors \\(v_1,\\ldots,v_k\\) are linearly independent when</p><div class="eq">\\[c_1v_1+\\cdots+c_kv_k=0\\]</div><p>has only the trivial solution \\(c_1=\\cdots=c_k=0\\). If a nonzero coefficient choice also reaches zero, at least one vector can be reconstructed from the others: the set contains redundant directional information.</p>`},l17Clone(l17Ex1010),
{type:'quiz',title:'Dependence witness',q:'Which fact proves a set is linearly dependent?',options:['A nontrivial linear combination equals zero','Every vector is nonzero','The vectors lie in R⁴'],answer:0,why:'That is the operational dependence test.'}
]}]},
{id:'l17-basis',courseLesson:17,color:'#856b37',badge:'7',label:'Basis & dimension',title:'Basis = Span Without Redundancy',subtitle:'two requirements · dimension counts basis vectors',desc:'Turn parameterized subspaces into minimal coordinate systems.',lessons:[{title:'Basis',screens:[
{type:'teach',title:'A basis must pass two tests',html:`<p>${l17Explain}</p><p>A set is a basis for subspace \\(S\\) only if it <b>spans S</b> and is <b>linearly independent</b>. Spanning without independence has redundant vectors. Independence without spanning misses directions.</p><p>The <b>dimension</b> of \\(S\\) is the number of vectors in any basis for \\(S\\). Different bases can look completely different but always contain the same number of vectors.</p>`},l17Clone(l17Ex1013),l17Clone(l17P17),
{type:'quiz',title:'Basis logic',q:'Three vectors span a 2D subspace. What must be true?',options:['The three vectors are linearly dependent','The subspace actually has dimension 3','Every vector is zero'],answer:0,why:'A 2D subspace needs only two independent basis directions; a third spanning vector is redundant.'}
]}]},
{id:'l17-mastery',courseLesson:17,color:'#a24458',badge:'8',label:'Mastery',title:'Nov. 16 Mastery — Geometry to Basis',subtitle:'authentic O’Neil examples + full scratch boards',desc:'Rebuild every bridge from concrete vectors to abstract vector-space language.',lessons:[{title:'Geometry',screens:[l17Ex101,l17Ex104,l17Projection,l17Cross]},{title:'Subspaces',screens:[l17Ex107,l17Ex1010]},{title:'Basis',screens:[l17Ex1013,l17P17]}]}
];
if(!units.some(u=>u&&u.id==='l17-map'))units.push(...lesson17Units);
if(courseLessons[15])courseLessons[15].status='complete';
courseLessons[16]={number:17,title:'Vectors, Subspaces, Basis & Dimension',subtitle:'Nov. 16 · supplied O’Neil §§10.1–10.4 · Part 5 begins',status:'current'};
// Reconstruction pass: replace repeated mastery with unseen transfer and diagnostic work.
const l17Transfer=[
l17Board('Transfer 1 — line/plane relationship',`<p>${l17Recon}</p><p>A line is \\(r(t)=(1,2,-1)+t(2,-1,3)\\). A plane has normal \\(N=(1,1,-1)\\) and passes through \\(P=(1,2,-1)\\). Does the entire line lie in the plane?</p>`,`<p>The line starts at the plane point, so only the direction must be checked. A direction lies in the plane exactly when it is perpendicular to the normal:</p><div class="eq">\\[(2,-1,3)\\cdot(1,1,-1)=2-1-3=-2\\ne0.\\]</div><p>Therefore the direction is not parallel to the plane, so the line leaves the plane immediately.</p><div class="whybox"><p><b>Conclusion:</b> only the point \\(t=0\\) is guaranteed to lie in the plane; the whole line does not.</p></div>`,'Original transfer · lines and planes'),
l17Board('Transfer 2 — projection as an error decomposition',`<p>${l17Recon}</p><p>Let \\(u=(2,1,2)\\) and \\(v=(1,2,2)\\). Find the projection of \\(u\\) onto \\(v\\) and verify the error is perpendicular to \\(v\\).</p>`,`<p>Compute \\(u\\cdot v=8\\) and \\(v\\cdot v=9\\):</p><div class="eq">\\[p=\\operatorname{proj}_v u=\\frac89(1,2,2)=\\left(\\frac89,\\frac{16}9,\\frac{16}9\\right).\\]</div><p>The error is</p><div class="eq">\\[e=u-p=\\left(\\frac{10}9,-\\frac79,\\frac29\\right).\\]</div><p>Check:</p><div class="eq">\\[e\\cdot v=\\frac{10-14+4}{9}=0.\\]</div><div class="whybox"><p>The projection is the parallel component; the remainder is orthogonal by construction.</p></div>`,'Original transfer · projection'),
l17Board('Transfer 3 — cross product orientation trap',`<p>${l17Recon}</p><p>For \\(a=(1,0,1)\\), \\(b=(0,2,1)\\), compute both \\(a\\times b\\) and \\(b\\times a\\).</p>`,`<p>Using the determinant formula,</p><div class="eq">\\[a\\times b=(-2,-1,2).\\]</div><p>Reversing the order must reverse the sign:</p><div class="eq">\\[\\boxed{b\\times a=(2,1,-2)=-(a\\times b)}.\\]</div><p>Dotting either result with both original vectors gives zero, confirming perpendicularity.</p>`,'Original diagnostic · cross product'),
l17Board('Transfer 4 — subspace rejection without computation',`<p>${l17Recon}</p><p>Let \\(S=\\{(x,y,z)\\in\\mathbb R^3:x+y+z=1\\}\\). Is \\(S\\) a subspace? Give the fastest rigorous reason.</p>`,`<p>A subspace must contain the zero vector. But</p><div class="eq">\\[0+0+0=0\\ne1,\\]</div><p>so \\(0\\notin S\\).</p><div class="whybox"><p>Therefore \\(S\\) is not a subspace. No closure calculations are needed once a mandatory condition fails.</p></div>`,'Original diagnostic · subspaces'),
l17Board('Transfer 5 — independence in R²',`<p>${l17Recon}</p><p>Are \\(v_1=(1,2)\\), \\(v_2=(3,6)\\) linearly independent? Exhibit a dependence relation if one exists.</p>`,`<p>The second vector is a scalar multiple:</p><div class="eq">\\[v_2=3v_1.\\]</div><p>Hence</p><div class="eq">\\[3v_1-v_2=0\\]</div><p>is a nontrivial zero combination. Therefore the set is linearly dependent. Geometrically both vectors point along the same line, so only one independent direction is present.</p>`,'Original transfer · independence'),
l17Board('Transfer 6 — basis from constraints',`<p>${l17Recon}</p><p>Find a basis and dimension for \\(S=\\{(x,y,z,w)\\in\\mathbb R^4:x+z=0,\\ y-w=0\\}\\).</p>`,`<p>The constraints give \\(z=-x\\) and \\(w=y\\). Therefore</p><div class="eq">\\[(x,y,-x,y)=x(1,0,-1,0)+y(0,1,0,1).\\]</div><p>The two displayed vectors span \\(S\\) and are independent because a zero combination forces both coefficients to vanish.</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal B=\\{(1,0,-1,0),(0,1,0,1)\\},\\quad \\dim S=2}.\\]</div></div>`,'Original mastery · basis and dimension')
];
const l17MasteryUnit=units.find(u=>u&&u.id==='l17-mastery');
if(l17MasteryUnit){l17MasteryUnit.title='Nov. 16 Transfer Mastery';l17MasteryUnit.subtitle='6 unseen problems · geometry, subspaces, basis';l17MasteryUnit.desc='Transfer from geometric vectors to abstract R^n without replaying the worked O’Neil examples.';l17MasteryUnit.lessons=[{title:'Geometry transfer',screens:l17Transfer.slice(0,3)},{title:'Vector-space transfer',screens:l17Transfer.slice(3,6)}];}

// Additional numbered O’Neil practice: keep a few source-authentic problems without restoring repetitive banks.
const l17P1=l17Board('O’Neil §10.4 Problem 1 — subspace from scalar multiples',`<p>${l17Book}</p><p>Let \\(S\\subset\\mathbb R^4\\) consist of all scalar multiples of</p><div class="eq">\\[v=(-2,1,-1,4).\\]</div><p>Determine whether \\(S\\) is a subspace. If it is, give a basis and its dimension.</p>`,`<p>By definition,</p><div class="eq">\\[S=\\{tv:t\\in\\mathbb R\\}=\\operatorname{span}\\{v\\}.\\]</div><p>Every span contains zero and is closed under vector addition and scalar multiplication, so \\(S\\) is a subspace. Since \\(v\\ne0\\), the one-vector spanning set is independent.</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal B=\\{(-2,1,-1,4)\\},\\qquad \\dim S=1}.\\]</div></div>`,'§10.4 · Problem 1');
const l17P23=l17Board('O’Neil §10.4 Problem 23 — coordinates in a given basis',`<p>${l17Book}</p><p>Let</p><div class="eq">\\[X=(-5,-3,-3),\\quad v_1=(1,1,1),\\quad v_2=(0,1,1).\\]</div><p>Verify that \\(v_1,v_2\\) form a basis for their span and write \\(X\\) as a linear combination of them.</p>`,`<p>For independence, suppose \\(av_1+bv_2=0\\). The first component gives \\(a=0\\), and then the second gives \\(b=0\\). Thus the two vectors are independent and therefore form a basis for their span.</p><p>Now solve</p><div class="eq">\\[av_1+bv_2=(-5,-3,-3).\\]</div><p>The first coordinate gives \\(a=-5\\); the second gives \\(-5+b=-3\\), so \\(b=2\\). Therefore</p><div class="eq">\\[\\boxed{X=-5v_1+2v_2}.\\]</div><p>Direct addition returns \\((-5,-3,-3)\\).</p>`,'§10.4 · Problem 23');
const l17RnUnit=units.find(u=>u&&u.id==='l17-rn');
if(l17RnUnit&&!l17RnUnit.lessons[0].screens.some(s=>s.title===l17P1.title))l17RnUnit.lessons[0].screens.push(l17Clone(l17P1));
const l17BasisUnit=units.find(u=>u&&u.id==='l17-basis');
if(l17BasisUnit&&!l17BasisUnit.lessons[0].screens.some(s=>s.title===l17P23.title))l17BasisUnit.lessons[0].screens.push(l17Clone(l17P23));

if(typeof renderCourseMap==='function')renderCourseMap();
if(typeof render==='function')render();