/* Lesson 19 — Nov. 25: row operations, reduced matrices, Gaussian/Gauss–Jordan elimination, rank and nullity. */
const l19Core='<span class="supplementalTag">Core · Nov. 25 syllabus · Part 5</span>';
const l19Book='<span class="supplementalTag">Authentic textbook · supplied O’Neil §11.2</span>';
const l19Explain='<span class="supplementalTag">Expanded explanation · Lesson 1 depth standard</span>';
const l19Recon='<span class="supplementalTag">Syllabus-aligned reconstruction · not claimed as an O’Neil example</span>';
function l19Board(title,prompt,solution,section){return {type:'bookproblem',bookSection:section,title,prompt,solution};}
function l19Clone(s){return s?{...s,inlineBookPractice:true}:null;}
const l19Ex1113=l19Board('O’Neil Example 11.13 — reduce a matrix',`<p>${l19Book}</p><p>Reduce</p><div class="eq">\\[A=\\begin{pmatrix}-3&1&0\\\\4&-2&1\\end{pmatrix}\\]</div><p>to reduced row echelon form, showing why each operation is legal.</p>`,`<p>Row operations preserve the information relevant to the associated linear equations. Start by making the first pivot 1:</p><div class="eq">\\[R_1\\leftarrow-\\tfrac13R_1:\quad \\begin{pmatrix}1&-1/3&0\\\\4&-2&1\\end{pmatrix}.\\]</div><p>Clear below it:</p><div class="eq">\\[R_2\\leftarrow R_2-4R_1:\quad \\begin{pmatrix}1&-1/3&0\\\\0&-2/3&1\\end{pmatrix}.\\]</div><p>Make the second pivot 1:</p><div class="eq">\\[R_2\\leftarrow-\\tfrac32R_2:\quad \\begin{pmatrix}1&-1/3&0\\\\0&1&-3/2\\end{pmatrix}.\\]</div><p>Clear above it:</p><div class="eq">\\[R_1\\leftarrow R_1+\\tfrac13R_2.\\]</div><div class="eq">\\[\\boxed{A_R=\\begin{pmatrix}1&0&-1/2\\\\0&1&-3/2\\end{pmatrix}}.\\]</div>`,'§11.2 · Example 11.13');
const l19Gauss=l19Board('Gaussian elimination — solve by back-substitution',`<p>${l19Recon}</p><p>Solve</p><div class="eq">\\[\\begin{aligned}x+y+z&=6,\\\\2x-y+z&=3,\\\\x+2y-z&=2.\\end{aligned}\\]</div><p>Use elimination to echelon form, then back-substitute.</p>`,`<p>Use the augmented matrix:</p><div class="eq">\\[\\left[\\begin{array}{ccc|c}1&1&1&6\\\\2&-1&1&3\\\\1&2&-1&2\\end{array}\\right].\\]</div><p>Clear below the first pivot:</p><div class="eq">\\[R_2\\leftarrow R_2-2R_1,\\quad R_3\\leftarrow R_3-R_1\\]</div><div class="eq">\\[\\left[\\begin{array}{ccc|c}1&1&1&6\\\\0&-3&-1&-9\\\\0&1&-2&-4\\end{array}\\right].\\]</div><p>Swap rows 2 and 3, then clear below the second pivot:</p><div class="eq">\\[R_3\\leftarrow R_3+3R_2\\Rightarrow \\left[\\begin{array}{ccc|c}1&1&1&6\\\\0&1&-2&-4\\\\0&0&-7&-21\\end{array}\\right].\\]</div><p>Back-substitute: \\(z=3\\), then \\(y-6=-4\\Rightarrow y=2\\), then \\(x+2+3=6\\Rightarrow x=1\\).</p><div class="eq">\\[\\boxed{(x,y,z)=(1,2,3)}.\\]</div>`,'§11.2 Gaussian-elimination practice');
const l19GJ=l19Board('Gauss–Jordan elimination — continue all the way to RREF',`<p>${l19Recon}</p><p>Starting from the echelon matrix</p><div class="eq">\\[\\left[\\begin{array}{ccc|c}1&1&1&6\\\\0&1&-2&-4\\\\0&0&-7&-21\\end{array}\\right],\\]</div><p>continue to reduced row echelon form.</p>`,`<p>Normalize the third pivot:</p><div class="eq">\\[R_3\\leftarrow-\\tfrac17R_3\\Rightarrow[0,0,1|3].\\]</div><p>Clear above it:</p><div class="eq">\\[R_2\\leftarrow R_2+2R_3\\Rightarrow[0,1,0|2],\\]</div><div class="eq">\\[R_1\\leftarrow R_1-R_3\\Rightarrow[1,1,0|3].\\]</div><p>Clear above the second pivot:</p><div class="eq">\\[R_1\\leftarrow R_1-R_2\\Rightarrow[1,0,0|1].\\]</div><div class="eq">\\[\\boxed{\\left[\\begin{array}{ccc|c}1&0&0&1\\\\0&1&0&2\\\\0&0&1&3\\end{array}\\right]}.\\]</div><p>Gaussian elimination normally stops at echelon form and back-substitutes. Gauss–Jordan continues until every pivot column is cleared above and below, so the answer is read directly.</p>`,'§11.2 Gauss–Jordan practice');
const l19Rank=l19Board('Rank and nullity — count pivots and free directions',`<p>${l19Recon}</p><p>Suppose</p><div class="eq">\\[A_R=\\begin{pmatrix}1&0&2&-1&0\\\\0&1&3&0&4\\\\0&0&0&0&0\\end{pmatrix}.\\]</div><p>Find rank and nullity, and explain what they count.</p>`,`<p>There are two nonzero rows, equivalently two pivot columns, so</p><div class="eq">\\[\\operatorname{rank}(A)=2.\\]</div><p>There are five columns/unknowns. Columns 3, 4, 5 are nonpivot columns, so there are three free variables:</p><div class="eq">\\[\\operatorname{nullity}(A)=5-2=3.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{\\operatorname{rank}(A)+\\operatorname{nullity}(A)=5}.\\]</div><p>Rank counts independent constraints/pivot directions. Nullity counts independent free directions in the homogeneous solution space.</p></div>`,'§11.2 rank/nullity connection');
const l19P12=l19Board('O’Neil §11.2 Problem 12 — reduced form and row-operation matrix',`<p>${l19Book}</p><p>For</p><div class="eq">\\[A=\\begin{pmatrix}1&-1&3\\\\0&1&2\\\\0&0&0\\end{pmatrix},\\]</div><p>find \\(A_R\\) and a matrix \\(R\\) such that \\(RA=A_R\\).</p>`,`<p>The only reduction needed is</p><div class="eq">\\[R_1\\leftarrow R_1+R_2,\\]</div><p>so</p><div class="eq">\\[\\boxed{A_R=\\begin{pmatrix}1&0&5\\\\0&1&2\\\\0&0&0\\end{pmatrix}}.\\]</div><p>Apply the same row operation to \\(I_3\\):</p><div class="eq">\\[R=\\begin{pmatrix}1&1&0\\\\0&1&0\\\\0&0&1\\end{pmatrix}.\\]</div><p>Direct multiplication verifies \\(\\boxed{RA=A_R}\\).</p>`,'§11.2 · Problem 12');
const lesson19Units=[
{id:'l19-map',courseLesson:19,color:'#476a91',badge:'1',label:'Nov. 25 map',title:'Row Reduction, Elimination, Rank & Nullity',subtitle:'legal row moves · pivots · free variables',desc:'Turn systems and matrices into simpler equivalent forms.',lessons:[{title:'Map',screens:[{type:'teach',title:'Textbook numbering reconciliation',html:`<p>${l19Core}</p><p>The syllabus calls this O’Neil §6.2. In the supplied 8th SI edition the corresponding material is <b>§11.2, Row Operations and Reduced Matrices</b>. The syllabus additionally names Gaussian/Gauss–Jordan elimination and rank/nullity explicitly, so this lesson teaches those ideas in that context without pulling in the Nov. 30 systems lesson.</p>`},{type:'teach',title:'The central idea',html:`<p>${l19Explain}</p><p>Complicated equations can be replaced by simpler <b>equivalent</b> equations without changing their solution set. Row operations are the matrix version of three legal equation moves. Reduction is therefore controlled simplification—not arbitrary symbol manipulation.</p>`}]}]},
{id:'l19-ops',courseLesson:19,color:'#34776e',badge:'2',label:'Row operations',title:'The Three Elementary Row Operations',subtitle:'swap · scale · replace',desc:'Know exactly what moves are legal and reversible.',lessons:[{title:'Operations',screens:[{type:'teach',title:'Three reversible moves',html:`<p>${l19Book}</p><p>For a matrix, the elementary row operations are:</p><p><b>Type I:</b> swap two rows. <b>Type II:</b> multiply a row by a nonzero scalar. <b>Type III:</b> add a scalar multiple of one row to another.</p><p>Each is reversible. That is why they preserve the solution set of an associated system.</p>`},{type:'quiz',title:'Illegal scaling',q:'Why may you not multiply a row by 0 as a Type II operation?',options:['It destroys information and cannot be reversed','It makes the matrix square','It changes no entries'],answer:0,why:'Multiplying by zero erases an equation, so the original information cannot be recovered.'}]}]},
{id:'l19-rref',courseLesson:19,color:'#795d9a',badge:'3',label:'Reduced form',title:'Pivots and Reduced Row Echelon Form',subtitle:'leading 1s · cleared pivot columns · zero rows last',desc:'Learn the target form before learning the algorithm.',lessons:[{title:'RREF',screens:[{type:'teach',title:'What “reduced” means',html:`<p>${l19Book}</p><p>In reduced row echelon form: every nonzero row begins with a leading 1; each pivot column is zero everywhere else; zero rows are at the bottom; and pivots move strictly right as you move downward.</p><p>O’Neil states that every matrix is row equivalent to a unique reduced form \\(A_R\\). Different legal routes may be used, but the final RREF is the same.</p>`},l19Clone(l19Ex1113),l19Clone(l19P12)]}]},
{id:'l19-gauss',courseLesson:19,color:'#9a6038',badge:'4',label:'Gaussian',title:'Gaussian Elimination',subtitle:'forward elimination · echelon form · back-substitution',desc:'Solve efficiently without doing unnecessary clearing.',lessons:[{title:'Gaussian',screens:[{type:'teach',title:'What Gaussian elimination is doing',html:`<p>${l19Explain}</p><p>Write the system as an augmented matrix. Use row operations to create pivots and zeros <b>below</b> them, producing row echelon form. Then solve from the bottom equation upward. This is back-substitution.</p><p>The goal is triangular structure: later equations contain fewer unknowns.</p>`},l19Clone(l19Gauss)]}]},
{id:'l19-gj',courseLesson:19,color:'#3e7287',badge:'5',label:'Gauss–Jordan',title:'Gauss–Jordan Elimination',subtitle:'continue until answers are visible',desc:'Clear above pivots too and reach RREF.',lessons:[{title:'Gauss–Jordan',screens:[{type:'teach',title:'Gaussian versus Gauss–Jordan',html:`<p>${l19Explain}</p><p><b>Gaussian elimination</b> typically stops after clearing below pivots, then back-substitutes. <b>Gauss–Jordan</b> continues: normalize every pivot to 1 and clear both above and below each pivot. The final coefficient matrix is RREF, so pivot variables can be read directly in terms of free variables.</p>`},l19Clone(l19GJ)]}]},
{id:'l19-rank',courseLesson:19,color:'#536b48',badge:'6',label:'Rank',title:'Rank, Free Variables, and Nullity',subtitle:'pivots count constraints · free columns count freedom',desc:'Read structural information directly from reduced form.',lessons:[{title:'Rank & nullity',screens:[{type:'teach',title:'Rank is the number of pivots',html:`<p>${l19Core}</p><p>The <b>rank</b> of a matrix is the number of nonzero rows in its reduced form—equivalently the number of pivots. O’Neil explicitly states that for a homogeneous system \\(AX=0\\) with \\(m\\) unknowns, the <b>dimension of the solution space</b> is \\(m-\\operatorname{rank}(A)\\). The syllabus names this dimension the <b>nullity</b>, so in the course terminology</p><div class="eq">\\[\\boxed{\\operatorname{nullity}(A)=m-\\operatorname{rank}(A)}.\\]</div><p>Thus rank counts pivot constraints, while nullity counts independent free directions. The formula is introduced here because Nov. 25 explicitly requires both rank and nullity.</p>`},l19Clone(l19Rank),{type:'quiz',title:'Rank/nullity',q:'A 3×6 matrix has rank 3. What is the nullity of AX=0?',options:['3','6','0'],answer:0,why:'There are 6 unknowns and 3 pivots, leaving 3 free variables.'}]}]},
{id:'l19-method',courseLesson:19,color:'#856b37',badge:'7',label:'Method choice',title:'A Reliable Reduction Workflow',subtitle:'choose pivots intelligently · avoid arithmetic blow-up',desc:'Make elimination systematic instead of improvisational.',lessons:[{title:'Workflow',screens:[{type:'teach',title:'Practical pivot strategy',html:`<p>${l19Explain}</p><p>At each stage: (1) find a nonzero entry in the next pivot column; (2) swap rows if a simpler pivot is available; (3) clear entries below it; (4) move down and right. For Gauss–Jordan, return upward afterward to normalize pivots and clear above them.</p><p>Prefer pivots such as \\(1\\) or \\(-1\\) when available; this reduces fractions and arithmetic mistakes. Row swapping is not a failure—it is one of the legal tools.</p>`},{type:'quiz',title:'Zero pivot',q:'Your intended pivot is 0 but a lower row has a nonzero entry in that column. What should you do?',options:['Swap rows','Divide by 0','Delete the column'],answer:0,why:'A Type I row swap puts a usable pivot in position without changing the solution information.'}]}]},
{id:'l19-mastery',courseLesson:19,color:'#a24458',badge:'8',label:'Mastery',title:'Nov. 25 Transfer Mastery',subtitle:'6 unseen problems · reduction, elimination, rank, diagnosis',desc:'Mastery now tests transfer rather than replaying the guided examples. All six are original course problems built only from material taught in this lesson.',lessons:[{title:'Reduction transfer',screens:[
 l19Board('Transfer 1 — legal row moves and reversibility',`<p>${l19Recon}</p><p>Starting with \\(A=\\begin{pmatrix}1&2\\\\3&7\\end{pmatrix}\\), perform \\(R_2\\leftarrow R_2-3R_1\\), then state the single row operation that reverses your step.</p>`,`<p>The replacement gives</p><div class="eq">\\[\\begin{pmatrix}1&2\\\\0&1\\end{pmatrix}.\\]</div><p>Type III operations are reversible: undo the subtraction by adding the same multiple back,</p><div class="eq">\\[\\boxed{R_2\\leftarrow R_2+3R_1}.\\]</div><p>This reversibility is why elementary row operations preserve the solution information.</p>`,'Original transfer · row operations'),
 l19Board('Transfer 2 — reach RREF without unnecessary fractions',`<p>${l19Recon}</p><p>Reduce \\(\\begin{pmatrix}1&2&-1\\\\2&4&1\\end{pmatrix}\\) to RREF and identify the pivot columns.</p>`,`<p>Clear below the first pivot:</p><div class="eq">\\[R_2\\leftarrow R_2-2R_1\\Rightarrow\\begin{pmatrix}1&2&-1\\\\0&0&3\\end{pmatrix}.\\]</div><p>Normalize row 2 and clear above its pivot:</p><div class="eq">\\[R_2\\leftarrow\\tfrac13R_2,\\qquad R_1\\leftarrow R_1+R_2.\\]</div><div class="eq">\\[\\boxed{\\begin{pmatrix}1&2&0\\\\0&0&1\\end{pmatrix}}.\\]</div><p>The pivots are in columns 1 and 3; column 2 is nonpivot.</p>`,'Original transfer · RREF') ]},{title:'Elimination transfer',screens:[
 l19Board('Transfer 3 — Gaussian elimination on a fresh system',`<p>${l19Recon}</p><p>Solve by Gaussian elimination:</p><div class="eq">\\[\\begin{aligned}x+y+z&=4,\\\\2x-y+z&=1,\\\\x+2y+3z&=9.\\end{aligned}\\]</div>`,`<p>Use the augmented matrix and clear below the first pivot:</p><div class="eq">\\[R_2\\leftarrow R_2-2R_1,\\quad R_3\\leftarrow R_3-R_1\\]</div><div class="eq">\\[\\left[\\begin{array}{ccc|c}1&1&1&4\\\\0&-3&-1&-7\\\\0&1&2&5\\end{array}\\right].\\]</div><p>Swap rows 2 and 3, then eliminate:</p><div class="eq">\\[R_3\\leftarrow R_3+3R_2\\Rightarrow\\left[\\begin{array}{ccc|c}1&1&1&4\\\\0&1&2&5\\\\0&0&5&8\\end{array}\\right].\\]</div><p>Thus \\(z=8/5\\), \\(y=9/5\\), and \\(x=3/5\\).</p><div class="eq">\\[\\boxed{(x,y,z)=(3/5,9/5,8/5)}.\\]</div><p>Substitution verifies all three equations.</p>`,'Original transfer · Gaussian elimination'),
 l19Board('Transfer 4 — rank and nullity from structure',`<p>${l19Recon}</p><p>A \\(4\\times6\\) matrix has RREF with pivots in columns 1, 2, and 5. Find its rank and the nullity of \\(AX=0\\).</p>`,`<p>There are three pivot columns, so \\(\\operatorname{rank}(A)=3\\). There are six unknowns and therefore three nonpivot columns/free variables:</p><div class="eq">\\[\\boxed{\\operatorname{nullity}(A)=6-3=3}.\\]</div><p>The homogeneous solution space has three independent parameter directions.</p>`,'Original diagnostic · rank/nullity') ]},{title:'Reasoning & traps',screens:[
 l19Board('Transfer 5 — why rank survives row reduction',`<p>${l19Recon}</p><p>A student says row reduction can change the rank because many entries change. Diagnose the claim.</p>`,`<p>Rank is defined from the number of nonzero rows in the unique reduced form. Elementary row operations move within the same row-equivalence class and do not alter that reduced form. Therefore</p><div class="eq">\\[\\boxed{\\operatorname{rank}(A)=\\operatorname{rank}(A_R)}.\\]</div><p>Individual entries may change dramatically while the number of independent pivot constraints does not.</p>`,'Original diagnostic · rank invariance'),
 l19Board('Transfer 6 — more equations does not guarantee uniqueness',`<p>${l19Recon}</p><p>A system has 5 equations and 3 unknowns. A student claims it must have a unique solution because there are more equations than unknowns. Is that valid?</p>`,`<p>No. Equation count alone does not determine the solution type. The equations may be dependent or contradictory. Uniqueness requires consistency and a pivot in every unknown column. For example, repeated copies of \\(x+y+z=1\\) give many equations but only one independent constraint, hence infinitely many solutions.</p><div class="whybox"><p>Count pivots and check consistency; do not infer uniqueness from raw equation count.</p></div>`,'Original diagnostic · structural reasoning') ]}]}
];
if(!units.some(u=>u&&u.id==='l19-map'))units.push(...lesson19Units);
if(courseLessons[17])courseLessons[17].status='complete';
courseLessons[18]={number:19,title:'Row Reduction, Elimination, Rank & Nullity',subtitle:'Nov. 25 · supplied O’Neil §11.2',status:'current'};

const l19P13=l19Board('O’Neil §11.2 Problem 13 — another reduced form with R',`<p>${l19Book}</p><p>For</p><div class="eq">\\[A=\\begin{pmatrix}3&1&1&4\\\\0&1&0&0\\end{pmatrix},\\]</div><p>find \\(A_R\\) and a matrix \\(R\\) satisfying \\(RA=A_R\\).</p>`,`<p>Scale the first row, then clear the entry above the second pivot:</p><div class="eq">\\[R_1\\leftarrow\\tfrac13R_1,\\qquad R_1\\leftarrow R_1-\\tfrac13R_2.\\]</div><p>This gives</p><div class="eq">\\[\\boxed{A_R=\\begin{pmatrix}1&0&1/3&4/3\\\\0&1&0&0\\end{pmatrix}}.\\]</div><p>The combined row-operation matrix is</p><div class="eq">\\[\\boxed{R=\\begin{pmatrix}1/3&-1/3\\\\0&1\\end{pmatrix}}.\\]</div><p>Multiplying \\(RA\\) reproduces \\(A_R\\), providing an independent check.</p>`,'§11.2 · Problem 13');
const l19P17=l19Board('O’Neil §11.2 Problem 17 — rank-deficient reduction',`<p>${l19Book}</p><p>For</p><div class="eq">\\[A=\\begin{pmatrix}2&2\\\\1&1\\end{pmatrix},\\]</div><p>find the reduced form and a matrix \\(R\\) with \\(RA=A_R\\).</p>`,`<p>First scale row 1, then eliminate row 2:</p><div class="eq">\\[R_1\\leftarrow\\tfrac12R_1,\\qquad R_2\\leftarrow R_2-R_1.\\]</div><p>Therefore</p><div class="eq">\\[\\boxed{A_R=\\begin{pmatrix}1&1\\\\0&0\\end{pmatrix}}.\\]</div><p>The combined row-operation matrix is</p><div class="eq">\\[\\boxed{R=\\begin{pmatrix}1/2&0\\\\-1/2&1\\end{pmatrix}}.\\]</div><p>Indeed \\(RA=A_R\\). The one pivot also shows \\(\\operatorname{rank}(A)=1\\).</p>`,'§11.2 · Problem 17');
const l19RrefUnit=units.find(u=>u&&u.id==='l19-rref');
if(l19RrefUnit){
 if(!l19RrefUnit.lessons[0].screens.some(s=>s.title===l19P13.title))l19RrefUnit.lessons[0].screens.push(l19Clone(l19P13));
 if(!l19RrefUnit.lessons[0].screens.some(s=>s.title===l19P17.title))l19RrefUnit.lessons[0].screens.push(l19Clone(l19P17));
}

if(typeof renderCourseMap==='function')renderCourseMap();if(typeof render==='function')render();