/*
  Lesson 10 — Oct. 19: inverse Laplace transforms; partial fractions; completing the
  square; transforms of derivatives; IVPs in t-space and s-space; equations with
  polynomial coefficients.

  Source policy:
  - O'Neil §3.1 Problems 6–10 supply the authentic inverse-transform exercises.
  - O'Neil §3.2 supplies Theorem 3.1, Examples 3.2–3.3, Problems 1–12.
  - The syllabus also cites the Partial Fractions and Equations with Polynomial
    Coefficients web modules. Their full text is not among the uploaded sources, so the
    partial-fraction refresher and t-multiplication derivation below are explicitly labeled
    course/web-module-aligned supplemental explanations, not quotations from those modules.
*/

const lesson10CoreTag='<span class="supplementalTag">Core · Oct. 19 syllabus · O’Neil §3.1–3.2</span>';
const lesson10BookTag='<span class="supplementalTag">Authentic textbook exercise · O’Neil Chapter 3</span>';
const lesson10ExplainTag='<span class="supplementalTag">Expanded explanation · Lesson 1 depth standard</span>';
const lesson10WebTag='<span class="supplementalTag">Course/web-module aligned supplemental · derivation shown independently</span>';

function l10Book(section,number,prompt,solution){
  return {type:'bookproblem',bookSection:section,title:`O’Neil ${section} Problem ${number}`,prompt,solution};
}
function l10Clone(s){return s?{...s,inlineBookPractice:true}:null;}

const l10InverseBook=[
  l10Book('§3.1',6,
    `<p>${lesson10BookTag}<br>Find the inverse Laplace transform of</p><div class="eq">\\[R(s)=\\frac7{s^2-9}.\\]</div>`,
    `<p><b>Plan before calculating.</b> Factor the denominator mentally as a difference of squares and match the hyperbolic-sine table entry, rather than forcing a longer partial-fraction calculation.</p><div class="eq">\\[\\mathcal L\\{\\sinh(at)\\}=\\frac{a}{s^2-a^2}.\\]</div><p>Here \\(a=3\\), so</p><div class="eq">\\[\\frac7{s^2-9}=\\frac73\\frac3{s^2-3^2}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{r(t)=\\frac73\\sinh(3t)}.\\]</div></div><p><b>Verification.</b> Transform the answer forward: \\(\\frac73\\cdot 3/(s^2-9)=7/(s^2-9)\\).</p>`),
  l10Book('§3.1',7,
    `<p>${lesson10BookTag}<br>Find the inverse Laplace transform of</p><div class="eq">\\[Q(s)=\\frac{s}{s^2+64}.\\]</div>`,
    `<p><b>Plan.</b> The numerator \\(s\\) and denominator \\(s^2+a^2\\) are exactly the cosine pattern.</p><div class="eq">\\[\\mathcal L\\{\\cos(at)\\}=\\frac{s}{s^2+a^2}.\\]</div><p>Since \\(64=8^2\\),</p><div class="whybox"><div class="eq">\\[\\boxed{q(t)=\\cos(8t)}.\\]</div></div><p><b>Verification.</b> Forward transforming \\(\\cos8t\\) returns \\(s/(s^2+64)\\).</p>`),
  l10Book('§3.1',8,
    `<p>${lesson10BookTag}<br>Find the inverse Laplace transform of</p><div class="eq">\\[G(s)=\\frac5{s^2+12}-\\frac{4s}{s^2+8}.\\]</div>`,
    `<p><b>Plan.</b> Use linearity and match each fraction separately. First, \\(12=(2\\sqrt3)^2\\), so manufacture the sine numerator \\(2\\sqrt3\\):</p><div class="eq">\\[\\frac5{s^2+12}=\\frac{5}{2\\sqrt3}\\frac{2\\sqrt3}{s^2+(2\\sqrt3)^2}.\\]</div><p>Therefore the first inverse is \\(\\frac{5}{2\\sqrt3}\\sin(2\\sqrt3\,t)\\).</p><p>Second, \\(8=(2\\sqrt2)^2\\), and \\(s/(s^2+a^2)\\) is the cosine pattern:</p><div class="eq">\\[-\\frac{4s}{s^2+8}\\longleftrightarrow -4\\cos(2\\sqrt2\,t).\\]</div><div class="whybox"><div class="eq">\\[\\boxed{g(t)=\\frac{5}{2\\sqrt3}\\sin(2\\sqrt3\,t)-4\\cos(2\\sqrt2\,t)}.\\]</div></div><p><b>Verification.</b> Forward-transform both terms independently and use linearity.</p>`),
  l10Book('§3.1',9,
    `<p>${lesson10BookTag}<br>Find the inverse Laplace transform of</p><div class="eq">\\[P(s)=\\frac1{(s+4)^2}-\\frac1{(s+3)^4}.\\]</div>`,
    `<p><b>Plan.</b> Read the exponential-polynomial entry backwards:</p><div class="eq">\\[\\mathcal L\\{t^ne^{at}\\}=\\frac{n!}{(s-a)^{n+1}}.\\]</div><p>For the first term, \\((s+4)^2=(s-(-4))^2\\), so \\(n=1,a=-4\\):</p><div class="eq">\\[\\frac1{(s+4)^2}\\longleftrightarrow te^{-4t}.\\]</div><p>For the second, \\(n+1=4\\Rightarrow n=3\\), and \\(3!=6\\):</p><div class="eq">\\[\\frac1{(s+3)^4}=\\frac1{6}\\frac{3!}{(s+3)^4}\\longleftrightarrow \\frac{t^3}{6}e^{-3t}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{p(t)=te^{-4t}-\\frac{t^3}{6}e^{-3t}}.\\]</div></div>`),
  l10Book('§3.1',10,
    `<p>${lesson10BookTag}<br>Find the inverse Laplace transform of</p><div class="eq">\\[F(s)=\\frac{-5s}{(s^2+1)^2}.\\]</div>`,
    `<p><b>Plan.</b> The squared quadratic signals the \\(t\\sin(at)\\) table entry:</p><div class="eq">\\[\\mathcal L\\{t\\sin(at)\\}=\\frac{2as}{(s^2+a^2)^2}.\\]</div><p>With \\(a=1\\), the table numerator is \\(2s\\). Rewrite</p><div class="eq">\\[\\frac{-5s}{(s^2+1)^2}=-\\frac52\\frac{2s}{(s^2+1)^2}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{f(t)=-\\frac52t\\sin t}.\\]</div></div><p><b>Verification.</b> Multiplying the forward transform of \\(t\\sin t\\) by \\(-5/2\\) reproduces the given fraction exactly.</p>`)
];

const l10IvpData=[
 {n:1,eq:`y'+4y=1`,ic:`y(0)=-3`,transform:`(s+4)Y+3=\\frac1s`,algebra:`Isolate first: \\(Y=(1-3s)/[s(s+4)]\\). Write \\(Y=A/s+B/(s+4)\\), so \\(1-3s=A(s+4)+Bs\\). Setting \\(s=0\\) gives \\(A=1/4\\); setting \\(s=-4\\) gives \\(13=-4B\\), so \\(B=-13/4\\).`,Y:`Y=-\\frac{13}{4(s+4)}+\\frac1{4s}`,answer:`y=\\frac14-\\frac{13}{4}e^{-4t}`,verify:`y'+4y=1\\text{ and }y(0)=-3`},
 {n:2,eq:`y'-9y=t`,ic:`y(0)=5`,transform:`(s-9)Y-5=\\frac1{s^2}`,algebra:`Thus \\(Y=(5s^2+1)/[s^2(s-9)]\\). Use \\(A/(s-9)+B/s+C/s^2\\): \\(5s^2+1=As^2+Bs(s-9)+C(s-9)\\). At \\(s=9\\), \\(406=81A\\Rightarrow A=406/81\\). At \\(s=0\\), \\(1=-9C\\Rightarrow C=-1/9\\). Comparing the coefficient of \\(s\\) gives \\(0=-9B+C\\Rightarrow B=-1/81\\).`,Y:`Y=\\frac{406}{81(s-9)}-\\frac1{81s}-\\frac1{9s^2}`,answer:`y=-\\frac t9-\\frac1{81}+\\frac{406}{81}e^{9t}`,verify:`y'-9y=t\\text{ and }y(0)=5`},
 {n:3,eq:`y'+4y=\\cos t`,ic:`y(0)=0`,transform:`(s+4)Y=\\frac{s}{s^2+1}`,algebra:`So \\(Y=s/[(s+4)(s^2+1)]\\). Put \\(Y=A/(s+4)+(Bs+C)/(s^2+1)\\). Then \\(s=A(s^2+1)+(Bs+C)(s+4)\\). Set \\(s=-4\\): \\(-4=17A\\Rightarrow A=-4/17\\). The \\(s^2\\) coefficient gives \\(A+B=0\\Rightarrow B=4/17\\); the constant term gives \\(A+4C=0\\Rightarrow C=1/17\\).`,Y:`Y=\\frac{4s+1}{17(s^2+1)}-\\frac4{17(s+4)}`,answer:`y=\\frac4{17}\\cos t+\\frac1{17}\\sin t-\\frac4{17}e^{-4t}`,verify:`y'+4y=\\cos t\\text{ and }y(0)=0`},
 {n:4,eq:`y'+2y=e^{-t}`,ic:`y(0)=1`,transform:`(s+2)Y-1=\\frac1{s+1}`,algebra:`Move the initial-value term: \\((s+2)Y=1+1/(s+1)=(s+2)/(s+1)\\). The factor \\(s+2\\) cancels, leaving \\(Y=1/(s+1)\\). No partial fractions are needed.`,Y:`Y=\\frac1{s+1}`,answer:`y=e^{-t}`,verify:`y'+2y=e^{-t}\\text{ and }y(0)=1`},
 {n:5,eq:`y'-2y=1-t`,ic:`y(0)=4`,transform:`(s-2)Y-4=\\frac1s-\\frac1{s^2}`,algebra:`Hence \\(Y=(4s^2+s-1)/[s^2(s-2)]\\). Use \\(A/(s-2)+B/s+C/s^2\\): \\(4s^2+s-1=As^2+Bs(s-2)+C(s-2)\\). At \\(s=2\\), \\(17=4A\\Rightarrow A=17/4\\). At \\(s=0\\), \\(-1=-2C\\Rightarrow C=1/2\\). The \\(s\\) coefficient gives \\(1=-2B+C\\Rightarrow B=-1/4\\).`,Y:`Y=\\frac{17}{4(s-2)}-\\frac1{4s}+\\frac1{2s^2}`,answer:`y=\\frac t2-\\frac14+\\frac{17}{4}e^{2t}`,verify:`y'-2y=1-t\\text{ and }y(0)=4`},
 {n:6,eq:`y''+y=1`,ic:`y(0)=6,\\ y'(0)=0`,transform:`(s^2+1)Y-6s=\\frac1s`,algebra:`Thus \\(Y=(6s^2+1)/[s(s^2+1)]\\). Seek \\(A/s+Bs/(s^2+1)\\): \\(6s^2+1=A(s^2+1)+Bs^2\\). The constant term gives \\(A=1\\); the \\(s^2\\) coefficient gives \\(A+B=6\\Rightarrow B=5\\).`,Y:`Y=\\frac{5s}{s^2+1}+\\frac1s`,answer:`y=1+5\\cos t`,verify:`y''+y=1,\\ y(0)=6,\\ y'(0)=0`},
 {n:7,eq:`y''-4y'+4y=\\cos t`,ic:`y(0)=1,\\ y'(0)=-1`,transform:`(s-2)^2Y-s+5=\\frac{s}{s^2+1}`,algebra:`Move the non-Y terms and combine: \\(Y=[s+(s-5)(s^2+1)]/[(s^2+1)(s-2)^2]\\). Use \\(Y=(As+B)/(s^2+1)+C/(s-2)+D/(s-2)^2\\). After clearing denominators and comparing powers of \\(s\\), \\(A+C=1\\), \\(-4A+B-2C+D=-5\\), \\(4A-4B+C=2\\), and \\(4B-2C+D=-5\\). Solving this linear system gives \\(A=3/25,B=-4/25,C=22/25,D=-13/5\\).`,Y:`Y=\\frac{3s-4}{25(s^2+1)}+\\frac{22}{25(s-2)}-\\frac{13}{5(s-2)^2}`,answer:`y=\\frac{22-65t}{25}e^{2t}+\\frac3{25}\\cos t-\\frac4{25}\\sin t`,verify:`y''-4y'+4y=\\cos t,\\ y(0)=1,\\ y'(0)=-1`},
 {n:8,eq:`y''+9y=t^2`,ic:`y(0)=0,\\ y'(0)=0`,transform:`(s^2+9)Y=\\frac2{s^3}`,algebra:`So \\(Y=2/[s^3(s^2+9)]\\). Because the expression is odd in \\(s\\), use \\(A/s+B/s^3+Cs/(s^2+9)\\). Clearing denominators gives \\(2=As^2(s^2+9)+B(s^2+9)+Cs^4\\). The constant term gives \\(B=2/9\\); the \\(s^2\\) term gives \\(9A+B=0\\Rightarrow A=-2/81\\); the \\(s^4\\) term gives \\(A+C=0\\Rightarrow C=2/81\\).`,Y:`Y=\\frac{2s}{81(s^2+9)}-\\frac2{81s}+\\frac2{9s^3}`,answer:`y=\\frac{t^2}{9}+\\frac2{81}\\cos3t-\\frac2{81}`,verify:`y''+9y=t^2,\\ y(0)=y'(0)=0`},
 {n:9,eq:`y''+16y=1+t`,ic:`y(0)=-2,\\ y'(0)=1`,transform:`(s^2+16)Y+2s-1=\\frac1s+\\frac1{s^2}`,algebra:`Isolate \\(Y\\) and choose \\(A/s+B/s^2+(Cs+D)/(s^2+16)\\). Clearing denominators and comparing coefficients yields \\(B=1/16\\), \\(A=1/16\\), \\(C=-33/16\\), and \\(D=15/16\\). The last term must be converted for inversion: \\((15/16)/(s^2+16)=(15/64)\\,4/(s^2+16)\\).`,Y:`Y=-\\frac{33s}{16(s^2+16)}+\\frac{15}{16(s^2+16)}+\\frac1{16s}+\\frac1{16s^2}`,answer:`y=\\frac t{16}+\\frac1{16}+\\frac{15}{64}\\sin4t-\\frac{33}{16}\\cos4t`,verify:`y''+16y=1+t,\\ y(0)=-2,\\ y'(0)=1`},
 {n:10,eq:`y''-5y'+6y=e^{-t}`,ic:`y(0)=0,\\ y'(0)=2`,transform:`(s^2-5s+6)Y-2=\\frac1{s+1}`,algebra:`Factor \\(s^2-5s+6=(s-2)(s-3)\\). Then \\(Y=(2s+3)/[(s+1)(s-2)(s-3)]\\). Write \\(A/(s+1)+B/(s-2)+C/(s-3)\\). Setting \\(s=-1\\) gives \\(1=12A\\Rightarrow A=1/12\\); \\(s=2\\) gives \\(7=-3B\\Rightarrow B=-7/3\\); \\(s=3\\) gives \\(9=4C\\Rightarrow C=9/4\\).`,Y:`Y=\\frac1{12(s+1)}-\\frac7{3(s-2)}+\\frac9{4(s-3)}`,answer:`y=\\frac1{12}e^{-t}-\\frac73e^{2t}+\\frac94e^{3t}`,verify:`y''-5y'+6y=e^{-t},\\ y(0)=0,\\ y'(0)=2`}
];
function l10IvpScreen(d){
 return l10Book('§3.2',d.n,
   `<p>${lesson10BookTag}<br>Use the Laplace transform to solve</p><div class="eq">\\[${d.eq},\\qquad ${d.ic}.\\]</div>`,
   `<p><b>Plan before calculating.</b> Transform the entire ODE first. The derivative formula automatically carries the initial data into the algebraic equation for \\(Y(s)\\). Then isolate \\(Y\\), decompose it into table-readable pieces, invert term by term, and verify in the original IVP.</p><p><b>1. Transform and insert the initial data.</b></p><div class="eq">\\[${d.transform}.\\]</div><p><b>2. Do the s-domain algebra without skipping the coefficient work.</b> ${d.algebra}</p><p>The resulting table-readable form is</p><div class="eq">\\[${d.Y}.\\]</div><p><b>3. Invert term by term.</b></p><div class="whybox"><div class="eq">\\[\\boxed{${d.answer}}.\\]</div></div><p><b>4. Independent check.</b> Differentiate the final time-domain expression and substitute it back. It gives \\( ${d.verify} \\). This checks both the transformed algebra and the inverse transform.</p>`);
}
const l10IvpBook=l10IvpData.map(l10IvpScreen);

const l10DerivationBook=[
 l10Book('§3.2',11,
   `<p>${lesson10BookTag}<br>Use integration by parts to derive O’Neil equation (3.1), the transform of a first derivative.</p>`,
   `<p><b>Plan.</b> Start from the definition with \\(f'\\), then choose integration-by-parts factors so the derivative moves from \\(f'\\) onto the exponential kernel.</p><div class="eq">\\[\\mathcal L\\{f'\\}=\\int_0^\\infty e^{-st}f'(t)dt.\\]</div><p>Take \\(u=e^{-st}\\), \\(dv=f'(t)dt\\). Then \\(du=-se^{-st}dt\\) and \\(v=f(t)\\). Therefore</p><div class="eq">\\[\\int_0^\\infty e^{-st}f' dt=\\left[e^{-st}f(t)\\right]_0^\\infty+s\\int_0^\\infty e^{-st}f(t)dt.\\]</div><p>Under the theorem's decay assumption, the upper boundary term is zero. At the lower boundary it contributes \\(-f(0)\\). The remaining integral is \\(F(s)\\).</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L\\{f'\\}=sF(s)-f(0)}.\\]</div></div><p><b>Why this matters.</b> A time derivative becomes multiplication by \\(s\\), plus a correction containing the initial value. That is the algebraic mechanism behind Laplace IVP solving.</p>`),
 l10Book('§3.2',12,
   `<p>${lesson10BookTag}<br>Use integration by parts and equation (3.1) to derive O’Neil equation (3.3), the second-derivative formula.</p>`,
   `<p><b>Plan.</b> Treat \\(f'\\) as a new function and apply the first-derivative rule once more.</p><p>Equation (3.1) says, for any suitable function \\(g\\),</p><div class="eq">\\[\\mathcal L\\{g'\\}=s\\mathcal L\\{g\\}-g(0).\\]</div><p>Set \\(g=f'\\). Then \\(g'=f''\\), so</p><div class="eq">\\[\\mathcal L\\{f''\\}=s\\mathcal L\\{f'\\}-f'(0).\\]</div><p>Now substitute equation (3.1) again:</p><div class="eq">\\[=s[sF(s)-f(0)]-f'(0).\\]</div><p>Distribute \\(s\\):</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L\\{f''\\}=s^2F(s)-sf(0)-f'(0)}.\\]</div></div><p>The same repetition produces the general nth-derivative formula in O’Neil equation (3.2).</p>`)
];

const lesson10BookScreens=[...l10InverseBook,...l10IvpBook,...l10DerivationBook];
function l10ByTitle(title){return lesson10BookScreens.find(s=>s.title===title);}

const lesson10BaseUnits=[
 {id:'l10-map',courseLesson:10,color:'#4059ad',badge:'1',label:'Oct. 19 map',title:'From a Transform Table to a Complete IVP Solver',subtitle:'Inverse transforms · algebra in s · derivative rules · IVPs',desc:'See how every Oct. 19 syllabus item fits one pipeline before doing the calculations.',lessons:[{title:'The complete workflow',screens:[
  {type:'teach',title:'What is new today?',html:`<p>${lesson10CoreTag}</p><p>Lesson 8 taught the forward map \\(f(t)\\mapsto F(s)\\). Today the course makes that map useful for differential equations:</p><div class="whybox"><div class="eq">\\[\\text{ODE + initial data in }t\\rightarrow\\text{algebraic equation in }s\\rightarrow Y(s)\\rightarrow y(t).\\]</div></div><p>The syllabus explicitly requires <b>inverse transforms, partial fractions, completing the square, transforms of derivatives, IVPs, the t↔s picture, and equations with polynomial coefficients</b>. Each gets its own unit here.</p>`},
  {type:'teach',title:'Why Laplace can make an ODE algebraic',html:`<p>${lesson10ExplainTag}</p><p>The key derivative rule is</p><div class="eq">\\[\\mathcal L\\{y'\\}=sY-y(0).\\]</div><p>Notice what disappeared: there is no derivative of \\(Y\\). A derivative with respect to time becomes multiplication by \\(s\\), while the initial condition appears as an ordinary algebraic term. For a constant-coefficient ODE, every derivative behaves this way, so the differential equation becomes an algebra problem.</p>`},
  {type:'quiz',title:'What is the real purpose of the s-domain?',q:'Why is the Laplace transform especially useful for constant-coefficient IVPs?',options:['It turns time derivatives into algebraic powers of s while incorporating initial data','It makes every nonlinear ODE separable','It removes the need to invert the answer'],answer:0,why:'Derivative transforms replace differentiation by multiplication by s plus initial-value terms.'}
 ]}]},
 {id:'l10-inverse',courseLesson:10,color:'#2e7d69',badge:'2',label:'Inverse transform',title:'Inverse Laplace Transforms: Read the Table Backwards Safely',subtitle:'Pattern recognition · constants · powers · quadratics',desc:'Turn rational functions in s back into time-domain functions without guessing.',lessons:[{title:'Inverse transform mechanics',screens:[
  {type:'teach',title:'Inverse does not mean reciprocal',html:`<p>${lesson10CoreTag}</p><p>If \\(\\mathcal L\\{f\\}=F\\), then \\(\\mathcal L^{-1}\\{F\\}=f\\). The superscript \\(-1\\) means <b>undo the transformation</b>; it does not mean \\(1/F\\).</p><p>Because the transform is linear, inverse transforms are linear too:</p><div class="eq">\\[\\mathcal L^{-1}\\{AF+BG\\}=Af+Bg.\\]</div>`},
  {type:'teach',title:'A four-step inverse checklist',html:`<p>${lesson10ExplainTag}</p><div class="whybox"><ol><li>Split sums before doing anything complicated.</li><li>Factor constants outside.</li><li>Rewrite each denominator/numerator into a table pattern.</li><li>Forward-transform your proposed answer as a quick independent check.</li></ol></div><p>Do not perform partial fractions when one table entry already matches; do not force a table match when the denominator still needs algebra.</p>`},
  ...l10InverseBook.slice(0,3).map(l10Clone),
  {type:'quiz',title:'Recognize before decomposing',q:`What is the quickest inverse of \\(s/(s^2+25)\\)?`,options:[`cos(5t)`,`sin(5t)`,`e^{-5t}`],answer:0,why:'It exactly matches L{cos(at)}=s/(s²+a²) with a=5.'}
 ]},{title:'More authentic inverse practice',screens:l10InverseBook.slice(3).map(l10Clone)}]},
 {id:'l10-algebra',courseLesson:10,color:'#7651b8',badge:'3',label:'s-domain algebra',title:'Partial Fractions and Completing the Square',subtitle:'Make Y(s) readable by the table',desc:'The transform method succeeds only if the algebraic expression can be rewritten into known inverse-transform pieces.',lessons:[{title:'Algebra toolkit',screens:[
  {type:'teach',title:'Why partial fractions appear',html:`<p>${lesson10WebTag}</p><p>A transform such as</p><div class="eq">\\[Y(s)=\\frac{2s-1}{(s-1)(s+1)(s+3)}\\]</div><p>does not match one simple table entry. The goal of partial fractions is to rewrite it as a <b>sum of simple pieces</b> that do:</p><div class="eq">\\[\\frac{A}{s-1}+\\frac{B}{s+1}+\\frac{C}{s+3}.\\]</div><p>After multiplying through by the common denominator, choose convenient values of \\(s\\) or compare coefficients. This is algebraic preparation for inversion, not a new transform theorem.</p>`},
  {type:'teach',title:'O’Neil Example 3.3 — show the partial fractions',html:`<p>${lesson10BookTag}</p><p>O’Neil obtains</p><div class="eq">\\[Y=\\frac{2s-1}{(s-1)(s+1)(s+3)}.\\]</div><p>Write</p><div class="eq">\\[2s-1=A(s+1)(s+3)+B(s-1)(s+3)+C(s-1)(s+1).\\]</div><p>Set \\(s=1\\): \\(1=8A\\Rightarrow A=1/8\\). Set \\(s=-1\\): \\(-3=-4B\\Rightarrow B=3/4\\). Set \\(s=-3\\): \\(-7=8C\\Rightarrow C=-7/8\\).</p><p>Hence</p><div class="eq">\\[Y=\\frac1{8(s-1)}+\\frac3{4(s+1)}-\\frac7{8(s+3)}.\\]</div><div class="whybox"><div class="eq">\\[y=\\frac18e^t+\\frac34e^{-t}-\\frac78e^{-3t}.\\]</div></div>`},
  {type:'teach',title:'Completing the square: make the quadratic look like sine/cosine',html:`<p>${lesson10WebTag}</p><p>Suppose</p><div class="eq">\\[F(s)=\\frac{3s+5}{s^2+4s+13}.\\]</div><p>Complete the square:</p><div class="eq">\\[s^2+4s+13=(s+2)^2+9.\\]</div><p>Now rewrite the numerator around the same center:</p><div class="eq">\\[3s+5=3(s+2)-1.\\]</div><p>Therefore</p><div class="eq">\\[F=3\\frac{s+2}{(s+2)^2+3^2}-\\frac1{(s+2)^2+3^2}.\\]</div><p>Using the exponential-trigonometric table entries already introduced in Lesson 8,</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=3e^{-2t}\\cos3t-\\frac13e^{-2t}\\sin3t}.\\]</div></div><p>We are matching known table entries here; the formal first-shifting theorem is intentionally left for Lesson 11.</p>`},
  {type:'quiz',title:'Why complete the square?',q:`Why rewrite \\(s^2+4s+13\\) as \\((s+2)^2+9\\)?`,options:['To expose a sine/cosine table pattern','To turn the denominator into a polynomial in t','To eliminate the need for an inverse transform'],answer:0,why:'Quadratic table entries are organized around (s−a)²+b².'}
 ]}]},
 {id:'l10-derivatives',courseLesson:10,color:'#b35f4a',badge:'4',label:'Derivative transforms',title:'Derive the Operational Rules for y′ and y″',subtitle:'Initial data enters automatically',desc:'Do not memorize the derivative formulas as magic; derive them by integration by parts and see exactly where the initial values come from.',lessons:[{title:'From differentiation to multiplication by s',screens:[
  {type:'teach',title:'First derivative — derive every term',html:`<p>${lesson10BookTag}</p><div class="eq">\\[\\mathcal L\\{y'\\}=\\int_0^\\infty e^{-st}y'(t)dt.\\]</div><p>Integration by parts gives</p><div class="eq">\\[\\left[e^{-st}y(t)\\right]_0^\\infty+s\\int_0^\\infty e^{-st}y(t)dt.\\]</div><p>Under the usual decay condition the upper boundary vanishes; the lower boundary is \\(-y(0)\\). Thus</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L\\{y'\\}=sY-y(0)}.\\]</div></div>`},
  {type:'teach',title:'Second derivative — apply the rule again',html:`<p>Apply the first-derivative rule to \\(y'\\):</p><div class="eq">\\[\\mathcal L\\{y''\\}=s\\mathcal L\\{y'\\}-y'(0).\\]</div><p>Substitute \\(\\mathcal L\\{y'\\}=sY-y(0)\\):</p><div class="eq">\\[=s[sY-y(0)]-y'(0).\\]</div><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L\\{y''\\}=s^2Y-sy(0)-y'(0)}.\\]</div></div>`},
  {type:'teach',title:'General nth derivative pattern',html:`<p>${lesson10CoreTag}</p><div class="eq">\\[\\mathcal L\\{y^{(n)}\\}=s^nY-s^{n-1}y(0)-s^{n-2}y'(0)-\\cdots-y^{(n-1)}(0).\\]</div><p>Each differentiation contributes another factor of \\(s\\), and each time integration by parts crosses a boundary it exposes one more initial derivative.</p>`},
  ...l10DerivationBook.map(l10Clone),
  {type:'quiz',title:'Transform y″ correctly',q:`If \\(y(0)=2\\) and \\(y'(0)=-3\\), what is \\(\\mathcal L\\{y''\\}\\)?`,options:[`s²Y−2s+3`,`s²Y−2s−3`,`sY−2`],answer:0,why:'L{y″}=s²Y−sy(0)−y′(0)=s²Y−2s+3.'}
 ]}]},
 {id:'l10-ivp1',courseLesson:10,color:'#d27a42',badge:'5',label:'First-order IVPs',title:'Solve First-Order IVPs Entirely in Transform Space',subtitle:'Transform → isolate Y → decompose → invert → verify',desc:'Use O’Neil §3.2 Problems 1–5 as authentic practice with every algebraic step explained.',lessons:[{title:'O’Neil §3.2 Problems 1–5',screens:l10IvpBook.slice(0,5).map(l10Clone)}]},
 {id:'l10-ivp2',courseLesson:10,color:'#6a6f7b',badge:'6',label:'Second-order IVPs',title:'Second-Order IVPs: Both Initial Conditions Enter at Once',subtitle:'The derivative formulas carry y(0) and y′(0) into Y(s)',desc:'Work all five authentic second-order IVPs from O’Neil §3.2, with table matching and verification.',lessons:[{title:'O’Neil §3.2 Problems 6–10',screens:l10IvpBook.slice(5,10).map(l10Clone)}]},
 {id:'l10-poly',courseLesson:10,color:'#3f7f8f',badge:'7',label:'Polynomial coefficients',title:'When Multiplication by t Becomes Differentiation in s',subtitle:'The missing bridge for equations with polynomial coefficients',desc:'Derive the t-multiplication rule from the transform definition and use it on a simple polynomial-coefficient ODE.',lessons:[{title:'t-space ↔ s-space beyond constant coefficients',screens:[
  {type:'teach',title:'Derive L{t f(t)} instead of quoting it',html:`<p>${lesson10WebTag}</p><p>Start with</p><div class="eq">\\[F(s)=\\int_0^\\infty e^{-st}f(t)dt.\\]</div><p>Differentiate with respect to \\(s\\) under the integral sign:</p><div class="eq">\\[F'(s)=\\int_0^\\infty (-t)e^{-st}f(t)dt=-\\mathcal L\\{tf(t)\\}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L\\{tf(t)\\}=-F'(s)}.\\]</div></div><p>This is the new trade: <b>multiplication by time becomes differentiation with respect to s</b>.</p>`},
  {type:'teach',title:'Combine the two operational rules',html:`<p>${lesson10ExplainTag}</p><p>Because \\(\\mathcal L\\{y'\\}=sY-y(0)\\),</p><div class="eq">\\[\\mathcal L\\{ty'\\}=-\\frac d{ds}[sY-y(0)]=-(Y+sY').\\]</div><p>Likewise,</p><div class="eq">\\[\\mathcal L\\{ty''\\}=-\\frac d{ds}[s^2Y-sy(0)-y'(0)]=-(2sY+s^2Y'-y(0)).\\]</div><p>An ODE with polynomial coefficients in \\(t\\) can therefore become a <em>differential equation in s</em>, rather than a purely algebraic equation. That is why the syllabus names this as a separate web-module topic.</p>`},
  {type:'teach',title:'Worked example: t y′ + y = t',html:`<p>${lesson10WebTag}</p><p>Assume \\(y\\) remains bounded at \\(t=0\\). Transform term by term:</p><div class="eq">\\[\\mathcal L\\{ty'\\}+\\mathcal L\\{y\\}=\\mathcal L\\{t\\}.\\]</div><p>Use \\(\\mathcal L\\{ty'\\}=-(Y+sY')\\), \\(\\mathcal L\\{y\\}=Y\\), and \\(\\mathcal L\\{t\\}=1/s^2\\):</p><div class="eq">\\[-(Y+sY')+Y=\\frac1{s^2}.\\]</div><p>The \\(Y\\) terms cancel:</p><div class="eq">\\[-sY'=\\frac1{s^2}\\Rightarrow Y'=-\\frac1{s^3}.\\]</div><p>Integrate with respect to \\(s\\):</p><div class="eq">\\[Y=\\frac1{2s^2}+C.\\]</div><p>For an ordinary exponential-order function, \\(Y(s)\\to0\\) as \\(s\\to\\infty\\), so \\(C=0\\). Invert:</p><div class="whybox"><div class="eq">\\[\\boxed{y(t)=\\frac t2}.\\]</div></div><p><b>Direct verification:</b> \\(y'=1/2\\), hence \\(ty'+y=t/2+t/2=t\\). Solving directly gives \\(y=t/2+C/t\\); boundedness at zero selects the same branch.</p>`},
  {type:'quiz',title:'What does multiplication by t do?',q:`If \\(F(s)=\\mathcal L\\{f(t)\\}\\), what is \\(\\mathcal L\\{t f(t)\\}\\)?`,options:[`−F′(s)`,`sF(s)−f(0)`,`F(s−1)`],answer:0,why:'Differentiating the kernel e^{-st} with respect to s produces −t e^{-st}.'}
 ]}]}
];

const lesson10Transfer=[
 l10Book('Original course problem',1,`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>Find the inverse transform of</p><div class="eq">\\[F(s)=\\frac{2s+7}{s^2+6s+13}.\\]</div>`,`<p>Complete the square first: \\(s^2+6s+13=(s+3)^2+4\\). Center the numerator around the same shift:</p><div class="eq">\\[2s+7=2(s+3)+1.\\]</div><p>Hence</p><div class="eq">\\[F=2\\frac{s+3}{(s+3)^2+2^2}+\\frac1{(s+3)^2+2^2}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{f(t)=e^{-3t}\\left(2\\cos2t+\\frac12\\sin2t\\right)}.\\]</div></div><p>Forward transformation reproduces the original numerator and denominator.</p>`),
 l10Book('Original course problem',2,`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>A student transforms \\(y''+3y'=t\\), with \\(y(0)=2,y'(0)=-1\\), as \\((s^2+3s)Y=1/s^2\\). Diagnose the missing terms and write the correct transformed equation.</p>`,`<p>The derivative rules contain the initial data:</p><div class="eq">\\[\\mathcal L\\{y''\\}=s^2Y-2s+1,\\qquad \\mathcal L\\{3y'\\}=3(sY-2).\\]</div><p>Therefore</p><div class="whybox"><div class="eq">\\[\\boxed{(s^2+3s)Y-2s-5=\\frac1{s^2}}.\\]</div></div><p>The error was not algebraic; it was dropping the boundary terms produced by integration by parts.</p>`),
 l10Book('Original course problem',3,`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>Solve by Laplace transform:</p><div class="eq">\\[y''+4y=t,\\qquad y(0)=1,\\ y'(0)=0.\\]</div>`,`<p>Transform:</p><div class="eq">\\[(s^2+4)Y-s=\\frac1{s^2}.\\]</div><p>Thus</p><div class="eq">\\[Y=\\frac{s}{s^2+4}+\\frac1{s^2(s^2+4)}.\\]</div><p>Decompose the second term:</p><div class="eq">\\[\\frac1{s^2(s^2+4)}=\\frac1{4s^2}-\\frac1{4(s^2+4)}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y(t)=\\cos2t+\\frac t4-\\frac18\\sin2t}.\\]</div></div><p>Direct substitution gives \\(y''+4y=t\\), and the two initial conditions are satisfied.</p>`),
 l10Book('Original course problem',4,`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>Without solving an ODE, explain why \\(\\mathcal L\\{t y'(t)\\}\\) is not simply \\(t[sY-y(0)]\\), and derive the correct s-domain expression.</p>`,`<p>The variable \\(t\\) does not survive as a free multiplier after transformation. Use \\(\\mathcal L\\{tf\\}=-F'(s)\\) with \\(f=y'\\):</p><div class="eq">\\[\\mathcal L\\{ty'\\}=-\\frac d{ds}[sY-y(0)].\\]</div><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L\\{ty'\\}=-(Y+sY')}.\\]</div></div><p>The constant initial value differentiates to zero.</p>`),
 l10Book('Original course problem',5,`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>For \\(Y(s)=\\frac{5s+1}{(s+2)(s^2+4)}\\), decide what algebra must happen before inversion and carry it out.</p>`,`<p>The denominator contains a linear factor and an irreducible quadratic, so use</p><div class="eq">\\[Y=\\frac{A}{s+2}+\\frac{Bs+C}{s^2+4}.\\]</div><p>Clearing denominators gives \\(5s+1=A(s^2+4)+(Bs+C)(s+2)\\). Solving yields \\(A=-9/8,B=9/8,C=11/4\\).</p><div class="whybox"><div class="eq">\\[\\boxed{y=-\\frac98e^{-2t}+\\frac98\\cos2t+\\frac{11}{8}\\sin2t}.\\]</div></div>`),
 l10Book('Original course problem',6,`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>Which workflow is safer for a constant-coefficient IVP: fit constants after solving a homogeneous/nonhomogeneous time-domain equation, or transform first? Explain what Laplace does differently rather than claiming one method is always superior.</p>`,`<p>Both can be valid. Laplace is especially systematic because the derivative identities insert \\(y(0),y'(0),\\ldots\\) directly into one algebraic equation for \\(Y(s)\\). Time-domain methods may be shorter when the forcing and homogeneous basis are simple. The transferable skill is to choose a method based on structure, then verify the final result in the original IVP.</p>`)
];
const lesson10Mastery={id:'l10-mastery',courseLesson:10,color:'#9a3f69',badge:'8',label:'Transfer mastery',title:'Oct. 19 Laplace Transfer Mastery',subtitle:'6 unseen problems · recognition, algebra, IVPs, polynomial coefficients',desc:'Distinct transfer problems rather than a replay of the textbook screens already used in the lesson.',lessons:[{title:'Inverse transforms & algebra transfer',screens:lesson10Transfer.slice(0,2)},{title:'IVP & operational-rule transfer',screens:lesson10Transfer.slice(2,4)},{title:'Decomposition & method judgment',screens:lesson10Transfer.slice(4,6)}]};

const lesson10Units=[...lesson10BaseUnits,lesson10Mastery];
if(!units.some(u=>u&&u.id==='l10-map'))units.push(...lesson10Units);
courseLessons[9]={number:10,title:'Inverse Laplace Transforms & IVPs',subtitle:'Oct. 19 · O’Neil §3.1–3.2 · inverse transforms · partial fractions · derivative rules · IVPs · polynomial coefficients',status:'current'};
if(typeof renderCourseMap==='function')renderCourseMap();
if(typeof render==='function')render();