/* Lesson 11 — Oct. 21: first shifting theorem; Heaviside H(t-a); pulses; second shifting theorem. */
const lesson11CoreTag='<span class="supplementalTag">Core · Oct. 21 syllabus · O’Neil §3.3.1–3.3.2</span>';
const lesson11BookTag='<span class="supplementalTag">Authentic textbook · O’Neil §3.3</span>';
const lesson11ExplainTag='<span class="supplementalTag">Expanded explanation · Lesson 1 depth standard</span>';
const lesson11BoundaryTag='<span class="supplementalTag">Scope boundary · Oct. 28 material intentionally deferred</span>';
function l11Book(n,prompt,solution){return {type:'bookproblem',bookSection:'§3.3',title:`O’Neil §3.3 Problem ${n}`,prompt,solution};}
function l11Clone(s){return s?{...s,inlineBookPractice:true}:null;}
const l11ForwardData=[
 {n:1,p:`f(t)=(t^3-3t+2)e^{-2t}`,work:`Ignoring the exponential first gives \\(F_0(s)=6/s^4-3/s^2+2/s\\). Since \\(e^{-2t}=e^{at}\\) with \\(a=-2\\), the first shifting theorem replaces every \\(s\\) by \\(s+2\\).`,ans:`\\frac6{(s+2)^4}-\\frac3{(s+2)^2}+\\frac2{s+2}`,why:`The plus sign inside \\(s+2\\) follows from \\(F(s-a)\\) with \\(a=-2\\).`},
 {n:2,p:`f(t)=e^{-3t}(t-2)`,work:`For \\(t-2\\), \\(F_0(s)=1/s^2-2/s\\). Here \\(a=-3\\), so use \\(F_0(s+3)\\).`,ans:`\\frac1{(s+3)^2}-\\frac2{s+3}`,why:`Both terms receive the same shift because the same exponential multiplies the entire function.`},
 {n:3,p:`f(t)=\\begin{cases}1,&0\\le t<7,\\\\ \\cos t,&t\\ge7.\\end{cases}`,work:`Use the baseline-plus-change form \\(f=1+H(t-7)(\\cos t-1)\\). Put \\(u=t-7\\). Then \\(\\cos t=\\cos(u+7)=\\cos7\\cos u-\\sin7\\sin u\\). The correction therefore transforms to \\(e^{-7s}[s\\cos7/(s^2+1)-\\sin7/(s^2+1)-1/s]\\).`,ans:`\\frac1s+e^{-7s}\\left(\\frac{s\\cos7-\\sin7}{s^2+1}-\\frac1s\\right)`,why:`Before 7 the correction is zero; after 7 it changes the baseline 1 into \\(\\cos t\\).`},
 {n:4,p:`f(t)=e^{-4t}(t-\\cos t)`,work:`The transform of \\(t-\\cos t\\) is \\(1/s^2-s/(s^2+1)\\). The factor \\(e^{-4t}\\) means replace \\(s\\) everywhere by \\(s+4\\).`,ans:`\\frac1{(s+4)^2}-\\frac{s+4}{(s+4)^2+1}`,why:`The whole transform shifts; shifting only one term would not represent multiplication of the whole time function by \\(e^{-4t}\\).`},
 {n:5,p:`f(t)=\\begin{cases}t,&0\\le t<3,\\\\1-3t,&t\\ge3.\\end{cases}`,work:`Write \\(f=t+H(t-3)(1-4t)\\). With \\(u=t-3\\), the change is \\(1-4(u+3)=-4u-11\\). Its transform is \\(e^{-3s}[-4/s^2-11/s]\\).`,ans:`\\frac1{s^2}-e^{-3s}\\left(\\frac4{s^2}+\\frac{11}s\\right)`,why:`For \\(t\\ge3\\), the baseline plus correction is \\(t+(1-4t)=1-3t\\).`},
 {n:6,p:`f(t)=\\begin{cases}2t-\\sin t,&0\\le t<\\pi,\\\\0,&t\\ge\\pi.\\end{cases}`,work:`Let \\(g(t)=2t-\\sin t\\) and write \\(f=g-H(t-\\pi)g\\). With \\(u=t-\\pi\\), \\(g(u+\\pi)=2u+2\\pi+\\sin u\\). Transform the original \\(g\\), then subtract the delayed copy.`,ans:`\\frac2{s^2}-\\frac1{s^2+1}-e^{-\\pi s}\\left(\\frac2{s^2}+\\frac{2\\pi}s+\\frac1{s^2+1}\\right)`,why:`The delayed copy equals the original signal after \\(\\pi\\), so subtracting it turns the signal off.`},
 {n:7,p:`f(t)=e^{-t}(1-t^2+\\sin t)`,work:`First transform the parentheses: \\(F_0=1/s-2/s^3+1/(s^2+1)\\). Since \\(a=-1\\), replace \\(s\\) by \\(s+1\\) everywhere.`,ans:`\\frac1{s+1}-\\frac2{(s+1)^3}+\\frac1{(s+1)^2+1}`,why:`The same exponential modulation applies to every summand.`}
];
l11ForwardData.push(
 {n:8,p:`f(t)=\\begin{cases}t^2,&0\\le t<2,\\\\1-t-4t^2,&t\\ge2.\\end{cases}`,work:`Use baseline \\(t^2\\): \\(f=t^2+H(t-2)(1-t-5t^2)\\). With \\(u=t-2\\), expand the change: \\(1-(u+2)-5(u+2)^2=-5u^2-21u-21\\). Transform that polynomial and multiply by \\(e^{-2s}\\).`,ans:`\\frac2{s^3}-e^{-2s}\\left(\\frac{10}{s^3}+\\frac{21}{s^2}+\\frac{21}s\\right)`,why:`Writing the new piece as a polynomial in \\(t-2\\) is what makes the second shift apply.`},
 {n:9,p:`f(t)=\\begin{cases}\\cos t,&0\\le t<2\\pi,\\\\2-\\sin t,&t\\ge2\\pi.\\end{cases}`,work:`Start with \\(\\cos t\\), then add \\(H(t-2\\pi)[2-\\sin t-\\cos t]\\). With \\(u=t-2\\pi\\), sine and cosine are unchanged because of period \\(2\\pi\\).`,ans:`\\frac{s}{s^2+1}+e^{-2\\pi s}\\left(\\frac2s-\\frac{1+s}{s^2+1}\\right)`,why:`The switch occurs after a whole period, so no extra phase constants appear.`},
 {n:10,p:`f(t)=\\begin{cases}-4,&0\\le t<1,\\\\0,&1\\le t<3,\\\\e^{-t},&t\\ge3.\\end{cases}`,work:`Represent the first block by \\(-4+4H(t-1)\\). The last block is \\(H(t-3)e^{-t}\\). With \\(u=t-3\\), \\(e^{-t}=e^{-3}e^{-u}\\), so that term transforms to \\(e^{-3s}e^{-3}/(s+1)\\).`,ans:`-\\frac4s+\\frac{4e^{-s}}s+\\frac{e^{-3}e^{-3s}}{s+1}`,why:`Checking the three time intervals confirms the Heaviside representation before transforming.`},
 {n:11,p:`f(t)=te^{-t}\\cos(3t)`,work:`Use \\(\\mathcal L\\{t\\cos(at)\\}=(s^2-a^2)/(s^2+a^2)^2\\) with \\(a=3\\), then apply \\(e^{-t}\\) by replacing \\(s\\) with \\(s+1\\).`,ans:`\\frac{(s+1)^2-9}{[(s+1)^2+9]^2}`,why:`This is a first-shift problem; no Heaviside gate is present.`},
 {n:12,p:`f(t)=e^t(1-\\cosh t)`,work:`The unmodulated transform is \\(F_0(s)=1/s-s/(s^2-1)\\). The factor \\(e^t\\) has \\(a=1\\), so use \\(F_0(s-1)\\).`,ans:`\\frac1{s-1}-\\frac{s-1}{(s-1)^2-1}`,why:`A growing factor \\(e^{+t}\\) produces the shift \\(s-1\\).`},
 {n:13,p:`f(t)=\\begin{cases}t-2,&0\\le t<16,\\\\-1,&t\\ge16.\\end{cases}`,work:`Use \\(f=t-2+H(t-16)(1-t)\\). With \\(u=t-16\\), \\(1-t=-u-15\\). Transform the baseline and the delayed correction separately.`,ans:`\\frac1{s^2}-\\frac2s-e^{-16s}\\left(\\frac1{s^2}+\\frac{15}s\\right)`,why:`For \\(t\\ge16\\), \\(t-2+(1-t)=-1\\), matching the stated piece.`},
 {n:14,p:`f(t)=\\begin{cases}1-\\cos(2t),&0\\le t<3\\pi,\\\\0,&t\\ge3\\pi.\\end{cases}`,work:`Let \\(g=1-\\cos2t\\) and write \\(f=g-H(t-3\\pi)g\\). Because \\(g(u+3\\pi)=1-\\cos(2u+6\\pi)=g(u)\\), the delayed copy has the same base transform.`,ans:`(1-e^{-3\\pi s})\\left(\\frac1s-\\frac{s}{s^2+4}\\right)`,why:`The subtraction turns the waveform off exactly at \\(3\\pi\\).`},
 {n:15,p:`f(t)=e^{-5t}(t^4+2t^2+t)`,work:`Transform the polynomial first: \\(24/s^5+4/s^3+1/s^2\\). Then the factor \\(e^{-5t}\\) shifts every \\(s\\) to \\(s+5\\).`,ans:`\\frac{24}{(s+5)^5}+\\frac4{(s+5)^3}+\\frac1{(s+5)^2}`,why:`All three terms are multiplied by the same exponential and receive the same shift.`}
);
function l11Forward(d){return l11Book(d.n,`<p>${lesson11BookTag}<br>Find the Laplace transform of</p><div class="eq">\\[${d.p}.\\]</div>`,`<p><b>Plan before calculating.</b> Decide first whether this is an exponential first-shift problem or a switching/Heaviside problem. Rewrite the time-domain function into the theorem's exact pattern before touching the transform table.</p><p><b>Work.</b> ${d.work}</p><div class="whybox"><div class="eq">\\[\\boxed{F(s)=${d.ans}}.\\]</div></div><p><b>Verification idea.</b> ${d.why}</p>`);}
const l11ForwardBook=l11ForwardData.map(l11Forward);
const l11InverseData=[
 {n:16,p:`F(s)=\\frac1{s^2+4s+12}`,work:`Complete the square: \\(s^2+4s+12=(s+2)^2+8=(s+2)^2+(2\\sqrt2)^2\\). Write the numerator as \\((1/(2\\sqrt2))(2\\sqrt2)\\), then use the sine pair with a first shift by \\(-2\\).`,ans:`f(t)=\\frac1{2\\sqrt2}e^{-2t}\\sin(2\\sqrt2\,t)`},
 {n:17,p:`F(s)=\\frac1{s^2-4s+5}`,work:`Complete the square: \\(s^2-4s+5=(s-2)^2+1\\). The base inverse of \\(1/(s^2+1)\\) is \\(\\sin t\\); the center \\(s-2\\) supplies the factor \\(e^{2t}\\).`,ans:`f(t)=e^{2t}\\sin t`},
 {n:18,p:`F(s)=\\frac{e^{-5s}}{s^3}`,work:`Since \\(\\mathcal L\\{t^2\\}=2/s^3\\), the base inverse of \\(1/s^3\\) is \\(t^2/2\\). The factor \\(e^{-5s}\\) delays that base function by 5.`,ans:`f(t)=\\frac12H(t-5)(t-5)^2`},
 {n:19,p:`F(s)=\\frac{e^{-2s}}{s^2+9}`,work:`The base inverse of \\(1/(s^2+9)\\) is \\((1/3)\\sin3t\\). Delay it by 2 using the second shifting theorem.`,ans:`f(t)=\\frac13H(t-2)\\sin(3(t-2))`},
 {n:20,p:`F(s)=\\frac{3e^{-4s}}{s+2}`,work:`The base inverse of \\(3/(s+2)\\) is \\(3e^{-2t}\\). The factor \\(e^{-4s}\\) delays and gates the entire waveform by 4.`,ans:`f(t)=3H(t-4)e^{-2(t-4)}`},
 {n:21,p:`F(s)=\\frac1{s^2+6s+7}`,work:`Complete the square: \\(s^2+6s+7=(s+3)^2-2=(s+3)^2-(\\sqrt2)^2\\). Since \\(\\sinh(at)\\leftrightarrow a/(s^2-a^2)\\), include a factor \\(1/\\sqrt2\\) and shift by \\(-3\\).`,ans:`f(t)=\\frac1{\\sqrt2}e^{-3t}\\sinh(\\sqrt2\,t)`},
 {n:22,p:`F(s)=\\frac{s-4}{s^2-8s+10}`,work:`The denominator is \\((s-4)^2-6\\), and the numerator is already \\(s-4\\). This is the shifted cosh pair \\(s/(s^2-a^2)\\leftrightarrow\\cosh(at)\\) with \\(a=\\sqrt6\\).`,ans:`f(t)=e^{4t}\\cosh(\\sqrt6\,t)`},
 {n:23,p:`F(s)=\\frac{s+2}{s^2+6s+1}`,work:`Write the denominator as \\((s+3)^2-8=(s+3)^2-(2\\sqrt2)^2\\) and the numerator as \\(s+2=(s+3)-1\\). The first part is a shifted cosh pair; the second is \\(-1/(2\\sqrt2)\\) times the corresponding shifted sinh pair.`,ans:`f(t)=e^{-3t}\\left[\\cosh(2\\sqrt2\,t)-\\frac1{2\\sqrt2}\\sinh(2\\sqrt2\,t)\\right]`},
 {n:24,p:`F(s)=\\frac{e^{-s}}{s-5}`,work:`The base inverse of \\(1/(s-5)\\) is \\(e^{5t}\\). The factor \\(e^{-s}\\) delays it by one: shift the argument to \\(t-1\\) and gate with \\(H(t-1)\\).`,ans:`f(t)=H(t-1)e^{5(t-1)}`},
 {n:25,p:`F(s)=\\frac{e^{-21s}}{s(s^2+16)}`,work:`First decompose \\(1/[s(s^2+16)]=(1/16)[1/s-s/(s^2+16)]\\). Its base inverse is \\((1/16)(1-\\cos4t)\\). Then delay the whole function by 21.`,ans:`f(t)=\\frac1{16}H(t-21)\\left[1-\\cos(4(t-21))\\right]`}
];
function l11Inverse(d){return l11Book(d.n,`<p>${lesson11BookTag}<br>Find the inverse Laplace transform of</p><div class="eq">\\[${d.p}.\\]</div>`,`<p><b>Plan before calculating.</b> Separate the two mechanisms: a shift inside \\(F(s-a)\\) is handled by the first shifting theorem; an outside factor \\(e^{-as}\\) is a time delay handled by the second shifting theorem.</p><p><b>Work.</b> ${d.work}</p><div class="whybox"><div class="eq">\\[\\boxed{${d.ans}}.\\]</div></div><p><b>Check.</b> Apply the corresponding forward shifting theorem to the boxed time-domain expression.</p>`);}
const l11InverseBook=l11InverseData.map(l11Inverse);
const l11P26=l11Book(26,
 `<p>${lesson11BookTag}<br>Use the first shifting theorem to determine</p><div class="eq">\\[\\mathcal L\\left\\{e^{-2t}\\int_0^t e^{2\\xi}\\cos(3\\xi)\\,d\\xi\\right\\}.\\]</div>`,
 `<p><b>Plan.</b> Name the integral \\(h(t)\\). Find \\(H(s)=\\mathcal L\\{h\\}\\) from its derivative, then use the outer factor \\(e^{-2t}\\) as a first shift.</p><p>Because</p><div class="eq">\\[h'(t)=e^{2t}\\cos3t,\\qquad h(0)=0,\\]</div><p>the derivative rule gives</p><div class="eq">\\[sH(s)=\\mathcal L\\{e^{2t}\\cos3t\\}=\\frac{s-2}{(s-2)^2+9}.\\]</div><p>Therefore</p><div class="eq">\\[H(s)=\\frac{s-2}{s[(s-2)^2+9]}.\\]</div><p>The outer factor is \\(e^{-2t}\\), so the first shifting theorem says to replace \\(s\\) by \\(s+2\\):</p><div class="eq">\\[H(s+2)=\\frac{s}{(s+2)(s^2+9)}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L\\left\\{e^{-2t}\\int_0^t e^{2\\xi}\\cos(3\\xi)\\,d\\xi\\right\\}=\\frac{s}{(s+2)(s^2+9)}}.\\]</div></div><p><b>Check.</b> The shift is \\(s+2\\), consistent with the decaying factor \\(e^{-2t}\\).</p>`);
const lesson11BaseUnits=[
 {id:'l11-map',courseLesson:11,color:'#4059ad',badge:'1',label:'Oct. 21 map',title:'Two Different Shifts — Do Not Mix Them Up',subtitle:'first shift in s · second shift in t · Heaviside switching',desc:'Build a conceptual map of the two shifting theorems and the Heaviside function before applying formulas.',lessons:[{title:'The two shifts',screens:[
  {type:'teach',title:'The syllabus boundary for Oct. 21',html:`<p>${lesson11CoreTag}</p><p>Today has four connected ideas: <b>the first shifting theorem, the Heaviside step function, pulses, and the second shifting theorem</b>.</p><div class="reviewGrid"><div class="mini"><b>Exponential modulation</b><p>Multiplying by \\(e^{at}\\) shifts the transform in the \\(s\\)-variable.</p></div><div class="mini"><b>Delayed start</b><p>A factor \\(H(t-a)\\) can switch a signal on at time \\(a\\); a factor \\(e^{-as}\\) represents a time delay in transform space.</p></div></div>`},
  {type:'teach',title:'What is deliberately deferred?',html:`<p>${lesson11BoundaryTag}</p><p>O’Neil §3.3 continues into discontinuous-forcing IVPs, switched circuits, and §3.3.3 Heaviside's formula. The syllabus schedules those worked applications and Heaviside's formula for <b>Oct. 28</b>, so this lesson stops before that boundary.</p>`},
  {type:'quiz',title:'Which shift is which?',q:`Which feature in s-space is the signature of a time delay by a>0?`,options:[`A factor e^{-as}`,`Replacing s by s-a only`,`Multiplying F(s) by s`],answer:0,why:'The second shifting theorem maps H(t-a)f(t-a) to e^{-as}F(s).'}
 ]}]},
 {id:'l11-first',courseLesson:11,color:'#2e7d69',badge:'2',label:'First shift',title:'First Shifting Theorem: Exponentials Shift s',subtitle:'L{e^{at}f(t)}=F(s-a)',desc:'Derive the theorem from the Laplace integral, then use O’Neil Examples 3.4–3.6 and authentic exercises.',lessons:[{title:'Derive and use the first shift',screens:[
  {type:'teach',title:'Derive the first shifting theorem from the definition',html:`<p>${lesson11BookTag}</p><p>Suppose \\(F(s)=\\mathcal L\\{f(t)\\}\\). Then</p><div class="eq">\\[\\mathcal L\\{e^{at}f(t)\\}=\\int_0^\\infty e^{-st}e^{at}f(t)dt=\\int_0^\\infty e^{-(s-a)t}f(t)dt.\\]</div><p>The last integral is exactly \\(F\\) evaluated at \\(s-a\\):</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L\\{e^{at}f(t)\\}=F(s-a)}.\\]</div></div><p>The theorem comes directly from combining the two exponentials in the kernel.</p>`},
  {type:'teach',title:'O’Neil Example 3.4 — forward shift',html:`<p>${lesson11BookTag}</p><p>Since \\(\\mathcal L\\{\\cos2t\\}=s/(s^2+4)\\), multiplying by \\(e^{6t}\\) means replace \\(s\\) by \\(s-6\\):</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L\\{e^{6t}\\cos2t\\}=\\frac{s-6}{(s-6)^2+4}}.\\]</div></div>`},
  {type:'teach',title:'Inverse form of the first shift',html:`<p>Read the theorem backwards:</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L^{-1}\\{F(s-a)\\}=e^{at}f(t)}.\\]</div></div><p><b>Sign check:</b> a center \\(s+2=s-(-2)\\) corresponds to \\(e^{-2t}\\).</p>`},
  {type:'teach',title:'O’Neil Example 3.5 — complete the square first',html:`<p>${lesson11BookTag}</p><div class="eq">\\[\\frac4{s^2+4s+20}=\\frac4{(s+2)^2+16}.\\]</div><p>The base inverse of \\(4/(s^2+16)\\) is \\(\\sin4t\\). The center is \\(s+2=s-(-2)\\), hence</p><div class="whybox"><div class="eq">\\[\\boxed{e^{-2t}\\sin4t}.\\]</div></div>`},
  {type:'teach',title:'O’Neil Example 3.6 — shift hyperbolic pairs',html:`<p>${lesson11BookTag}</p><p>Complete the square and center the numerator:</p><div class="eq">\\[\\frac{3s-1}{s^2-6s+2}=\\frac{3(s-3)}{(s-3)^2-7}+\\frac8{(s-3)^2-7}.\\]</div><p>Match cosh and sinh, then shift by 3:</p><div class="whybox"><div class="eq">\\[\\boxed{3e^{3t}\\cosh(\\sqrt7t)+\\frac8{\\sqrt7}e^{3t}\\sinh(\\sqrt7t)}.\\]</div></div>`},
  ...[1,2,4,7].map(n=>l11Clone(l11ForwardBook[n-1])),
  {type:'quiz',title:'First-shift sign check',q:`If F(s)=L{f}, what is L{e^{-5t}f(t)}?`,options:[`F(s+5)`,`F(s-5)`,`e^{-5s}F(s)`],answer:0,why:'Here a=-5, so F(s-a)=F(s+5).'}
 ]},{title:'More first-shift book practice',screens:[11,12,15].map(n=>l11Clone(l11ForwardBook[n-1])).concat([l11Clone(l11P26)])}]},
 {id:'l11-heaviside',courseLesson:11,color:'#7651b8',badge:'3',label:'Heaviside',title:'Heaviside Functions: Turn a Signal On at a Chosen Time',subtitle:'H(t-a) is a switch, not a shifted waveform by itself',desc:'Learn the exact piecewise meaning of the unit step and how multiplication gates a signal.',lessons:[{title:'Step functions as switches',screens:[
  {type:'teach',title:'Definition and endpoint convention',html:`<p>${lesson11BookTag}</p><div class="eq">\\[H(t)=\\begin{cases}0,&t<0,\\\\1,&t\\ge0,\\end{cases}\\qquad H(t-a)=\\begin{cases}0,&t<a,\\\\1,&t\\ge a.\\end{cases}\\]</div><p>O’Neil uses the convention \\(H(0)=1\\). The value at one isolated point does not change a Laplace integral.</p>`},
  {type:'teach',title:'Multiplying by H(t-a) gates a function',html:`<p>${lesson11ExplainTag}</p><div class="eq">\\[H(t-a)g(t)=\\begin{cases}0,&t<a,\\\\g(t),&t\\ge a.\\end{cases}\\]</div><p>This does <b>not</b> automatically shift \\(g\\). Thus \\(H(t-\\pi)\\cos t\\) is the ordinary cosine switched off before \\(\\pi\\), while \\(H(t-3)\\cos(t-3)\\) is both gated and shifted.</p>`},
  {type:'quiz',title:'Gate versus shift',q:`For t≥3, what does H(t-3)cos(t) equal?`,options:[`cos(t)`,`cos(t-3)`,`0`],answer:0,why:'The Heaviside factor gates the existing cos(t); it does not change its argument.'}
 ]}]},
 {id:'l11-pulses',courseLesson:11,color:'#b35f4a',badge:'4',label:'Pulses',title:'Pulses: Turn a Signal On, Then Off Again',subtitle:'H(t-a)-H(t-b) isolates an interval',desc:'Build finite-duration inputs from differences of step functions and translate multi-piece definitions systematically.',lessons:[{title:'Pulse logic',screens:[
  {type:'teach',title:'Derive the pulse piece by piece',html:`<p>${lesson11BookTag}</p><p>For \\(0<a<b\\),</p><div class="eq">\\[H(t-a)-H(t-b)=\\begin{cases}0,&t<a,\\\\1,&a\\le t<b,\\\\0,&t\\ge b.\\end{cases}\\]</div><p>Multiplying by \\(g(t)\\) leaves \\(g\\) untouched only on \\([a,b)\\).</p>`},
  {type:'teach',title:'O’Neil Example 3.11 — represent three pieces',html:`<p>${lesson11BookTag}</p><p>For \\(f=0\\) before 2, \\(f=t-1\\) on \\([2,3)\\), and \\(f=-4\\) from 3 onward, use a pulse for the middle piece and a step for the last:</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=[H(t-2)-H(t-3)](t-1)-4H(t-3)}.\\]</div></div><p>Check all three intervals explicitly before transforming.</p>`},
  {type:'quiz',title:'Build a unit pulse',q:`Which expression equals 1 for 2≤t<5 and 0 outside that interval?`,options:[`H(t-2)-H(t-5)`,`H(t-5)-H(t-2)`,`H(t-2)+H(t-5)`],answer:0,why:'The first step turns on at 2 and the second subtracts it back off at 5.'}
 ]}]}
];
lesson11BaseUnits.push(
 {id:'l11-second',courseLesson:11,color:'#d27a42',badge:'5',label:'Second shift',title:'Second Shifting Theorem: A Time Delay Becomes e^{-as}',subtitle:'L{H(t-a)f(t-a)}=e^{-as}F(s)',desc:'Derive the delay theorem, learn the crucial rewrite in t-a, and apply O’Neil Examples 3.7–3.9.',lessons:[{title:'Derive and use the time shift',screens:[
  {type:'teach',title:'Derive the second shifting theorem',html:`<p>${lesson11BookTag}</p><p>Start from the gated shifted function. Because it is zero before \\(a\\),</p><div class="eq">\\[\\mathcal L\\{H(t-a)f(t-a)\\}=\\int_a^\\infty e^{-st}f(t-a)dt.\\]</div><p>Set \\(u=t-a\\), so \\(t=u+a\\):</p><div class="eq">\\[\\int_0^\\infty e^{-s(u+a)}f(u)du=e^{-as}\\int_0^\\infty e^{-su}f(u)du.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L\\{H(t-a)f(t-a)\\}=e^{-as}F(s)}.\\]</div></div><p>The factor \\(e^{-as}\\) is the algebraic signature of a delay by \\(a\\).</p>`},
  {type:'teach',title:'Inverse form: delay the whole waveform',html:`<p>Read the theorem backwards:</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L^{-1}\\{e^{-as}F(s)\\}=H(t-a)f(t-a)}.\\]</div></div><div class="warn"><b>Common error:</b> writing \\(H(t-a)f(t)\\). The waveform itself must also shift to \\(f(t-a)\\).</div>`},
  {type:'teach',title:'O’Neil Example 3.7 — transform of a delayed step',html:`<p>${lesson11BookTag}</p><p>Take \\(f(t)=1\\), so \\(F(s)=1/s\\). Then</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L\\{H(t-a)\\}=\\frac{e^{-as}}s}.\\]</div></div>`},
  {type:'teach',title:'O’Neil Example 3.8 — rewrite everything in t-2',html:`<p>${lesson11BookTag}</p><p>If \\(g=0\\) before 2 and \\(g=t^2+1\\) afterward, rewrite</p><div class="eq">\\[t^2+1=(t-2)^2+4(t-2)+5.\\]</div><p>Thus \\(g=H(t-2)[(t-2)^2+4(t-2)+5]\\), so</p><div class="whybox"><div class="eq">\\[\\boxed{G(s)=e^{-2s}\\left(\\frac2{s^3}+\\frac4{s^2}+\\frac5s\\right)}.\\]</div></div>`},
  {type:'teach',title:'O’Neil Example 3.9 — read the delay from e^{-3s}',html:`<p>${lesson11BookTag}</p><p>The base inverse of \\(s/(s^2+4)\\) is \\(\\cos2t\\). Therefore</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L^{-1}\\left\\{e^{-3s}\\frac{s}{s^2+4}\\right\\}=H(t-3)\\cos(2(t-3))}.\\]</div></div>`},
  ...[3,5,6].map(n=>l11Clone(l11ForwardBook[n-1])),
  {type:'quiz',title:'Rewrite before transforming',q:`To use the second shifting theorem on H(t-4)t², how should t² be rewritten in terms of t-4?`,options:[`(t-4)²+8(t-4)+16`,`(t-4)² only`,`t²e^{-4s}`],answer:0,why:'Write t=(t-4)+4 and expand; the theorem needs a function of the shifted argument.'}
 ]}]},
 {id:'l11-piecewise',courseLesson:11,color:'#6a6f7b',badge:'6',label:'Piecewise transforms',title:'Translate Piecewise Functions into Heaviside Form',subtitle:'baseline + changes at each jump',desc:'Practice the most error-prone step: encoding a piecewise function correctly before transforming it.',lessons:[{title:'Authentic piecewise book practice',screens:[8,9,10,13,14].map(n=>l11Clone(l11ForwardBook[n-1]))}]},
 {id:'l11-inverse',courseLesson:11,color:'#3f7f8f',badge:'7',label:'Shifted inverses',title:'Inverse Transforms with First and Second Shifts',subtitle:'centered quadratics versus e^{-as} delays',desc:'Use authentic O’Neil Problems 16–25 to distinguish the two inverse-shift mechanisms and execute both cleanly.',lessons:[{title:'Book Problems 16–20',screens:l11InverseBook.slice(0,5).map(l11Clone)},{title:'Book Problems 21–25',screens:l11InverseBook.slice(5).map(l11Clone)}]}
);
const lesson11Transfer=[
 l11Book('T1',`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>A transform contains \\(F(s+4)\\). What time-domain operation does that represent if \\(F(s)=\\mathcal L\\{f(t)\\}\\)? Explain the sign.</p>`,`<p>Write \\(s+4=s-(-4)\\). The first shifting theorem gives</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L^{-1}\\{F(s+4)\\}=e^{-4t}f(t)}.\\]</div></div><p>The positive shift inside the argument corresponds to a decaying exponential because the theorem uses \\(F(s-a)\\).</p>`),
 l11Book('T2',`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>Encode \\(f(t)=2\\) for \\(0\\le t<3\\), \\(5-t\\) for \\(3\\le t<6\\), and \\(0\\) afterward using Heaviside functions.</p>`,`<p>Use the first piece as a baseline, then add each change when it occurs:</p><div class="eq">\\[f(t)=2+H(t-3)[(5-t)-2]+H(t-6)[0-(5-t)].\\]</div><p>Therefore</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=2+H(t-3)(3-t)+H(t-6)(t-5)}.\\]</div></div><p>Checking all three time intervals is the fastest verification.</p>`),
 l11Book('T3',`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>Find the inverse transform of \\(e^{-2s}\\frac{s+1}{(s+1)^2+4}\\).</p>`,`<p>The base inverse is \\(e^{-t}\\cos2t\\). The outside factor \\(e^{-2s}\\) delays the entire base waveform by 2:</p><div class="whybox"><div class="eq">\\[\\boxed{H(t-2)e^{-(t-2)}\\cos(2(t-2))}.\\]</div></div><p>Do not write \\(H(t-2)e^{-t}\\cos2t\\); a true delay shifts the internal clock as well as gating the signal.</p>`),
 l11Book('T4',`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>Construct a pulse of height 7 active only on \\(4\\le t<9\\), and give its Laplace transform.</p>`,`<p>The pulse is</p><div class="eq">\\[7[H(t-4)-H(t-9)].\\]</div><p>Using \\(\\mathcal L\\{H(t-a)\\}=e^{-as}/s\\),</p><div class="whybox"><div class="eq">\\[\\boxed{F(s)=\\frac7s(e^{-4s}-e^{-9s})}.\\]</div></div>`),
 l11Book('T5',`<p><span class="supplementalTag">Original diagnostic · not an O’Neil exercise</span><br>A student claims \\(e^{-3s}F(s)\\) corresponds to \\(e^{-3t}f(t)\\). Diagnose the confusion.</p>`,`<p>They have mixed the two shifting theorems. Multiplication by \\(e^{-3t}\\) produces the <b>first shift</b> \\(F(s+3)\\). Multiplication by \\(e^{-3s}\\) in transform space produces the <b>time delay</b></p><div class="eq">\\[\\boxed{H(t-3)f(t-3)}.\\]</div>`),
 l11Book('T6',`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>Write \\(H(t-5)t^2\\) in the exact shifted form required by the second shifting theorem, then transform it.</p>`,`<p>Set \\(u=t-5\\), so \\(t=u+5\\) and \\(t^2=u^2+10u+25\\). Hence</p><div class="eq">\\[H(t-5)t^2=H(t-5)[(t-5)^2+10(t-5)+25].\\]</div><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L= e^{-5s}\\left(\\frac2{s^3}+\\frac{10}{s^2}+\\frac{25}s\\right)}.\\]</div></div>`)
];
const lesson11Mastery={id:'l11-mastery',courseLesson:11,color:'#9a3f69',badge:'8',label:'Transfer mastery',title:'Oct. 21 Shifting & Heaviside Transfer Mastery',subtitle:'6 unseen problems · first shift, delay, pulses, piecewise encoding',desc:'Distinct transfer and diagnostic work rather than replaying the §3.3 textbook bank already used throughout the lesson.',lessons:[{title:'Shift recognition & piecewise encoding',screens:lesson11Transfer.slice(0,2)},{title:'Delay & pulse transfer',screens:lesson11Transfer.slice(2,4)},{title:'Error diagnosis & shifted rewrite',screens:lesson11Transfer.slice(4,6)}]};
const lesson11Units=[...lesson11BaseUnits,lesson11Mastery];
if(!units.some(u=>u&&u.id==='l11-map'))units.push(...lesson11Units);
courseLessons[10]={number:11,title:'Shifting Theorems, Heaviside Functions & Pulses',subtitle:'Oct. 21 · O’Neil §3.3.1–3.3.2 · first shift · H(t-a) · pulses · second shift',status:'current'};
if(typeof renderCourseMap==='function')renderCourseMap();
if(typeof render==='function')render();