/* Lesson 23 — Dec. 9: X'=AX, eigenvalue method, complex eigenvalues, phase portraits. */
const l23Core='<span class="supplementalTag">Core · Dec. 9 syllabus · Part 5</span>',l23Book='<span class="supplementalTag">Authentic textbook concept · supplied O’Neil §§13.1–13.2, §14.1.1</span>',l23Explain='<span class="supplementalTag">Expanded explanation · Lesson 1 depth standard</span>',l23Recon='<span class="supplementalTag">Syllabus-aligned reconstruction · not claimed as an O’Neil example</span>';
function l23Board(title,prompt,solution,section){return {type:'bookproblem',bookSection:section,title,prompt,solution};} function l23Clone(s){return s?{...s,inlineBookPractice:true}:null;}
const l23Real=l23Board('Eigenvalue method — two real modes',`<p>${l23Recon}</p><p>Solve</p><div class="eq">\\[X'=AX,\\qquad A=\\begin{pmatrix}3&1\\\\1&3\\end{pmatrix}.\\]</div><p>Give the general real solution and classify the origin.</p>`,`<p>Try a modal solution \\(X=e^{\\lambda t}v\\). Then</p><div class="eq">\\[\\lambda e^{\\lambda t}v=Ae^{\\lambda t}v\\iff Av=\\lambda v.\\]</div><p>The characteristic equation is \\((3-\\lambda)^2-1=0\\), so \\(\\lambda_1=4\\), \\(\\lambda_2=2\\). Corresponding eigenvectors are \\(v_1=(1,1)^T\\), \\(v_2=(1,-1)^T\\). Hence</p><div class="eq">\\[\\boxed{X(t)=c_1e^{4t}\\binom11+c_2e^{2t}\\binom1{-1}}.\\]</div><p>Both eigenvalues are positive, so every nonzero mode grows forward in time. The origin is an <b>unstable node/source</b>. Direct verification follows from differentiating each mode and using \\(Av_i=\\lambda_i v_i\\).</p>`,'§13.2 constant-A eigenvalue method');
const l23Saddle=l23Board('Phase portrait — saddle from opposite signs',`<p>${l23Recon}</p><p>For \\(A=\\operatorname{diag}(2,-1)\\), solve \\(X'=AX\\) and describe the phase portrait.</p>`,`<div class="eq">\\[x'=2x,\\qquad y'=-y\\Rightarrow x=c_1e^{2t},\\quad y=c_2e^{-t}.\\]</div><p>The \\(x\\)-axis is an unstable eigendirection and the \\(y\\)-axis is stable. As \\(t\\to\\infty\\), only initial states exactly on the stable \\(y\\)-axis approach the origin; every generic trajectory has a nonzero unstable component and eventually moves away along the \\(x\\)-direction. Opposite-sign real eigenvalues therefore give a</p><div class="eq">\\[\\boxed{\\text{saddle point (always unstable)}}.\\]</div>`,'§14.1.1 phase portraits');
const l23Complex=l23Board('Complex eigenvalues — build a real solution',`<p>${l23Recon}</p><p>Solve</p><div class="eq">\\[X'=\\begin{pmatrix}1&-2\\\\2&1\\end{pmatrix}X\\]</div><p>in real form and classify the origin.</p>`,`<p>The characteristic polynomial is \\((1-\\lambda)^2+4=0\\), so \\(\\lambda=1\\pm2i\\). The matrix splits as \\(A=I+2J\\), where \\(J=\\begin{pmatrix}0&-1\\\\1&0\\end{pmatrix}\\) generates rotation. A real fundamental pair is</p><div class="eq">\\[e^t\\binom{\\cos2t}{\\sin2t},\\qquad e^t\\binom{-\\sin2t}{\\cos2t}.\\]</div><p>Therefore</p><div class="eq">\\[\\boxed{X=e^t\\left[c_1\\binom{\\cos2t}{\\sin2t}+c_2\\binom{-\\sin2t}{\\cos2t}\\right]}.\\]</div><p>The factor \\(e^t\\) makes radius grow while the trigonometric factors rotate: an <b>unstable spiral/source</b>. Substitution verifies the pair directly.</p>`,'§13.2.1 complex eigenvalue case');
const l23IC=l23Board('Initial condition — solve modal constants',`<p>${l23Recon}</p><p>For the system in the real-modes example, impose \\(X(0)=(3,1)^T\\).</p>`,`<p>At \\(t=0\\),</p><div class="eq">\\[c_1\\binom11+c_2\\binom1{-1}=\\binom31.\\]</div><p>Thus \\(c_1+c_2=3\\), \\(c_1-c_2=1\\), so \\(c_1=2,c_2=1\\). Hence</p><div class="eq">\\[\\boxed{X(t)=2e^{4t}\\binom11+e^{2t}\\binom1{-1}}.\\]</div><p>At \\(t=0\\), this returns \\((3,1)^T\\), providing the IC check.</p>`,'§13.1 initial-value structure');
const l23Class=l23Board('Classify from eigenvalues before sketching',`<p>${l23Recon}</p><p>Classify the origin for each eigenvalue pair: (a) \\(-3,-1\\), (b) \\(2,-4\\), (c) \\(-1\\pm3i\\), (d) \\(\\pm2i\\).</p>`,`<p>(a) Two negative real eigenvalues: <b>stable node/sink</b>.</p><p>(b) Opposite signs: <b>saddle, unstable</b>.</p><p>(c) Negative real part with nonzero imaginary part: <b>stable spiral/sink</b>.</p><p>(d) Pure imaginary pair in the standard diagonalizable planar linear case: <b>center</b>, with closed periodic orbits and neutral (not asymptotic) stability.</p><p>The real part controls exponential growth/decay; the imaginary part supplies rotation/oscillation.</p>`,'§14.1.1 phase portraits');
const lesson23Units=[
{id:'l23-map',courseLesson:23,color:'#476a91',badge:'1',label:'Dec. 9 map',title:'Systems X′ = AX & Phase Portraits',subtitle:'structure · eigenvalue method · complex modes · geometry',desc:'Use eigenpairs to turn coupled first-order ODEs into natural modes.',lessons:[{title:'Map',screens:[{type:'teach',title:'Textbook numbering reconciliation',html:`<p>${l23Core}</p><p>The syllabus calls this O’Neil §§8.1–8.2 and §9.1.1. In the supplied 8th SI edition, the matching material is <b>§13.1 Linear Systems</b>, <b>§13.1.1 Structure of Solutions of X′=AX</b>, <b>§13.2 Solution of X′=AX When A Is Constant</b>, <b>§13.2.1 Complex Eigenvalue Case</b>, and <b>§14.1.1 Phase Portraits of Homogeneous Linear Systems</b>.</p>`},{type:'teach',title:'What X′=AX means',html:`<p>${l23Explain}</p><p>If \\(X=(x_1,\\ldots,x_n)^T\\), then \\(X'\\) means differentiate each component. The matrix equation \\(X'=AX\\) is simply a compact form of \\(n\\) coupled first-order ODEs. The zero vector is always an equilibrium because \\(A0=0\\).</p>`}]}]},
{id:'l23-structure',courseLesson:23,color:'#34776e',badge:'2',label:'Structure',title:'Solution Space of X′ = AX',subtitle:'superposition · fundamental modes · initial values',desc:'Carry scalar linear-ODE structure into vector form.',lessons:[{title:'Structure',screens:[{type:'teach',title:'Superposition survives',html:`<p>${l23Book}</p><p>If \\(X_1,X_2\\) solve the homogeneous linear system, then so does \\(c_1X_1+c_2X_2\\). For an \\(n\\)-dimensional system, \\(n\\) linearly independent solution vectors form a fundamental set; an initial condition \\(X(t_0)=X_0\\) then determines the constants uniquely under the standard continuity assumptions.</p>`},l23Clone(l23IC)]}]},
{id:'l23-method',courseLesson:23,color:'#795d9a',badge:'3',label:'Eigenvalue method',title:'Why X=e^{λt}v Works',subtitle:'differential equation becomes Av=λv',desc:'Derive the method from the trial form.',lessons:[{title:'Method',screens:[{type:'teach',title:'Choose a mode whose direction stays fixed',html:`<p>${l23Explain}</p><p>For constant \\(A\\), seek a solution with fixed spatial direction \\(v\\) and scalar exponential amplitude:</p><div class="eq">\\[X(t)=e^{\\lambda t}v.\\]</div><p>Then \\(X'=\\lambda e^{\\lambda t}v\\) while \\(AX=e^{\\lambda t}Av\\). Cancel the never-zero exponential to obtain</p><div class="eq">\\[\\boxed{Av=\\lambda v}.\\]</div><p>So the trial form is not a guess pulled from nowhere: it deliberately converts the ODE into the eigenvalue problem learned in Lesson 22.</p>`},l23Clone(l23Real)]}]},
{id:'l23-phase',courseLesson:23,color:'#9a6038',badge:'4',label:'Phase portrait',title:'From Eigenvalues to Geometry',subtitle:'sink · source · saddle · center/spiral',desc:'Read long-time behavior without solving every initial condition.',lessons:[{title:'Portrait',screens:[{type:'teach',title:'A phase portrait removes time from the axes',html:`<p>${l23Explain}</p><p>For a planar system, plot \\((x_1(t),x_2(t))\\) in the state plane. Arrows show increasing time. Eigenvectors give invariant straight-line directions. Signs of real eigenvalues determine growth or decay along those lines.</p>`},l23Clone(l23Saddle)]}]},
{id:'l23-complex',courseLesson:23,color:'#3e7287',badge:'5',label:'Complex pair',title:'Complex Eigenvalues, Real Motion',subtitle:'α±iβ ⇒ e^{αt} × rotation',desc:'Turn complex modes into real sine-cosine solutions.',lessons:[{title:'Complex modes',screens:[{type:'teach',title:'Interpret α ± iβ',html:`<p>${l23Book}</p><p>For a real matrix, complex eigenvalues occur as conjugates \\(\\alpha\\pm i\\beta\\). Euler’s formula converts \\(e^{(\\alpha+i\\beta)t}\\) into</p><div class="eq">\\[e^{\\alpha t}(\\cos\\beta t+i\\sin\\beta t).\\]</div><p>The real part \\(\\alpha\\) controls radial growth/decay; \\(\\beta\\) controls angular oscillation. Real and imaginary parts of one complex vector solution provide two real solutions.</p>`},l23Clone(l23Complex)]}]},
{id:'l23-classify',courseLesson:23,color:'#536b48',badge:'6',label:'Classify',title:'Classification Checklist',subtitle:'real part first · then directions/rotation',desc:'Make the sketch from eigenvalue data.',lessons:[{title:'Classification',screens:[{type:'teach',title:'Planar quick map',html:`<p>${l23Explain}</p><p>Distinct real \\(\\lambda_1,\\lambda_2<0\\): stable node. Both positive: unstable node. Opposite signs: saddle. Complex \\(\\alpha\\pm i\\beta\\): spiral sink if \\(\\alpha<0\\), spiral source if \\(\\alpha>0\\), center in the standard pure-imaginary case \\(\\alpha=0\\). Repeated/defective cases need extra care.</p>`},l23Clone(l23Class)]}]},
{id:'l23-verify',courseLesson:23,color:'#856b37',badge:'7',label:'Verify',title:'Verification & Physical Meaning',subtitle:'differentiate · multiply · check IC · interpret stability',desc:'Do not stop at a symbolic formula.',lessons:[{title:'Verification',screens:[{type:'teach',title:'Four checks for a system solution',html:`<p>${l23Explain}</p><p><b>1.</b> Differentiate the proposed \\(X(t)\\). <b>2.</b> Compute \\(AX(t)\\) independently and compare every component. <b>3.</b> Check the initial condition. <b>4.</b> Compare the formula’s growth/decay with the phase-portrait classification.</p><p>In an engineering state model, a stable sink means small unforced perturbations decay; a source or saddle means some perturbations grow.</p>`},{type:'quiz',title:'Stability test',q:'A real 2×2 system has eigenvalues −2 and −5. What should every solution do as t→∞?',options:['Approach the origin','Spiral outward','Move away along one eigendirection'],answer:0,why:'Both independent modal exponentials decay.'}]}]},
{id:'l23-mastery',courseLesson:23,color:'#a24458',badge:'8',label:'Mastery',title:'Dec. 9 Mastery',subtitle:'solve · impose IC · classify · verify',desc:'Use the scratch boards before revealing the complete route.',lessons:[{title:'Real modes',screens:[l23Real,l23IC]},{title:'Portraits',screens:[l23Saddle,l23Class]},{title:'Complex mode',screens:[l23Complex]}]}
];
if(!units.some(u=>u&&u.id==='l23-map'))units.push(...lesson23Units);if(courseLessons[21])courseLessons[21].status='complete';courseLessons[22]={number:23,title:'Systems X′ = AX & Phase Portraits',subtitle:'Dec. 9 · supplied O’Neil §§13.1–13.2, §14.1.1',status:'current'};

// Quality reconstruction: add source-authentic examples, teach the defective case, and replace repeated mastery.
const l23Ex136=l23Board('O’Neil Example 13.6 — direct eigenvalue solution',`<p>${l23Book}</p><p>O’Neil considers</p><div class="eq">\\[X'=\\begin{pmatrix}4&2\\\\3&3\\end{pmatrix}X,\\]</div><p>whose eigenvalues are \\(1,6\\) with corresponding eigenvectors \\((2,-3)^T,(1,1)^T\\). Write the general solution and a fundamental matrix.</p>`,`<p>Each eigenpair produces a modal solution \\(Ee^{\\lambda t}\\). Therefore</p><div class="eq">\\[\\boxed{X=c_1e^t\\binom2{-3}+c_2e^{6t}\\binom11}.\\]</div><p>Using those independent solutions as columns gives</p><div class="eq">\\[\\boxed{\\Phi(t)=\\begin{pmatrix}2e^t&e^{6t}\\\\-3e^t&e^{6t}\\end{pmatrix}}.\\]</div><p>The determinant is \\(5e^{7t}\\ne0\\), so the columns are independent for every \\(t\\).</p>`,'§13.2 · Example 13.6');
const l23Defective=l23Board('O’Neil Example 13.9 — defective repeated eigenvalue',`<p>${l23Book}</p><p>For</p><div class="eq">\\[A=\\begin{pmatrix}1&3\\\\-3&7\\end{pmatrix},\\]</div><p>O’Neil finds the repeated eigenvalue \\(\\lambda=4\\) but only one eigenvector direction \\(E=(1,1)^T\\). Explain how a second solution is constructed.</p>`,`<p>The first mode is</p><div class="eq">\\[X_1=Ee^{4t}.\\]</div><p>Because a second eigenvector does not exist, O’Neil tries</p><div class="eq">\\[X_2=(tE+K)e^{4t}.\\]</div><p>Substitution into \\(X'=AX\\), using \\(AE=4E\\), leaves the algebraic condition</p><div class="eq">\\[(A-4I)K=E.\\]</div><p>One valid choice from O’Neil is \\(K=(1,4/3)^T\\), giving</p><div class="eq">\\[\\boxed{X_2=e^{4t}\\binom{1+t}{4/3+t}}.\\]</div><p>The explicit \\(t\\) factor makes \\(X_2\\) independent of \\(X_1\\). This is the missing case when algebraic multiplicity exceeds the available eigenvector count.</p>`,'§13.2 · Example 13.9');
const l23P1=l23Board('O’Neil §13.1 Problem 1 — independence, fundamental matrix, IVP',`<p>${l23Book}</p><p>For \\(x_1'=5x_1+3x_2\\), \\(x_2'=x_1+3x_2\\), O’Neil supplies</p><div class="eq">\\[X_1=e^{2t}\\binom{-1}{1},\\qquad X_2=e^{6t}\\binom31,\\]</div><p>with \\(X(0)=(0,4)^T\\). Show independence and solve the IVP.</p>`,`<p>At \\(t=0\\), the solution vectors are \\((-1,1)^T\\) and \\((3,1)^T\\). Their determinant is</p><div class="eq">\\[(-1)(1)-3(1)=-4\\ne0,\\]</div><p>so they are independent and form a fundamental set. Write</p><div class="eq">\\[X=c_1X_1+c_2X_2.\\]</div><p>The initial condition gives \\(-c_1+3c_2=0\\), \\(c_1+c_2=4\\), hence \\(c_1=3,c_2=1\\). Therefore</p><div class="eq">\\[\\boxed{X(t)=3e^{2t}\\binom{-1}{1}+e^{6t}\\binom31}.\\]</div>`,'§13.1 · Problem 1');
const l23Transfer=[
l23Board('Transfer 1 — build the matrix system',`<p>${l23Recon}</p><p>Rewrite \\(x'=2x-y\\), \\(y'=3x+4y\\) as \\(X'=AX\\), clearly defining \\(X\\) and \\(A\\).</p>`,`<p>Set \\(X=(x,y)^T\\). Then</p><div class="eq">\\[\\boxed{X'=\\begin{pmatrix}2&-1\\\\3&4\\end{pmatrix}X}.\\]</div><p>Each row reproduces one scalar differential equation, so this is only a compact notation change—not a new model.</p>`,'Original transfer · system notation'),
l23Board('Transfer 2 — solution-space independence',`<p>${l23Recon}</p><p>Two solutions of a \\(2\\times2\\) homogeneous system satisfy \\(X_1(0)=(1,2)^T\\), \\(X_2(0)=(2,4)^T\\). Can they form a fundamental set?</p>`,`<p>No. Their initial vectors are dependent because \\(X_2(0)=2X_1(0)\\), so the determinant of the initial-value matrix is zero. By O’Neil’s independence criterion, the solution functions are not independent and cannot form a fundamental set.</p>`,'Original diagnostic · fundamental solutions'),
l23Board('Transfer 3 — solve from eigenpairs only',`<p>${l23Recon}</p><p>A constant matrix has eigenpairs \\((\\lambda_1,v_1)=(-2,(1,3)^T)\\) and \\((\\lambda_2,v_2)=(1,(2,-1)^T)\\). Write the general solution and classify the origin.</p>`,`<div class="eq">\\[X=c_1e^{-2t}\\binom13+c_2e^t\\binom2{-1}.\\]</div><p>One mode decays and the other grows, so the origin is a \\(\\boxed{\\text{saddle}}\\), hence unstable.</p>`,'Original transfer · eigenvalue method'),
l23Board('Transfer 4 — defective diagnosis',`<p>${l23Recon}</p><p>A \\(2\\times2\\) system has a repeated eigenvalue \\(\\lambda=-3\\) but only one eigenvector. Why is \\(c_1e^{-3t}v+c_2e^{-3t}v\\) not a general solution, and what structural ingredient is missing?</p>`,`<p>Those two terms are scalar multiples of the same solution, so they span only one solution direction. A two-dimensional system needs two independent solutions. In the defective case, the second solution must contain a generalized-eigenvector/polynomial factor, typically</p><div class="eq">\\[e^{-3t}(tv+k),\\]</div><p>with \\(k\\) chosen by substitution.</p>`,'Original diagnostic · defective system'),
l23Board('Transfer 5 — complex-pair interpretation',`<p>${l23Recon}</p><p>A real planar system has eigenvalues \\(-0.5\\pm4i\\). Without computing eigenvectors, what can you say about amplitude, oscillation frequency, and stability?</p>`,`<p>The real part gives the envelope \\(e^{-0.5t}\\), so amplitudes decay. The imaginary magnitude gives angular frequency \\(4\\). Thus trajectories rotate while shrinking toward the origin: a stable spiral/sink.</p>`,'Original transfer · complex eigenvalues'),
l23Board('Transfer 6 — phase portrait trap',`<p>${l23Recon}</p><p>A student sees eigenvalues \\(3\\) and \\(1\\) and labels the origin “stable because both eigenvalues are real.” Diagnose the error.</p>`,`<p>Reality of the eigenvalues does not determine stability; their <b>signs</b> do. Since both are positive, both modal exponentials grow forward in time. The origin is an unstable nodal source.</p>`,'Original diagnostic · stability')
];
const l23StructureUnit=units.find(u=>u&&u.id==='l23-structure');if(l23StructureUnit&&!l23StructureUnit.lessons[0].screens.some(s=>s.title&&s.title.includes('Problem 1')))l23StructureUnit.lessons[0].screens.push(l23P1);
const l23MethodUnit=units.find(u=>u&&u.id==='l23-method');if(l23MethodUnit&&!l23MethodUnit.lessons[0].screens.some(s=>s.title&&s.title.includes('Example 13.6')))l23MethodUnit.lessons[0].screens.push(l23Ex136);
const l23ClassUnit=units.find(u=>u&&u.id==='l23-classify');if(l23ClassUnit&&!l23ClassUnit.lessons[0].screens.some(s=>s.title&&s.title.includes('Example 13.9')))l23ClassUnit.lessons[0].screens.unshift({type:'teach',title:'Repeated eigenvalue: when eigenvectors are missing',html:`<p>${l23Book}</p><p>A repeated eigenvalue is not automatically a problem. If its eigenspace supplies the full multiplicity, ordinary eigenmodes are enough. If it does <b>not</b>, O’Neil §13.2 constructs additional independent solutions with polynomial factors in \\(t\\). This defective case must be checked before writing a claimed general solution.</p>`},l23Defective);
const l23Mastery=units.find(u=>u&&u.id==='l23-mastery');if(l23Mastery){l23Mastery.title='Dec. 9 Transfer Mastery';l23Mastery.subtitle='6 unseen problems · notation, independence, modes, defects, stability';l23Mastery.desc='Tests system reasoning without replaying the guided examples.';l23Mastery.lessons=[{title:'Structure & modes',screens:l23Transfer.slice(0,3)},{title:'Defects & complex modes',screens:l23Transfer.slice(3,5)},{title:'Portrait diagnosis',screens:l23Transfer.slice(5,6)}];}

const l23P1312=l23Board('O’Neil §13.1 Problem 2 — fundamental matrix and IVP',`<p>${l23Book}</p><p>For</p><div class="eq">\\[x_1'=2x_1+x_2,\\qquad x_2'=-3x_1+6x_2,\\]</div><p>O’Neil supplies the solutions</p><div class="eq">\\[X_1=e^{5t}\\binom13,\\qquad X_2=e^{3t}\\binom11,\\]</div><p>with \\(X(0)=(-2,1)^T\\). Verify independence, form a fundamental matrix, and solve the IVP.</p>`,`<p>At \\(t=0\\), the solution columns are \\((1,3)^T\\) and \\((1,1)^T\\), whose determinant is \\(1-3=-2\\ne0\\). Thus they are independent.</p><div class="eq">\\[\\Phi(t)=\\begin{pmatrix}e^{5t}&e^{3t}\\\\3e^{5t}&e^{3t}\\end{pmatrix}.\\]</div><p>Write \\(X=c_1X_1+c_2X_2\\). The initial condition gives</p><div class="eq">\\[c_1+c_2=-2,\\qquad3c_1+c_2=1,\\]</div><p>so \\(c_1=3/2\\), \\(c_2=-7/2\\). Therefore</p><div class="eq">\\[\\boxed{X(t)=\\frac32e^{5t}\\binom13-\\frac72e^{3t}\\binom11}.\\]</div>`,'§13.1 · Problem 2');
const l23P1321=l23Board('O’Neil §13.2 Problem 1 — build a real fundamental matrix',`<p>${l23Book}</p><p>Find a real fundamental matrix for</p><div class="eq">\\[X'=AX,\\qquad A=\\begin{pmatrix}3&0\\\\5&-4\\end{pmatrix}.\\]</div>`,`<p>The eigenvalues are the diagonal entries of this triangular matrix: \\(3\\) and \\(-4\\).</p><p>For \\(\\lambda=3\\), solve \\((A-3I)v=0\\): \\(5x-7y=0\\), so choose \\(v_1=(7,5)^T\\). For \\(\\lambda=-4\\), choose \\(v_2=(0,1)^T\\).</p><p>The two modal solutions form the columns</p><div class="eq">\\[\\boxed{\\Phi(t)=\\begin{pmatrix}7e^{3t}&0\\\\5e^{3t}&e^{-4t}\\end{pmatrix}}.\\]</div><p>Its determinant is \\(7e^{-t}\\ne0\\), so the columns are independent for every real \\(t\\).</p>`,'§13.2 · Problem 1');
const l23StructurePractice=units.find(u=>u&&u.id==='l23-structure');
if(l23StructurePractice&&!l23StructurePractice.lessons[0].screens.some(s=>s.title===l23P1312.title))l23StructurePractice.lessons[0].screens.push(l23Clone(l23P1312));
const l23MethodPractice=units.find(u=>u&&u.id==='l23-method');
if(l23MethodPractice&&!l23MethodPractice.lessons[0].screens.some(s=>s.title===l23P1321.title))l23MethodPractice.lessons[0].screens.push(l23Clone(l23P1321));

if(typeof renderCourseMap==='function')renderCourseMap();if(typeof render==='function')render();