/* Lesson 14 — Nov. 4: power-series review, analytic functions, ordinary/singular points, recurrence relations. */
const l14Core='<span class="supplementalTag">Core · Nov. 4 syllabus</span>';
const l14Book='<span class="supplementalTag">Authentic textbook · O’Neil §2.5.1 in supplied 8th SI edition</span>';
const l14Explain='<span class="supplementalTag">Expanded explanation · Lesson 1 depth standard</span>';
const l14Recon='<span class="supplementalTag">Syllabus-aligned reconstruction · not claimed as an O’Neil example</span>';
function l14Board(title,prompt,solution,section){return {type:'bookproblem',bookSection:section,title,prompt,solution};}
function l14Clone(s){return s?{...s,inlineBookPractice:true}:null;}
const l14Ex218=l14Board('O’Neil Example 2.18 — build a recurrence from a first-order equation',
`<p>${l14Book}</p><p>Find a power-series solution about \\(x=0\\) for</p><div class="eq">\\[y'+2xy=\\frac1{1-x}.\\]</div><p>Work far enough to see how one free coefficient remains.</p>`,
`<p><b>1 · Choose the series where the center is 0.</b></p><div class="eq">\\[y=\\sum_{n=0}^{\\infty}a_nx^n,\\qquad y'=\\sum_{n=1}^{\\infty}na_nx^{n-1}.\\]</div><p>Also, for \\(|x|<1\\),</p><div class="eq">\\[\\frac1{1-x}=\\sum_{n=0}^{\\infty}x^n.\\]</div><p><b>2 · Substitute before trying to compare coefficients.</b></p><div class="eq">\\[\\sum_{n=1}^{\\infty}na_nx^{n-1}+2\\sum_{n=0}^{\\infty}a_nx^{n+1}=\\sum_{n=0}^{\\infty}x^n.\\]</div><p>The powers do not yet line up. Reindex:</p><div class="eq">\\[\\sum_{n=0}^{\\infty}(n+1)a_{n+1}x^n+\\sum_{n=1}^{\\infty}2a_{n-1}x^n=\\sum_{n=0}^{\\infty}x^n.\\]</div><p><b>3 · Separate the exceptional low-index term.</b> At \\(n=0\\), \\(a_1=1\\). For \\(n\\ge1\\),</p><div class="eq">\\[(n+1)a_{n+1}+2a_{n-1}=1.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{a_{n+1}=\\frac{1-2a_{n-1}}{n+1}},\\qquad n\\ge1.\\]</div></div><p>Thus \\(a_0\\) stays arbitrary, as expected for a first-order differential equation. The first coefficients are</p><div class="eq">\\[a_1=1,\\quad a_2=\\tfrac12(1-2a_0),\\quad a_3=-\\tfrac13,\\quad a_4=\\tfrac12a_0,\\quad a_5=\\tfrac13.\\]</div><p>So the solution begins</p><div class="eq">\\[y=a_0+x+\\tfrac12(1-2a_0)x^2-\\tfrac13x^3+\\tfrac12a_0x^4+\\tfrac13x^5+\\cdots.\\]</div><p><b>Verification idea.</b> Differentiate this truncated series, substitute, and check that coefficients match through the retained order. The source series for \\(1/(1-x)\\) limits this expansion to \\(|x|<1\\).</p>`,'§2.5.1');
const l14Ex219=l14Board('O’Neil Example 2.19 — a second-order recurrence splits into two solution families',
`<p>${l14Book}</p><p>Find a power-series solution about \\(x=0\\) for</p><div class="eq">\\[y''+x^2y=0.\\]</div><p>Generate enough coefficients to expose the two arbitrary constants.</p>`,
`<p><b>1 · Start with a general power series.</b></p><div class="eq">\\[y=\\sum_{n=0}^{\\infty}a_nx^n,\\qquad y''=\\sum_{n=2}^{\\infty}n(n-1)a_nx^{n-2}.\\]</div><p>Substitute:</p><div class="eq">\\[\\sum_{n=2}^{\\infty}n(n-1)a_nx^{n-2}+\\sum_{n=0}^{\\infty}a_nx^{n+2}=0.\\]</div><p>Reindex both to powers \\(x^n\\):</p><div class="eq">\\[\\sum_{n=0}^{\\infty}(n+2)(n+1)a_{n+2}x^n+\\sum_{n=2}^{\\infty}a_{n-2}x^n=0.\\]</div><p><b>2 · Low powers come first.</b> The \\(x^0\\) and \\(x^1\\) coefficients give</p><div class="eq">\\[2a_2=0,\\qquad 6a_3=0,\\]</div><p>so \\(a_2=a_3=0\\). For \\(n\\ge2\\),</p><div class="whybox"><div class="eq">\\[\\boxed{a_{n+2}=-\\frac{a_{n-2}}{(n+2)(n+1)}}.\\]</div></div><p>The recurrence advances by four indices, so coefficients descend from either \\(a_0\\) or \\(a_1\\); the \\(a_2,a_3\\) branches vanish.</p><div class="eq">\\[a_4=-\\frac{a_0}{12},\\quad a_5=-\\frac{a_1}{20},\\quad a_8=\\frac{a_0}{672},\\quad a_9=\\frac{a_1}{1440}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y=a_0\\left(1-\\frac{x^4}{12}+\\frac{x^8}{672}+\\cdots\\right)+a_1\\left(x-\\frac{x^5}{20}+\\frac{x^9}{1440}+\\cdots\\right)}.\\]</div></div><p>Two arbitrary constants are exactly what a second-order equation should produce.</p>`,'§2.5.1');
const l14R1=l14Board('Series skill — determine a radius of convergence',`<p>${l14Recon}</p><p>For</p><div class="eq">\\[\\sum_{n=0}^{\\infty}\\frac{(x-2)^n}{5^n},\\]</div><p>find the center and radius of convergence.</p>`,`<p>Rewrite as a geometric series:</p><div class="eq">\\[\\sum_{n=0}^{\\infty}\\left(\\frac{x-2}{5}\\right)^n.\\]</div><p>A geometric series converges when the magnitude of its ratio is less than one:</p><div class="eq">\\[\\left|\\frac{x-2}{5}\\right|<1\\iff |x-2|<5.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{x_0=2,\\qquad R=5}.\\]</div></div><p>The radius says how far you may move from the center before this series representation ceases to converge.</p>`,'Syllabus series review');
const l14R2=l14Board('Series skill — classify the expansion point',`<p>${l14Recon}</p><p>Classify \\(x_0=0\\) for</p><div class="eq">\\[x(1+x)y''+(1-x)y'+2y=0.\\]</div>`,`<p>Here \\(P(x)=x(1+x)\\), the coefficient of \\(y''\\). Since \\(P(0)=0\\), zero is a <b>singular point</b>, not an ordinary point.</p><p>For a preview of Lesson 15, divide by \\(P\\) away from zero. Then</p><div class="eq">\\[x\\frac{Q}{P}=\\frac{1-x}{1+x},\\qquad x^2\\frac{R}{P}=\\frac{2x}{1+x},\\]</div><p>both analytic near zero, so the singular point is actually <b>regular singular</b>. That extra classification is what permits the Frobenius method next lesson.</p>`,'Syllabus point classification');
const l14R3=l14Board('Recurrence skill — do not lose the low-index equations',`<p>${l14Recon}</p><p>Suppose substitution gives</p><div class="eq">\\[\\sum_{n=0}^{\\infty}(n+2)(n+1)a_{n+2}x^n+\\sum_{n=1}^{\\infty}a_{n-1}x^n=0.\\]</div><p>Find the low-index equation and the recurrence.</p>`,`<p>The second sum starts at 1, so the \\(n=0\\) term exists only in the first sum:</p><div class="eq">\\[2a_2=0\\Rightarrow a_2=0.\\]</div><p>Now combine the sums only for \\(n\\ge1\\):</p><div class="eq">\\[(n+2)(n+1)a_{n+2}+a_{n-1}=0.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{a_{n+2}=-\\frac{a_{n-1}}{(n+2)(n+1)}},\\qquad n\\ge1.\\]</div></div><p>The separate low-index equation is not bookkeeping trivia; dropping it can create a spurious free coefficient and therefore a wrong solution space.</p>`,'Syllabus recurrence practice');
const l14TransferMastery=[
l14Board('Transfer 1 — center and radius from structure',`<p>${l14Recon}</p><p>For</p><div class="eq">\\[\\sum_{n=0}^{\\infty}\\frac{(x+3)^n}{4^n},\\]</div><p>identify the center and radius, and state what must still be checked at the endpoints.</p>`,`<p>This is geometric with ratio \\(r=(x+3)/4\\). Therefore</p><div class="eq">\\[|x+3|<4.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{x_0=-3,\\qquad R=4}.\\]</div></div><p>The endpoints \\(x=1\\) and \\(x=-7\\) are not decided by the radius alone; each must be tested separately in the original series.</p>`,'Original course transfer'),
l14Board('Transfer 2 — ordinary-point decision before algebra',`<p>${l14Recon}</p><p>Classify \\(x_0=0\\) for</p><div class="eq">\\[(2+x)y''+(1-x)y'+e^x y=0.\\]</div><p>Explain why the ordinary power-series method is justified locally.</p>`,`<p>The leading coefficient is \\(P(x)=2+x\\), so \\(P(0)=2\\ne0\\). Dividing by \\(P\\) gives coefficients \\((1-x)/(2+x)\\) and \\(e^x/(2+x)\\), both analytic near zero because their denominator is nonzero there.</p><div class="whybox"><div class="eq">\\[\\boxed{x=0\\text{ is an ordinary point}.}\\]</div></div><p>That is the classification needed before assuming an ordinary Taylor series solution.</p>`,'Original course transfer'),
l14Board('Transfer 3 — recurrence with a three-index stride',`<p>${l14Recon}</p><p>For</p><div class="eq">\\[y''+xy=0,\\]</div><p>derive the power-series recurrence about zero and identify the forced low-index coefficient.</p>`,`<p>Use \\(y=\\sum a_nx^n\\). Then</p><div class="eq">\\[y''=\\sum_{n=0}^{\\infty}(n+2)(n+1)a_{n+2}x^n,\\qquad xy=\\sum_{n=1}^{\\infty}a_{n-1}x^n.\\]</div><p>The \\(n=0\\) equation gives \\(2a_2=0\\), hence \\(a_2=0\\). For \\(n\\ge1\\),</p><div class="whybox"><div class="eq">\\[\\boxed{a_{n+2}=-\\frac{a_{n-1}}{(n+2)(n+1)}}.\\]</div></div><p>The recurrence moves by three indices, leaving the \\(a_0\\) and \\(a_1\\) branches independent while the \\(a_2\\) branch vanishes.</p>`,'Original course transfer'),
l14Board('Transfer 4 — first-order series and the number of free constants',`<p>${l14Recon}</p><p>Solve by a power series about zero far enough to obtain the recurrence:</p><div class="eq">\\[y'-xy=0.\\]</div>`,`<p>Substitute</p><div class="eq">\\[\\sum_{n=0}^{\\infty}(n+1)a_{n+1}x^n-\\sum_{n=1}^{\\infty}a_{n-1}x^n=0.\\]</div><p>The low-index equation is \\(a_1=0\\). For \\(n\\ge1\\),</p><div class="eq">\\[\\boxed{a_{n+1}=\\frac{a_{n-1}}{n+1}}.\\]</div><p>Thus only \\(a_0\\) is free, as expected for a first-order ODE. The series begins \\(a_0(1+x^2/2+x^4/8+\\cdots)\\), consistent with the closed form \\(Ce^{x^2/2}\\).</p>`,'Original course transfer'),
l14Board('Transfer 5 — diagnose an illegal index merge',`<p>${l14Recon}</p><p>A student combines</p><div class="eq">\\[\\sum_{n=0}^{\\infty}(n+2)(n+1)a_{n+2}x^n+\\sum_{n=2}^{\\infty}a_{n-2}x^n=0\\]</div><p>into one sum starting at \\(n=0\\) without separating anything. What is wrong?</p>`,`<p>The second sum has no \\(n=0\\) or \\(n=1\\) terms. Combining from zero would silently invent \\(a_{-2}\\) and \\(a_{-1}\\), or equivalently lose the real low-power equations.</p><p>Separate them first:</p><div class="eq">\\[2a_2+6a_3x+\\sum_{n=2}^{\\infty}[(n+2)(n+1)a_{n+2}+a_{n-2}]x^n=0.\\]</div><p>Hence \\(a_2=a_3=0\\) before the general recurrence is used.</p>`,'Original course diagnostic'),
l14Board('Transfer 6 — initial data live in the first coefficients',`<p>${l14Recon}</p><p>An ordinary-point second-order solution is written</p><div class="eq">\\[y=\\sum_{n=0}^{\\infty}a_nx^n.\\]</div><p>If \\(y(0)=2\\) and \\(y'(0)=-1\\), what are \\(a_0\\) and \\(a_1\\), and why does this matter?</p>`,`<p>At the center,</p><div class="eq">\\[y(0)=a_0,\\qquad y'(0)=a_1.\\]</div><p>Therefore</p><div class="whybox"><div class="eq">\\[\\boxed{a_0=2,\\qquad a_1=-1}.\\]</div></div><p>For a second-order recurrence, these two starting coefficients are the series-language version of the two initial conditions. Once they are fixed, the recurrence determines the remaining coefficients.</p>`,'Original course transfer')
];

const lesson14Units=[
{id:'l14-map',courseLesson:14,color:'#476a91',badge:'1',label:'Nov. 4 map',title:'Why Series Solutions Exist',subtitle:'power series · convergence · analytic functions · ordinary/singular points',desc:'Build the prerequisites before manipulating infinite sums.',lessons:[{title:'Map',screens:[
{type:'teach',title:'First reconcile the syllabus with the supplied textbook',html:`<p>${l14Core}</p><p>The syllabus labels the Nov. 4 material as <b>O’Neil §4.1</b>. In the supplied <b>8th Edition SI</b>, the matching material is actually <b>§2.5.1 Power Series Solutions</b>. This lesson follows the syllabus topic list while sourcing the mathematics and authentic examples from the supplied edition’s §2.5.1.</p><p>The required sequence is: power-series review → radius of convergence → analytic functions → ordinary versus singular points → substitution of a series into an ODE → recurrence relations.</p>`},
{type:'teach',title:'Why use an infinite series at all?',html:`<p>${l14Explain}</p><p>Earlier methods succeeded because the equation fit a recognizable closed-form pattern. But some variable-coefficient ODEs do not collapse into elementary functions. A power series replaces the impossible question “Can I guess the whole function?” with the local question “Can I determine its coefficients one at a time?”</p><div class="eq">\\[y(x)=a_0+a_1(x-x_0)+a_2(x-x_0)^2+\\cdots.\\]</div><p>Once the ODE forces a rule connecting the coefficients, that rule is a <b>recurrence relation</b>. It is the series analogue of solving for constants in a characteristic equation.</p>`},
{type:'quiz',title:'What changes?',q:'In a power-series method, what are the unknowns we solve for?',options:['The coefficients a₀,a₁,a₂,…','Only the center x₀','Only the radius R'],answer:0,why:'The center is chosen and the ODE determines relationships among the coefficients.'}
]}]},
{id:'l14-review',courseLesson:14,color:'#34776e',badge:'2',label:'Series review',title:'Power Series, Centers, and Radius of Convergence',subtitle:'what the symbols mean · where the series is valid',desc:'Make convergence a mathematical condition rather than an afterthought.',lessons:[{title:'Convergence',screens:[
{type:'teach',title:'Read a power series structurally',html:`<p>${l14Explain}</p><div class="eq">\\[\\sum_{n=0}^{\\infty}a_n(x-x_0)^n.\\]</div><p><b>\\(x_0\\)</b> is the center. <b>\\(a_n\\)</b> is the coefficient sequence. For a particular value of \\(x\\), the expression becomes an ordinary numerical infinite series. It may converge or diverge.</p><p>A power series has a radius \\(R\\in[0,\\infty]\\) such that it converges for \\(|x-x_0|<R\\) and diverges for \\(|x-x_0|>R\\). At finite endpoints, check separately unless a theorem already resolves them.</p>`},
{type:'teach',title:'Why differentiating term by term is legal',html:`<p>Inside the radius of convergence, a power series may be differentiated and integrated term by term, and the resulting series have the same radius. Thus</p><div class="eq">\\[y=\\sum_{n=0}^\\infty a_n(x-x_0)^n\\Rightarrow y'=\\sum_{n=1}^\\infty n a_n(x-x_0)^{n-1},\\]</div><div class="eq">\\[y''=\\sum_{n=2}^\\infty n(n-1)a_n(x-x_0)^{n-2}.\\]</div><p>This is the engine of the ODE method: differentiation converts the unknown function into algebraic factors involving \\(n\\) and the same coefficients.</p>`},
l14Clone(l14R1),
{type:'quiz',title:'Endpoint caution',q:'If a power series has radius R=3 about x₀=1, what can you say immediately about x=4?',options:['It is an endpoint and must be checked separately','It always converges','It always diverges'],answer:0,why:'|4−1|=3=R. Radius rules alone do not decide a finite endpoint.'}
]}]},
{id:'l14-analytic',courseLesson:14,color:'#795d9a',badge:'3',label:'Analytic functions',title:'Analytic Means “Equal to Its Local Power Series”',subtitle:'Taylor coefficients · local representation · nearest obstruction',desc:'Connect calculus Taylor series to the ODE existence idea.',lessons:[{title:'Analyticity',screens:[
{type:'teach',title:'Smooth and analytic are not synonyms',html:`<p>${l14Core}</p><p>A function is <b>analytic at \\(x_0\\)</b> if it equals a convergent power series in some interval around \\(x_0\\):</p><div class="eq">\\[f(x)=\\sum_{n=0}^{\\infty}a_n(x-x_0)^n.\\]</div><p>If the equality holds, repeated differentiation at the center gives the Taylor coefficients</p><div class="eq">\\[a_n=\\frac{f^{(n)}(x_0)}{n!}.\\]</div><p>Having derivatives of every order is not by itself enough in advanced analysis; analyticity additionally says the Taylor series actually represents the function locally.</p>`},
{type:'teach',title:'Why singularities control how far a series can go',html:`<p>${l14Explain}</p><p>For familiar analytic functions, a Taylor series expands until it encounters an obstruction to analytic continuation. A simple real example is</p><div class="eq">\\[\\frac1{1-x}=1+x+x^2+\\cdots,\\qquad |x|<1.\\]</div><p>The denominator vanishes at \\(x=1\\), exactly one unit from the expansion center 0. This is why coefficient singularities matter when we ask where an ODE’s series solution is guaranteed to exist.</p>`},
{type:'quiz',title:'Analytic at a point',q:'Which statement captures “f is analytic at x₀”?',options:['f equals a convergent power series in a neighborhood of x₀','f merely has a first derivative at x₀','f is bounded everywhere'],answer:0,why:'Analyticity is a local power-series representation.'}
]}]},
{id:'l14-points',courseLesson:14,color:'#9a6038',badge:'4',label:'Ordinary vs singular',title:'Where May We Use an Ordinary Power Series?',subtitle:'normalize the ODE · inspect the leading coefficient',desc:'Classify the expansion point before launching the algebra.',lessons:[{title:'Point classification',screens:[
{type:'teach',title:'Ordinary point: the leading coefficient does not vanish',html:`<p>${l14Core}</p><p>Write a second-order linear equation as</p><div class="eq">\\[P(x)y''+Q(x)y'+R(x)y=F(x).\\]</div><p>If \\(P(x_0)\\ne0\\), we can divide by \\(P\\) near \\(x_0\\). If the normalized coefficients \\(Q/P\\), \\(R/P\\), and \\(F/P\\) are analytic there, \\(x_0\\) is an <b>ordinary point</b> for the series method. We expect an ordinary power series with two freely chosen starting coefficients for a homogeneous second-order equation.</p>`},
{type:'teach',title:'Singular point: ordinary Taylor machinery can break',html:`<p>If \\(P(x_0)=0\\), the equation loses its highest-derivative coefficient at the center. Then \\(x_0\\) is a <b>singular point</b>. Dividing by \\(P\\) may create terms such as \\(1/x\\) or \\(1/x^2\\), which are not analytic at the center.</p><p>Do not conclude “no solution.” It means the ordinary power-series template may be too restrictive. Lesson 15 expands the template to \\(x^{n+r}\\) at <b>regular singular points</b>.</p>`},
l14Clone(l14R2),
{type:'quiz',title:'Classify quickly',q:'For (1+x²)yʺ+xyʹ−3y=0, is x₀=0 ordinary or singular?',options:['Ordinary','Singular','Impossible to tell'],answer:0,why:'The leading coefficient is P(0)=1, so it does not vanish.'}
]}]},
{id:'l14-method',courseLesson:14,color:'#3e7287',badge:'5',label:'Power-series method',title:'Substitute, Align Powers, Compare Coefficients',subtitle:'index shifts · exceptional terms · recurrence relations',desc:'Learn the exact algebraic workflow that prevents most series mistakes.',lessons:[{title:'Algorithm',screens:[
{type:'teach',title:'The six-step power-series algorithm',html:`<p>${l14Explain}</p><p><b>1.</b> Classify the center. <b>2.</b> Write \\(y=\\sum a_n(x-x_0)^n\\) and the derivatives. <b>3.</b> Substitute every series into the ODE. <b>4.</b> Reindex until terms use a common power. <b>5.</b> Pull out low-index terms that do not share the same starting index. <b>6.</b> Set each coefficient equal to zero (or to the matching forcing coefficient) and solve the resulting recurrence.</p><p>The most common error occurs in Steps 4–5: changing an index without changing the coefficient, or combining sums before their starting indices match.</p>`},
{type:'teach',title:'Why coefficients may be compared',html:`<p>If a power series vanishes for every \\(x\\) in an interval,</p><div class="eq">\\[c_0+c_1x+c_2x^2+\\cdots=0,\\]</div><p>then every coefficient must vanish: \\(c_n=0\\). One way to see this is to evaluate at 0 to get \\(c_0=0\\), differentiate and evaluate at 0 to get \\(c_1=0\\), and continue. Therefore an ODE identity turns into infinitely many algebraic equations.</p>`},
l14Clone(l14R3),
{type:'quiz',title:'Index shift',q:'How should Σ from n=2 of n(n−1)aₙxⁿ⁻² be rewritten using powers xⁿ?',options:['Σ from n=0 of (n+2)(n+1)aₙ₊₂xⁿ','Σ from n=0 of n(n−1)aₙxⁿ','Σ from n=2 of (n−2)(n−3)aₙ₋₂xⁿ'],answer:0,why:'Set the old index k=n+2, so k(k−1)a_k becomes (n+2)(n+1)a_{n+2}.'}
]}]},
{id:'l14-bookexamples',courseLesson:14,color:'#4f7650',badge:'6',label:'O’Neil examples',title:'O’Neil §2.5.1 Worked Examples',subtitle:'Example 2.18 · Example 2.19',desc:'Use the supplied textbook’s authentic series examples with every index shift exposed.',lessons:[{title:'Examples 2.18–2.19',screens:[l14Clone(l14Ex218),l14Clone(l14Ex219)]}]},
{id:'l14-practice',courseLesson:14,color:'#856b37',badge:'7',label:'Interleaved practice',title:'Series Method Practice',subtitle:'new checks · convergence · classification · recurrence',desc:'Alternate fresh conceptual and algebraic decisions rather than replaying the guided examples.',lessons:[{title:'Practice',screens:[
{type:'quiz',title:'Radius recognition',q:'For Σ[(x−1)/2]ⁿ, what is the radius of convergence?',options:['2','1','∞'],answer:0,why:'It is geometric and converges when |x−1|<2.'},
{type:'quiz',title:'Ordinary-point recognition',q:'For (3−x)yʺ+(1+x)yʹ+y=0, what is x₀=0?',options:['Ordinary','Regular singular','Irregular singular'],answer:0,why:'The leading coefficient equals 3 at zero, so normalization is analytic nearby.'},
{type:'quiz',title:'Lowest-power bookkeeping',q:'After reindexing, one sum starts at n=0 and another at n=2. What should happen before combining them?',options:['Write the n=0 and n=1 terms separately','Pretend the second sum also starts at zero','Delete the first two terms'],answer:0,why:'The unmatched low powers give real coefficient equations and cannot be discarded.'},
{type:'quiz',title:'Order predicts free coefficients',q:'At an ordinary point of a homogeneous second-order ODE, how many starting coefficients should normally remain free?',options:['Two','One','None'],answer:0,why:'They correspond to two initial data values, typically y(x₀) and yʹ(x₀).' },
{type:'quiz',title:'Method selection',q:'If P(x₀)=0 in P yʺ+Q yʹ+R y=0, what should you do before assuming y=Σaₙ(x−x₀)ⁿ works?',options:['Classify the singular point','Divide by y','Use Laplace transform automatically'],answer:0,why:'A singular point may require Frobenius rather than an ordinary Taylor series.'}
]}]},
{id:'l14-mastery',courseLesson:14,color:'#a24458',badge:'8',label:'Mastery',title:'Nov. 4 Mastery — Series Transfer & Diagnostics',subtitle:'6 original problems · recognition, recurrence, indices, initial data',desc:'A non-repetitive mastery set that transfers the lesson’s ideas to new equations instead of replaying the examples and guided practice already completed.',lessons:[{title:'Convergence & classification',screens:l14TransferMastery.slice(0,2)},{title:'Recurrence transfer',screens:l14TransferMastery.slice(2,4)},{title:'Index & initial-data diagnostics',screens:l14TransferMastery.slice(4,6)}]}
];

// Authentic numbered O’Neil practice: keep a small varied set instead of a repetitive bank.
const l14P1=l14Board('O’Neil §2.5.1 Problem 1 — first-order power series',`<p>${l14Book}</p><p>Find a power-series solution about \\(x=0\\) for</p><div class="eq">\\[y'-xy=1-x.\\]</div><p>Derive the recurrence and generate the first coefficients.</p>`,`<p>Write</p><div class="eq">\\[y=\\sum_{n=0}^\\infty a_nx^n,\\qquad y'=\\sum_{n=0}^\\infty(n+1)a_{n+1}x^n,\\qquad xy=\\sum_{n=1}^\\infty a_{n-1}x^n.\\]</div><p>Matching the constant and linear terms gives</p><div class="eq">\\[a_1=1,\\qquad 2a_2-a_0=-1.\\]</div><p>Hence \\(a_2=(a_0-1)/2\\). For \\(n\\ge2\\),</p><div class="eq">\\[(n+1)a_{n+1}-a_{n-1}=0,\\]</div><div class="whybox"><div class="eq">\\[\\boxed{a_m=\\frac{a_{m-2}}{m}},\\qquad m\\ge3.\\]</div></div><p>Thus</p><div class="eq">\\[y=a_0+x+\\frac{a_0-1}{2}x^2+\\frac13x^3+\\frac{a_0-1}{8}x^4+\\frac1{15}x^5+\\cdots.\\]</div><p>Only \\(a_0\\) is free, as expected for a first-order ODE.</p>`,'§2.5.1 · Problem 1');
const l14P5=l14Board('O’Neil §2.5.1 Problem 5 — second-order recurrence',`<p>${l14Book}</p><p>Find a power-series solution about \\(x=0\\) for</p><div class="eq">\\[y''-xy'+y=3.\\]</div>`,`<p>Using \\(y=\\sum a_nx^n\\), the constant term gives</p><div class="eq">\\[2a_2+a_0=3\\quad\\Rightarrow\\quad a_2=\\frac{3-a_0}{2}.\\]</div><p>For \\(n\\ge1\\),</p><div class="eq">\\[(n+2)(n+1)a_{n+2}+(1-n)a_n=0,\\]</div><div class="whybox"><div class="eq">\\[\\boxed{a_{n+2}=\\frac{n-1}{(n+1)(n+2)}a_n}.\\]</div></div><p>In particular, \\(a_3=0\\), \\(a_4=(3-a_0)/24\\), and \\(a_6=(3-a_0)/240\\). Therefore</p><div class="eq">\\[\\boxed{y=a_0+a_1x+(3-a_0)\\left(\\frac{x^2}{2}+\\frac{x^4}{24}+\\frac{x^6}{240}+\\cdots\\right)}.\\]</div><p>The two free coefficients \\(a_0,a_1\\) match the second-order nature of the equation.</p>`,'§2.5.1 · Problem 5');
const l14P7=l14Board('O’Neil §2.5.1 Problem 7 — mixed-index recurrence',`<p>${l14Book}</p><p>Find the recurrence for a power-series solution about zero of</p><div class="eq">\\[y''-x^2y'+2y=x.\\]</div><p>Pay special attention to the low-index equations.</p>`,`<p>Substitution gives</p><div class="eq">\\[\\sum_{n=0}^\\infty(n+2)(n+1)a_{n+2}x^n-\\sum_{n=2}^\\infty(n-1)a_{n-1}x^n+2\\sum_{n=0}^\\infty a_nx^n=x.\\]</div><p>The unmatched powers are</p><div class="eq">\\[2a_2+2a_0=0,\\qquad 6a_3+2a_1=1.\\]</div><p>So \\(a_2=-a_0\\) and \\(a_3=(1-2a_1)/6\\). For \\(n\\ge4\\),</p><div class="whybox"><div class="eq">\\[\\boxed{a_n=\\frac{(n-3)a_{n-3}-2a_{n-2}}{n(n-1)}}.\\]</div></div><p>The next coefficients are</p><div class="eq">\\[a_4=\\frac{a_1+2a_0}{12},\\quad a_5=\\frac{-6a_0-1+2a_1}{60},\\quad a_6=\\frac{3-7a_1-2a_0}{180}.\\]</div><p>This problem is useful precisely because the recurrence couples different index strides and punishes careless reindexing.</p>`,'§2.5.1 · Problem 7');
const l14MethodBook=lesson14Units.find(u=>u&&u.id==='l14-method');
if(l14MethodBook)l14MethodBook.lessons.push({title:'Numbered O’Neil practice · §2.5.1',screens:[l14P1,l14P5,l14P7].map(l14Clone)});

if(!units.some(u=>u&&u.id==='l14-map'))units.push(...lesson14Units);
if(courseLessons[12])courseLessons[12].status='complete';
courseLessons[13]={number:14,title:'Power Series Foundations',subtitle:'Nov. 4 · syllabus series-solutions block · supplied O’Neil §2.5.1 · recurrence relations',status:'current'};
if(typeof renderCourseMap==='function')renderCourseMap();
if(typeof render==='function')render();