/* Lesson 18 — Nov. 23: orthogonalization, projections, matrices, matrix algebra, random walks. */
const l18Core='<span class="supplementalTag">Core · Nov. 23 syllabus · Part 5</span>';
const l18Book='<span class="supplementalTag">Authentic textbook · supplied O’Neil §§10.5–10.6, 11.1</span>';
const l18Explain='<span class="supplementalTag">Expanded explanation · Lesson 1 depth standard</span>';
const l18Recon='<span class="supplementalTag">Syllabus-aligned reconstruction · not claimed as an O’Neil example</span>';
function l18Board(title,prompt,solution,section){return {type:'bookproblem',bookSection:section,title,prompt,solution};}
function l18Clone(s){return s?{...s,inlineBookPractice:true}:null;}
const l18GS=l18Board('Gram–Schmidt — remove the overlap',`<p>${l18Recon}</p><p>Starting from</p><div class="eq">\\[X_1=(1,1,0),\\qquad X_2=(1,0,1),\\]</div><p>construct an orthogonal basis for their span. Explain every subtraction.</p>`,`<p>Keep the first direction:</p><div class="eq">\\[V_1=X_1=(1,1,0).\\]</div><p>The part of \\(X_2\\) pointing along \\(V_1\\) is its projection:</p><div class="eq">\\[\\operatorname{proj}_{V_1}X_2=\\frac{X_2\\cdot V_1}{V_1\\cdot V_1}V_1=\\frac{1}{2}(1,1,0).\\]</div><p>Subtract that overlap:</p><div class="eq">\\[V_2=X_2-\\operatorname{proj}_{V_1}X_2=(1/2,-1/2,1).\\]</div><p>Scaling does not change direction, so use \\(V_2=(1,-1,2)\\). Check:</p><div class="eq">\\[V_1\\cdot V_2=1-1+0=0.\\]</div><div class="whybox"><p>Thus \\(\\boxed{(1,1,0),(1,-1,2)}\\) is an orthogonal basis for the same span. Gram–Schmidt preserves the space while removing directional overlap.</p></div>`,'§10.5 Gram–Schmidt practice');
const l18P4=l18Board('O’Neil §10.5 Problem 4 — Gram–Schmidt',`<p>${l18Book}</p><p>Use Gram–Schmidt on</p><div class="eq">\\[X_1=(1,4,0),\\qquad X_2=(2,-5,0).\\]</div>`,`<p>Take \\(V_1=X_1\\). Then</p><div class="eq">\\[X_2\\cdot V_1=2-20=-18,\\qquad V_1\\cdot V_1=17.\\]</div><p>Hence</p><div class="eq">\\[V_2=X_2-\\frac{-18}{17}V_1=(2,-5,0)+\\frac{18}{17}(1,4,0).\\]</div><p>Multiplying by 17 gives the cleaner parallel vector</p><div class="eq">\\[(52,-13,0)=13(4,-1,0).\\]</div><p>So we may choose</p><div class="eq">\\[\\boxed{V_1=(1,4,0),\\quad V_2=(4,-1,0)}.\\]</div><p>Check: \\(1(4)+4(-1)=0\\).</p>`,'§10.5 · Problem 4');
const l18Proj=l18Board('Orthogonal projection onto a subspace',`<p>${l18Recon}</p><p>Let \\(S\\subset\\mathbb R^3\\) have orthogonal basis \\(v_1=(1,1,0)\\), \\(v_2=(1,-1,0)\\). Decompose \\(u=(3,1,4)\\) as \\(u=u_S+u_\\perp\\).</p>`,`<p>Project onto each orthogonal basis direction:</p><div class="eq">\\[u_S=\\frac{u\\cdot v_1}{v_1\\cdot v_1}v_1+\\frac{u\\cdot v_2}{v_2\\cdot v_2}v_2.\\]</div><p>Here \\(u\\cdot v_1=4\\), \\(u\\cdot v_2=2\\), and both squared lengths are 2:</p><div class="eq">\\[u_S=2(1,1,0)+1(1,-1,0)=(3,1,0).\\]</div><p>Therefore</p><div class="eq">\\[u_\\perp=u-u_S=(0,0,4).\\]</div><p>Check: \\(u_\\perp\\cdot v_1=u_\\perp\\cdot v_2=0\\).</p><div class="whybox"><p>\\(u_S\\) is the closest vector in \\(S\\) to \\(u\\); the error vector is perpendicular to the entire subspace.</p></div>`,'§10.6 projection practice');
const l18MatMul=l18Board('O’Neil Example 11.3 — matrix multiplication',`<p>${l18Book}</p><p>For</p><div class="eq">\\[A=\\begin{pmatrix}1&3\\\\2&5\\end{pmatrix},\\qquad B=\\begin{pmatrix}1&1&3\\\\2&1&4\\end{pmatrix},\\]</div><p>compute \\(AB\\) and explain why its dimensions are \\(2\\times3\\).</p>`,`<p>The inner dimensions match: \\(A\\) is \\(2\\times2\\), \\(B\\) is \\(2\\times3\\), so the product exists and has the outside dimensions \\(2\\times3\\).</p><p>Each entry is a row–column dot product:</p><div class="eq">\\[AB=\\begin{pmatrix}1(1)+3(2)&1(1)+3(1)&1(3)+3(4)\\\\2(1)+5(2)&2(1)+5(1)&2(3)+5(4)\\end{pmatrix}.\\]</div><div class="eq">\\[\\boxed{AB=\\begin{pmatrix}7&4&15\\\\12&7&26\\end{pmatrix}}.\\]</div><p>Matrix multiplication is composition-like, not element-by-element multiplication.</p>`,'§11.1 · Example 11.3');
const l18NonComm=l18Board('Matrix order matters',`<p>${l18Recon}</p><p>Let \\(A=\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}\\), \\(B=\\begin{pmatrix}1&0\\\\1&1\\end{pmatrix}\\). Compute both \\(AB\\) and \\(BA\\).</p>`,`<div class="eq">\\[AB=\\begin{pmatrix}2&1\\\\1&1\\end{pmatrix},\\qquad BA=\\begin{pmatrix}1&1\\\\1&2\\end{pmatrix}.\\]</div><div class="whybox"><p>\\[\\boxed{AB\\ne BA}.\\]</p><p>Unlike ordinary numbers, matrix multiplication is generally not commutative. Never reverse factors unless you have proved it is allowed.</p></div>`,'§11.1 matrix algebra practice');
const l18Walk=l18Board('Random walks — why powers of an adjacency matrix count paths',`<p>${l18Recon}</p><p>For the three-site chain \\(v_1-v_2-v_3\\), use its adjacency matrix to count length-2 walks from \\(v_1\\) to \\(v_3\\).</p>`,`<p>The adjacency matrix is</p><div class="eq">\\[A=\\begin{pmatrix}0&1&0\\\\1&0&1\\\\0&1&0\\end{pmatrix}.\\]</div><p>Square it:</p><div class="eq">\\[A^2=\\begin{pmatrix}1&0&1\\\\0&2&0\\\\1&0&1\\end{pmatrix}.\\]</div><p>The \\((1,3)\\) entry is 1, so there is exactly one length-2 walk from \\(v_1\\) to \\(v_3\\):</p><div class="eq">\\[v_1\\to v_2\\to v_3.\\]</div><p>Why does multiplication count? The \\((i,j)\\) entry of \\(A^2\\) sums over every possible intermediate site \\(r\\): \\(a_{ir}a_{rj}\\). Each product contributes 1 exactly when both required edges exist.</p>`,'§11.1.3 random-walk application');
const lesson18Units=[
{id:'l18-map',courseLesson:18,color:'#476a91',badge:'1',label:'Nov. 23 map',title:'Orthogonality to Matrices',subtitle:'clean bases · projections · matrix language',desc:'Turn geometric decomposition into the matrix machinery used next.',lessons:[{title:'Map',screens:[{type:'teach',title:'Textbook numbering reconciliation',html:`<p>${l18Core}</p><p>The syllabus lists O’Neil §§5.5–5.6 and §6.1. In the supplied 8th SI edition these topics are actually <b>§§10.5–10.6 and §11.1</b>. We follow the syllabus topics and the supplied book’s real numbering.</p>`},{type:'teach',title:'Today’s bridge',html:`<p>${l18Explain}</p><p>Lesson 17 gave us bases and dot products. Today we make bases easier to use by making them <b>orthogonal</b>, use those bases for <b>projections</b>, then package many vectors/numbers into <b>matrices</b>. The connection is important: a matrix is not a disconnected new topic—its rows and columns are vectors, and matrix multiplication is built from dot products.</p>`}]}]},
{id:'l18-orth',courseLesson:18,color:'#34776e',badge:'2',label:'Orthogonal sets',title:'Orthogonal Sets and Coordinates',subtitle:'perpendicular vectors automatically independent',desc:'See why orthogonality makes coordinates easy.',lessons:[{title:'Orthogonality',screens:[{type:'teach',title:'Why orthogonal bases are special',html:`<p>${l18Book}</p><p>Nonzero mutually orthogonal vectors are automatically linearly independent. If \\(V_1,\\dots,V_m\\) is an orthogonal basis and \\(F=\\sum c_jV_j\\), dotting with \\(V_k\\) kills every term except one:</p><div class="eq">\\[F\\cdot V_k=c_k\\|V_k\\|^2,\\qquad \\boxed{c_k=\\frac{F\\cdot V_k}{\\|V_k\\|^2}}.\\]</div><p>For an orthonormal basis, \\(\\|V_k\\|=1\\), so simply \\(c_k=F\\cdot V_k\\).</p>`},{type:'quiz',title:'Orthogonal set',q:'A finite set of nonzero mutually orthogonal vectors must be…',options:['linearly independent','linearly dependent','all unit vectors'],answer:0,why:'Dotting a zero linear combination with each vector forces every coefficient to zero.'}]}]},
{id:'l18-gs',courseLesson:18,color:'#795d9a',badge:'3',label:'Gram–Schmidt',title:'Gram–Schmidt = Subtract Projections',subtitle:'same span · no overlap',desc:'Build an orthogonal basis one vector at a time.',lessons:[{title:'Gram–Schmidt',screens:[{type:'teach',title:'The idea before the formula',html:`<p>${l18Explain}</p><p>Suppose \\(X_1,X_2\\) are independent but not perpendicular. Keep \\(V_1=X_1\\). To make a second direction perpendicular, take \\(X_2\\) and remove exactly the part pointing along \\(V_1\\):</p><div class="eq">\\[V_2=X_2-\\operatorname{proj}_{V_1}X_2.\\]</div><p>For a third vector, remove its projections onto both earlier orthogonal directions. This is all Gram–Schmidt is doing.</p>`},l18Clone(l18GS),l18Clone(l18P4)]}]},
{id:'l18-proj',courseLesson:18,color:'#9a6038',badge:'4',label:'Projection',title:'Orthogonal Complements and Projections',subtitle:'u = closest part + perpendicular error',desc:'Decompose any vector relative to a subspace.',lessons:[{title:'Projection',screens:[{type:'teach',title:'S and S⊥',html:`<p>${l18Book}</p><p>For a subspace \\(S\\), its orthogonal complement \\(S^\\perp\\) contains every vector perpendicular to every vector in \\(S\\). Every \\(u\\in\\mathbb R^n\\) splits uniquely as</p><div class="eq">\\[\\boxed{u=u_S+u_\\perp},\\qquad u_S\\in S,\\quad u_\\perp\\in S^\\perp.\\]</div><p>The component \\(u_S\\) is the orthogonal projection onto \\(S\\), and it is the closest vector in \\(S\\) to \\(u\\).</p>`},l18Clone(l18Proj),{type:'quiz',title:'Projection error',q:'After projecting u onto S, where does u−u_S lie?',options:['S⊥','S','nowhere in Rⁿ'],answer:0,why:'The projection removes all components along S, leaving a vector orthogonal to S.'}]}]},
{id:'l18-matrix',courseLesson:18,color:'#3e7287',badge:'5',label:'Matrices',title:'Matrices and Matrix Algebra',subtitle:'dimensions · rows · columns · special matrices',desc:'Learn the data structure before operating on it.',lessons:[{title:'Matrices',screens:[{type:'teach',title:'What an n×m matrix means',html:`<p>${l18Book}</p><p>An \\(n\\times m\\) matrix has \\(n\\) rows and \\(m\\) columns. Row \\(i\\) behaves like a vector in \\(\\mathbb R^m\\); column \\(j\\) behaves like a vector in \\(\\mathbb R^n\\). Important special matrices include the zero matrix, identity \\(I_n\\), and transpose \\(A^T\\), which swaps rows and columns.</p><p>Addition requires equal dimensions. Scalar multiplication acts entrywise.</p>`},{type:'quiz',title:'Dimensions',q:'A matrix with 3 rows and 5 columns is…',options:['3×5','5×3','8×1'],answer:0,why:'Rows are named first, columns second.'}]}]},
{id:'l18-multiply',courseLesson:18,color:'#536b48',badge:'6',label:'Multiplication',title:'Matrix Multiplication Is Row × Column',subtitle:'inner dimensions match · order matters',desc:'Understand the operation that powers the rest of linear algebra.',lessons:[{title:'Multiplication',screens:[{type:'teach',title:'Why the dimension rule exists',html:`<p>${l18Explain}</p><p>If \\(A\\) is \\(n\\times k\\) and \\(B\\) is \\(k\\times m\\), a row of \\(A\\) and a column of \\(B\\) each contain \\(k\\) entries, so their dot product is defined. Those dot products fill an \\(n\\times m\\) result:</p><div class="eq">\\[(AB)_{ij}=\\sum_{s=1}^{k}a_{is}b_{sj}.\\]</div>`},l18Clone(l18MatMul),l18Clone(l18NonComm),{type:'quiz',title:'Product size',q:'If A is 4×2 and B is 2×7, AB is…',options:['4×7','2×2','7×4'],answer:0,why:'The inner 2s match; keep the outside dimensions 4 and 7.'}]}]},
{id:'l18-walk',courseLesson:18,color:'#856b37',badge:'7',label:'Random walks',title:'Application — Random Walks in Crystals',subtitle:'adjacency matrices · powers count walks',desc:'See matrix multiplication encode repeated physical moves.',lessons:[{title:'Random walks',screens:[{type:'teach',title:'From a crystal lattice to a matrix',html:`<p>${l18Book}</p><p>Represent lattice sites by graph vertices. Put \\(a_{ij}=1\\) when sites \\(v_i,v_j\\) are adjacent and 0 otherwise. O’Neil shows that the \\((i,j)\\) entry of \\(A^k\\) counts length-\\(k\\) walks from \\(v_i\\) to \\(v_j\\). Repeated matrix multiplication therefore encodes repeated allowed jumps.</p>`},l18Clone(l18Walk)]}]},
{id:'l18-mastery',courseLesson:18,color:'#a24458',badge:'8',label:'Mastery',title:'Nov. 23 Mastery',subtitle:'orthogonalize · project · multiply · interpret',desc:'Work the entire chain with full scratch boards.',lessons:[{title:'Orthogonalization',screens:[l18GS,l18P4,l18Proj]},{title:'Matrices',screens:[l18MatMul,l18NonComm,l18Walk]}]}
];
if(!units.some(u=>u&&u.id==='l18-map'))units.push(...lesson18Units);
if(courseLessons[16])courseLessons[16].status='complete';
courseLessons[17]={number:18,title:'Orthogonalization, Projections & Matrices',subtitle:'Nov. 23 · supplied O’Neil §§10.5–10.6, 11.1',status:'current'};
// Reconstruction pass: mastery now tests transfer rather than repeating the guided boards.
const l18Transfer=[
l18Board('Transfer 1 — Gram–Schmidt preserves span',`<p>${l18Recon}</p><p>Start with \\(x_1=(1,1,1)\\), \\(x_2=(1,0,0)\\). Construct an orthogonal basis for the same span and verify orthogonality.</p>`,`<p>Take \\(v_1=x_1\\). The projection coefficient is</p><div class="eq">\\[\\frac{x_2\\cdot v_1}{v_1\\cdot v_1}=\\frac13.\\]</div><p>Hence</p><div class="eq">\\[v_2=x_2-\\frac13v_1=\\left(\\frac23,-\\frac13,-\\frac13\\right).\\]</div><p>Scale by 3 to use \\(v_2=(2,-1,-1)\\). Then</p><div class="eq">\\[(1,1,1)\\cdot(2,-1,-1)=0.\\]</div><div class="whybox"><p>Subtracting a multiple of \\(x_1\\) from \\(x_2\\) does not change the span, so \\(\\{(1,1,1),(2,-1,-1)\\}\\) is an orthogonal basis of the original subspace.</p></div>`,'Original transfer · Gram–Schmidt'),
l18Board('Transfer 2 — projection onto a plane subspace',`<p>${l18Recon}</p><p>Let \\(S=\\operatorname{span}\\{(1,0,0),(0,1,0)\\}\\). Decompose \\(u=(2,-3,5)\\) into \\(u_S+u_\\perp\\).</p>`,`<p>The given basis is orthonormal, so the projection coefficients are simply dot products:</p><div class="eq">\\[u_S=2(1,0,0)-3(0,1,0)=(2,-3,0).\\]</div><p>Therefore</p><div class="eq">\\[u_\\perp=u-u_S=(0,0,5).\\]</div><p>The error is perpendicular to both basis vectors, so it lies in \\(S^\\perp\\).</p>`,'Original transfer · orthogonal projection'),
l18Board('Transfer 3 — matrix-dimension diagnosis',`<p>${l18Recon}</p><p>If \\(A\\) is \\(3\\times4\\) and \\(B\\) is \\(4\\times2\\), which products exist and what are their sizes?</p>`,`<p>For \\(AB\\), the inner dimensions 4 and 4 match, so</p><div class="eq">\\[\\boxed{AB\\text{ exists and is }3\\times2}.\\]</div><p>For \\(BA\\), the inner dimensions would be 2 and 3, which do not match. Thus \\(BA\\) is undefined.</p><div class="whybox"><p>This is stronger than saying matrix multiplication is noncommutative: sometimes reversing the order is not even dimensionally legal.</p></div>`,'Original diagnostic · matrix multiplication'),
l18Board('Transfer 4 — row-by-column computation',`<p>${l18Recon}</p><p>Compute \\(AB\\) for \\(A=\\begin{pmatrix}1&-1&2\\\\0&3&1\\end{pmatrix}\\), \\(B=\\begin{pmatrix}2&1\\\\1&0\\\\-1&4\\end{pmatrix}\\).</p>`,`<p>Each entry is a row–column dot product:</p><div class="eq">\\[AB=\\begin{pmatrix}1(2)+(-1)(1)+2(-1)&1(1)+(-1)(0)+2(4)\\\\0(2)+3(1)+1(-1)&0(1)+3(0)+1(4)\\end{pmatrix}.\\]</div><div class="eq">\\[\\boxed{AB=\\begin{pmatrix}-1&9\\\\2&4\\end{pmatrix}}.\\]</div>`,'Original transfer · matrix multiplication'),
l18Board('Transfer 5 — orthogonal-coordinate shortcut',`<p>${l18Recon}</p><p>Let \\(v_1=(1,1,0)\\), \\(v_2=(1,-1,0)\\) be an orthogonal basis of \\(S\\). Find the coordinates of \\(f=(5,1,0)\\) in this basis.</p>`,`<p>For an orthogonal basis,</p><div class="eq">\\[c_k=\\frac{f\\cdot v_k}{v_k\\cdot v_k}.\\]</div><p>Thus \\(c_1=6/2=3\\) and \\(c_2=4/2=2\\). Therefore</p><div class="eq">\\[\\boxed{f=3v_1+2v_2}.\\]</div><p>Check: \\(3(1,1,0)+2(1,-1,0)=(5,1,0)\\).</p>`,'Original transfer · orthogonal coordinates'),
l18Board('Transfer 6 — adjacency powers as walk counts',`<p>${l18Recon}</p><p>For \\(A=\\begin{pmatrix}0&1\\\\1&1\\end{pmatrix}\\), compute \\(A^2\\) and interpret its \\((1,2)\\) entry as a length-2 walk count.</p>`,`<div class="eq">\\[A^2=\\begin{pmatrix}1&1\\\\1&2\\end{pmatrix}.\\]</div><p>The \\((1,2)\\) entry is 1. In the graph encoded by \\(A\\), there is exactly one two-step walk from vertex 1 to vertex 2. The matrix product sums over all possible intermediate vertices, which is why powers count walks.</p>`,'Original mastery · random-walk interpretation')
];
const l18MasteryUnit=units.find(u=>u&&u.id==='l18-mastery');
if(l18MasteryUnit){l18MasteryUnit.title='Nov. 23 Transfer Mastery';l18MasteryUnit.subtitle='6 unseen problems · orthogonality, matrices, interpretation';l18MasteryUnit.desc='Tests why the methods work and whether they transfer beyond the guided examples.';l18MasteryUnit.lessons=[{title:'Orthogonal transfer',screens:l18Transfer.slice(0,2)},{title:'Matrix transfer',screens:l18Transfer.slice(2,5)},{title:'Application transfer',screens:l18Transfer.slice(5,6)}];}

const l18P5=l18Board('O’Neil §10.5 Problem 5 — a second Gram–Schmidt problem',`<p>${l18Book}</p><p>Use Gram–Schmidt to produce an orthogonal basis spanning the same subspace as</p><div class="eq">\\[X_1=(0,-1,2,0),\\qquad X_2=(0,3,-4,0).\\]</div>`,`<p>Set \\(V_1=X_1\\). Then</p><div class="eq">\\[X_2\\cdot V_1=-11,\\qquad V_1\\cdot V_1=5.\\]</div><p>Remove the projection of \\(X_2\\) onto \\(V_1\\):</p><div class="eq">\\[V_2=X_2-\\frac{-11}{5}V_1=(0,4/5,2/5,0).\\]</div><p>Scale the second direction to avoid fractions:</p><div class="eq">\\[\\boxed{V_1=(0,-1,2,0),\\qquad V_2=(0,2,1,0)}.\\]</div><p>Check: \\(V_1\\cdot V_2=-2+2=0\\).</p>`,'§10.5 · Problem 5');
const l18P1061=l18Board('O’Neil §10.6 Problem 1 — projection and distance to a subspace',`<p>${l18Book}</p><p>Let</p><div class="eq">\\[u=(-2,6,1,7)\\]</div><p>and let \\(S\\) have orthogonal basis</p><div class="eq">\\[v_1=(1,-1,0,0),\\qquad v_2=(1,1,0,0).\\]</div><p>Write \\(u=u_S+u_\\perp\\) and find the distance from \\(u\\) to \\(S\\).</p>`,`<p>Because the basis is orthogonal, project separately:</p><div class="eq">\\[u\\cdot v_1=-8,\\quad u\\cdot v_2=4,\\quad \\|v_1\\|^2=\\|v_2\\|^2=2.\\]</div><p>Thus</p><div class="eq">\\[u_S=-4v_1+2v_2=(-2,6,0,0).\\]</div><p>The perpendicular remainder is</p><div class="eq">\\[u_\\perp=u-u_S=(0,0,1,7).\\]</div><p>Therefore</p><div class="eq">\\[\\boxed{\\operatorname{dist}(u,S)=\\|u_\\perp\\|=\\sqrt{50}=5\\sqrt2}.\\]</div><p>The remainder has zero dot product with both basis vectors, verifying it lies in \\(S^\\perp\\).</p>`,'§10.6 · Problem 1');
const l18GsUnit=units.find(u=>u&&u.id==='l18-gs');
if(l18GsUnit&&!l18GsUnit.lessons[0].screens.some(s=>s.title===l18P5.title))l18GsUnit.lessons[0].screens.push(l18Clone(l18P5));
const l18ProjUnit=units.find(u=>u&&u.id==='l18-proj');
if(l18ProjUnit&&!l18ProjUnit.lessons[0].screens.some(s=>s.title===l18P1061.title))l18ProjUnit.lessons[0].screens.push(l18Clone(l18P1061));

if(typeof renderCourseMap==='function')renderCourseMap();if(typeof render==='function')render();