/* Lesson 15 — Nov. 9: Airy/power-series examples, MSE context, Frobenius, indicial roots. */
const l15Core='<span class="supplementalTag">Core · Nov. 9 syllabus</span>';
const l15Book='<span class="supplementalTag">Authentic textbook · O’Neil §2.5.2 in supplied 8th SI edition</span>';
const l15Explain='<span class="supplementalTag">Expanded explanation · Lesson 1 depth standard</span>';
const l15Recon='<span class="supplementalTag">Syllabus-aligned reconstruction · not claimed as an O’Neil example</span>';
function l15Board(title,prompt,solution,section){return {type:'bookproblem',bookSection:section,title,prompt,solution};}
function l15Clone(s){return s?{...s,inlineBookPractice:true}:null;}
const l15Airy=l15Board('Airy equation — power series about an ordinary point',
`<p>${l15Recon}</p><p>The syllabus explicitly calls for the Airy equation. Solve by a power series about \\(x=0\\):</p><div class="eq">\\[y''-xy=0.\\]</div><p>Derive the recurrence rather than quoting Airy functions.</p>`,
`<p><b>1 · Why an ordinary series is allowed.</b> The coefficient of \\(y''\\) is 1, so \\(x=0\\) is ordinary.</p><div class="eq">\\[y=\\sum_{n=0}^\\infty a_nx^n,\\qquad y''=\\sum_{n=0}^\\infty(n+2)(n+1)a_{n+2}x^n.\\]</div><p>Also</p><div class="eq">\\[xy=\\sum_{n=0}^\\infty a_nx^{n+1}=\\sum_{n=1}^\\infty a_{n-1}x^n.\\]</div><p>Substitution gives</p><div class="eq">\\[\\sum_{n=0}^\\infty(n+2)(n+1)a_{n+2}x^n-\\sum_{n=1}^\\infty a_{n-1}x^n=0.\\]</div><p>The \\(n=0\\) equation is \\(2a_2=0\\), so \\(a_2=0\\). For \\(n\\ge1\\),</p><div class="whybox"><div class="eq">\\[\\boxed{a_{n+2}=\\frac{a_{n-1}}{(n+2)(n+1)}}.\\]</div></div><p>This recurrence advances by three indices. Therefore the \\(a_0\\) and \\(a_1\\) branches survive while the \\(a_2\\) branch remains zero:</p><div class="eq">\\[a_3=\\frac{a_0}{6},\\ a_4=\\frac{a_1}{12},\\ a_6=\\frac{a_0}{180},\\ a_7=\\frac{a_1}{504}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y=a_0\\left(1+\\frac{x^3}{6}+\\frac{x^6}{180}+\\cdots\\right)+a_1\\left(x+\\frac{x^4}{12}+\\frac{x^7}{504}+\\cdots\\right)}.\\]</div></div><p>These two series are proportional to two standard Airy-function combinations, but the course skill here is obtaining them directly from the ODE.</p>`,'Syllabus Airy example');
const l15MSE=l15Board('MSE context — a linearly graded coefficient produces Airy structure',
`<p>${l15Recon}</p><p>Consider an idealized one-dimensional field \\(u(x)\\) in a graded material obeying</p><div class="eq">\\[u''-\\alpha x\\,u=0,\\qquad \\alpha>0.\\]</div><p>Show how to scale it to the Airy equation and identify the characteristic length.</p>`,
`<p>This is a representative syllabus-aligned materials model, not an instructor-supplied or O’Neil example. The term \\(\\alpha x\\) represents a coefficient varying linearly with position.</p><p>Let \\(x=\\ell\\xi\\). Then</p><div class="eq">\\[\\frac{d^2u}{dx^2}=\\frac1{\\ell^2}\\frac{d^2u}{d\\xi^2}.\\]</div><p>Substitute:</p><div class="eq">\\[\\frac1{\\ell^2}u_{\\xi\\xi}-\\alpha\\ell\\xi u=0.\\]</div><p>Multiply by \\(\\ell^2\\):</p><div class="eq">\\[u_{\\xi\\xi}-\\alpha\\ell^3\\xi u=0.\\]</div><p>Choose \\(\\alpha\\ell^3=1\\), so</p><div class="whybox"><div class="eq">\\[\\boxed{\\ell=\\alpha^{-1/3}},\\qquad \\boxed{u_{\\xi\\xi}-\\xi u=0}.\\]</div></div><p>The cube-root length is dictated by dimensional balance: a second derivative contributes length\\(^{-2}\\), while \\(\\alpha x\\) must carry the same dimension. The Airy form therefore naturally appears when a coefficient changes approximately linearly through a region.</p>`,'Syllabus MSE context');
const l15Ex220=l15Board('O’Neil Example 2.20 — derive the indicial equation and recurrence',
`<p>${l15Book}</p><p>At \\(x=0\\), analyze</p><div class="eq">\\[x^2y''+5xy'+(x+4)y=0.\\]</div><p>Use a Frobenius series and obtain the first solution.</p>`,
`<p><b>1 · Classify zero.</b> Here \\(P=x^2,Q=5x,R=x+4\\). Since \\(P(0)=0\\), zero is singular. But</p><div class="eq">\\[x\\frac{Q}{P}=5,\\qquad x^2\\frac{R}{P}=x+4,\\]</div><p>are analytic at zero, so it is <b>regular singular</b>.</p><p><b>2 · Enlarge the series template.</b></p><div class="eq">\\[y=\\sum_{n=0}^{\\infty}c_nx^{n+r},\\qquad c_0\\ne0.\\]</div><p>Then</p><div class="eq">\\[y'=\\sum(n+r)c_nx^{n+r-1},\\quad y''=\\sum(n+r)(n+r-1)c_nx^{n+r-2}.\\]</div><p>After substitution and shifting the lone \\(x y\\) contribution,</p><div class="eq">\\[[r(r-1)+5r+4]c_0x^r+\\sum_{n=1}^{\\infty}[(n+r)(n+r-1)+5(n+r)+4]c_nx^{n+r}+\\sum_{n=1}^{\\infty}c_{n-1}x^{n+r}=0.\\]</div><p>The lowest power gives the <b>indicial equation</b></p><div class="eq">\\[r(r-1)+5r+4=0\\iff (r+2)^2=0.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{r=-2\\text{ (repeated)}}.\\]</div></div><p>For \\(n\\ge1\\), substituting \\(r=-2\\) simplifies the coefficient to \\(n^2\\), so</p><div class="eq">\\[n^2c_n+c_{n-1}=0\\Rightarrow \\boxed{c_n=-\\frac{c_{n-1}}{n^2}}.\\]</div><p>Therefore \\(c_n=(-1)^nc_0/(n!)^2\\), and one Frobenius solution is</p><div class="whybox"><div class="eq">\\[\\boxed{y_1=c_0\\sum_{n=0}^{\\infty}\\frac{(-1)^n}{(n!)^2}x^{n-2}}.\\]</div></div><p>Because the root is repeated, one series is not the entire second-order solution space. The theorem predicts a logarithmic structure for a second independent solution.</p>`,'§2.5.2 · Example 2.20');
const l15Ex221=l15Board('O’Neil Example 2.21 — Case 1: roots not separated by a positive integer',
`<p>${l15Book}</p><p>For</p><div class="eq">\\[x^2y''+x\\left(\\frac12+2x\\right)y'+\\left(x-\\frac12\\right)y=0,\\]</div><p>the indicial roots are \\(r_1=1\\) and \\(r_2=-\\tfrac12\\). Explain which Frobenius case applies and state the two independent series forms obtained in the textbook.</p>`,
`<p>The root difference is</p><div class="eq">\\[r_1-r_2=1-(-1/2)=3/2,\\]</div><p>which is <b>not</b> a positive integer. This is Case 1: two independent Frobenius series can be generated directly, one from each root.</p><p>For \\(r=1\\), O’Neil’s recurrence produces</p><div class="eq">\\[y_1=c_0\\left(x-\\frac65x^2+\\frac67x^3-\\frac49x^4+\\cdots\\right).\\]</div><p>For \\(r=-1/2\\), the recurrence makes all coefficients after \\(c_0^*\\) vanish in this example, leaving</p><div class="eq">\\[y_2=c_0^*x^{-1/2},\\qquad x>0.\\]</div><div class="whybox"><p><b>Case 1 pattern:</b> no logarithmic correction is required when the indicial roots do not differ by a positive integer.</p></div>`,'§2.5.2 · Example 2.21');
const l15Ex222=l15Board('O’Neil Example 2.22 — repeated root: construct the logarithmic second solution',
`<p>${l15Book}</p><p>Continue Example 2.20 for</p><div class="eq">\\[x^2y''+5xy'+(x+4)y=0,\\]</div><p>whose repeated indicial root is \\(r=-2\\) and whose first solution is \\(y_1=\\sum_{n=0}^{\\infty}(-1)^n x^{n-2}/(n!)^2\\) up to an arbitrary nonzero scale.</p>`,
`<p><b>1 · Why a new template is needed.</b> A repeated indicial root gives only one direct Frobenius series. O’Neil’s Case 2 therefore prescribes</p><div class="eq">\\[y_2=y_1\\ln x+\\sum_{n=1}^{\\infty}c_n^*x^{n-2},\\qquad x>0.\\]</div><p><b>2 · Substitute the whole template.</b> The terms multiplied by \\(\\ln x\\) cancel because \\(y_1\\) already solves the differential equation. Matching the remaining powers first gives \\(c_1^*=2\\), and for \\(n\\ge2\\) O’Neil obtains</p><div class="eq">\\[\\boxed{c_n^*=-\\frac{1}{n^2}c_{n-1}^*-\\frac{2(-1)^n}{n(n!)^2}}.\\]</div><p>The resulting second solution begins</p><div class="whybox"><div class="eq">\\[\\boxed{y_2=y_1\\ln x+\\frac2x-\\frac34+\\frac{11}{108}x-\\frac{25}{3456}x^2+\\cdots}.\\]</div></div><p><b>Why this matters.</b> Example 2.20 identifies the repeated root; Example 2.22 actually constructs the missing independent solution. The logarithm is part of the theorem’s repeated-root mechanism, not an optional decoration.</p>`,'§2.5.2 · Example 2.22');

const l15Ex223=l15Board('O’Neil Example 2.23 — Case 3 can have k=0',
`<p>${l15Book}</p><p>Analyze</p><div class="eq">\\[x^2y''+x^2y'-2y=0.\\]</div><p>The indicial roots are \\(2\\) and \\(-1\\). What does the integer difference imply, and what special feature occurs in this textbook example?</p>`,
`<p>The difference is \\(2-(-1)=3\\), a positive integer, so the problem belongs to <b>Case 3</b>. The theorem permits a second solution of the form</p><div class="eq">\\[y_2=k y_1\\ln x+\\sum c_n^*x^{n+r_2}.\\]</div><p>But “permits” does not mean the logarithm must survive. For the larger root \\(r=2\\), the first solution begins</p><div class="eq">\\[y_1=c_0x^2\\left(1-\\frac12x+\\frac3{20}x^2-\\frac1{30}x^3+\\cdots\\right).\\]</div><p>For the smaller-root branch, consistency yields a simple independent solution proportional to</p><div class="eq">\\[\\boxed{y_2=\\frac1x-\\frac12}.\\]</div><p>Here the logarithmic coefficient is \\(k=0\\). This is the important warning: an integer-separated root pair signals Case 3, but the actual log coefficient may vanish for a particular equation.</p>`,'§2.5.2 · Example 2.23');
const l15Ex224=l15Board('O’Neil Example 2.24 — Case 3 can genuinely require a logarithm',
`<p>${l15Book}</p><p>For</p><div class="eq">\\[xy''-y=0,\\]</div><p>the indicial roots are \\(r_1=1\\) and \\(r_2=0\\). Explain why a second plain Frobenius series fails and what form must replace it.</p>`,
`<p>The root difference is 1, so this is Case 3. For \\(r=1\\), the recurrence gives</p><div class="eq">\\[c_n=\\frac{c_{n-1}}{n(n+1)},\\]</div><p>hence</p><div class="eq">\\[y_1=c_0\\left(x+\\frac12x^2+\\frac1{12}x^3+\\frac1{144}x^4+\\cdots\\right).\\]</div><p>If we naively put \\(r=0\\) into the same recurrence, the \\(n=1\\) relation would force \\(c_0=0\\), contradicting the Frobenius requirement \\(c_0\\ne0\\). That failure is diagnostic: the second solution is not a plain smaller-root series.</p><div class="whybox"><div class="eq">\\[\\boxed{y_2=k y_1\\ln x+\\sum_{n=0}^{\\infty}c_n^*x^n}.\\]</div></div><p>O’Neil’s coefficient calculation shows a nonzero logarithmic contribution in this example. Thus Examples 2.23 and 2.24 together show both possibilities inside Case 3.</p>`,'§2.5.2 · Example 2.24');
const l15Class=l15Board('Frobenius skill — classify a singular point',`<p>${l15Recon}</p><p>Classify \\(x=0\\) for</p><div class="eq">\\[x^2y''+x(1+x)y'+(2+x^2)y=0.\\]</div>`,`<p>Because \\(P=x^2\\) vanishes at zero, it is singular. Check regularity:</p><div class="eq">\\[x\\frac{Q}{P}=1+x,\\qquad x^2\\frac{R}{P}=2+x^2.\\]</div><p>Both are analytic at zero, hence</p><div class="whybox"><div class="eq">\\[\\boxed{x=0\\text{ is a regular singular point}.}\\]</div></div><p>That classification justifies attempting \\(y=\\sum c_nx^{n+r}\\).</p>`,'Syllabus Frobenius practice');
const l15Roots=l15Board('Indicial-root decision — identify the theorem case',`<p>${l15Recon}</p><p>For each root pair, choose the Frobenius case: (a) \\(2,1/2\\); (b) \\(-1,-1\\); (c) \\(3,-1\\).</p>`,`<p><b>(a)</b> Difference \\(3/2\\), not a positive integer → <b>Case 1</b>, two direct Frobenius series.</p><p><b>(b)</b> Difference 0 → <b>Case 2</b>, repeated root; the second solution has a logarithmic template.</p><p><b>(c)</b> Difference 4 → <b>Case 3</b>; a logarithmic term may occur, but its coefficient can sometimes be zero.</p>`,'Syllabus indicial-root practice');
const l15TransferMastery=[
l15Board('Transfer 1 — classify before choosing Frobenius',`<p>${l15Recon}</p><p>Classify \\(x=0\\) for</p><div class="eq">\\[x^2y''+x(1+x)y'+(3+x)y=0.\\]</div>`,`<p>The leading coefficient \\(P=x^2\\) vanishes, so zero is singular. Check</p><div class="eq">\\[x\\frac{Q}{P}=1+x,\\qquad x^2\\frac{R}{P}=3+x.\\]</div><p>Both are analytic at zero, hence</p><div class="whybox"><div class="eq">\\[\\boxed{x=0\\text{ is regular singular}.}\\]</div></div><p>That classification justifies a Frobenius trial.</p>`,'Original course transfer'),
l15Board('Transfer 2 — derive an indicial equation independently',`<p>${l15Recon}</p><p>For</p><div class="eq">\\[x^2y''+3xy'+y=0,\\]</div><p>derive the indicial equation and classify its roots.</p>`,`<p>Use the leading Frobenius behavior \\(y\\sim c_0x^r\\). Then</p><div class="eq">\\[x^2y''+3xy'+y\\sim c_0[r(r-1)+3r+1]x^r.\\]</div><p>Since \\(c_0\\ne0\\),</p><div class="eq">\\[r(r-1)+3r+1=r^2+2r+1=(r+1)^2=0.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{r=-1\\text{ is a repeated root — Case 2}.}\\]</div></div>`,'Original course transfer'),
l15Board('Transfer 3 — theorem-case recognition',`<p>${l15Recon}</p><p>Indicial roots are \\(r_1=5/2\\) and \\(r_2=-1\\). Which Frobenius case applies, and what should you expect?</p>`,`<p>The difference is</p><div class="eq">\\[r_1-r_2=\\frac72,\\]</div><p>which is not a positive integer. Therefore this is <b>Case 1</b>: two independent Frobenius series can be generated directly, one from each root.</p>`,'Original course transfer'),
l15Board('Transfer 4 — repeated-root logarithm in a solvable model',`<p>${l15Recon}</p><p>Analyze</p><div class="eq">\\[xy''+y'=0,\\qquad x>0.\\]</div><p>Use the Frobenius viewpoint to explain why a logarithm appears.</p>`,`<p>Here \\(P=x,Q=1,R=0\\). Since \\(xQ/P=1\\) and \\(x^2R/P=0\\), zero is regular singular. For \\(y=x^r\\),</p><div class="eq">\\[xy''+y'=r(r-1)x^{r-1}+rx^{r-1}=r^2x^{r-1}.\\]</div><p>The indicial equation is \\(r^2=0\\), a repeated root \\(r=0\\). One solution is \\(y_1=1\\). Direct integration gives \\(xy'=C\\), hence</p><div class="whybox"><div class="eq">\\[\\boxed{y_2=\\ln x}.\\]</div></div><p>This concrete equation shows the Case-2 logarithm rather than merely stating the theorem.</p>`,'Original course transfer'),
l15Board('Transfer 5 — integer-separated roots do not force a logarithm',`<p>${l15Recon}</p><p>Use Frobenius on the Euler equation</p><div class="eq">\\[x^2y''+xy'-4y=0,\\qquad x>0.\\]</div><p>What do the roots predict, and does a logarithm actually survive?</p>`,`<p>The indicial equation is</p><div class="eq">\\[r(r-1)+r-4=r^2-4=0,\\]</div><p>so \\(r_1=2\\), \\(r_2=-2\\), with difference 4. This is Case 3. Yet both pure powers solve the equation directly:</p><div class="whybox"><div class="eq">\\[\\boxed{y=c_1x^2+c_2x^{-2}}.\\]</div></div><p>Thus the allowed Case-3 logarithmic coefficient is \\(k=0\\), matching the warning illustrated by O’Neil Example 2.23.</p>`,'Original course transfer'),
l15Board('Transfer 6 — diagnose a false Frobenius conclusion',`<p>${l15Recon}</p><p>A student finds indicial roots \\(r_1=3\\), \\(r_2=0\\) and writes: “Because the roots differ by an integer, the second solution must contain a nonzero \\(y_1\\ln x\\) term.” Diagnose the statement.</p>`,`<p>The root difference is a positive integer, so <b>Case 3</b> applies. But the theorem gives the template</p><div class="eq">\\[y_2=k y_1\\ln x+\\sum c_n^*x^{n+r_2}.\\]</div><p>It does not require \\(k\\ne0\\). The coefficient must be determined by substitution; it may vanish, as in O’Neil Example 2.23.</p><div class="whybox"><p><b>Correct conclusion:</b> integer separation permits a logarithmic term; it does not guarantee a nonzero one.</p></div>`,'Original course diagnostic')
];

const lesson15Units=[
{id:'l15-map',courseLesson:15,color:'#48658d',badge:'1',label:'Nov. 9 map',title:'From Ordinary Power Series to Frobenius',subtitle:'Airy · MSE context · regular singular points · indicial roots',desc:'See why changing one exponent parameter repairs the ordinary-series method at many singular points.',lessons:[{title:'Map',screens:[
{type:'teach',title:'The supplied edition uses different section numbers than the syllabus',html:`<p>${l15Core}</p><p>The syllabus labels the Nov. 9 material as O’Neil §§4.1–4.2. In the supplied 8th Edition SI, the corresponding series chapter is <b>§2.5</b>: ordinary power series in §2.5.1 and Frobenius in §2.5.2. We follow the syllabus’s topic order while citing the supplied edition’s actual sections and example numbers.</p>`},
{type:'teach',title:'The conceptual jump is only one exponent',html:`<p>${l15Explain}</p><p>At an ordinary point we tried</p><div class="eq">\\[y=\\sum_{n=0}^\\infty a_nx^n.\\]</div><p>At a regular singular point, the equation may demand behavior such as \\(x^{-1/2}\\) or \\(x^2\\) that an ordinary Taylor series cannot represent. Frobenius adds an unknown leading exponent:</p><div class="whybox"><div class="eq">\\[\\boxed{y=\\sum_{n=0}^\\infty c_nx^{n+r},\\qquad c_0\\ne0}.\\]</div></div><p>The ODE itself determines \\(r\\) through the lowest-power coefficient—the <b>indicial equation</b>.</p>`},
{type:'quiz',title:'Why add r?',q:'What problem does the Frobenius exponent r solve?',options:['It allows non-integer or negative leading behavior near a regular singular point','It changes the ODE order','It is the radius of convergence'],answer:0,why:'The new leading power x^r lets the series match singular local behavior.'}
]}]},
{id:'l15-airy',courseLesson:15,color:'#33796f',badge:'2',label:'Airy equation',title:'Power-Series Worked Example: Airy’s Equation',subtitle:'ordinary point · recurrence stride 3 · two independent branches',desc:'Use Lesson 14’s algorithm on the syllabus’s named example.',lessons:[{title:'Airy',screens:[
l15Clone(l15Airy),
{type:'teach',title:'What the recurrence pattern tells you before you compute forever',html:`<p>${l15Explain}</p><p>For Airy, \\(a_{n+2}\\) depends on \\(a_{n-1}\\), so indices advance by 3. That partitions coefficients into classes modulo 3. Since \\(a_2=0\\), the class \\(2,5,8,\\ldots\\) dies. The other two classes generate the two independent solutions required by a second-order equation.</p><p>Recognizing this structure is more useful than blindly calculating ten coefficients.</p>`},
{type:'quiz',title:'Airy branch check',q:'For yʺ−xy=0, which initial coefficient is forced to zero by the lowest-power equation?',options:['a₂','a₀','a₁'],answer:0,why:'The n=0 coefficient is 2a₂=0.'}
]}]},
{id:'l15-mse',courseLesson:15,color:'#8c6736',badge:'3',label:'MSE context',title:'Why Airy-Type Equations Appear in Graded Models',subtitle:'nondimensionalization · characteristic length · linear variation',desc:'Connect the series example to a representative materials-science scaling argument without inventing instructor notes.',lessons:[{title:'Graded coefficient model',screens:[
l15Clone(l15MSE),
{type:'teach',title:'What the scaling accomplished',html:`<p>The dimensional model contains \\(\\alpha\\), whose numerical value depends on the chosen units. After choosing \\(\\ell=\\alpha^{-1/3}\\), the dimensionless equation has no free coefficient:</p><div class="eq">\\[u_{\\xi\\xi}-\\xi u=0.\\]</div><p>This tells us that different physical systems with the same dimensionless form share the same mathematical solution curves after rescaling. That is the engineering value of nondimensionalization—not just cleaner notation.</p>`}
]}]},
{id:'l15-regular',courseLesson:15,color:'#725d94',badge:'4',label:'Regular singular points',title:'Ordinary, Regular Singular, Irregular',subtitle:'the classification test that chooses the method',desc:'Make the regular-singular test mechanical and meaningful.',lessons:[{title:'Classification',screens:[
{type:'teach',title:'The regular-singular test',html:`<p>${l15Book}</p><p>For</p><div class="eq">\\[P(x)y''+Q(x)y'+R(x)y=0,\\]</div><p>a point \\(x_0\\) with \\(P(x_0)=0\\) is singular. It is <b>regular singular</b> when</p><div class="eq">\\[(x-x_0)\\frac{Q(x)}{P(x)},\\qquad (x-x_0)^2\\frac{R(x)}{P(x)}\\]</div><p>are analytic at \\(x_0\\). Otherwise it is irregular.</p><p>Why those powers? After dividing by \\(P\\), a regular singular point allows at worst a simple pole in the \\(y'\\) coefficient and a double pole in the \\(y\\) coefficient. Frobenius is designed precisely for that controlled singularity.</p>`},
l15Clone(l15Class),
{type:'quiz',title:'Method choice',q:'If x₀ is regular singular, what is the standard first trial?',options:['y=Σcₙ(x−x₀)ⁿ⁺ʳ','y=eʳˣ only','A Fourier series'],answer:0,why:'The Frobenius template extends the ordinary power series by an unknown leading exponent.'}
]}]},
{id:'l15-indicial',courseLesson:15,color:'#3f7485',badge:'5',label:'Indicial equation',title:'Where the Indicial Equation Comes From',subtitle:'lowest power · c₀≠0 · recurrence after r',desc:'Derive r from the ODE instead of memorizing a formula without context.',lessons:[{title:'Indicial logic',screens:[
{type:'teach',title:'The lowest power decides the leading exponent',html:`<p>${l15Explain}</p><p>After substituting a Frobenius series, collect the smallest occurring power, often \\(x^r\\) or \\(x^{r-1}\\). Its coefficient has the form</p><div class="eq">\\[I(r)c_0=0.\\]</div><p>By definition we choose \\(c_0\\ne0\\); otherwise the stated leading power was not actually leading. Therefore</p><div class="whybox"><div class="eq">\\[\\boxed{I(r)=0}\\]</div></div><p>is the <b>indicial equation</b>. Solve it first. Only then substitute each allowable root into the general recurrence for \\(c_n\\).</p>`},
l15Clone(l15Ex220),
{type:'quiz',title:'Why c₀≠0?',q:'Why is c₀ required to be nonzero in the Frobenius trial?',options:['So xʳ is genuinely the leading term and the indicial equation is meaningful','Because c₀ must equal 1 in every problem','To force convergence'],answer:0,why:'If c₀ were zero, the first nonzero term would occur at a different exponent and r would not describe the true leading behavior.'}
]}]},
{id:'l15-threecases',courseLesson:15,color:'#536b48',badge:'6',label:'Three root cases',title:'The Three Cases of Indicial Roots',subtitle:'noninteger separation · repeated root · integer separation',desc:'Know what kind of second solution to expect before grinding coefficients.',lessons:[
{title:'Case 1',screens:[
{type:'teach',title:'Case 1 — root difference is not a positive integer',html:`<p>${l15Book}</p><p>Let real roots satisfy \\(r_1\\ge r_2\\). If \\(r_1-r_2\\) is <b>not</b> a positive integer, the theorem gives two independent Frobenius series, one built from each root:</p><div class="eq">\\[y_1=\\sum c_nx^{n+r_1},\\qquad y_2=\\sum c_n^*x^{n+r_2}.\\]</div><p>This is the cleanest case.</p>`},l15Clone(l15Ex221)]},
{title:'Case 2',screens:[
{type:'teach',title:'Case 2 — repeated indicial root',html:`<p>${l15Book}</p><p>If \\(r_1=r_2\\), one Frobenius series comes from that root, while a second independent solution has the template</p><div class="eq">\\[\\boxed{y_2=y_1\\ln x+\\sum_{n=1}^{\\infty}c_n^*x^{n+r_1}}.\\]</div><p>The logarithm is not an arbitrary trick: the repeated exponent fails to provide two independent leading behaviors, so a new functional direction is needed.</p>`},l15Clone(l15Ex222)]},
{title:'Case 3',screens:[
{type:'teach',title:'Case 3 — roots differ by a positive integer',html:`<p>${l15Book}</p><p>If \\(r_1-r_2\\) is a positive integer, the second solution has the general template</p><div class="eq">\\[\\boxed{y_2=k y_1\\ln x+\\sum_{n=0}^{\\infty}c_n^*x^{n+r_2}}.\\]</div><p>The constant \\(k\\) can be zero or nonzero depending on the equation. Therefore “integer difference” does <b>not</b> mean “a log definitely appears”; it means the logarithmic template may be necessary.</p>`},l15Clone(l15Ex223),l15Clone(l15Ex224)]}
]},
{id:'l15-practice',courseLesson:15,color:'#88673a',badge:'7',label:'Interleaved practice',title:'Frobenius Decision Practice',subtitle:'fresh classification checks · indicial roots · theorem cases',desc:'Practice the decisions that should happen before long coefficient algebra without replaying an earlier worked problem.',lessons:[{title:'Practice',screens:[
{type:'quiz',title:'Regular-singular test',q:'For x²yʺ+2xyʹ+(1+x)y=0 at x=0, which classification is correct?',options:['Regular singular','Ordinary','Irregular singular'],answer:0,why:'P=x² vanishes, while xQ/P=2 and x²R/P=1+x are analytic at zero.'},
l15Clone(l15Roots),
{type:'quiz',title:'Repeated root',q:'An indicial equation has r=−2 twice. Which theorem case?',options:['Case 2','Case 1','Case 3'],answer:0,why:'A repeated root means r₁−r₂=0, which is the repeated-root case.'},
{type:'quiz',title:'Integer-separated roots',q:'If r₁−r₂=3, what can you assert about the logarithm in y₂?',options:['Case 3 applies, but the log coefficient may be zero','A log must always be nonzero','No second solution exists'],answer:0,why:'O’Neil Example 2.23 is an explicit Case-3 example with k=0.'}
]}]},
{id:'l15-mastery',courseLesson:15,color:'#a14359',badge:'8',label:'Mastery',title:'Nov. 9 Mastery — Frobenius Transfer & Diagnostics',subtitle:'6 original problems · classification, indicial roots, theorem cases, logs',desc:'A non-repetitive transfer set. Authentic O’Neil Examples 2.20–2.24 remain in the teaching sequence; mastery now checks whether those ideas transfer to unfamiliar equations.',lessons:[{title:'Classification & indicial equation',screens:l15TransferMastery.slice(0,2)},{title:'Root cases & repeated roots',screens:l15TransferMastery.slice(2,4)},{title:'Integer separation & diagnosis',screens:l15TransferMastery.slice(4,6)}]}
];

// Authentic numbered O’Neil practice: one problem for each Frobenius root-case pattern.
const l15P9=l15Board('O’Neil §2.5.2 Problem 9 — repeated root with a logarithmic second solution',`<p>${l15Book}</p><p>Find two independent Frobenius solutions near \\(x=0\\) for</p><div class="eq">\\[x(2-x)y''-2(x-1)y'+2y=0.\\]</div><p>Classify the indicial roots before constructing the second solution.</p>`,`<p>Zero is regular singular because</p><div class="eq">\\[x\\frac{Q}{P}=-\\frac{2(x-1)}{2-x},\\qquad x^2\\frac{R}{P}=\\frac{2x}{2-x},\\]</div><p>are analytic near zero. For the leading Frobenius term \\(y\\sim c_0x^r\\), the lowest power gives</p><div class="eq">\\[2r(r-1)+2r=2r^2=0.\\]</div><p>Thus \\(r=0\\) is a repeated root: <b>Case 2</b>.</p><p>A direct solution from the first branch is</p><div class="eq">\\[\\boxed{y_1=1-x}.\\]</div><p>For an independently verified second solution, use reduction of order after dividing by \\(x(2-x)\\). With \\(P_1(x)=-2(x-1)/[x(2-x)]\\),</p><div class="eq">\\[y_2=y_1\\int\\frac{e^{-\\int P_1(x)dx}}{y_1^2}dx.\\]</div><p>Carrying out the integral gives, on \\(0<x<2\\),</p><div class="whybox"><div class="eq">\\[\\boxed{y_2=(1-x)\\ln\\!\\left(\\frac{x}{2-x}\\right)+2}.\\]</div></div><p>Direct substitution gives zero, so the logarithmic solution is independently checked. Expanding the analytic part near zero and discarding a constant multiple of \\(y_1\\) if desired gives the local structure</p><div class="eq">\\[y_2=(1-x)\\ln x+2+\\frac{x}{2}-\\frac{3x^2}{8}-\\frac{x^3}{12}-\\frac{5x^4}{192}+O(x^5).\\]</div><p>The logarithm is the signature of the repeated indicial root.</p>`,'§2.5.2 · Problem 9');
const l15P5=l15Board('O’Neil §2.5.2 Problem 5 — noninteger-separated roots',`<p>${l15Book}</p><p>Find the first five terms of two independent Frobenius solutions for</p><div class="eq">\\[4xy''+2y'+y=0.\\]</div>`,`<p>The regular-singular test passes at zero. The indicial equation is</p><div class="eq">\\[4r(r-1)+2r=2r(2r-1)=0,\\]</div><p>so \\(r_1=1/2\\), \\(r_2=0\\). Their difference is not a positive integer, so Case 1 gives two direct Frobenius series.</p><p>For either root, the recurrence is</p><div class="eq">\\[[4(n+r)(n+r-1)+2(n+r)]c_n+c_{n-1}=0.\\]</div><p>For \\(r=1/2\\),</p><div class="eq">\\[c_n=-\\frac{c_{n-1}}{2n(2n+1)},\\]</div><p>giving</p><div class="eq">\\[\\boxed{y_1=c_0\\left(x^{1/2}-\\frac{x^{3/2}}6+\\frac{x^{5/2}}{120}-\\frac{x^{7/2}}{5040}+\\frac{x^{9/2}}{362880}+\\cdots\\right)}.\\]</div><p>For \\(r=0\\),</p><div class="eq">\\[c_n=-\\frac{c_{n-1}}{2n(2n-1)},\\]</div><p>so</p><div class="whybox"><div class="eq">\\[\\boxed{y_2=c_0^*\\left(1-\\frac x2+\\frac{x^2}{24}-\\frac{x^3}{720}+\\frac{x^4}{40320}+\\cdots\\right)}.\\]</div></div>`,'§2.5.2 · Problem 5');
const l15P7=l15Board('O’Neil §2.5.2 Problem 7 — integer-separated roots with no log',`<p>${l15Book}</p><p>Find two independent solutions for</p><div class="eq">\\[x^2y''-2xy'-(x^2-2)y=0.\\]</div><p>Use the Frobenius root structure and give the first five nonzero terms of each solution.</p>`,`<p>The indicial polynomial is</p><div class="eq">\\[r(r-1)-2r+2=(r-1)(r-2),\\]</div><p>so \\(r_1=2\\), \\(r_2=1\\). The roots differ by the positive integer 1, so this is Case 3. However, the logarithmic coefficient happens to vanish.</p><p>O’Neil’s selected answer can be expressed in the simple closed forms</p><div class="whybox"><div class="eq">\\[\\boxed{y_1=x\\sinh x,\\qquad y_2=xe^{-x}}.\\]</div></div><p>The corresponding series begin</p><div class="eq">\\[y_1=x^2+\\frac{x^4}{6}+\\frac{x^6}{120}+\\frac{x^8}{5040}+\\frac{x^{10}}{362880}+\\cdots,\\]</div><div class="eq">\\[y_2=x-x^2+\\frac{x^3}{2}-\\frac{x^4}{6}+\\frac{x^5}{24}+\\cdots.\\]</div><p>Direct substitution verifies both exact forms. This is a clean textbook example of an integer-separated pair where Case 3 does <b>not</b> force a nonzero logarithm.</p>`,'§2.5.2 · Problem 7');
const l15CasesBook=lesson15Units.find(u=>u&&u.id==='l15-threecases');
if(l15CasesBook){
  const c1=l15CasesBook.lessons.find(l=>l.title==='Case 1');if(c1)c1.screens.push(l15Clone(l15P5));
  const c2=l15CasesBook.lessons.find(l=>l.title==='Case 2');if(c2)c2.screens.push(l15Clone(l15P9));
  const c3=l15CasesBook.lessons.find(l=>l.title==='Case 3');if(c3)c3.screens.push(l15Clone(l15P7));
}

if(!units.some(u=>u&&u.id==='l15-map'))units.push(...lesson15Units);
if(courseLessons[13])courseLessons[13].status='complete';
courseLessons[14]={number:15,title:'Airy Equation & Frobenius Solutions',subtitle:'Nov. 9 · supplied O’Neil §2.5.1–2.5.2 · regular singular points · indicial roots',status:'current'};
if(typeof renderCourseMap==='function')renderCourseMap();
if(typeof render==='function')render();