/* Lesson 24 — Dec. 14: Project presentations. No new examinable mathematics. */
const l24Core='<span class="supplementalTag">Core · Dec. 14 syllabus · Project presentations</span>',l24Explain='<span class="supplementalTag">Presentation support · derived from official project requirements</span>';
function l24Board(title,prompt,solution){return {type:'bookproblem',bookSection:'Final Project presentation support · not an O’Neil exercise',title,prompt,solution};} function l24Clone(s){return s?{...s,inlineBookPractice:true}:null;}
const l24Model=l24Board('Six-minute explanation drill',`<p>${l24Explain}</p><p>On the scratch board, outline a six-minute explanation of an ODE model. Your outline must state: the physical question, variables and units, modeling assumptions, the governing ODE/system, why the chosen solution method applies, the main result, at least two verification checks, and one limitation.</p>`,`<p>A strong structure is:</p><p><b>0:00–0:45 — Frame.</b> State the engineering question and define every variable with units.</p><p><b>0:45–1:45 — Model.</b> Explain the physical balance/law that produces the ODE and state assumptions.</p><p><b>1:45–3:15 — Solve.</b> Name the mathematical form, justify the method, and show only the decisive steps.</p><p><b>3:15–4:30 — Interpret.</b> Translate the formula back into engineering behavior.</p><p><b>4:30–5:30 — Verify.</b> Show independent checks such as substitution/residual, IC/BC, units, limiting behavior, numerical comparison, or a second route.</p><p><b>5:30–6:00 — Limitations.</b> State where the model can fail and what would improve it.</p><p>This is a presentation framework, not a fabricated textbook solution.</p>`);
const l24Audit=l24Board('AI-audit explanation drill',`<p>${l24Explain}</p><p>An AI solution reaches the correct-looking final formula but skips the model derivation and never checks units or the initial condition. Prepare a concise audit verdict.</p>`,`<p><b>Verdict:</b> the result is not yet adequately verified. A plausible final expression does not establish that the model or solution is correct.</p><p><b>Diagnosis:</b> first reconstruct the governing equation from the physical assumptions; then verify the proposed expression by substitution and the IC/BC; then check dimensional consistency and relevant limiting/long-time behavior. If those pass, the formula gains independent support. If any fail, identify the first failing step rather than merely saying “AI was wrong.”</p>`);
const l24QA=l24Board('Two-minute Q&A drill',`<p>${l24Explain}</p><p>Prepare answers to: “Why did you choose this method?”, “How do you know the answer is correct?”, and “What is the biggest limitation of your model?”</p>`,`<p><b>Why this method?</b> Identify the equation’s mathematical structure first, then name the theorem/technique whose hypotheses match it.</p><p><b>How do you know?</b> Give concrete checks: residual/substitution, data or IC/BC agreement, units, asymptotics, numerical/independent route.</p><p><b>Limitation?</b> Name a specific assumption—linearity, constant coefficients, idealized forcing, neglected losses/coupling, parameter uncertainty—and explain the direction in which reality may depart from the model.</p>`);
const lesson24Units=[
{id:'l24-map',courseLesson:24,color:'#476a91',badge:'1',label:'Dec. 14 map',title:'Project Presentation Day',subtitle:'communicate · justify · verify · defend',desc:'No new examinable mathematics: turn your project mathematics into a rigorous six-minute argument.',lessons:[{title:'Map',screens:[{type:'teach',title:'What the syllabus actually schedules',html:`<p>${l24Core}</p><p>Dec. 14 is <b>Project Presentations</b>, not a new textbook-content lecture. The official course outline specifies a <b>six-minute group presentation plus two minutes of Q&A</b>. This lesson therefore adds no new O’Neil theory and does not pretend that presentation guidance is textbook material.</p>`},{type:'teach',title:'The mathematical story your audience needs',html:`<p>${l24Explain}</p><p>Use the same reasoning standard as the learning lessons: physical question → variables/units → assumptions → governing equation → method choice → solution → interpretation → independent checks → limitations. The goal is not to display algebra; it is to make every important mathematical decision defensible.</p>`}]}]},
{id:'l24-frame',courseLesson:24,color:'#34776e',badge:'2',label:'Frame',title:'Explain the Model Before the Algebra',subtitle:'question · variables · units · assumptions',desc:'Make the physical model understandable before showing a solution.',lessons:[{title:'Model story',screens:[{type:'teach',title:'Translate physics into mathematics',html:`<p>${l24Explain}</p><p>State what changes, what causes that change, and what is neglected. Define each symbol before it appears. Where applicable, say the balance in words first—such as “rate of change = input − output”—then write the ODE. Track units so the audience can see why the terms can legitimately be added.</p>`},l24Clone(l24Model)]}]},
{id:'l24-method',courseLesson:24,color:'#795d9a',badge:'3',label:'Method',title:'Defend the Method Choice',subtitle:'classify first · solve second',desc:'Show why your technique fits the equation.',lessons:[{title:'Method choice',screens:[{type:'teach',title:'One sentence of classification can save a minute of algebra',html:`<p>${l24Explain}</p><p>Examples: “This is a constant-coefficient second-order linear ODE, so the characteristic equation gives the homogeneous modes”; “The forcing is piecewise, so the Heaviside/Laplace route avoids solving separate IVPs”; “This constant matrix system has a full eigenbasis, so each eigenpair produces a modal solution.” State the structural reason, not merely the method name.</p>`},{type:'quiz',title:'Best justification',q:'Which statement best defends using an integrating factor?',options:['It is a formula I remember','After standardizing the equation as y′+p(x)y=q(x), the integrating factor turns the left side into a product derivative','It usually works for ODEs'],answer:1,why:'Method choice should follow from the equation’s structure.'}]}]},
{id:'l24-verify',courseLesson:24,color:'#9a6038',badge:'4',label:'Verify',title:'Show Evidence, Not Confidence',subtitle:'residual · conditions · units · behavior',desc:'Use complementary checks that could actually expose an error.',lessons:[{title:'Verification',screens:[{type:'teach',title:'Five complementary check families',html:`<p>${l24Explain}</p><p><b>Equation check:</b> substitute into the ODE/system. <b>Condition check:</b> verify every IC/BC. <b>Dimensional check:</b> compare units term by term. <b>Behavior check:</b> inspect limits, signs, stability, or conservation. <b>Independent check:</b> compare with a second analytic route, numerical calculation, or trusted special case. Choose checks that are genuinely independent of the derivation.</p>`},l24Clone(l24Audit)]}]},
{id:'l24-qa',courseLesson:24,color:'#3e7287',badge:'5',label:'Q&A',title:'Defend Assumptions and Limitations',subtitle:'answer the question behind the question',desc:'Use the two-minute Q&A to demonstrate understanding.',lessons:[{title:'Q&A',screens:[{type:'teach',title:'A limitation is not a confession',html:`<p>${l24Explain}</p><p>A good limitation names an assumption and explains its consequence. “We assumed linear damping” is stronger when followed by what nonlinearity would change. If a parameter is uncertain, say which prediction is sensitive to it. If the model has a restricted domain, state that domain.</p>`},l24Clone(l24QA)]}]},
{id:'l24-delivery',courseLesson:24,color:'#536b48',badge:'6',label:'Delivery',title:'Compress Without Hiding Reasoning',subtitle:'one idea per visual · equations with purpose',desc:'Keep the rigorous chain while removing nonessential algebra.',lessons:[{title:'Delivery',screens:[{type:'teach',title:'What to put on a slide',html:`<p>${l24Explain}</p><p>Every displayed equation should answer a question: What is the model? Why this method? What is the result? How was it checked? Avoid walls of derivation. Keep notation identical between speech, equations, plots, and the report. Label axes and units. When showing a graph, say what physical conclusion the audience should read from it.</p>`}]}]},
{id:'l24-check',courseLesson:24,color:'#856b37',badge:'7',label:'Checklist',title:'Pre-Presentation Mathematical Audit',subtitle:'definitions · logic · checks · limitations',desc:'Catch presentation-day weaknesses before Q&A does.',lessons:[{title:'Audit',screens:[{type:'teach',title:'Final pass',html:`<p>${l24Explain}</p><p>Confirm that every symbol is defined; equations are dimensionally meaningful; initial/boundary conditions are stated; the method’s hypotheses hold; constants/signs are correct; plots agree with the formula; verification is shown rather than asserted; AI-generated work has been independently audited; and limitations are specific.</p>`}]}]},
{id:'l24-mastery',courseLesson:24,color:'#a24458',badge:'8',label:'Mastery',title:'Presentation Rehearsal',subtitle:'frame · defend · verify · answer',desc:'Rehearse the mathematical argument on the scratch boards.',lessons:[{title:'Six minutes',screens:[l24Model]},{title:'Audit',screens:[l24Audit]},{title:'Q&A',screens:[l24QA]}]}
];
if(!units.some(u=>u&&u.id==='l24-map'))units.push(...lesson24Units);if(courseLessons[22])courseLessons[22].status='complete';courseLessons[23]={number:24,title:'Project Presentation Day',subtitle:'Dec. 14 · no new examinable mathematics',status:'current'};

// Quality reconstruction: align the rehearsal with the official rubric and replace repeated mastery drills.
const l24Transfer=[
l24Board('Diagnostic 1 — undefined-symbol failure',`<p>${l24Explain}</p><p>A presentation slide suddenly shows \\(m y''+cy'+ky=F(t)\\) without defining any symbols. Identify the mathematical communication failure and repair it in one concise opening statement.</p>`,`<p>The equation is uninterpretable until the variables, parameters, and units are defined. A repair is: “Let \\(y(t)\\) be displacement in meters; \\(m\\) mass in kg; \\(c\\) damping coefficient in N·s/m; \\(k\\) spring constant in N/m; and \\(F(t)\\) applied force in N. Newton’s second law then gives \\(my''+cy'+ky=F(t)\\).” This also exposes dimensional inconsistencies immediately.</p>`),
l24Board('Diagnostic 2 — method-name is not justification',`<p>${l24Explain}</p><p>A speaker says, “We used Laplace transforms because Laplace transforms are good for this.” Rewrite the justification for an IVP with a load switched on at \\(t=3\\).</p>`,`<p>A defensible statement is: “The model is a linear IVP with piecewise forcing. Writing the switch with \\(H(t-3)\\) lets the Laplace transform incorporate both the initial data and the discontinuous input algebraically; the second shifting theorem then returns the delayed response.” The structural feature, not preference, justifies the method.</p>`),
l24Board('Diagnostic 3 — two checks that are not independent',`<p>${l24Explain}</p><p>A group says it verified a solution by (1) redoing the same algebra and (2) asking the same AI model to recompute it. Why is this weak, and name two stronger complementary checks.</p>`,`<p>Both checks can reproduce the same reasoning error, so they are not strongly independent. Better choices include direct residual substitution into the original ODE/system, checking every IC/BC, dimensional consistency, asymptotic behavior, a numerical solution, or a trusted limiting case. For example: substitute the formula into the ODE and independently compare a numerical trajectory at selected times.</p>`),
l24Board('Diagnostic 4 — graph without mathematical meaning',`<p>${l24Explain}</p><p>A slide shows a smooth curve but has no axis labels, units, or stated conclusion. What must be added before the plot counts as mathematical evidence?</p>`,`<p>Label both axes with variables and units, identify parameter values/initial data, state whether the curve is analytic or numerical, and say what claim it supports. A plot becomes evidence only when the audience can connect it to the model and reproduce the interpretation.</p>`),
l24Board('Diagnostic 5 — AI audit with a plausible final answer',`<p>${l24Explain}</p><p>An AI gives the same final formula as your derivation but assumes constant tank volume even though the listed inflow and outflow rates differ. What should your audit conclude?</p>`,`<p>The agreement of final formulas does not rescue an inconsistent model assumption. First compute the net volume rate. If inflow differs from outflow, concentration denominators must reflect changing volume unless another flow balances it. The audit should identify the modeling error, rebuild the governing balance with the correct volume function, and then re-solve or explain why the previous formula is invalid.</p>`),
l24Board('Diagnostic 6 — limitation with consequence',`<p>${l24Explain}</p><p>Improve the weak statement “Our model is not perfect” for a linear spring–mass–damper model.</p>`,`<p>A useful limitation names the assumption and consequence: “We assume linear viscous damping \\(F_d=-cy'\\). At large amplitudes or speeds, real damping may be nonlinear, so the predicted decay envelope and resonance amplitude can be inaccurate. Measuring force–velocity data and fitting a nonlinear damping law would test and improve this assumption.”</p>`)
];
const l24Mastery=units.find(u=>u&&u.id==='l24-mastery');if(l24Mastery){l24Mastery.title='Presentation Transfer Rehearsal';l24Mastery.subtitle='6 unseen diagnostics · framing, method, verification, audit, limitations';l24Mastery.desc='Uses the official project rubric as a reasoning test instead of replaying the guided six-minute/Q&A drills.';l24Mastery.lessons=[{title:'Framing & method',screens:l24Transfer.slice(0,2)},{title:'Verification evidence',screens:l24Transfer.slice(2,4)},{title:'AI audit & limitations',screens:l24Transfer.slice(4,6)}];}
const l24CheckUnit=units.find(u=>u&&u.id==='l24-check');if(l24CheckUnit&&!l24CheckUnit.lessons[0].screens.some(s=>s.title==='Official rubric lens'))l24CheckUnit.lessons[0].screens.unshift({type:'teach',title:'Official rubric lens',html:`<p>${l24Core}</p><p>The official project rubric weights <b>modeling and framing 25%</b>, <b>mathematical correctness and rigor 25%</b>, <b>verification 15%</b>, <b>AI audit 15%</b>, <b>writing 10%</b>, and <b>presentation 10%</b>. Your six-minute talk cannot reproduce the whole report, but it should visibly demonstrate the mathematical core: a defensible model, correct method, evidence, audit judgment, and limitations.</p>`});
if(typeof renderCourseMap==='function')renderCourseMap();if(typeof render==='function')render();