/* Lesson 13 — Nov. 2: convolution, transfer/impulse response, Dirac delta, systems by Laplace. */
const l13Core='<span class="supplementalTag">Core · Nov. 2 syllabus · O’Neil §§3.4–3.6</span>';
const l13Book='<span class="supplementalTag">Authentic textbook · O’Neil</span>';
const l13Explain='<span class="supplementalTag">Expanded explanation · Lesson 1 depth standard</span>';
function l13Board(title,prompt,solution,section){return {type:'bookproblem',bookSection:section,title,prompt,solution};}
function l13Clone(s){return s?{...s,inlineBookPractice:true}:null;}
const l13Ex313=l13Board('O’Neil Example 3.13 — inverse transform by convolution',
`<p>${l13Book}<br>Use convolution to find</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac1{s(s-4)^2}\\right\\}.\\]</div>`,
`<p><b>Why convolution applies.</b> The transform is already a product of two factors whose inverses are simple:</p><div class="eq">\\[\\frac1s\\cdot\\frac1{(s-4)^2},\\qquad \\mathcal L^{-1}\\{1/s\\}=1,\\quad \\mathcal L^{-1}\\{1/(s-4)^2\\}=te^{4t}.\\]</div><p>Therefore</p><div class="eq">\\[f(t)=(1*te^{4t})(t)=\\int_0^t \\tau e^{4\\tau}d\\tau.\\]</div><p>Integrate by parts:</p><div class="eq">\\[\\int \\tau e^{4\\tau}d\\tau=\\frac14\\tau e^{4\\tau}-\\frac1{16}e^{4\\tau}.\\]</div><p>Evaluate from 0 to \\(t\\):</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=\\frac14te^{4t}-\\frac1{16}e^{4t}+\\frac1{16}}.\\]</div></div><p><b>Check.</b> Transforming the three terms recombines to \\(1/[s(s-4)^2]\\).</p>`,'§3.4');
const l13Ex314=l13Board('O’Neil Example 3.14 — arbitrary input as an impulse-response convolution',
`<p>${l13Book}<br>Solve in terms of the unspecified input \\(f(t)\\):</p><div class="eq">\\[y''-2y'-8y=f(t),\\qquad y(0)=1,\\ y'(0)=0.\\]</div>`,
`<p><b>1 · Transform the dynamics and carry the initial data.</b></p><div class="eq">\\[(s^2-2s-8)Y-(s-2)=F(s).\\]</div><p>Hence</p><div class="eq">\\[Y=\\frac{s-2}{(s-4)(s+2)}+\\frac{1}{(s-4)(s+2)}F.\\]</div><p><b>2 · Separate initial-condition response from input response.</b></p><div class="eq">\\[\\frac{s-2}{(s-4)(s+2)}=\\frac1{3(s-4)}+\\frac2{3(s+2)},\\]</div><div class="eq">\\[\\frac1{(s-4)(s+2)}=\\frac1{6(s-4)}-\\frac1{6(s+2)}.\\]</div><p>Invert the first part directly. The second part is a product \\(G(s)F(s)\\), so it becomes convolution:</p><div class="whybox"><div class="eq">\\[\\boxed{y(t)=\\frac13e^{4t}+\\frac23e^{-2t}+\\left[\\frac16e^{4t}-\\frac16e^{-2t}\\right]*f(t)}.\\]</div></div><p>The bracketed function is the system's <b>impulse response</b> for zero initial conditions. Notice the \\(e^{4t}\\) term: this mathematical system is unstable, so its impulse response grows rather than decays.</p>`,'§3.4');
const l13Ex316=l13Board('O’Neil Example 3.16 — a delayed impulse',
`<p>${l13Book}<br>Solve</p><div class="eq">\\[y''+2y'+2y=\\delta(t-3),\\qquad y(0)=y'(0)=0.\\]</div>`,
`<p><b>1 · Transform the impulse.</b> A unit impulse delayed to \\(t=3\\) has transform \\(e^{-3s}\\). Zero initial conditions remove all extra derivative terms, so</p><div class="eq">\\[(s^2+2s+2)Y=e^{-3s}.\\]</div><p>Complete the square:</p><div class="eq">\\[Y=e^{-3s}\\frac1{(s+1)^2+1}.\\]</div><p><b>2 · Recognize the undelayed response.</b></p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac1{(s+1)^2+1}\\right\\}=e^{-t}\\sin t.\\]</div><p><b>3 · Apply the delay.</b></p><div class="whybox"><div class="eq">\\[\\boxed{y(t)=H(t-3)e^{-(t-3)}\\sin(t-3)}.\\]</div></div><p>The impulse deposits an instantaneous kick at \\(t=3\\); after that, the system follows its own damped natural response.</p>`,'§3.5');
const l13Ex317=l13Board('O’Neil Example 3.17 — an RLC impulse response',
`<p>${l13Book}<br>O’Neil applies a unit impulse voltage to the RLC circuit whose charge satisfies</p><div class="eq">\\[q''+10q'+100q=\\delta(t),\\qquad q(0)=q'(0)=0.\\]</div><p>Find the charge response and interpret it as an impulse response.</p>`,
`<p><b>1 · Transform the zero-state equation.</b></p><div class="eq">\\[(s^2+10s+100)Q=1.\\]</div><p>Complete the square:</p><div class="eq">\\[Q(s)=\\frac1{(s+5)^2+75}=\\frac1{(s+5)^2+(5\\sqrt3)^2}.\\]</div><p><b>2 · Invert the shifted sine transform.</b></p><div class="whybox"><div class="eq">\\[\\boxed{q(t)=\\frac1{5\\sqrt3}e^{-5t}\\sin(5\\sqrt3\\,t)}.\\]</div></div><p>Because the input is \\(\\delta(t)\\), this zero-state charge is the circuit's impulse response from source voltage to capacitor charge. The exponential envelope decays because the resistor dissipates stored energy; the sine factor reflects the underdamped oscillation. O’Neil notes that the capacitor output voltage is \\(100q(t)\\).</p>`,'§3.5 · Example 3.17');

const l13Ex318=l13Board('O’Neil Example 3.18 — solve a coupled differential system by Laplace',
`<p>${l13Book}<br>Solve</p><div class="eq">\\[x''-2x'+3y'+2y=4,\\qquad 2y'-x'+3y=0,\\]</div><div class="eq">\\[x(0)=x'(0)=y(0)=0.\\]</div>`,
`<p><b>1 · Transform both equations.</b> The derivatives disappear in favor of the algebraic unknowns \\(X(s),Y(s)\\):</p><div class="eq">\\[s^2X-2sX+(3s+2)Y=\\frac4s,\\]</div><div class="eq">\\[-sX+(2s+3)Y=0.\\]</div><p><b>Why this helps.</b> We now solve a 2-by-2 simultaneous algebra problem instead of two coupled differential equations.</p><p>From the second equation, \\(sX=(2s+3)Y\\). Substitution into the first and simplification gives</p><div class="eq">\\[X(s)=\\frac{4s+6}{s^2(s+2)(s-1)},\\qquad Y(s)=\\frac2{s(s+2)(s-1)}.\\]</div><p>Partial fractions:</p><div class="eq">\\[X=-\\frac7{2s}-\\frac3{s^2}+\\frac1{6(s+2)}+\\frac{10}{3(s-1)},\\]</div><div class="eq">\\[Y=-\\frac1s+\\frac1{3(s+2)}+\\frac2{3(s-1)}.\\]</div><p>Invert term by term:</p><div class="whybox"><div class="eq">\\[\\boxed{x(t)=-\\frac72-3t+\\frac16e^{-2t}+\\frac{10}{3}e^t},\\]</div><div class="eq">\\[\\boxed{y(t)=-1+\\frac13e^{-2t}+\\frac23e^t}.\\]</div></div><p><b>Verification.</b> Both initial values are zero, and direct differentiation/substitution satisfies both original equations.</p>`,'§3.6');

const c34=[
l13Board('O’Neil §3.4 Problem 1',`<p>${l13Book}<br>Use the convolution theorem to determine</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac1{(s^2+4)(s^2-4)}\\right\\}.\\]</div>`,`<p>Think of the transform as a product of \\(1/(s^2+4)\\) and \\(1/(s^2-4)\\), whose inverses are \\(\\tfrac12\\sin2t\\) and \\(\\tfrac12\\sinh2t\\). Thus the inverse is their convolution. To evaluate cleanly, the same product also decomposes as</p><div class="eq">\\[\\frac1{(s^2+4)(s^2-4)}=-\\frac1{8(s^2+4)}+\\frac1{8(s^2-4)}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{f(t)=\\frac1{16}(\\sinh2t-\\sin2t)}.\\]</div></div>`,'§3.4'),
l13Board('O’Neil §3.4 Problem 2',`<p>${l13Book}<br>Determine</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac{e^{-2s}}{s^2+16}\\right\\}.\\]</div>`,`<p>The undelayed factor has inverse \\(\\tfrac14\\sin4t\\). The factor \\(e^{-2s}\\) delays the entire response by 2:</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=\\frac14H(t-2)\\sin(4(t-2))}.\\]</div></div><p>This is also consistent with the convolution viewpoint: multiplication in the \\(s\\)-domain corresponds to combining time-domain responses.</p>`,'§3.4'),
l13Board('O’Neil §3.4 Problem 3',`<p>${l13Book}<br>For positive constants \\(a,b\\), determine</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac{s}{(s^2+a^2)(s^2+b^2)}\\right\\}.\\]</div>`,`<p>Use the product \\(1/(s^2+a^2)\\cdot s/(s^2+b^2)\\). Its inverse is</p><div class="eq">\\[\\frac1a\\sin(at)*\\cos(bt).\\]</div><p>For \\(a\\ne b\\), an equivalent partial-fraction evaluation gives</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=\\frac{\\cos(at)-\\cos(bt)}{b^2-a^2}}.\\]</div></div><p>If \\(a=b\\), take the limit \\(b\\to a\\), giving \\(f(t)=t\\sin(at)/(2a)\\). Stating the coincident-frequency case avoids silently dividing by zero.</p>`,'§3.4'),
l13Board('O’Neil §3.4 Problem 4',`<p>${l13Book}<br>Determine</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac{s^2}{(s-3)(s^2+5)}\\right\\}.\\]</div>`,`<p>Decompose into one exponential pole and one quadratic block:</p><div class="eq">\\[\\frac{s^2}{(s-3)(s^2+5)}=\\frac{9}{14(s-3)}+\\frac{5s+15}{14(s^2+5)}.\\]</div><p>Now use \\(\\mathcal L^{-1}\\{s/(s^2+a^2)\\}=\\cos at\\) and \\(\\mathcal L^{-1}\\{1/(s^2+a^2)\\}=\\sin(at)/a\\):</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=\\frac9{14}e^{3t}+\\frac5{14}\\cos(\\sqrt5t)+\\frac{15}{14\\sqrt5}\\sin(\\sqrt5t)}.\\]</div></div>`,'§3.4'),
l13Board('O’Neil §3.4 Problem 5',`<p>${l13Book}<br>For \\(a>0\\), determine</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac1{s(s^2+a^2)^2}\\right\\}.\\]</div>`,`<p>One convolution route is \\(1*\\mathcal L^{-1}\\{1/(s^2+a^2)^2\\}\\). For evaluation, expose standard pieces:</p><div class="eq">\\[\\frac1{s(s^2+a^2)^2}=\\frac1{a^4s}-\\frac{s}{a^4(s^2+a^2)}-\\frac{s}{a^2(s^2+a^2)^2}.\\]</div><p>Use \\(\\mathcal L^{-1}\\{s/(s^2+a^2)^2\\}=t\\sin(at)/(2a)\\):</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=\\frac{1-\\cos(at)}{a^4}-\\frac{t\\sin(at)}{2a^3}}.\\]</div></div>`,'§3.4'),
l13Board('O’Neil §3.4 Problem 6',`<p>${l13Book}<br>Determine</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac1{s^4(s-5)}\\right\\}.\\]</div>`,`<p>The convolution theorem immediately gives</p><div class="eq">\\[f(t)=\\int_0^t\\frac{(t-\\tau)^3}{6}e^{5\\tau}d\\tau.\\]</div><p>Evaluating that integral, or equivalently decomposing the transform, yields</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=\\frac{e^{5t}-1}{625}-\\frac{t}{125}-\\frac{t^2}{50}-\\frac{t^3}{30}}.\\]</div></div><p>The polynomial terms are exactly what cancel the first few terms of the exponential expansion near \\(t=0\\), consistent with the four powers of \\(s\\) in the denominator.</p>`,'§3.4'),
l13Board('O’Neil §3.4 Problem 7',`<p>${l13Book}<br>Determine</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac{e^{-4s}}{s(s+2)}\\right\\}.\\]</div>`,`<p>First invert the undelayed factor:</p><div class="eq">\\[\\frac1{s(s+2)}=\\frac12\\left(\\frac1s-\\frac1{s+2}\\right)\\Longrightarrow g(t)=\\frac12(1-e^{-2t}).\\]</div><p>Then delay by 4:</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=\\frac12H(t-4)\\left(1-e^{-2(t-4)}\\right)}.\\]</div></div>`,'§3.4'),
l13Board('O’Neil §3.4 Problem 8',`<p>${l13Book}<br>Determine</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac2{s^2(s^2+5)}\\right\\}.\\]</div>`,`<p>Separate the two quadratic factors:</p><div class="eq">\\[\\frac2{s^2(s^2+5)}=\\frac{2}{5s^2}-\\frac{2}{5(s^2+5)}.\\]</div><p>Invert:</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=\\frac25t-\\frac{2}{5\\sqrt5}\\sin(\\sqrt5t)}.\\]</div></div>`,'§3.4')
];
const c34ivp=[
l13Board('O’Neil §3.4 Problem 9',`<p>${l13Book}<br>Use convolution to write a formula for</p><div class="eq">\\[y''-5y'+6y=f(t),\\qquad y(0)=y'(0)=0.\\]</div>`,`<p>Zero initial data give</p><div class="eq">\\[(s-2)(s-3)Y=F.\\]</div><p>The transfer factor is</p><div class="eq">\\[G(s)=\\frac1{(s-2)(s-3)}=-\\frac1{s-2}+\\frac1{s-3}.\\]</div><p>So the impulse response is \\(g(t)=e^{3t}-e^{2t}\\), and</p><div class="whybox"><div class="eq">\\[\\boxed{y(t)=(e^{3t}-e^{2t})*f(t)=\\int_0^t[e^{3(t-\\tau)}-e^{2(t-\\tau)}]f(\\tau)d\\tau}.\\]</div></div>`,'§3.4'),
l13Board('O’Neil §3.4 Problem 10',`<p>${l13Book}<br>Write the convolution solution of</p><div class="eq">\\[y''+10y'+24y=f(t),\\quad y(0)=1,\\ y'(0)=0.\\]</div>`,`<p>Transforming gives</p><div class="eq">\\[(s+4)(s+6)Y-(s+10)=F.\\]</div><p>The initial-condition part is</p><div class="eq">\\[\\frac{s+10}{(s+4)(s+6)}=\\frac3{s+4}-\\frac2{s+6},\\]</div><p>and the impulse-response factor is</p><div class="eq">\\[G=\\frac1{(s+4)(s+6)}=\\frac12\\left(\\frac1{s+4}-\\frac1{s+6}\\right).\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y=3e^{-4t}-2e^{-6t}+\\frac12(e^{-4t}-e^{-6t})*f}.\\]</div></div>`,'§3.4'),
l13Board('O’Neil §3.4 Problem 11',`<p>${l13Book}<br>Write the convolution solution of</p><div class="eq">\\[y''-8y'+12y=f(t),\\quad y(0)=-3,\\ y'(0)=2.\\]</div>`,`<p>Transforming carefully:</p><div class="eq">\\[(s-2)(s-6)Y+3s-26=F,\\]</div><div class="eq">\\[Y=\\frac{-3s+26}{(s-2)(s-6)}+\\frac{F}{(s-2)(s-6)}.\\]</div><p>The natural part is \\(-5e^{2t}+2e^{6t}\\); the impulse response is \\(\\tfrac14(e^{6t}-e^{2t})\\). Therefore</p><div class="whybox"><div class="eq">\\[\\boxed{y=-5e^{2t}+2e^{6t}+\\frac14(e^{6t}-e^{2t})*f}.\\]</div></div><p>Check at \\(t=0\\): \\(y=-3\\), \\(y'=2\\).</p>`,'§3.4'),
l13Board('O’Neil §3.4 Problem 12',`<p>${l13Book}<br>Write the convolution solution of</p><div class="eq">\\[y''-4y'-5y=f(t),\\quad y(0)=2,\\ y'(0)=1.\\]</div>`,`<p>The transformed equation is</p><div class="eq">\\[(s-5)(s+1)Y-2s+7=F.\\]</div><p>The initial-condition response is \\(\\tfrac12e^{5t}+\\tfrac32e^{-t}\\), while</p><div class="eq">\\[G(s)=\\frac1{(s-5)(s+1)}=\\frac16\\left(\\frac1{s-5}-\\frac1{s+1}\\right).\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y=\\frac12e^{5t}+\\frac32e^{-t}+\\frac16(e^{5t}-e^{-t})*f}.\\]</div></div>`,'§3.4'),
l13Board('O’Neil §3.4 Problem 13',`<p>${l13Book}<br>Write the convolution solution of</p><div class="eq">\\[y''+9y=f(t),\\quad y(0)=-1,\\ y'(0)=1.\\]</div>`,`<p>Transform:</p><div class="eq">\\[(s^2+9)Y+s-1=F.\\]</div><p>Thus the natural response is \\(-\\cos3t+\\tfrac13\\sin3t\\), and the impulse response is \\(g(t)=\\tfrac13\\sin3t\\):</p><div class="whybox"><div class="eq">\\[\\boxed{y=-\\cos3t+\\frac13\\sin3t+\\frac13\\sin3t*f}.\\]</div></div>`,'§3.4'),
l13Board('O’Neil §3.4 Problem 14',`<p>${l13Book}<br>For \\(k>0\\), write the convolution solution of</p><div class="eq">\\[y''-k^2y=f(t),\\quad y(0)=2,\\ y'(0)=-4.\\]</div>`,`<p>Transforming gives</p><div class="eq">\\[(s^2-k^2)Y-2s+4=F.\\]</div><p>The homogeneous initial-condition response is</p><div class="eq">\\[2\\cosh(kt)-\\frac4k\\sinh(kt).\\]</div><p>Because \\(\\mathcal L^{-1}\\{1/(s^2-k^2)\\}=\\sinh(kt)/k\\),</p><div class="whybox"><div class="eq">\\[\\boxed{y=2\\cosh(kt)-\\frac4k\\sinh(kt)+\\frac1k\\sinh(kt)*f}.\\]</div></div>`,'§3.4'),
l13Board('O’Neil §3.4 Problem 15',`<p>${l13Book}<br>Write the convolution solution of</p><div class="eq">\\[y'''-y''-4y'+4y=f(t),\\]</div><div class="eq">\\[y(0)=y'(0)=1,\\qquad y''(0)=0.\\]</div>`,`<p>The characteristic factor is</p><div class="eq">\\[s^3-s^2-4s+4=(s-1)(s-2)(s+2).\\]</div><p>Transforming all derivatives gives</p><div class="eq">\\[(s-1)(s-2)(s+2)Y-s^2+5=F.\\]</div><p>The natural response is</p><div class="eq">\\[\\frac43e^t-\\frac14e^{2t}-\\frac1{12}e^{-2t}.\\]</div><p>The impulse response is</p><div class="eq">\\[g(t)=-\\frac13e^t+\\frac14e^{2t}+\\frac1{12}e^{-2t}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y=\\frac43e^t-\\frac14e^{2t}-\\frac1{12}e^{-2t}+g*f}.\\]</div></div><p>Checking \\(y(0),y'(0),y''(0)\\) returns \\(1,1,0\\).</p>`,'§3.4'),
l13Board('O’Neil §3.4 Problem 16',`<p>${l13Book}<br>With all initial data zero, write the convolution solution of</p><div class="eq">\\[y^{(4)}-11y''+18y=f(t).\\]</div>`,`<p>Zero initial data make the transfer function simply the reciprocal of the characteristic polynomial:</p><div class="eq">\\[G(s)=\\frac1{s^4-11s^2+18}=\\frac1{(s^2-2)(s^2-9)}.\\]</div><p>Separate the quadratic factors:</p><div class="eq">\\[G=-\\frac1{7(s^2-2)}+\\frac1{7(s^2-9)}.\\]</div><p>Therefore</p><div class="eq">\\[g(t)=-\\frac1{7\\sqrt2}\\sinh(\\sqrt2t)+\\frac1{21}\\sinh3t.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y(t)=g*f}.\\]</div></div>`,'§3.4')
];
const c35=[
l13Board('O’Neil §3.5 Problem 1',`<p>${l13Book}<br>Solve and graph</p><div class="eq">\\[y''+5y'+6y=3\\delta(t-2)-4\\delta(t-5),\\quad y(0)=y'(0)=0.\\]</div>`,`<p>The zero-state impulse response of \\(D^2+5D+6\\) is</p><div class="eq">\\[g(t)=\\mathcal L^{-1}\\left\\{\\frac1{(s+2)(s+3)}\\right\\}=e^{-2t}-e^{-3t}.\\]</div><p>Linearity means each delayed impulse launches a scaled delayed copy of \\(g\\):</p><div class="whybox"><div class="eq">\\[\\boxed{y=3H(t-2)[e^{-2(t-2)}-e^{-3(t-2)}]-4H(t-5)[e^{-2(t-5)}-e^{-3(t-5)}]}.\\]</div></div><p>The graph is zero until 2, receives a positive transient there, then receives a negative transient at 5.</p>`,'§3.5'),
l13Board('O’Neil §3.5 Problem 2',`<p>${l13Book}<br>Solve and graph</p><div class="eq">\\[y''-4y'+13y=4\\delta(t-3),\\quad y(0)=y'(0)=0.\\]</div>`,`<p>Complete the square:</p><div class="eq">\\[s^2-4s+13=(s-2)^2+9.\\]</div><p>The impulse response is \\(g(t)=\\tfrac13e^{2t}\\sin3t\\). Delay to \\(t=3\\) and scale by 4:</p><div class="whybox"><div class="eq">\\[\\boxed{y(t)=\\frac43H(t-3)e^{2(t-3)}\\sin(3(t-3))}.\\]</div></div><p>The positive exponential envelope shows this system is unstable even though the impulse occurs only once.</p>`,'§3.5'),
l13Board('O’Neil §3.5 Problem 3',`<p>${l13Book}<br>Solve and graph</p><div class="eq">\\[y'''+4y''+5y'+2y=6\\delta(t),\\quad y(0)=y'(0)=y''(0)=0.\\]</div>`,`<p>With zero initial data and \\(\\mathcal L\\{\\delta(t)\\}=1\\),</p><div class="eq">\\[Y=\\frac6{s^3+4s^2+5s+2}=\\frac6{(s+1)^2(s+2)}.\\]</div><p>Decompose:</p><div class="eq">\\[Y=\\frac6{s+2}-\\frac6{s+1}+\\frac6{(s+1)^2}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y(t)=6e^{-2t}-6e^{-t}+6te^{-t}}.\\]</div></div>`,'§3.5'),
l13Board('O’Neil §3.5 Problem 4',`<p>${l13Book}<br>Solve and graph, with \\(a=5\\pi/8\\):</p><div class="eq">\\[y''+6y'=12\\delta(t-a),\\quad y(0)=3,\\ y'(0)=0.\\]</div>`,`<p>The initial value \\(y(0)=3\\) contributes the constant response 3. The impulse channel has transfer</p><div class="eq">\\[\\frac{12}{s(s+6)}=2\\left(\\frac1s-\\frac1{s+6}\\right).\\]</div><p>Delay it to \\(a=5\\pi/8\\):</p><div class="whybox"><div class="eq">\\[\\boxed{y(t)=3+2H(t-a)\\left(1-e^{-6(t-a)}\\right),\\qquad a=\\frac{5\\pi}{8}}.\\]</div></div>`,'§3.5'),
l13Board('O’Neil §3.5 Problem 5',`<p>${l13Book}<br>Solve and graph</p><div class="eq">\\[y''+5y'+6y=B\\delta(t),\\quad y(0)=3,\\ y'(0)=0.\\]</div>`,`<p>Transform formally with \\(\\mathcal L\\{\\delta(t)\\}=1\\):</p><div class="eq">\\[(s+2)(s+3)Y=3s+15+B.\\]</div><p>Separate the ordinary initial response from the impulse contribution:</p><div class="eq">\\[Y=\\frac9{s+2}-\\frac6{s+3}+B\\left(\\frac1{s+2}-\\frac1{s+3}\\right).\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y(t)=(9+B)e^{-2t}-(6+B)e^{-3t}}.\\]</div></div><p>The right derivative at \\(0^+\\) is \\(B\\): the impulse changes velocity instantaneously. That is the physical role of an impulse applied exactly at the initial time.</p>`,'§3.5'),
l13Board('O’Neil §3.5 Problem 6 — filtering property',`<p>${l13Book}<br>For continuous \\(f\\), derive</p><div class="eq">\\[\\int_0^\\infty f(t)\\delta(t-a)dt=f(a)\\]</div><p>from the rectangular-pulse approximation to \\(\\delta(t-a)\\).</p>`,`<p>Replace the delta by the width-\\(\\varepsilon\\), height-\\(1/\\varepsilon\\) pulse:</p><div class="eq">\\[\\delta_\\varepsilon(t-a)=\\frac1\\varepsilon[H(t-a)-H(t-a-\\varepsilon)].\\]</div><p>Then</p><div class="eq">\\[\\int_0^\\infty f(t)\\delta_\\varepsilon(t-a)dt=\\frac1\\varepsilon\\int_a^{a+\\varepsilon}f(t)dt.\\]</div><p>This is the average value of \\(f\\) on a shrinking interval beginning at \\(a\\). Continuity implies that average tends to \\(f(a)\\):</p><div class="whybox"><div class="eq">\\[\\boxed{\\int_0^\\infty f(t)\\delta(t-a)dt=f(a)}.\\]</div></div><p>This is why the delta is called a sampling or filtering distribution.</p>`,'§3.5')
];
const c36=[
l13Board('O’Neil §3.6 Problem 1',`<p>${l13Book}<br>Solve</p><div class="eq">\\[x'-2y'=1,\\qquad x'+y-x=0,\\qquad x(0)=y(0)=0.\\]</div>`,`<p>Transform:</p><div class="eq">\\[sX-2sY=\\frac1s,\\qquad (s-1)X+Y=0.\\]</div><p>From the second, \\(Y=-(s-1)X\\). Substitute into the first:</p><div class="eq">\\[sX[1+2(s-1)]=sX(2s-1)=\\frac1s.\\]</div><p>Thus</p><div class="eq">\\[X=\\frac1{s^2(2s-1)}=\\frac4{2s-1}-\\frac2s-\\frac1{s^2},\\]</div><div class="eq">\\[Y=\\frac2{2s-1}-\\frac1s-\\frac1{s^2}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{x=-t+2e^{t/2}-2,\\qquad y=-t+e^{t/2}-1}.\\]</div></div>`,'§3.6'),
l13Board('O’Neil §3.6 Problem 2',`<p>${l13Book}<br>Solve</p><div class="eq">\\[2x'-3y+y'=0,\\qquad x'+y'=t,\\qquad x(0)=y(0)=0.\\]</div>`,`<p>Transform:</p><div class="eq">\\[2sX+(s-3)Y=0,\\qquad sX+sY=\\frac1{s^2}.\\]</div><p>Solving the two algebraic equations gives</p><div class="eq">\\[X=\\frac{3-s}{s^3(s+3)},\\qquad Y=\\frac2{s^2(s+3)}.\\]</div><p>Partial fractions and inversion yield</p><div class="whybox"><div class="eq">\\[\\boxed{x=\\frac12t^2-\\frac23t+\\frac29-\\frac29e^{-3t}},\\]</div><div class="eq">\\[\\boxed{y=\\frac23t-\\frac29+\\frac29e^{-3t}}.\\]</div></div><p>Differentiate and substitute: the first equation reduces to 0 and the second to \\(t\\).</p>`,'§3.6'),
l13Board('O’Neil §3.6 Problem 3',`<p>${l13Book}<br>Solve</p><div class="eq">\\[x'+2y'-y=1,\\qquad 2x'+y=0,\\qquad x(0)=y(0)=0.\\]</div>`,`<p>Transform:</p><div class="eq">\\[sX+(2s-1)Y=\\frac1s,\\qquad 2sX+Y=0.\\]</div><p>Solving gives</p><div class="eq">\\[X=-\\frac1{s^2(4s-3)},\\qquad Y=\\frac2{s(4s-3)}.\\]</div><p>After partial fractions,</p><div class="whybox"><div class="eq">\\[\\boxed{x=\\frac t3-\\frac49e^{3t/4}+\\frac49,\\qquad y=\\frac23e^{3t/4}-\\frac23}.\\]</div></div><p>Direct substitution checks both equations and both zero initial values.</p>`,'§3.6'),
l13Board('O’Neil §3.6 Problem 4',`<p>${l13Book}<br>Solve</p><div class="eq">\\[x'+y'-x=\\cos t,\\qquad x'+2y'=0,\\qquad x(0)=y(0)=0.\\]</div>`,`<p>Transform:</p><div class="eq">\\[(s-1)X+sY=\\frac{s}{s^2+1},\\qquad sX+2sY=0.\\]</div><p>Solving and decomposing gives inverses</p><div class="whybox"><div class="eq">\\[\\boxed{x=\\frac45e^{2t}+\\frac25\\sin t-\\frac45\\cos t},\\]</div><div class="eq">\\[\\boxed{y=-\\frac25e^{2t}-\\frac15\\sin t+\\frac25\\cos t}.\\]</div></div><p>At \\(t=0\\), both are zero. Differentiation verifies \\(x'+2y'=0\\) and \\(x'+y'-x=\\cos t\\).</p>`,'§3.6')
];

const l13TransferMastery=[
l13Board('Transfer 1 — convolution without a textbook label',`<p>${l13Explain}</p><p>Find the zero-state response whose transform is</p><div class="eq">\\[Y(s)=\\frac1{(s+1)(s+2)}.\\]</div><p>Explain both the convolution interpretation and the final closed form.</p>`,`<p>Write \\(Y=F G\\) with \\(F=1/(s+1)\\), \\(G=1/(s+2)\\). Then \\(f=e^{-t}\\), \\(g=e^{-2t}\\), so</p><div class="eq">\\[y=(f*g)(t)=\\int_0^t e^{-(t-\\tau)}e^{-2\\tau}d\\tau.\\]</div><p>Factor out \\(e^{-t}\\):</p><div class="eq">\\[y=e^{-t}\\int_0^t e^{-\\tau}d\\tau=e^{-t}(1-e^{-t}).\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y=e^{-t}-e^{-2t}}.\\]</div></div><p>Partial fractions give the same answer, which is a useful independent check.</p>`,'Original course transfer'),
l13Board('Transfer 2 — build the transfer function before solving',`<p>${l13Explain}</p><p>For the zero-initial-condition system</p><div class="eq">\\[y''+4y'+5y=f(t),\\]</div><p>find the transfer function and impulse response.</p>`,`<p>With zero initial data, transformation gives</p><div class="eq">\\[(s^2+4s+5)Y=F.\\]</div><p>Therefore</p><div class="eq">\\[G(s)=\\frac{Y}{F}=\\frac1{(s+2)^2+1}.\\]</div><p>Invert the shifted sine transform:</p><div class="whybox"><div class="eq">\\[\\boxed{g(t)=e^{-2t}\\sin t}.\\]</div></div><p>The poles \\(-2\\pm i\\) have negative real part, so the impulse response decays while oscillating.</p>`,'Original course transfer'),
l13Board('Transfer 3 — delayed impulse through a known system',`<p>${l13Explain}</p><p>The system in Transfer 2 is struck by \\(3\\delta(t-2)\\). With zero initial data, determine the output.</p>`,`<p>The input transform is \\(F(s)=3e^{-2s}\\). Hence</p><div class="eq">\\[Y=3e^{-2s}G(s).\\]</div><p>Since \\(g(t)=e^{-2t}\\sin t\\), the second shifting theorem gives</p><div class="whybox"><div class="eq">\\[\\boxed{y(t)=3H(t-2)e^{-2(t-2)}\\sin(t-2)}.\\]</div></div><p>Causality check: the output is exactly zero before the impulse arrives.</p>`,'Original course transfer'),
l13Board('Transfer 4 — what an impulse makes jump',`<p>${l13Explain}</p><p>Suppose \\(y\\) satisfies</p><div class="eq">\\[y''+ay'+by=J\\delta(t-t_0).\\]</div><p>Assume \\(y\\) remains finite and continuous through \\(t_0\\). Determine the jump in \\(y'\\).</p>`,`<p>Integrate the ODE from \\(t_0-\\varepsilon\\) to \\(t_0+\\varepsilon\\). Then</p><div class="eq">\\[y'(t_0+)-y'(t_0-)+a[y(t_0+)-y(t_0-)]+b\\int y\\,dt=J.\\]</div><p>Continuity makes the middle jump zero, and the bounded integral tends to zero as \\(\\varepsilon\\to0\\). Therefore</p><div class="whybox"><div class="eq">\\[\\boxed{y'(t_0+)-y'(t_0-)=J}.\\]</div></div><p>This is the time-domain physical meaning of an ideal impulse in a unit-leading-coefficient second-order model.</p>`,'Original course transfer'),
l13Board('Transfer 5 — coupled system by Laplace',`<p>${l13Explain}</p><p>Solve</p><div class="eq">\\[x'+y=0,\\qquad y'-x=0,\\qquad x(0)=1,\\ y(0)=0.\\]</div>`,`<p>Transform both equations:</p><div class="eq">\\[sX-1+Y=0,\\qquad sY-X=0.\\]</div><p>From the second, \\(X=sY\\). Substitute into the first:</p><div class="eq">\\[(s^2+1)Y=1.\\]</div><p>Hence</p><div class="eq">\\[Y=\\frac1{s^2+1},\\qquad X=\\frac{s}{s^2+1}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{x=\\cos t,\\qquad y=\\sin t}.\\]</div></div><p>Direct differentiation verifies both equations and both initial conditions.</p>`,'Original course transfer'),
l13Board('Transfer 6 — diagnose the representation',`<p>${l13Explain}</p><p>A zero-state LTI model has \\(G(s)=1/(s+3)\\) and input \\(f(t)\\). A student writes \\(y(t)=e^{-3t}f(t)\\). Diagnose the error and give the correct formula.</p>`,`<p>Multiplication in the \\(s\\)-domain becomes <b>convolution</b>, not pointwise multiplication, in time. Since \\(g(t)=e^{-3t}\\),</p><div class="whybox"><div class="eq">\\[\\boxed{y(t)=(g*f)(t)=\\int_0^t e^{-3(t-\\tau)}f(\\tau)d\\tau}.\\]</div></div><p>The incorrect expression would generally have a different Laplace transform and ignores the system's memory of earlier input values.</p>`,'Original course transfer')
];

const lesson13Units=[
{id:'l13-map',courseLesson:13,color:'#425d98',badge:'1',label:'Nov. 2 map',title:'From Products in s to Memory in Time',subtitle:'convolution · transfer function · impulse response · delta · systems',desc:'See how the four syllabus topics are one connected Laplace story.',lessons:[{title:'Map',screens:[
{type:'teach',title:'The Nov. 2 syllabus in one picture',html:`<p>${l13Core}</p><p><b>Convolution</b> tells us what a product \\(F(s)G(s)\\) means in time. A <b>transfer function</b> isolates how a zero-initial-condition system maps input to output. Its inverse transform is the <b>impulse response</b>. The <b>Dirac delta</b> is the ideal input used to reveal that response directly. Finally, for <b>systems of ODEs</b>, Laplace turns every derivative equation into simultaneous algebraic equations.</p>`},
{type:'teach',title:'The central input-output equation',html:`<p>${l13Explain}</p><p>For a <b>linear time-invariant (LTI)</b> system with zero initial conditions, suppose transformation gives</p><div class="eq">\\[Y(s)=G(s)F(s).\\]</div><p>Here \\(F\\) represents the input, \\(G\\) is the transfer function, and \\(Y\\) is the output. In time, multiplication becomes convolution:</p><div class="whybox"><div class="eq">\\[\\boxed{y(t)=(g*f)(t)},\\qquad g=\\mathcal L^{-1}\\{G\\}.\\]</div></div><p>So the output at time \\(t\\) is built from the whole earlier input history, weighted by the system response \\(g\\).</p>`},
{type:'quiz',title:'Connect the ideas',q:'If Y(s)=G(s)F(s), what is the zero-state time-domain output?',options:['g*f','g+f','g/f'],answer:0,why:'The convolution theorem converts products of Laplace transforms into time-domain convolution.'}
]}]},
{id:'l13-convolution',courseLesson:13,color:'#317c74',badge:'2',label:'Convolution',title:'Convolution: Why a Product of Transforms Becomes an Integral',subtitle:'definition · theorem · commutativity · textbook examples',desc:'Build the convolution integral from meaning before using it as a transform shortcut.',lessons:[{title:'Concept and examples',screens:[
{type:'teach',title:'What convolution is actually doing',html:`<p>${l13Explain}</p><p>Define</p><div class="eq">\\[(f*g)(t)=\\int_0^t f(t-\\tau)g(\\tau)d\\tau.\\]</div><p>For every past time \\(\\tau\\), the value \\(g(\\tau)\\) contributes to the present, weighted by how much time \\(t-\\tau\\) has elapsed through \\(f(t-\\tau)\\). The integral adds all those past contributions.</p><p>A change of variable shows \\(f*g=g*f\\). The formula may look asymmetric, but the operation is commutative.</p>`},
{type:'teach',title:'Why the convolution theorem is plausible',html:`<p>Starting from the convolution integral and taking a Laplace transform creates a double integral over the triangle \\(0\\le\\tau\\le t<\\infty\\). Reversing the order and setting \\(u=t-\\tau\\) separates that double integral into</p><div class="eq">\\[\\left(\\int_0^\\infty e^{-su}f(u)du\\right)\\left(\\int_0^\\infty e^{-s\\tau}g(\\tau)d\\tau\\right)=F(s)G(s).\\]</div><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L\\{f*g\\}=FG,\\qquad \\mathcal L^{-1}\\{FG\\}=f*g}.\\]</div></div>`},
l13Clone(l13Ex313),
{type:'teach',title:'O’Neil Example 3.15 — convolution inside an integral equation',html:`<p>${l13Book}</p><p>O’Neil considers</p><div class="eq">\\[f(t)=2t^2+\\int_0^t f(t-\\tau)e^{-\\tau}d\\tau.\\]</div><p>The integral is \\(f*e^{-t}\\). Transforming turns the unknown convolution into multiplication:</p><div class="eq">\\[F=\\frac4{s^3}+\\frac{F}{s+1}.\\]</div><p>Solving algebraically gives \\(F=4/s^3+4/s^4\\), so</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=2t^2+\\frac23t^3}.\\]</div></div><p>This example shows convolution is not only for ODEs; it also untangles integral equations.</p>`},
{type:'quiz',title:'Why τ and t−τ?',q:'In (f*g)(t)=∫₀ᵗ f(t−τ)g(τ)dτ, what does τ represent?',options:['A past time being accumulated','A new Laplace variable','Only the final time'],answer:0,why:'The convolution adds contributions from every past time τ between 0 and the present t.'}
]}]},
{id:'l13-conv-practice',courseLesson:13,color:'#4b7488',badge:'3',label:'§3.4 inverse practice',title:'O’Neil §3.4 Problems 1–8',subtitle:'authentic textbook convolution practice',desc:'Work every inverse-transform convolution problem from the first block of §3.4.',lessons:[{title:'Book Problems 1–8',screens:[...c34.map(l13Clone)]}]},
{id:'l13-transfer',courseLesson:13,color:'#9a6336',badge:'4',label:'Transfer & impulse response',title:'Transfer Function and Impulse Response',subtitle:'zero-input + zero-state · arbitrary forcing · O’Neil Problems 9–16',desc:'Understand why one kernel can solve an entire family of forcing problems.',lessons:[{title:'System viewpoint',screens:[
{type:'teach',title:'Zero-input and zero-state are different pieces',html:`<p>${l13Explain}</p><p>With nonzero initial conditions, transforming a linear ODE usually gives</p><div class="eq">\\[Y(s)=Y_{zi}(s)+G(s)F(s).\\]</div><p><b>Zero-input response</b> \\(Y_{zi}\\) is motion caused by stored initial energy/data with no external forcing. <b>Zero-state response</b> \\(G F\\) is motion caused by the input when the initial state is zero. Linearity lets us add them.</p>`},
{type:'teach',title:'Why G(s) is called a transfer function',html:`<p>Set all initial conditions to zero and solve algebraically for the ratio</p><div class="eq">\\[\\boxed{G(s)=\\frac{Y(s)}{F(s)}}.\\]</div><p>This ratio depends only on the system coefficients, not on the particular input. Once \\(G\\) is known, every new input \\(F\\) is handled by multiplication in \\(s\\)-space, or convolution with \\(g=\\mathcal L^{-1}G\\) in time.</p>`},
l13Clone(l13Ex314),
...c34ivp.map(l13Clone)
]}]},
{id:'l13-delta',courseLesson:13,color:'#8a4f70',badge:'5',label:'Dirac delta',title:'Impulses and the Dirac Delta',subtitle:'unit area · distribution · transform · delayed impulse',desc:'Build δ from shrinking pulses so the formulas have physical meaning.',lessons:[{title:'From narrow pulse to ideal impulse',screens:[
{type:'teach',title:'An impulse is finite area, not “infinity at one point”',html:`<p>${l13Book}</p><p>O’Neil starts with the rectangular pulse</p><div class="eq">\\[\\delta_\\varepsilon(t)=\\frac1\\varepsilon[H(t)-H(t-\\varepsilon)].\\]</div><p>Its width is \\(\\varepsilon\\), height is \\(1/\\varepsilon\\), and area is exactly 1. As \\(\\varepsilon\\to0^+\\), it becomes narrower and taller while preserving unit area. The limiting \\(\\delta\\) is a <b>distribution</b>, not an ordinary function with a conventional point value.</p>`},
{type:'teach',title:'Derive the Laplace transform of a delayed impulse',html:`<p>For the shifted pulse beginning at \\(a\\),</p><div class="eq">\\[\\mathcal L\\{\\delta_\\varepsilon(t-a)\\}=e^{-as}\\frac{1-e^{-\\varepsilon s}}{\\varepsilon s}.\\]</div><p>As \\(\\varepsilon\\to0\\), the quotient tends to 1 because \\(1-e^{-\\varepsilon s}\\sim\\varepsilon s\\). Therefore</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L\\{\\delta(t-a)\\}=e^{-as}},\\qquad \\boxed{\\mathcal L\\{\\delta(t)\\}=1}.\\]</div></div><p>The same exponential that represented an ordinary time delay now locates an instantaneous impulse at time \\(a\\).</p>`},
{type:'teach',title:'Impulse response is literally the response to δ(t)',html:`<p>For a zero-state system \\(Y=GF\\), choose the input \\(f(t)=\\delta(t)\\). Since \\(F(s)=1\\),</p><div class="eq">\\[Y(s)=G(s).\\]</div><p>Therefore the output is</p><div class="whybox"><div class="eq">\\[y(t)=\\mathcal L^{-1}\\{G(s)\\}=g(t).\\]</div></div><p>That is why \\(g\\) is called the <b>impulse response</b>: the delta input exposes the system's own input-output kernel directly.</p>`},
l13Clone(l13Ex316),
l13Clone(l13Ex317),
{type:'quiz',title:'Area of the approximating pulse',q:'As ε→0, what happens to the area of δε(t)?',options:['It remains 1','It tends to 0','It tends to infinity'],answer:0,why:'Height 1/ε times width ε equals one for every ε>0.'}
]}]},
{id:'l13-delta-practice',courseLesson:13,color:'#744f8e',badge:'6',label:'§3.5 practice',title:'O’Neil §3.5 Problems 1–6',subtitle:'authentic impulse IVPs · filtering property',desc:'Solve every §3.5 exercise, including delayed impulses and the delta sampling identity.',lessons:[{title:'Book Problems 1–6',screens:[
{type:'teach',title:'A fast physical check for impulse IVPs',html:`<p>${l13Explain}</p><p>An impulse has finite integrated effect over essentially zero duration. In a second-order mechanical-style equation, displacement-like variables usually remain continuous while velocity-like derivatives can jump. The transform solution should reflect that. Also check causality: a delayed impulse at \\(a\\) cannot create a response before \\(a\\).</p>`},
...c35.map(l13Clone)
]}]},
{id:'l13-systems',courseLesson:13,color:'#3f6f4c',badge:'7',label:'§3.6 systems',title:'Systems of Linear ODEs by Laplace Transform',subtitle:'differentiate → transform → simultaneous algebra → invert',desc:'Use Laplace as a bridge from coupled ODEs to ordinary linear algebra.',lessons:[{title:'System method and book problems',screens:[
{type:'teach',title:'The systems algorithm — and why it works',html:`<p>${l13Core}</p><p>For each equation: take its Laplace transform, insert the initial values immediately, and denote transforms by capital letters such as \\(X(s),Y(s)\\). You now have simultaneous <b>algebraic</b> equations. Solve those equations for \\(X,Y\\), simplify each into invertible pieces, then transform back.</p><p>The coupling has not disappeared; it has moved from derivatives into algebraic cross-terms such as \\(sX\\) and \\(sY\\), where ordinary elimination is available.</p>`},
l13Clone(l13Ex318),
...c36.map(l13Clone)
]}]},
{id:'l13-mastery',courseLesson:13,color:'#a13f58',badge:'8',label:'Mastery',title:'Nov. 2 Mastery — Transfer, Diagnosis & Verification',subtitle:'6 original transfer problems · no replay of the textbook bank',desc:'A mixed mastery set testing convolution, transfer functions, impulse response, jump behavior, systems, and representation errors without duplicating the O’Neil practice already completed in the lesson.',lessons:[
{title:'Convolution & transfer',screens:l13TransferMastery.slice(0,2)},
{title:'Impulses & physical meaning',screens:l13TransferMastery.slice(2,4)},
{title:'Systems & diagnosis',screens:l13TransferMastery.slice(4,6)}
]}
];
if(!units.some(u=>u&&u.id==='l13-map'))units.push(...lesson13Units);
courseLessons[12]={number:13,title:'Convolution, Impulses & Systems by Laplace',subtitle:'Nov. 2 · O’Neil §§3.4–3.6 · transfer function · impulse response · Dirac delta · linear systems',status:'current'};
if(typeof renderCourseMap==='function')renderCourseMap();
if(typeof render==='function')render();