/* Lesson 21 — Dec. 2: inverses, determinants, row/column evaluation, Cramer's rule. */
const l21Core='<span class="supplementalTag">Core · Dec. 2 syllabus · Part 5</span>',l21Book='<span class="supplementalTag">Authentic textbook · supplied O’Neil §§11.5–11.7</span>',l21Explain='<span class="supplementalTag">Expanded explanation · Lesson 1 depth standard</span>',l21Recon='<span class="supplementalTag">Syllabus-aligned reconstruction · not claimed as an O’Neil example</span>';
function l21Board(title,prompt,solution,section){return {type:'bookproblem',bookSection:section,title,prompt,solution};} function l21Clone(s){return s?{...s,inlineBookPractice:true}:null;}
const l21Inv=l21Board('O’Neil Example 11.24 — inverse by augmentation',`<p>${l21Book}</p><p>Find the inverse of</p><div class="eq">\\[A=\\begin{pmatrix}5&-1\\\\6&8\\end{pmatrix}\\]</div><p>by reducing \\([A|I]\\).</p>`,`<p>Start with</p><div class="eq">\\[\\left[\\begin{array}{cc|cc}5&-1&1&0\\\\6&8&0&1\\end{array}\\right].\\]</div><p>At this point in the lesson we have not yet introduced determinants, so use the row-reduction criterion itself. Reduce \\([A|I]\\); because the left block reaches \\(I\\), the inverse exists, and the right block becomes \\(A^{-1}\\):</p><div class="eq">\\[\\boxed{A^{-1}=\\frac1{46}\\begin{pmatrix}8&1\\\\-6&5\\end{pmatrix}}.\\]</div><p>Independent check:</p><div class="eq">\\[A\\,A^{-1}=\\frac1{46}\\begin{pmatrix}46&0\\\\0&46\\end{pmatrix}=I.\\]</div>`,'§11.5 · Example 11.24');
const l21Det=l21Board('Determinant — cofactor expansion and sign pattern',`<p>${l21Recon}</p><p>Evaluate</p><div class="eq">\\[D=\\begin{vmatrix}2&1&0\\\\3&-1&4\\\\0&5&2\\end{vmatrix}\\]</div><p>using a cofactor expansion along the first row.</p>`,`<p>The first-row signs are \\(+,-,+\\). Therefore</p><div class="eq">\\[D=2\\begin{vmatrix}-1&4\\\\5&2\\end{vmatrix}-1\\begin{vmatrix}3&4\\\\0&2\\end{vmatrix}+0.\\]</div><div class="eq">\\[=2((-1)(2)-20)-(6)=2(-22)-6=\\boxed{-50}.\\]</div><p>A determinant is a scalar, not a matrix. Its sign and magnitude encode oriented volume scaling; most importantly here, \\(D\\ne0\\) means the matrix is nonsingular.</p>`,'§11.6 determinants');
const l21Row=l21Board('Determinant by row operations — track every change',`<p>${l21Recon}</p><p>Evaluate</p><div class="eq">\\[\\det A,\\quad A=\\begin{pmatrix}1&2&3\\\\2&5&8\\\\0&1&2\\end{pmatrix}\\]</div><p>using row operations.</p>`,`<p>Use replacement operations, which do <b>not</b> change the determinant:</p><div class="eq">\\[R_2\\leftarrow R_2-2R_1\\Rightarrow\\begin{pmatrix}1&2&3\\\\0&1&2\\\\0&1&2\\end{pmatrix}.\\]</div><p>Then</p><div class="eq">\\[R_3\\leftarrow R_3-R_2\\Rightarrow\\begin{pmatrix}1&2&3\\\\0&1&2\\\\0&0&0\\end{pmatrix}.\\]</div><p>A zero row makes the determinant zero:</p><div class="eq">\\[\\boxed{\\det A=0}.\\]</div><p>This also proves \\(A\\) is singular, so it cannot have an inverse.</p>`,'§11.6.1 row/column evaluation');
const l21Cramer=l21Board('O’Neil §11.7 method — Cramer’s rule',`<p>${l21Book}</p><p>Solve</p><div class="eq">\\[\\begin{aligned}2x+y&=5,\\\\x-y&=1\\end{aligned}\\]</div><p>using Cramer’s rule.</p>`,`<p>Here</p><div class="eq">\\[A=\\begin{pmatrix}2&1\\\\1&-1\\end{pmatrix},\\qquad B=\\begin{pmatrix}5\\\\1\\end{pmatrix},\\qquad |A|=-3.\\]</div><p>Because \\(|A|\\ne0\\), the solution is unique. Replace column 1 by \\(B\\):</p><div class="eq">\\[D_1=\\begin{vmatrix}5&1\\\\1&-1\\end{vmatrix}=-6,\\qquad x=D_1/D=2.\\]</div><p>Replace column 2:</p><div class="eq">\\[D_2=\\begin{vmatrix}2&5\\\\1&1\\end{vmatrix}=-3,\\qquad y=D_2/D=1.\\]</div><div class="eq">\\[\\boxed{(x,y)=(2,1)}.\\]</div><p>Direct substitution checks both equations.</p>`,'§11.7 Cramer’s rule');
const l21Links=l21Board('Invertibility links — connect the whole lesson',`<p>${l21Recon}</p><p>For a square \\(n\\times n\\) matrix \\(A\\), explain the connection among \\(A^{-1}\\), \\(\\det A\\), rank, and uniqueness of \\(AX=B\\).</p>`,`<p>These statements are equivalent:</p><div class="eq">\\[A^{-1}\\text{ exists}\\iff\\det A\\ne0\\iff\\operatorname{rank}(A)=n.\\]</div><p>When they hold, every right-hand side \\(B\\) has exactly one solution:</p><div class="eq">\\[\\boxed{X=A^{-1}B}.\\]</div><p>Cramer’s rule is then also valid because its denominator \\(\\det A\\) is nonzero. If \\(\\det A=0\\), the matrix is singular: depending on \\(B\\), a nonhomogeneous system may have no solution or infinitely many, but never a unique solution.</p>`,'§§11.5–11.7 synthesis');
const lesson21Units=[
{id:'l21-map',courseLesson:21,color:'#476a91',badge:'1',label:'Dec. 2 map',title:'Inverses, Determinants & Cramer’s Rule',subtitle:'invertibility · determinant · unique solutions',desc:'Connect row reduction to the algebra of square matrices.',lessons:[{title:'Map',screens:[{type:'teach',title:'Textbook numbering reconciliation',html:`<p>${l21Core}</p><p>The syllabus calls this O’Neil §§6.5–6.7. In the supplied 8th SI edition the matching material is <b>§11.5 Matrix Inverses</b>, <b>§11.6 Determinants</b> (including §11.6.1 row/column evaluation), and <b>§11.7 Cramer’s Rule</b>.</p>`},{type:'teach',title:'One theme connects all three topics',html:`<p>${l21Explain}</p><p>This lesson will connect four tests for a square matrix: whether an inverse exists, whether row reduction gives full rank, whether every system \\(AX=B\\) has a unique solution, and—<b>after determinants are defined later in this lesson</b>—whether the determinant is nonzero. For now, use only the row-reduction/inverse ideas already taught; the determinant criterion will be justified after the determinant section.</p>`}]}]},
{id:'l21-inv',courseLesson:21,color:'#34776e',badge:'2',label:'Inverse',title:'Matrix Inverses',subtitle:'AA⁻¹ = I · singular vs nonsingular',desc:'Understand what an inverse means before computing one.',lessons:[{title:'Inverse',screens:[{type:'teach',title:'Definition and uniqueness',html:`<p>${l21Book}</p><p>For square \\(A\\), an inverse is a matrix \\(A^{-1}\\) satisfying</p><div class="eq">\\[AA^{-1}=A^{-1}A=I.\\]</div><p>If it exists it is unique. A matrix with an inverse is <b>nonsingular</b>; one without an inverse is <b>singular</b>.</p>`},l21Clone(l21Inv)]}]},
{id:'l21-aug',courseLesson:21,color:'#795d9a',badge:'3',label:'Compute inverse',title:'Finding A⁻¹ by Row Reduction',subtitle:'[A|I] → [I|A⁻¹]',desc:'See why one augmented reduction computes all inverse columns.',lessons:[{title:'Augmentation',screens:[{type:'teach',title:'Why [A|I] works',html:`<p>${l21Explain}</p><p>Row operations correspond to left multiplication by elementary matrices. If their combined effect turns \\(A\\) into \\(I\\), the same operations turn \\(I\\) into the matrix that reverses \\(A\\). Thus</p><div class="eq">\\[[A|I]\\longrightarrow[I|A^{-1}].\\]</div><p>If the left side cannot reduce to \\(I\\), \\(A\\) is singular.</p>`},{type:'quiz',title:'Singular warning',q:'During [A|I] reduction, the A side develops a zero row and cannot become I. What does that mean?',options:['A has no inverse','The inverse is the zero matrix','Swap the identity columns'],answer:0,why:'A square matrix is invertible exactly when its reduced form is I.'}]}]},
{id:'l21-det',courseLesson:21,color:'#9a6038',badge:'4',label:'Determinant',title:'Determinants and Cofactors',subtitle:'2×2 rule · minors · cofactor expansion',desc:'Build the determinant from smaller determinants.',lessons:[{title:'Determinants',screens:[{type:'teach',title:'From 2×2 to n×n',html:`<p>${l21Book}</p><p>For \\(2\\times2\\),</p><div class="eq">\\[\\det\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}=ad-bc.\\]</div><p>For larger matrices, delete row \\(i\\) and column \\(j\\) to form the minor \\(M_{ij}\\); the cofactor is \\(C_{ij}=(-1)^{i+j}M_{ij}\\). Expanding along any row or column gives the same determinant.</p>`},l21Clone(l21Det)]}]},
{id:'l21-rowdet',courseLesson:21,color:'#3e7287',badge:'5',label:'Efficient determinant',title:'Evaluation by Row & Column Operations',subtitle:'track swaps · scalings · replacements',desc:'Create zeros before expanding.',lessons:[{title:'Operations',screens:[{type:'teach',title:'What each row operation does to det',html:`<p>${l21Book}</p><p>Swapping two rows multiplies the determinant by \\(-1\\). Multiplying a row by \\(c\\) multiplies the determinant by \\(c\\). Adding a multiple of one row to another leaves the determinant unchanged. The same rules hold for columns.</p><p>Use these rules to create zeros, then expand along a sparse row or column.</p>`},l21Clone(l21Row)]}]},
{id:'l21-cramer',courseLesson:21,color:'#536b48',badge:'6',label:'Cramer',title:'Cramer’s Rule',subtitle:'replace one column · divide by det(A)',desc:'A determinant formula for each unknown when A is nonsingular.',lessons:[{title:'Cramer',screens:[{type:'teach',title:'Formula and condition',html:`<p>${l21Book}</p><p>For a nonsingular square system \\(AX=B\\), replace column \\(k\\) of \\(A\\) by \\(B\\) to form \\(A(k;B)\\). Then</p><div class="eq">\\[\\boxed{x_k=\\frac{\\det A(k;B)}{\\det A}}.\\]</div><p>The condition \\(\\det A\\ne0\\) is essential; if \\(\\det A=0\\), Cramer’s rule does not apply.</p>`},l21Clone(l21Cramer)]}]},
{id:'l21-links',courseLesson:21,color:'#856b37',badge:'7',label:'Connections',title:'The Invertibility Picture',subtitle:'inverse ↔ determinant ↔ rank ↔ uniqueness',desc:'Know which test answers which question fastest.',lessons:[{title:'Connections',screens:[l21Clone(l21Links),{type:'quiz',title:'Fast conclusion',q:'A is 4×4 and det(A) ≠ 0. What can you conclude about AX=B for every B?',options:['Exactly one solution','Sometimes no solution','Always infinitely many solutions'],answer:0,why:'Nonzero determinant means A is invertible, so X=A⁻¹B is unique.'}]}]},
{id:'l21-mastery',courseLesson:21,color:'#a24458',badge:'8',label:'Mastery',title:'Dec. 2 Transfer Mastery',subtitle:'6 unseen problems · inverses, determinants, Cramer, structure',desc:'Mastery now uses fresh problems and diagnostics rather than replaying the guided examples.',lessons:[{title:'Inverse transfer',screens:[
 l21Board('Transfer 1 — compute and verify a fresh inverse',`<p>${l21Recon}</p><p>Find the inverse of \\(A=\\begin{pmatrix}2&1\\\\5&3\\end{pmatrix}\\) and verify it by multiplication.</p>`,`<p>Row-reducing \\([A|I]\\) gives</p><div class="eq">\\[\\boxed{A^{-1}=\\begin{pmatrix}3&-1\\\\-5&2\\end{pmatrix}}.\\]</div><p>Check both structure and arithmetic:</p><div class="eq">\\[AA^{-1}=\\begin{pmatrix}2&1\\\\5&3\\end{pmatrix}\\begin{pmatrix}3&-1\\\\-5&2\\end{pmatrix}=\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}.\\]</div><p>So the candidate really is the inverse.</p>`,'Original transfer · matrix inverse'),
 l21Board('Transfer 2 — diagnose singularity during augmentation',`<p>${l21Recon}</p><p>Attempt to invert \\(B=\\begin{pmatrix}1&2\\\\2&4\\end{pmatrix}\\) using \\([B|I]\\). What feature proves the inverse does not exist?</p>`,`<p>Apply \\(R_2\\leftarrow R_2-2R_1\\). The left block becomes</p><div class="eq">\\[\\begin{pmatrix}1&2\\\\0&0\\end{pmatrix}.\\]</div><p>It cannot be reduced to \\(I_2\\); the second row has no pivot. Therefore</p><div class="eq">\\[\\boxed{B\\text{ is singular and has no inverse}.}\\]</div><p>Later determinant language gives the same conclusion because \\(\\det B=0\\).</p>`,'Original diagnostic · singular matrix') ]},{title:'Determinant transfer',screens:[
 l21Board('Transfer 3 — cofactor expansion on a fresh matrix',`<p>${l21Recon}</p><p>Evaluate</p><div class="eq">\\[\\det\\begin{pmatrix}1&0&2\\\\-1&3&1\\\\2&1&0\\end{pmatrix}\\]</div><p>by expanding along the first row.</p>`,`<p>The middle entry is zero, so expand along row 1:</p><div class="eq">\\[D=1\\begin{vmatrix}3&1\\\\1&0\\end{vmatrix}+2\\begin{vmatrix}-1&3\\\\2&1\\end{vmatrix}.\\]</div><p>The signs in positions \\((1,1)\\) and \\((1,3)\\) are both positive. Thus</p><div class="eq">\\[D=(3\\cdot0-1\\cdot1)+2((-1)(1)-3(2))=-1+2(-7)=\\boxed{-15}.\\]</div>`,'Original transfer · cofactors'),
 l21Board('Transfer 4 — track determinant changes through row operations',`<p>${l21Recon}</p><p>A matrix \\(A\\) is transformed into upper triangular \\(U\\) by: swap rows 1 and 2; multiply row 3 by 4; then add 5 times row 1 to row 2. If \\(\\det U=24\\), find \\(\\det A\\).</p>`,`<p>The row swap multiplies the determinant by \\(-1\\). Scaling row 3 by 4 multiplies it by 4. The replacement operation changes nothing. Hence</p><div class="eq">\\[\\det U=(-1)(4)\\det A=-4\\det A.\\]</div><p>Therefore</p><div class="eq">\\[\\boxed{\\det A=-6}.\\]</div><p>This is why determinant elimination requires bookkeeping: row operations simplify the matrix but not all preserve the determinant value.</p>`,'Original transfer · determinant row operations') ]},{title:'Cramer & synthesis',screens:[
 l21Board('Transfer 5 — Cramer’s rule on a new system',`<p>${l21Recon}</p><p>Use Cramer’s rule to solve</p><div class="eq">\\[3x+2y=7,\\qquad x-y=1.\\]</div>`,`<p>The coefficient determinant is</p><div class="eq">\\[D=\\begin{vmatrix}3&2\\\\1&-1\\end{vmatrix}=-5\\ne0.\\]</div><p>Replace column 1:</p><div class="eq">\\[D_x=\\begin{vmatrix}7&2\\\\1&-1\\end{vmatrix}=-9,\\qquad x=D_x/D=9/5.\\]</div><p>Replace column 2:</p><div class="eq">\\[D_y=\\begin{vmatrix}3&7\\\\1&1\\end{vmatrix}=-4,\\qquad y=D_y/D=4/5.\\]</div><div class="eq">\\[\\boxed{(x,y)=(9/5,4/5)}.\\]</div><p>Substitution checks both equations.</p>`,'Original transfer · Cramer’s rule'),
 l21Board('Transfer 6 — invertibility theorem diagnosis',`<p>${l21Recon}</p><p>For a square matrix \\(A\\), a student claims: “If one particular system \\(AX=B\\) happens to be consistent, then \\(A\\) must be invertible.” Diagnose the claim.</p>`,`<p>False. A singular matrix can still have consistent right-hand sides; it simply cannot give a <b>unique solution for every</b> \\(B\\). For example,</p><div class="eq">\\[A=\\begin{pmatrix}1&1\\\\2&2\\end{pmatrix},\\qquad B=\\binom12\\]</div><p>is consistent but has infinitely many solutions. The correct square-matrix equivalence is</p><div class="eq">\\[\\boxed{A\\text{ invertible}\\iff\\det A\\ne0\\iff\\operatorname{rank}(A)=n\\iff AX=B\\text{ has a unique solution for every }B}.\\]</div>`,'Original diagnostic · invertibility') ]}]}
];
if(!units.some(u=>u&&u.id==='l21-map'))units.push(...lesson21Units); if(courseLessons[19])courseLessons[19].status='complete'; courseLessons[20]={number:21,title:'Inverses, Determinants & Cramer’s Rule',subtitle:'Dec. 2 · supplied O’Neil §§11.5–11.7',status:'current'};

const l21P1151=l21Board('O’Neil §11.5 Problem 1 — find an inverse by augmentation',`<p>${l21Book}</p><p>Find the inverse of</p><div class="eq">\\[A=\\begin{pmatrix}-1&2\\\\2&1\\end{pmatrix}\\]</div><p>or show that it is singular.</p>`,`<p>Reduce \\([A|I]\\). One convenient route is</p><div class="eq">\\[R_1\\leftarrow-R_1,\\quad R_2\\leftarrow R_2-2R_1,\\quad R_2\\leftarrow\\tfrac15R_2,\\quad R_1\\leftarrow R_1+2R_2.\\]</div><p>The left block becomes \\(I\\), so the right block is the inverse:</p><div class="eq">\\[\\boxed{A^{-1}=\\begin{pmatrix}-1/5&2/5\\\\2/5&1/5\\end{pmatrix}}.\\]</div><p>Multiplying \\(AA^{-1}\\) gives \\(I\\).</p>`,'§11.5 · Problem 1');
const l21P1161=l21Board('O’Neil §11.6 Problem 1 — determinant by a smart expansion',`<p>${l21Book}</p><p>Evaluate</p><div class="eq">\\[\\det\\begin{pmatrix}-2&4&1\\\\1&6&3\\\\7&0&4\\end{pmatrix}.\\]</div>`,`<p>Expand along the first row:</p><div class="eq">\\[D=-2\\begin{vmatrix}6&3\\\\0&4\\end{vmatrix}-4\\begin{vmatrix}1&3\\\\7&4\\end{vmatrix}+\\begin{vmatrix}1&6\\\\7&0\\end{vmatrix}.\\]</div><p>Therefore</p><div class="eq">\\[D=-2(24)-4(4-21)+(0-42)=-48+68-42=\\boxed{-22}.\\]</div><p>The nonzero result also tells us the matrix is nonsingular.</p>`,'§11.6 · Problem 1');
const l21P1171=l21Board('O’Neil §11.7 Problem 1 — Cramer’s rule',`<p>${l21Book}</p><p>Solve by Cramer’s rule:</p><div class="eq">\\[15x_1-4x_2=5,\\qquad 8x_1+x_2=-4.\\]</div>`,`<p>The coefficient determinant is</p><div class="eq">\\[D=\\begin{vmatrix}15&-4\\\\8&1\\end{vmatrix}=47.\\]</div><p>Replace the first column by the right-hand side:</p><div class="eq">\\[D_1=\\begin{vmatrix}5&-4\\\\-4&1\\end{vmatrix}=-11.\\]</div><p>Replace the second column:</p><div class="eq">\\[D_2=\\begin{vmatrix}15&5\\\\8&-4\\end{vmatrix}=-100.\\]</div><p>Hence</p><div class="eq">\\[\\boxed{x_1=-11/47,\\qquad x_2=-100/47}.\\]</div><p>Since \\(D\\ne0\\), Cramer’s rule applies and the solution is unique.</p>`,'§11.7 · Problem 1');
const l21InvUnit=units.find(u=>u&&u.id==='l21-inv');
if(l21InvUnit&&!l21InvUnit.lessons[0].screens.some(s=>s.title===l21P1151.title))l21InvUnit.lessons[0].screens.push(l21Clone(l21P1151));
const l21DetUnit=units.find(u=>u&&u.id==='l21-det');
if(l21DetUnit&&!l21DetUnit.lessons[0].screens.some(s=>s.title===l21P1161.title))l21DetUnit.lessons[0].screens.push(l21Clone(l21P1161));
const l21CramerUnit=units.find(u=>u&&u.id==='l21-cramer');
if(l21CramerUnit&&!l21CramerUnit.lessons[0].screens.some(s=>s.title===l21P1171.title))l21CramerUnit.lessons[0].screens.push(l21Clone(l21P1171));

if(typeof renderCourseMap==='function')renderCourseMap();if(typeof render==='function')render();