/* Lesson 12 — Oct. 28: Heaviside formula; switched forcing; periodic forcing; staircase. */
const l12Core='<span class="supplementalTag">Core · Oct. 28 syllabus · O’Neil §3.3.3</span>';
const l12Book='<span class="supplementalTag">Authentic textbook · O’Neil</span>';
const l12Supp='<span class="supplementalTag">Course-aligned reconstruction · instructor notes not uploaded</span>';
const l12Explain='<span class="supplementalTag">Expanded explanation · Lesson 1 depth standard</span>';
function l12Board(title,prompt,solution,section='§3.3'){return {type:'bookproblem',bookSection:section,title,prompt,solution};}
function l12Clone(s){return s?{...s,inlineBookPractice:true}:null;}
const l12Ex310=l12Board('O’Neil Example 3.10 — discontinuous forcing',
`<p>${l12Book}<br>Solve</p><div class="eq">\\[y''+4y=f(t),\\qquad y(0)=y'(0)=0,\\]</div><div class="eq">\\[f(t)=\\begin{cases}0,&t<3,\\\\t,&t\\ge3.\\end{cases}\\]</div><p>Before opening the solution, first encode the forcing with a Heaviside function.</p>`,
`<p><b>1 · Encode what physically happens.</b> The force is absent until \\(t=3\\), then it becomes the ordinary function \\(t\\). Thus</p><div class="eq">\\[f(t)=H(t-3)t=H(t-3)[(t-3)+3].\\]</div><p>The rewrite in powers of \\(t-3\\) is essential because the second shifting theorem acts on \\(H(t-a)g(t-a)\\).</p><p><b>2 · Transform the IVP.</b></p><div class="eq">\\[(s^2+4)Y(s)=e^{-3s}\\left(\\frac1{s^2}+\\frac3s\\right),\\]</div><div class="eq">\\[Y(s)=e^{-3s}\\frac{3s+1}{s^2(s^2+4)}.\\]</div><p><b>3 · Expose transform-table pieces.</b></p><div class="eq">\\[\\frac{3s+1}{s^2(s^2+4)}=\\frac{3}{4s}-\\frac{3s}{4(s^2+4)}+\\frac1{4s^2}-\\frac1{4(s^2+4)}.\\]</div><p>Without the delay, the inverse is</p><div class="eq">\\[g(t)=\\frac34-\\frac34\\cos2t+\\frac14t-\\frac18\\sin2t.\\]</div><p><b>4 · Put the delay back.</b></p><div class="whybox"><div class="eq">\\[\\boxed{y(t)=H(t-3)\\left[\\frac34-\\frac34\\cos(2(t-3))+\\frac14(t-3)-\\frac18\\sin(2(t-3))\\right]}.\\]</div></div><p><b>Check.</b> At \\(t=3^+\\), both \\(y\\) and \\(y'\\) are zero, so the delayed response joins the pre-switch zero solution continuously.</p>`);
const l12Periodic11=l12Board('O’Neil §3.1 Problem 11 — derive the periodic-transform formula',
`<p>${l12Book}<br>Suppose \\(f(t+T)=f(t)\\). Derive a formula for \\(\\mathcal L\\{f\\}\\) using one period.</p>`,
`<p><b>Why split the integral?</b> Periodicity repeats the same waveform every \\(T\\) units, while the Laplace weight \\(e^{-st}\\) makes each later copy smaller by a fixed factor.</p><div class="eq">\\[F(s)=\\sum_{n=0}^{\\infty}\\int_{nT}^{(n+1)T}e^{-st}f(t)dt.\\]</div><p>Set \\(t=u+nT\\). Periodicity gives \\(f(u+nT)=f(u)\\), hence</p><div class="eq">\\[\\int_{nT}^{(n+1)T}e^{-st}f(t)dt=e^{-nsT}\\int_0^T e^{-su}f(u)du.\\]</div><p>Factor the one-period integral and sum the geometric series:</p><div class="eq">\\[\\sum_{n=0}^{\\infty}e^{-nsT}=\\frac1{1-e^{-sT}}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{F(s)=\\frac{1}{1-e^{-sT}}\\int_0^T e^{-st}f(t)dt}.\\]</div></div><p><b>Meaning.</b> Compute only one period; the denominator accounts for every repeated copy.</p>`,'§3.1');
const l12Periodic12=l12Board('O’Neil §3.1 Problem 12 — rectangular periodic signal',
`<p>${l12Book}<br>A function has period \\(6\\) and</p><div class="eq">\\[f(t)=\\begin{cases}5,&0<t\\le3,\\\\0,&3<t\\le6.\\end{cases}\\]</div><p>Find its Laplace transform using the periodic formula.</p>`,
`<p>Here \\(T=6\\). Only the first half of each period contributes:</p><div class="eq">\\[\\int_0^6e^{-st}f(t)dt=5\\int_0^3e^{-st}dt=\\frac5s(1-e^{-3s}).\\]</div><p>Divide by \\(1-e^{-6s}\\):</p><div class="eq">\\[F(s)=\\frac{5(1-e^{-3s})}{s(1-e^{-6s})}.\\]</div><p>Since \\(1-e^{-6s}=(1-e^{-3s})(1+e^{-3s})\\),</p><div class="whybox"><div class="eq">\\[\\boxed{F(s)=\\frac5{s(1+e^{-3s})}}.\\]</div></div><p><b>Check.</b> As \\(s\\to0^+\\), \\(sF(s)\\to5/2\\), the average value of the waveform over one period.</p>`,'§3.1');
const l12Periodic13=l12Board('O’Neil §3.1 Problem 13 — full-wave rectified sine',
`<p>${l12Book}<br>Find the Laplace transform of \\(f(t)=E|\\sin(\\omega t)|\\), with \\(E,\\omega>0\\).</p>`,
`<p><b>1 · Find the actual period.</b> Taking an absolute value folds the negative half-cycle upward, so the period is \\(T=\\pi/\\omega\\), not \\(2\\pi/\\omega\\).</p><p>On one period, \\(\\sin(\\omega t)\\ge0\\), hence</p><div class="eq">\\[I=E\\int_0^{\\pi/\\omega}e^{-st}\\sin(\\omega t)dt=\\frac{E\\omega(1+e^{-\\pi s/\\omega})}{s^2+\\omega^2}.\\]</div><p>Insert this into the periodic formula:</p><div class="whybox"><div class="eq">\\[\\boxed{F(s)=\\frac{E\\omega}{s^2+\\omega^2}\\frac{1+e^{-\\pi s/\\omega}}{1-e^{-\\pi s/\\omega}}}.\\]</div></div><p>The quotient may also be written with a hyperbolic cotangent, but the exponential form shows directly where the repeated periods come from.</p>`,'§3.1');
const l12RLC=l12Board('Course application — switched RLC step response',
`<p>${l12Supp}<br>A series RLC circuit has \\(L=1\\), \\(R=2\\), \\(C=1/2\\), zero initial charge/current, and a 1-V source switched on at \\(t=2\\). Solve for charge \\(q(t)\\) and current \\(i(t)=q'(t)\\).</p>`,
`<p><b>1 · Translate the circuit law.</b> Kirchhoff's voltage law gives \\(Lq''+Rq'+q/C=E(t)\\). With the stated values and delayed source,</p><div class="eq">\\[q''+2q'+2q=H(t-2),\\qquad q(0)=q'(0)=0.\\]</div><p><b>2 · Transform.</b></p><div class="eq">\\[Q(s)=e^{-2s}\\frac1{s[(s+1)^2+1]}.\\]</div><p>The undelayed factor decomposes as</p><div class="eq">\\[\\frac1{s[(s+1)^2+1]}=\\frac1{2s}-\\frac12\\frac{s+1}{(s+1)^2+1}-\\frac12\\frac1{(s+1)^2+1}.\\]</div><p>Therefore the ordinary step response is</p><div class="eq">\\[g(t)=\\frac12-\\frac12e^{-t}(\\cos t+\\sin t).\\]</div><p><b>3 · Delay the whole response by 2.</b></p><div class="whybox"><div class="eq">\\[\\boxed{q(t)=H(t-2)\\left[\\frac12-\\frac12e^{-(t-2)}(\\cos(t-2)+\\sin(t-2))\\right]}.\\]</div><div class="eq">\\[\\boxed{i(t)=H(t-2)e^{-(t-2)}\\sin(t-2)}.\\]</div></div><p><b>Physical checks.</b> Before the switch, both are zero. Charge tends to \\(C(1\\text{ V})=1/2\\) C. The current decays to zero after the transient dies out.</p>`,'Oct. 28');
const l12KV=l12Board('Course application — step-loaded Kelvin–Voigt element',
`<p>${l12Supp}<br>A Kelvin–Voigt element obeys \\(\\sigma=E\\varepsilon+\\eta\\varepsilon'\\). Starting from zero strain, a constant stress \\(\\sigma_0\\) is applied suddenly at \\(t=a\\). Find \\(\\varepsilon(t)\\) and interpret it.</p>`,
`<p><b>What the symbols mean.</b> \\(\\sigma\\) is stress (force per area), \\(\\varepsilon\\) is dimensionless strain, \\(E\\) is elastic modulus, and \\(\\eta\\) is viscosity. The spring and dashpot are in parallel, so they share the same strain and their stresses add.</p><p>The loading is \\(\\sigma(t)=\\sigma_0H(t-a)\\). Before \\(a\\), zero loading and zero initial strain give \\(\\varepsilon=0\\). After the load arrives, use delayed time \\(u=t-a\\):</p><div class="eq">\\[\\eta\\frac{d\\varepsilon}{du}+E\\varepsilon=\\sigma_0,\\qquad \\varepsilon(0)=0.\\]</div><p>This first-order linear equation has time constant \\(\\tau=\\eta/E\\):</p><div class="whybox"><div class="eq">\\[\\boxed{\\varepsilon(t)=\\frac{\\sigma_0}{E}H(t-a)\\left(1-e^{-(t-a)/\\tau}\\right)},\\qquad \\tau=\\frac\\eta E.\\]</div></div><p><b>Interpretation.</b> The dashpot prevents an instantaneous strain jump. The element creeps gradually toward the elastic equilibrium \\(\\sigma_0/E\\). After one time constant it has completed about 63% of that change.</p>`,'Oct. 28');
const l12Stair=l12Board('Course application — staircase input',
`<p>${l12Supp}<br>Define a unit staircase that jumps upward by one at \\(T,2T,3T,\\ldots\\):</p><div class="eq">\\[r(t)=\\sum_{n=1}^{\\infty}H(t-nT).\\]</div><p>Find \\(R(s)\\) and explain why this is not a periodic function.</p>`,
`<p>For any fixed finite \\(t\\), only finitely many steps are active, so the time-domain sum is well-defined. For real \\(s&gt;0\\), transform term by term:</p><div class="eq">\\[R(s)=\\frac1s\\sum_{n=1}^{\\infty}e^{-nsT}.\\]</div><p>The remaining series is geometric with first term and ratio \\(e^{-sT}\\). Because \\(0&lt;e^{-sT}&lt;1\\) when \\(s&gt;0\\) and \\(T&gt;0\\), it converges to</p><div class="whybox"><div class="eq">\\[\\boxed{R(s)=\\frac{e^{-sT}}{s(1-e^{-sT})}},\\qquad s&gt;0.\\]</div></div><p><b>Why the staircase is not periodic.</b> Its jump <i>times</i> repeat regularly, but \\(r(t+T)=r(t)+1\\), not \\(r(t)\\). Periodic-transform formulas therefore cannot be applied to the staircase itself.</p>`,'Oct. 28');
const l12Sec33=[
l12Board('O’Neil §3.3 Problem 27 — delayed constant forcing',`<p>${l12Book}<br>Solve</p><div class="eq">\\[y''+4y=f(t),\\qquad y(0)=1,\\ y'(0)=0,\\]</div><div class="eq">\\[f(t)=\\begin{cases}0,&0\\le t<4,\\\\3,&t\\ge4.\\end{cases}\\]</div>`,`<p><b>1 · Encode the forcing.</b> The constant input begins at \\(t=4\\), so \\(f(t)=3H(t-4)\\) and \\(F(s)=3e^{-4s}/s\\).</p><p><b>2 · Transform the IVP.</b></p><div class="eq">\\[(s^2+4)Y-s=\\frac{3e^{-4s}}s,\\]</div><div class="eq">\\[Y=\\frac{s}{s^2+4}+e^{-4s}\\frac{3}{s(s^2+4)}.\\]</div><p>The first term is the motion from the initial displacement: \\(\\cos2t\\). For the delayed step response,</p><div class="eq">\\[\\frac{3}{s(s^2+4)}=\\frac34\\left(\\frac1s-\\frac{s}{s^2+4}\\right).\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y(t)=\\cos2t+\\frac34H(t-4)\\left[1-\\cos(2(t-4))\\right]}.\\]</div></div><p><b>Check.</b> The added response and its first derivative are both zero at the switching instant, so \\(y\\) and \\(y'\\) join continuously.</p>`,'§3.3'),
l12Board('O’Neil §3.3 Problem 28 — unstable switched IVP',`<p>${l12Book}<br>Solve</p><div class="eq">\\[y''-2y'-3y=f(t),\\qquad y(0)=1,\\ y'(0)=0,\\]</div><div class="eq">\\[f(t)=\\begin{cases}0,&0\\le t<4,\\\\12,&t\\ge4.\\end{cases}\\]</div>`,`<p>Write \\(f(t)=12H(t-4)\\). Transforming gives</p><div class="eq">\\[(s-3)(s+1)Y-s+2=\\frac{12e^{-4s}}s.\\]</div><p>Separate the initial-condition response and the delayed input response:</p><div class="eq">\\[\\frac{s-2}{(s-3)(s+1)}=\\frac1{4(s-3)}+\\frac3{4(s+1)},\\]</div><div class="eq">\\[\\frac{12}{s(s-3)(s+1)}=\\frac1{s-3}+\\frac3{s+1}-\\frac4s.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y(t)=\\frac14e^{3t}+\\frac34e^{-t}+H(t-4)\\left[e^{3(t-4)}+3e^{-(t-4)}-4\\right]}.\\]</div></div><p>The \\(e^{3t}\\) mode grows, so this system is unstable; the switched input does not create that instability, it excites a mode already present in the homogeneous dynamics.</p>`,'§3.3'),
l12Board('O’Neil §3.3 Problem 29 — delayed forcing in a third-order IVP',`<p>${l12Book}<br>Solve</p><div class="eq">\\[y'''-8y=g(t),\\qquad y(0)=y'(0)=y''(0)=0,\\]</div><div class="eq">\\[g(t)=\\begin{cases}0,&0\\le t<6,\\\\2,&t\\ge6.\\end{cases}\\]</div>`,`<p>The input is \\(g(t)=2H(t-6)\\). Zero initial data give</p><div class="eq">\\[(s^3-8)Y=\\frac{2e^{-6s}}s.\\]</div><p>Factor \\(s^3-8=(s-2)(s^2+2s+4)\\). The undelayed step-response transform is</p><div class="eq">\\[\\frac2{s(s^3-8)}=-\\frac1{4s}+\\frac1{12(s-2)}+\\frac{s+1}{6(s^2+2s+4)}.\\]</div><p>Since \\(s^2+2s+4=(s+1)^2+3\\),</p><div class="whybox"><div class="eq">\\[\\boxed{y(t)=H(t-6)\\left[\\frac1{12}e^{2(t-6)}-\\frac14+\\frac16e^{-(t-6)}\\cos(\\sqrt3(t-6))\\right]}.\\]</div></div><p>The bracket and its first two derivatives match the zero pre-switch state at the switching time, as a third-order step-forced IVP requires.</p>`,'§3.3'),
l12Board('O’Neil §3.3 Problem 30 — switch a forcing off',`<p>${l12Book}<br>Solve</p><div class="eq">\\[y''+5y'+6y=f(t),\\qquad y(0)=y'(0)=0,\\]</div><div class="eq">\\[f(t)=\\begin{cases}-2,&0\\le t<3,\\\\0,&t\\ge3.\\end{cases}\\]</div>`,`<p><b>Encoding an OFF switch.</b> The forcing starts at \\(-2\\) and is canceled at \\(t=3\\):</p><div class="eq">\\[f(t)=-2+2H(t-3).\\]</div><p>The unit-step response of the operator is obtained from</p><div class="eq">\\[\\frac1{s(s+2)(s+3)}=\\frac1{6s}-\\frac1{2(s+2)}+\\frac1{3(s+3)},\\]</div><p>so define</p><div class="eq">\\[h(t)=\\frac16-\\frac12e^{-2t}+\\frac13e^{-3t}.\\]</div><p>By linearity, the first forcing contributes \\(-2h(t)\\) and the cancellation contributes \\(2H(t-3)h(t-3)\\):</p><div class="whybox"><div class="eq">\\[\\boxed{y(t)=-2h(t)+2H(t-3)h(t-3)}.\\]</div></div><p>This form makes the physics transparent: the second term launches the exact opposite step response at the switch-off time.</p>`,'§3.3'),
l12Board('O’Neil §3.3 Problem 31 — baseline plus a delayed increment',`<p>${l12Book}<br>Solve</p><div class="eq">\\[y'''-y''+4y'-4y=f(t),\\]</div><div class="eq">\\[y(0)=y'(0)=0,\\quad y''(0)=1,\\]</div><div class="eq">\\[f(t)=\\begin{cases}1,&0\\le t<5,\\\\2,&t\\ge5.\\end{cases}\\]</div>`,`<p>The forcing is \\(1+H(t-5)\\): a baseline of 1 plus an increment of 1 at \\(t=5\\). The characteristic factor is</p><div class="eq">\\[s^3-s^2+4s-4=(s-1)(s^2+4).\\]</div><p>Including the initial data,</p><div class="eq">\\[(s-1)(s^2+4)Y-1=\\frac1s+\\frac{e^{-5s}}s.\\]</div><p>The pre-switch response is</p><div class="eq">\\[y_0(t)=\\frac25e^t-\\frac15\\sin2t-\\frac3{20}\\cos2t-\\frac14.\\]</div><p>The response to one additional delayed unit step is based on</p><div class="eq">\\[h(t)=\\frac15e^t-\\frac1{10}\\sin2t+\\frac1{20}\\cos2t-\\frac14.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y(t)=y_0(t)+H(t-5)h(t-5)}.\\]</div></div><p>Direct differentiation gives \\(y_0(0)=y_0'(0)=0\\), \\(y_0''(0)=1\\), and the correct baseline forcing.</p>`,'§3.3'),
l12Board('O’Neil §3.3 Problem 32 — ramp plus a delayed jump',`<p>${l12Book}<br>Solve</p><div class="eq">\\[y''-4y'+4y=f(t),\\qquad y(0)=-2,\\ y'(0)=1,\\]</div><div class="eq">\\[f(t)=\\begin{cases}t,&0\\le t<3,\\\\t+2,&t\\ge3.\\end{cases}\\]</div>`,`<p>The input is not a delayed ramp; it is the same ramp everywhere plus a delayed constant increment:</p><div class="eq">\\[f(t)=t+2H(t-3).\\]</div><p>Transforming, with \\(s^2-4s+4=(s-2)^2\\), gives</p><div class="eq">\\[(s-2)^2Y+2s-9=\\frac1{s^2}+\\frac{2e^{-3s}}s.\\]</div><p>The response before the increment is</p><div class="eq">\\[y_0(t)=\\frac{21}{4}te^{2t}+\\frac14t-\\frac94e^{2t}+\\frac14.\\]</div><p>The delayed increment has base response</p><div class="eq">\\[h(t)=te^{2t}-\\frac12e^{2t}+\\frac12.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y(t)=y_0(t)+H(t-3)h(t-3)}.\\]</div></div><p>Check: \\(y_0(0)=-2\\), \\(y_0'(0)=1\\), and substitution gives the ramp forcing \\(t\\).</p>`,'§3.3'),
l12Board('O’Neil §3.3 Problem 33 — RL circuit switched off at t=5',`<p>${l12Book}<br>An RL circuit has resistance \\(R\\), inductance \\(L\\), and zero initial current. Its electromotive force is</p><div class="eq">\\[E(t)=\\begin{cases}k,&0\\le t<5,\\\\0,&t\\ge5.\\end{cases}\\]</div><p>Determine \\(i(t)\\).</p>`,`<p><b>1 · Model the circuit.</b> Kirchhoff's law for a series RL circuit is</p><div class="eq">\\[L i'(t)+Ri(t)=E(t),\\qquad i(0)=0.\\]</div><p>The source is \\(E(t)=k[1-H(t-5)]\\), hence</p><div class="eq">\\[I(s)=\\frac{k(1-e^{-5s})}{s(Ls+R)}.\\]</div><p>The response to a constant source \\(k\\) switched on at zero is</p><div class="eq">\\[r(t)=\\frac{k}{R}\\left(1-e^{-Rt/L}\\right).\\]</div><p>The source being switched off at 5 is represented by subtracting a delayed copy of that same step response:</p><div class="whybox"><div class="eq">\\[\\boxed{i(t)=\\frac{k}{R}\\left[(1-e^{-Rt/L})-H(t-5)(1-e^{-R(t-5)/L})\\right]}.\\]</div></div><p>For \\(t\\ge5\\), this is equivalently \\(\\frac{k}{R}(1-e^{-5R/L})e^{-R(t-5)/L}\\): after the battery is removed, the inductor current decays continuously rather than disappearing instantly.</p>`,'§3.3'),
l12Board('O’Neil §3.3 Problem 34 — Heaviside formula',`<p>${l12Book}<br>Use Heaviside's formula to find</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac{s+1}{s^2-3s+2}\\right\\}.\\]</div>`,`<p>Factor \\(q(s)=(s-1)(s-2)\\). The simple poles are 1 and 2.</p><p>At \\(a_1=1\\), delete \\(s-1\\): \\(q_1(1)=1-2=-1\\), so the coefficient is \\(p(1)/q_1(1)=2/(-1)=-2\\).</p><p>At \\(a_2=2\\), \\(q_2(2)=2-1=1\\), giving coefficient 3.</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=-2e^t+3e^{2t}}.\\]</div></div>`,'§3.3'),
l12Board('O’Neil §3.3 Problem 35 — three simple real poles',`<p>${l12Book}<br>Use Heaviside's formula to find</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac{s^2}{(s-1)(s-2)(s+5)}\\right\\}.\\]</div>`,`<p>Evaluate the simple-pole coefficient \\(p(a_j)/q_j(a_j)\\) at each root:</p><div class="eq">\\[A_1=\\frac{1}{(1-2)(1+5)}=-\\frac16,\\]</div><div class="eq">\\[A_2=\\frac{4}{(2-1)(2+5)}=\\frac47,\\]</div><div class="eq">\\[A_{-5}=\\frac{25}{(-5-1)(-5-2)}=\\frac{25}{42}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{f(t)=-\\frac16e^t+\\frac47e^{2t}+\\frac{25}{42}e^{-5t}}.\\]</div></div>`,'§3.3'),
l12Board('O’Neil §3.3 Problem 36 — complex poles',`<p>${l12Book}<br>Use Heaviside's formula to find</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac{s+4}{s^2+9}\\right\\}.\\]</div>`,`<p>The poles are \\(a_1=3i\\) and \\(a_2=-3i\\). Write \\(q(s)=(s-3i)(s+3i)\\). For the pole \\(3i\\), delete its factor and evaluate the other:</p><div class="eq">\\[A_1=\\frac{p(3i)}{q_1(3i)}=\\frac{3i+4}{3i+3i}=\\frac{4+3i}{6i}=\\frac12-\\frac23i.\\]</div><p>For the conjugate pole,</p><div class="eq">\\[A_2=\\frac{p(-3i)}{q_2(-3i)}=\\frac{4-3i}{-6i}=\\frac12+\\frac23i.\\]</div><p>Heaviside's formula therefore gives</p><div class="eq">\\[f(t)=\\left(\\frac12-\\frac23i\\right)e^{3it}+\\left(\\frac12+\\frac23i\\right)e^{-3it}.\\]</div><p>Now use \\(e^{i\\theta}=\\cos\\theta+i\\sin\\theta\\) and combine the conjugates. The imaginary parts cancel and the real parts add:</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=\\cos3t+\\frac43\\sin3t}.\\]</div></div><p><b>Independent table check.</b> \\(F=s/(s^2+9)+4/(s^2+9)\\), which gives the same result.</p>`,'§3.3'),
l12Board('O’Neil §3.3 Problem 37 — three unequal real poles',`<p>${l12Book}<br>Use Heaviside's formula to find</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac{s^2+2s-1}{(s-3)(s-5)(s+8)}\\right\\}.\\]</div>`,`<p>The poles are \\(3,5,-8\\). Compute each coefficient by deleting its own factor:</p><div class="eq">\\[A_3=\\frac{14}{(3-5)(3+8)}=-\\frac7{11},\\]</div><div class="eq">\\[A_5=\\frac{34}{(5-3)(5+8)}=\\frac{17}{13},\\]</div><div class="eq">\\[A_{-8}=\\frac{47}{(-8-3)(-8-5)}=\\frac{47}{143}.\\]</div><div class="whybox"><div class="eq">\\[\\boxed{f(t)=-\\frac7{11}e^{3t}+\\frac{17}{13}e^{5t}+\\frac{47}{143}e^{-8t}}.\\]</div></div>`,'§3.3'),
l12Board('O’Neil §3.3 Problem 38 — four complex simple poles',`<p>${l12Book}<br>Use Heaviside's formula to find</p><div class="eq">\\[\\mathcal L^{-1}\\left\\{\\frac{s}{(s^2+4)(s^2+9)}\\right\\}.\\]</div>`,`<p>The simple poles are \\(2i,-2i,3i,-3i\\). Apply Heaviside's coefficient rule to each one. At \\(2i\\),</p><div class="eq">\\[A_{2i}=\\frac{2i}{(2i+2i)(2i-3i)(2i+3i)}=\\frac{2i}{(4i)(-i)(5i)}=\\frac1{10}.\\]</div><p>By conjugacy, \\(A_{-2i}=1/10\\). At \\(3i\\),</p><div class="eq">\\[A_{3i}=\\frac{3i}{(3i-2i)(3i+2i)(3i+3i)}=\\frac{3i}{(i)(5i)(6i)}=-\\frac1{10},\\]</div><p>and similarly \\(A_{-3i}=-1/10\\). Therefore</p><div class="eq">\\[f(t)=\\frac1{10}(e^{2it}+e^{-2it})-\\frac1{10}(e^{3it}+e^{-3it}).\\]</div><p>Use \\(e^{i\\theta}+e^{-i\\theta}=2\\cos\\theta\\):</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=\\frac15(\\cos2t-\\cos3t)}.\\]</div></div><p><b>Independent algebra check.</b> \\(F=\\frac15\\frac{s}{s^2+4}-\\frac15\\frac{s}{s^2+9}\\), which inverts to the same expression.</p>`,'§3.3'),
l12Board('O’Neil §3.3 Problem 39 — why q′(a_j) can replace q_j(a_j)',`<p>${l12Book}<br>Show that Heaviside's formula may be written with \\(q'(a_j)\\) in the denominator instead of \\(q_j(a_j)\\).</p>`,`<p>Because \\(a_j\\) is a simple zero, write</p><div class="eq">\\[q(s)=(s-a_j)q_j(s).\\]</div><p>Differentiate using the product rule:</p><div class="eq">\\[q'(s)=q_j(s)+(s-a_j)q_j'(s).\\]</div><p>Now set \\(s=a_j\\). The second term vanishes:</p><div class="eq">\\[\\boxed{q'(a_j)=q_j(a_j)}.\\]</div><p>Therefore the coefficient forms are identical:</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L^{-1}\\{F\\}(t)=\\sum_{j=1}^n\\frac{p(a_j)}{q'(a_j)}e^{a_jt}}.\\]</div></div><p>The simple-root assumption is essential: if \\(a_j\\) were repeated, then \\(q'(a_j)\\) could also vanish.</p>`,'§3.3'),
l12Board('O’Neil §3.3 Problem 40 — derive Heaviside’s formula',`<p>${l12Book}<br>Fill in the partial-fraction derivation of Heaviside's formula for \\(F(s)=p(s)/q(s)\\) when all poles \\(a_1,\\ldots,a_n\\) are simple.</p>`,`<p>Start from the simple-pole partial fraction decomposition</p><div class="eq">\\[F(s)=\\sum_{j=1}^n\\frac{A_j}{s-a_j}.\\]</div><p>To isolate one coefficient, multiply by \\(s-a_j\\):</p><div class="eq">\\[(s-a_j)F(s)=A_j+\\sum_{k\\ne j}A_k\\frac{s-a_j}{s-a_k}.\\]</div><p>Let \\(s\\to a_j\\). Every term in the sum vanishes, so</p><div class="eq">\\[A_j=\\lim_{s\\to a_j}(s-a_j)\\frac{p(s)}{q(s)}.\\]</div><p>Since \\(q(s)=(s-a_j)q_j(s)\\), cancellation gives</p><div class="eq">\\[A_j=\\frac{p(a_j)}{q_j(a_j)}.\\]</div><p>Finally invert each \\(1/(s-a_j)\\):</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L^{-1}\\{F\\}(t)=\\sum_{j=1}^n\\frac{p(a_j)}{q_j(a_j)}e^{a_jt}}.\\]</div></div><p>This proves the formula and explains why it is not a separate magic trick: it is the cover-up coefficient calculation for simple poles written in general form.</p>`,'§3.3')
];
const lesson12Units=[
{id:'l12-map',courseLesson:12,color:'#415a9c',badge:'1',label:'Oct. 28 map',title:'From Switching to Repeated Inputs',subtitle:'Heaviside formula · discontinuous forcing · periodic forcing · staircase',desc:'Set the source boundary and connect the Oct. 21 shifting tools to the Oct. 28 applications.',lessons:[{title:'Scope and strategy',screens:[
{type:'teach',title:'What this lesson must cover',html:`<p>${l12Core}</p><p>The Oct. 28 syllabus requires four blocks: <b>Heaviside's formula</b>, <b>piecewise-defined forcing</b> with switched engineering examples, <b>periodic forcing</b>, and the <b>staircase function</b>.</p><p>O’Neil directly supplies §3.3.3 and discontinuous-input examples. The syllabus also names switched RLC and step-loaded viscoelastic examples in instructor-supplied notes, but those notes are not among the uploaded files. Those two applications are therefore reconstructed from the governing models already taught and are labeled as such rather than falsely attributed.</p>`},
{type:'teach',title:'The common idea: input history matters',html:`<p>${l12Explain}</p><p>A Heaviside factor answers <i>when</i> an input begins. A pulse answers when it begins and ends. A periodic function repeats one bounded waveform. A staircase accumulates repeated jumps. Laplace methods are useful because these timing rules become exponential factors such as \\(e^{-as}\\), which are algebraically easier to manipulate than solving a new ODE separately on every time interval.</p>`},
{type:'quiz',title:'Source honesty',q:'The syllabus names a step-loaded viscoelastic example, but the instructor notes are not uploaded. How should the app label a reconstructed example?',options:['Course-aligned reconstruction','Authentic O’Neil problem','Exact instructor-notes example'],answer:0,why:'The topic is required, but the unavailable source must not be fabricated.'}
]}]},
{id:'l12-heaviside-formula',courseLesson:12,color:'#7354a4',badge:'2',label:'Heaviside formula',title:'Heaviside’s Formula: Read Simple Poles Directly',subtitle:'simple roots · residue-like coefficients · complex roots allowed',desc:'Understand the assumptions, derive the coefficient rule from partial fractions, and reproduce O’Neil’s example.',lessons:[{title:'Where the formula comes from',screens:[
{type:'teach',title:'Assumptions first — when the shortcut is legal',html:`<p>${l12Book}</p><p>Let \\(F(s)=p(s)/q(s)\\), with \\(q\\) of higher degree than \\(p\\). Suppose</p><div class="eq">\\[q(s)=c(s-a_1)(s-a_2)\\cdots(s-a_n),\\]</div><p>where every root \\(a_j\\) is <b>simple</b> and no root of \\(q\\) is also a root of \\(p\\). These hypotheses matter: repeated poles need extra powers of \\(1/(s-a)\\), so this particular formula cannot simply be used unchanged.</p>`},
{type:'teach',title:'Derive the coefficient instead of memorizing it',html:`<p>${l12Explain}</p><p>For simple poles, partial fractions must have the form</p><div class="eq">\\[\\frac{p(s)}{q(s)}=\\sum_{j=1}^n\\frac{A_j}{s-a_j}.\\]</div><p>Multiply by \\(s-a_j\\) and then set \\(s=a_j\\). Every other term vanishes, leaving</p><div class="eq">\\[A_j=\\frac{p(a_j)}{q_j(a_j)},\\qquad q_j(s)=\\frac{q(s)}{s-a_j}.\\]</div><p>Since \\(\\mathcal L^{-1}\\{1/(s-a_j)\\}=e^{a_jt}\\),</p><div class="whybox"><div class="eq">\\[\\boxed{\\mathcal L^{-1}\\left\\{\\frac{p(s)}{q(s)}\\right\\}=\\sum_{j=1}^n\\frac{p(a_j)}{q_j(a_j)}e^{a_jt}}.\\]</div></div>`},
{type:'teach',title:'O’Neil §3.3.3 example — complex poles still give a real answer',html:`<p>${l12Book}</p><div class="eq">\\[F(s)=\\frac{s}{(s^2+4)(s-1)}=\\frac{s}{(s-2i)(s+2i)(s-1)}.\\]</div><p>The three simple poles are \\(2i,-2i,1\\). Applying the coefficient rule gives conjugate exponential terms plus \\(e^t/5\\). Combining the conjugates with Euler's identities produces the real function</p><div class="whybox"><div class="eq">\\[\\boxed{f(t)=-\\frac15\\cos2t+\\frac25\\sin2t+\\frac15e^t}.\\]</div></div><p>The complex arithmetic is only an intermediate representation; conjugate poles combine to real sine/cosine terms when the original rational function has real coefficients.</p>`},
{type:'quiz',title:'Can Heaviside’s formula be used?',q:'Which denominator violates the simple-root hypothesis of the stated Heaviside formula?',options:['(s-1)(s+2)(s+5)','(s-1)^2(s+2)','(s^2+4)(s-1)'],answer:1,why:'The pole s=1 is repeated, so the simple-pole coefficient rule is insufficient.'}
]},{title:'Authentic §3.3 Problems 34–40 · Heaviside formula',screens:l12Sec33.slice(7,14).map(l12Clone)}]},
{id:'l12-piecewise',courseLesson:12,color:'#2e7d69',badge:'3',label:'Piecewise forcing',title:'Discontinuous Forcing: Transform the Whole IVP at Once',subtitle:'encode the input · solve algebraically · delay the response',desc:'Use O’Neil Example 3.10 as the full workflow and connect it to switched physical inputs.',lessons:[{title:'A complete switched-forcing IVP',screens:[
{type:'teach',title:'Why Laplace beats interval-by-interval matching here',html:`<p>${l12Explain}</p><p>You could solve an ODE on \\(0<t<3\\), solve another on \\(t>3\\), then impose matching conditions. Laplace instead keeps the switch inside one algebraic calculation. The initial conditions enter automatically through transforms of derivatives, and the factor \\(e^{-3s}\\) carries the timing.</p>`},
l12Clone(l12Ex310),
{type:'teach',title:'O’Neil Example 3.12 — a finite switching window',html:`<p>${l12Book}</p><p>O’Neil's circuit switches at \\(t=2\\), stays in the new state for one second, then switches back at \\(t=3\\). Its output can be written as the difference of two delayed step responses:</p><div class="eq">\\[E_{out}(t)=10H(t-2)(1-e^{-4(t-2)})-10H(t-3)(1-e^{-4(t-3)}).\\]</div><p>The second term is not a mysterious correction: it subtracts the same type of response beginning at \\(t=3\\), thereby modeling the switch being reversed.</p>`},
{type:'quiz',title:'Why shift the argument too?',q:'If a base response is g(t), what is the response that starts at t=a?',options:['H(t-a)g(t-a)','H(t-a)g(t)','e^{-at}g(t)'],answer:0,why:'A true time delay gates the response and replaces its internal clock t by t-a.'}
]},{title:'Authentic §3.3 Problems 27–32 · switched IVPs',screens:l12Sec33.slice(0,6).map(l12Clone)}]},
{id:'l12-rlc',courseLesson:12,color:'#b45f4b',badge:'4',label:'Switched RLC',title:'Switched RLC Circuit: Model → Transform → Interpret',subtitle:'course-required application · source-honest reconstruction',desc:'Rebuild the Oct. 28 switched-RLC application from Kirchhoff’s law and check the result physically.',lessons:[{title:'Delayed voltage step',screens:[
{type:'teach',title:'Why charge is the natural state variable',html:`<p>${l12Supp}</p><p>For a series RLC circuit, current is \\(i=q'\\). The element voltages are \\(Lq''\\), \\(Rq'\\), and \\(q/C\\). Kirchhoff's voltage law therefore gives</p><div class="eq">\\[Lq''+Rq'+\\frac1Cq=E(t).\\]</div><p>Once \\(q\\) is known, the current follows by differentiation. This keeps the capacitor law algebraic rather than introducing an extra integral of current.</p>`},
l12Clone(l12RLC),
l12Clone(l12Sec33[6]),
{type:'quiz',title:'Long-time circuit check',q:'For the lesson RLC example with C=1/2 and a sustained 1-V DC input, what should q(t) approach?',options:['1/2 C','0 C','1 C'],answer:0,why:'At steady DC the current vanishes, so the capacitor carries q=CE=(1/2)(1)=1/2 C.'}
]}]},
{id:'l12-visco',courseLesson:12,color:'#9b6b2f',badge:'5',label:'Step viscoelasticity',title:'Step-Loaded Viscoelasticity: Creep Has a Time Scale',subtitle:'Kelvin–Voigt · delayed stress · retardation time',desc:'Connect Heaviside loading to the constitutive law and interpret the transient mechanically.',lessons:[{title:'Delayed creep',screens:[
{type:'teach',title:'Predict the behavior before solving',html:`<p>${l12Supp}</p><p>A Kelvin–Voigt element places an elastic spring and viscous dashpot in parallel. A sudden applied stress cannot instantly move the dashpot through a finite strain, so <b>strain should begin continuously from zero</b>. At long time the strain rate vanishes, leaving the spring to carry the stress, so <b>the final strain should be \\(\\sigma_0/E\\)</b>. The mathematics should reproduce both predictions.</p>`},
l12Clone(l12KV),
{type:'quiz',title:'Meaning of η/E',q:'What does τ=η/E control in the Kelvin–Voigt step response?',options:['The creep/retardation time scale','The final strain itself','The switching time a'],answer:0,why:'The exponential decays as e^{-(t-a)/τ}; τ sets how quickly equilibrium is approached.'}
]}]},
{id:'l12-periodic',courseLesson:12,color:'#3f7f8f',badge:'6',label:'Periodic forcing',title:'Periodic Forcing: One Period Generates the Infinite History',subtitle:'period T · geometric series · authentic O’Neil practice',desc:'Derive the periodic Laplace formula instead of memorizing it, then use textbook Problems 11–13.',lessons:[{title:'Derivation and book problems',screens:[
{type:'teach',title:'Periodic does not mean “use Heaviside repeatedly by hand”',html:`<p>${l12Explain}</p><p>If a waveform repeats forever, writing infinitely many shifted pulses is possible but inefficient. Periodicity lets us factor the entire infinite history into one period multiplied by a geometric-series factor. That is exactly what O’Neil Problem 11 derives.</p>`},
l12Clone(l12Periodic11),l12Clone(l12Periodic12),l12Clone(l12Periodic13),
{type:'quiz',title:'Period after rectification',q:'What is the period of |sin(ωt)|?',options:['π/ω','2π/ω','1/ω'],answer:0,why:'The negative half-cycle is reflected upward, so the waveform repeats after half the original sine period.'}
]}]},
{id:'l12-staircase',courseLesson:12,color:'#6d6f78',badge:'7',label:'Staircase',title:'The Staircase Function: Regular Jumps Without Periodic Values',subtitle:'infinite step sum · geometric transform · finite version',desc:'Distinguish a staircase from a periodic waveform and derive its transform from first principles.',lessons:[{title:'Build and transform a staircase',screens:[
{type:'teach',title:'Build a staircase from unit steps',html:`<p>${l12Supp}</p><p>A jump of +1 at \\(t=nT\\) is represented by \\(H(t-nT)\\). Adding all jumps gives</p><div class="eq">\\[r(t)=H(t-T)+H(t-2T)+H(t-3T)+\\cdots.\\]</div><p>On \\([mT,(m+1)T)\\), exactly \\(m\\) terms are active, so the value is \\(m\\).</p>`},
l12Clone(l12Stair),
{type:'teach',title:'Finite staircase — a useful engineering version',html:`<p>For only \\(N\\) scheduled increments,</p><div class="eq">\\[r_N(t)=\\sum_{n=1}^{N}H(t-nT).\\]</div><p>Now the geometric sum terminates:</p><div class="whybox"><div class="eq">\\[\\boxed{R_N(s)=\\frac{e^{-sT}(1-e^{-NsT})}{s(1-e^{-sT})}}.\\]</div></div><p>This is useful for command schedules or loads increased in a finite sequence of equal steps.</p>`},
{type:'quiz',title:'Periodic or staircase?',q:'Why is r(t)=Σ H(t-nT) not periodic?',options:['Because r(t+T)=r(t)+1','Because the jumps are irregular','Because Heaviside functions have no Laplace transform'],answer:0,why:'The timing pattern repeats, but the actual level keeps increasing.'}
]}]},
{id:'l12-mastery',courseLesson:12,color:'#9a3f69',badge:'8',label:'Transfer mastery',title:'Oct. 28 Switched & Repeated-Input Transfer Mastery',subtitle:'6 unseen problems · assumptions, switching, physical checks, periodicity',desc:'Distinct transfer problems that test the Oct. 28 ideas without repeating the textbook and engineering screens already completed above.',lessons:[
{title:'Heaviside formula assumptions & switched IVP',screens:[
 l12Board('Transfer 1 · When Heaviside’s formula is illegal',`<p><span class="supplementalTag">Original diagnostic · not an O’Neil exercise</span><br>A student applies the simple-pole Heaviside formula directly to \\(F(s)=1/[(s-2)^2(s+1)]\\). What assumption fails, and what method should replace the shortcut?</p>`,`<p>The pole \\(s=2\\) is repeated, so the simple-root hypothesis fails. In particular, the shortcut coefficient involving \\(q'(2)\\) is not usable because the repeated factor makes the denominator derivative vanish there. Use an ordinary partial-fraction decomposition containing both</p><div class="eq">\\[\\frac{A}{s-2}+\\frac{B}{(s-2)^2}+\\frac{C}{s+1}.\\]</div><p>The issue is a theorem-assumption failure, not an algebra inconvenience.</p>`),
 l12Board('Transfer 2 · A delayed constant load',`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>Solve \\(y'+2y=3H(t-4)\\), \\(y(0)=0\\).</p>`,`<p>Transforming gives \\((s+2)Y=3e^{-4s}/s\\), so</p><div class="eq">\\[Y=e^{-4s}\\frac3{s(s+2)}=e^{-4s}\\frac32\\left(\\frac1s-\\frac1{s+2}\\right).\\]</div><div class="whybox"><div class="eq">\\[\\boxed{y(t)=\\frac32H(t-4)\\left(1-e^{-2(t-4)}\\right)}.\\]</div></div><p>Before the switch the response is zero; afterward it approaches the steady value \\(3/2\\).</p>`)
]},
{title:'Engineering interpretation & periodic transfer',screens:[
 l12Board('Transfer 3 · RLC steady-state audit',`<p><span class="supplementalTag">Original diagnostic · not an O’Neil exercise</span><br>A proposed switched-RLC solution approaches nonzero current under a sustained DC source. Without re-solving the ODE, explain when that should make you suspicious.</p>`,`<p>For a stable series RLC circuit under constant DC forcing, long after the transient dies out the capacitor behaves as an open circuit. Thus current should approach zero, while capacitor charge approaches \\(CE_0\\). A proposed stable response with persistent nonzero current fails the physical long-time check even before residual substitution is attempted.</p>`),
 l12Board('Transfer 4 · Kelvin–Voigt 90% creep time',`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>A step-loaded Kelvin–Voigt element has \\(E=5\\,\\text{MPa}\\), \\(\\eta=20\\,\\text{MPa·s}\\). How long after loading until strain reaches 90% of its final value?</p>`,`<p>The retardation time is \\(\\tau=\\eta/E=4\\,\\text{s}\\). The normalized creep response is \\(1-e^{-u/\\tau}\\), where \\(u\\) is time since loading. Set</p><div class="eq">\\[1-e^{-u/4}=0.9.\\]</div><p>Then \\(e^{-u/4}=0.1\\), so</p><div class="whybox"><div class="eq">\\[\\boxed{u=4\\ln10\\approx9.21\\,\\text{s}}.\\]</div></div>`),
 l12Board('Transfer 5 · Period from the waveform, not the formula',`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>The waveform is \\(f(t)=|\\cos(2t)|\\). Find its fundamental period and state the one-period Laplace formula you would use.</p>`,`<p>The ordinary cosine \\(\\cos(2t)\\) has period \\(\\pi\\). Taking the absolute value folds each negative half-cycle upward, halving the period:</p><div class="eq">\\[\\boxed{T=\\pi/2}.\\]</div><p>Then</p><div class="whybox"><div class="eq">\\[\\boxed{F(s)=\\frac{1}{1-e^{-s\\pi/2}}\\int_0^{\\pi/2}e^{-st}|\\cos2t|\\,dt}.\\]</div></div><p>For actual evaluation, split the one-period integral at \\(t=\\pi/4\\): \\(\\cos2t\\ge0\\) on \\([0,\\pi/4]\\) and \\(\\cos2t\\le0\\) on \\([\\pi/4,\\pi/2]\\). Thus the absolute value must be handled piecewise rather than simply removed.</p>`)
]},
{title:'Staircase transfer',screens:[
 l12Board('Transfer 6 · Unequal staircase jumps',`<p><span class="supplementalTag">Original transfer · not an O’Neil exercise</span><br>A command signal jumps by +2 at \\(T\\), +2 at \\(2T\\), then +1 at \\(3T\\), with no later jumps. Write it with Heaviside functions and transform it.</p>`,`<p>Add one step for each increment:</p><div class="eq">\\[r(t)=2H(t-T)+2H(t-2T)+H(t-3T).\\]</div><p>Transform term by term:</p><div class="whybox"><div class="eq">\\[\\boxed{R(s)=\\frac{2e^{-sT}+2e^{-2sT}+e^{-3sT}}s}.\\]</div></div><p>This is a finite staircase, not a periodic function; after the last jump its level remains constant at 5.</p>`)
]}
]}
];
if(!units.some(u=>u&&u.id==='l12-map'))units.push(...lesson12Units);
courseLessons[11]={number:12,title:'Heaviside Formula, Switched & Periodic Forcing',subtitle:'Oct. 28 · O’Neil §3.3.3 · switched RLC · step viscoelasticity · periodic forcing · staircase',status:'current'};
if(typeof renderCourseMap==='function')renderCourseMap();
if(typeof render==='function')render();